supercollider/supercollider

HelpSource/Classes/Pen.schelp
I've tested this reasonably well here, but it could do with further stress testing.
=> Adding drawImage example to Pen.schelp

editors/scel/el/sclang-language.el
Noticed this when keys beginning with an uppercase letter in events weren't getting highlighted:
```supercollider
(
highlighted: "value",
NotHighlighted: "value"
)
```
=> scel: highlight uppercase symbols in emacs

SCClassLibrary/Common/Collections/Collection.sc, SCClassLibrary/Common/Collections/Dictionary.sc, SCClassLibrary/Common/Collections/SequenceableCollection.sc
This solution was suggested in the discussion about inject and it fixes #1245. The additional methods provides convenient transition between three commonly used and useful data structures:
key value pairs: common representation of arguments
collections of associations: ordering, array and collection methods
dictionaries: fast lookup, event compatibility
A possible improvement could be a primitive for the hasAssociations method, which currently prone to be misunderstood (too inefficient would have been the other choice).
=> class library: translations between key value pairs, asscociations, and dictionaries

server/scsynth/SC_Graph.cpp, server/scsynth/SC_GraphDef.cpp, server/scsynth/SC_GraphDef.h, server/supernova/sc/sc_synth.hpp, server/supernova/sc/sc_synth_definition.cpp, server/supernova/server/synth.hpp, server/supernova/server/synth_definition.hpp
This is a cleaned up version of the old branch bounded-controls. It fixes #1252.
=> Topic/bounded controls: cleaned up branch ready.

QtCollider/QtDownload.cpp
the current code is potentially prone to format string injection attacks, and there is a good reason why compilers warn about it!
=> qtcollider: avoid un-safe printf by using qWarning() instead

QtCollider/CMakeLists.txt, QtCollider/QtDownload.h
- The QtNetwork include path prefix is used in QtDownload.h for QNetwork* headers.
- For the QNetworkRequest header there is no QtNetwork inlude path prefix in QtDownload.cpp which gives a "header not found" compile error on ArchLinux.
Signed-off-by: Hanspeter Portner <dev@open-music-kontrollers.ch>
=> Fix "QNetworkRequest header not found".

CMakeLists.txt
adding back lines 396-402 makes the installation install help-files
again (at least under Linux). Fixes issue #1218
Signed-off-by: nuss <st9fan@gmail.com>
=> fix help installation

HelpSource/Classes/Collection.schelp, SCClassLibrary/Common/Collections/Collection.sc, SCClassLibrary/Common/Control/ResponseDefs.sc, SCClassLibrary/Common/Core/AbstractFunction.sc, SCClassLibrary/Common/Core/Nil.sc
The added collectInPlace method saves on object allocation for methods that are called very often.
This fixes #1329.
=> class library: FunctionList copies before iterating.

SCClassLibrary/Common/Math/Complex.sc
Please merge into 3.7. Complex:pow returns wrong results as it's currently written.
exp(Complex(0,pi));
-> Complex( -1, 1.2246467991474e-16 )
(1.exp)**(Complex(0,pi));
Without fix:
-> Complex( 6.1232339957368e-17, 1 )
With fix:
-> Complex( -1, 1.2246467991474e-16 )
There is a rather large difference between -1 (correct) and *i* (incorrect).
=> Classlib: Complex: Fix bugs in 'pow' method

editors/sc-ide/widgets/multi_editor.cpp
ctrl-tab executes this dialog, but the KeyRelease event may be lost if
the window flag is not marked as Qt::Popup
Signed-off-by: Tim Blechmann <tim@klingt.org>
=> scide: DocumentSelectPopUp - convert to Popup to fix lost KeyRelease event

HelpSource/Classes/Ndef.schelp
This fixed a broken link due to a capital letter "L" in th Ndef help file
=> Fix broken link in Ndef help file

server/plugins/TriggerUGens.cpp
Test case. It uses EnvGen to isolate the initial output values produced by these units' Ctors, showing that the "primed" outputs do not take into account a trigger that comes in during the first calculation block.
(
SynthDef(\test, {
var ugens = [
{ |trig, dur| Trig1.kr(trig, dur) },
{ |trig, dur| Trig.kr(trig, dur) },
{ |trig| SetResetFF.kr(trig) },
{ |in, trig| Gate.kr(in, trig) },
{ |in, lo, hi| Schmidt.kr(in, lo, hi) },
{ |trig| PulseDivider.kr(trig, 2, 1) },
{ |trig| PulseCount.kr(trig) },
{ |trig| Stepper.kr(trig) },
{ |in, delay| TDelay.kr(in, delay) }
],
args = (
trig: Impulse.kr(0),
dur: 0.1,
in: DC.kr(10),
lo: 0,
hi: 1,
delay: 0
),
lateTrig = DelayN.kr(args[\trig], 0.1, 0.1);
args.use {
ugens.do { |func, i|
var value = func.valueEnvir;
Poll.kr(lateTrig, EnvGen.kr(Env([value, …
=> plugins: fix 10 trigger UGens that did not initialize ZOUT correcly

HelpSource/Classes/Date.schelp
%m and %e are both for day of month (the latter with preceding space, if single digit), minute is %M not %m
=> Date.schelp: corrected peculiar format example

lang/LangPrimSource/PyrPrimitive.cpp
To test this, trash your ~/Library/Application Support/SuperCollider so that there is no existing ide config or lang config.
Startup supercollider. 
```supercollider
LanguageConfig.currentPath
```
should return nil.
This also fixes Quarks from trying to write to a config file of ""
Quarks.gui, install something, recompile.  Quarks.gui again and you should see the paths are saved to the config.
A language config file should exist with the default sclang_config.yaml
=> fixes #1369 LanguageConfig.current returns "", should return nil

HelpSource/Classes/Server.schelp, SCClassLibrary/Common/Control/Server.sc, server/plugins/DiskIO_UGens.cpp
This aims to fix a bug where DiskOut didn't always write the last chunk of samples. This should solve the problem discussed in Issue #1380 (although the default size should still be collected as suggested) and discussed on sc-dev in this thread: https://www.listarc.bham.ac.uk/lists/sc-dev/msg53886.html
It adds a Dtor which writes an extra msg to the DiskIO fifo if needed when the UGen is destroyed. There should be no API incompatibilities AFAICS.
=> fix-DiskOut

SCClassLibrary/Common/Streams/Patterns.sc
e.g.
```
Pbind(\degree, Pseq([1,2,3,4],1)).record();
// Keeps recording even after end of pattern, cmd-. is only way to stop
Pbind(\degree, Pseq([1,2,3,4],1)).record(dur:4)
// Same problem
```
Pull request fixes this by returning a 0 duration rest event, rather than just 0.
=> Pattern.record method doesn't stop recording

SCClassLibrary/Common/Control/MIDIResponder.sc, SCClassLibrary/Common/Control/ResponseDefs.sc
Protect against non-integral values for note and cc number. Ordinarily inputting invalid values here would be user error - however, it's plausible that a note or cc num here might be the product of some calculation which could have caused an implicit conversion to float, which would cause a silent failure. Fixes #325
=> classlib: note nums / cc channels must be integers

SCClassLibrary/Common/GUI/PlusGUI/Control/FreqScope.sc
scope now allows for a fill property which needs to be turned off for the Frequency Analyzer
=> FreqScope.sc: adapt to new fill property of scope.

SCClassLibrary/Common/Quarks/Quarks.sc, SCClassLibrary/Common/Quarks/QuarksGui.sc
This:
- fixes the *isCompatible* string in the quark description
- informs the user that a quark is being downloaded
While trying the new quark gui with a relatively slow internet, I got confused because I first thought that nothing happened with `Quarks.install('http://...')`..
=> Quarks GUI tiny improvements

editors/sc-ide/core/settings/theme.cpp, editors/sc-ide/core/settings/theme.hpp
While the default theme is black on white background, the "dark" theme is mostly
white on a black background.
This theme has been provided by http://fleuryfontaine.fr/
=> scide: theme: introducing built-in "dark" theme

editors/sc-ide/core/doc_manager.cpp, editors/sc-ide/core/sig_mux.cpp, editors/sc-ide/core/sig_mux.hpp, editors/sc-ide/widgets/multi_editor.cpp
The prevents a crash when iteratively closing all documents. Each doc close triggers a chain of signals that can result in - what appears to be - an already-removed document being referenced by a tab. This change prevents the crash directly by disconnecting the currentChanged signal, which avoids the chain of signals. It also adds some seatbelts in case of bad / null documents, and uses deleteLater() to delete the document, rather than a raw delete. The `Document*`'s should probably be changed to smart pointers - the signal logic when managing documents is complex enough that it's hard to analytically show that there isn't some pending signal or reference to a document floating around after DocumentManager::close(*) is called.
=> ide: fix crash on session switch

SCClassLibrary/Common/Control/NetAddr.sc
if *initClass failed to run on startup then connections is still nil
=> protect NetAddr-disconnectAll from failing during shutdown

SCClassLibrary/Common/GUI/Base/QLayout.sc
Fix #1383
```javascript
(
g = GridLayout.rows(
[[Button(), c: 2], [Button(), c: 2], Button()],
[[Button(), c: 5]]
);
w = Window("", 200@100).layout_(g).front();
)
```
```javascript
(
g = GridLayout.columns(
[Slider2D(), Slider2D(), Slider2D(), Slider2D(), Slider2D()],
[[Slider2D(), r: 2], [Slider2D(), r: 2], Slider2D()],
[[Slider2D(), r: 5]]
);
w = Window("", 200@100).layout_(g).front();
)
```
=> class library: GridLayout - fix position when using spanning

SCClassLibrary/Common/Quarks/Quark.sc, SCClassLibrary/Common/Quarks/Quarks.sc
Installs dependencies (including their dependencies) instead of just checking them out and linking them.
Fixes https://github.com/supercollider/supercollider/issues/1377
Parses refspecs in dependencies as advertised.
Also catches named quarks that are not found, posts the ERROR and returns nil.
```supercollider
Quark.parseDependency("Bjorklund");
Quark.parseDependency("DoesntExist");
Quark.parseDependency("crucial-library@tags/4.1.4");
Quark.parseDependency("crucial-library@tags/bad-tag");
Quark.parseDependency("DoesntExist@tags/4.1.4");
Quark.parseDependency("UnitTesting" -> 1.0)
Quark.parseDependency("DoesntExist" -> 1.0)
Quark.parseDependency(["UnitTesting", 1.0, "svn://sourceforge.net/etc/usw"])
Quark.parseDependency(["DoesntExist", 1.0, "svn://sourceforge.net/etc/usw"]) …
```
=> Fix: Install quark dependencies with refspecs

SCClassLibrary/Common/Math/SimpleNumber.sc
Same issue, same behavior as #1437, but this one is optimized for speed.
=> Classlib: lincurve: Prevent incorrect range clipping when curve ~= 0

editors/sc-ide/widgets/settings/editor_page.cpp
This should only apply to one control - the foreground color picker for the "current line" style. But, in general, if a format widget is disabled, then it's not user settable, and thus shouldn't be saved into the preferences yaml.
This fixes #1403
=> ide: do not save format settings for controls that are disabled.

lang/LangSource/SC_TerminalClient.cpp
Re #1324 but that one uses `-v` instead
=> Sclang: print version with -v

HelpSource/Guides/WritingClasses.schelp
Per a Facebook thread:
- D. Ogborn PS - by the way, in the SC documentation it says "protocols" but I do believe this is more like "categories" since it is about the implementation of the method also
- G. Newsome Definitely not equivalent to an Objective-C protocol. Is equivalent to an Objective-C category. Documentation is incorrect. Nice to know that this feature is part of SC as it's incredibly handy.
I don't know objective C so I don't feel qualified to evaluate these statements. But the pull request is here for other obj-c savvy developers to merge if correct.
=> Help: WritingClasses: Extension methods are like obj-c categories

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
resampledDomainSpec is the spec that is used when drawing the graph, so this should also be used when determining the data under the mouse position.
This fixes #264
=> classlib: Use correct spec for x coord of edits

QtCollider/style/ProxyStyle.cpp, editors/sc-ide/widgets/style/style.cpp
A bug in qt webkit results in animations related to scrollbar opacity and hidden-ness pointing to the QWebView instead of the scrollbars (see https://bugs.webkit.org/show_bug.cgi?id=104116). As a result, the QWebView gets hidden instead of the scrollbars in many cases. This bug was seemingly fixed, but in a very specific and limited way - either it has regressed, or we're running afoul because of our custom style. Regardless, we can work around by implementing the same fix referenced in the aforementioned bug in our own custom styles. Also  - this change removes an OLD webkit scrollbar hack, because it appears to no longer be a problem. This MAY fix the problems with help disappearing in the IDE as well.
=> sclang: workaround webkit scrollbar hiding bug

SCClassLibrary/Common/Control/SerialPort.sc, lang/LangPrimSource/PyrSerialPrim.cpp
The SerialPort destructor calls join, which crashes if run from the SerialPort thread itself. To close, SerialPort is flagged such that the thread will exit it's run loop, close the port, and then call prDoneAction, which in turn calls prCleanup - this ALWAYS happens from the SerialPort thread itself, meaning it always crashes.
This fixes by (a) ensuring that prCleanup always defers to the main thread, (b) erroring the primitive if we try to call it from the SerialPort thread, (c) asserting if we hit the destructor on the SerialPort thread (which should make problems here easier to track, at least). We are currently not destroying SerialPort backend objects (or removing the threads) properly when the language quits - I'll fix this in a separate commit, though there are no bad effects at …
=> sclang: fix crash during SerialPort cleanup

editors/sc-ide/core/doc_manager.cpp
This is an attempt to fix #758. There is no easy solution, because QFile objects don't fire a signal when the write is finished, and when the write cache is heavily backlogged I presume there's a delay in updating the mod date.
Those affected can test in this build:
http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-96380ae258bcdf87e8ca587482a14cb51d535ba5.zip
=> ide: Fix triggering of doc modified signal

README_LINUX.md
Needed, at least on Ubuntu 15.04
=> Add two qt5 packages to dependencies list

editors/sc-ide/widgets/code_editor/sc_editor.cpp
This adds two additional conditions for creating a double-newline when hitting return w/in brackets. We should NOT add a double-newline if we're in between two closing brackets - i.e. ]], ]), etc.
And, we should NOT add a double-newline if the closing bracket to the right of the cursor is the first thing on the line.
This avoids several spurious double-newlines that are common in SC code (see bug #814, for example). Note that this still allows a double-newline if you're adding function arguments to a function over multiple lines. Hitting return in this case:
([1, 2], [3, 4],<return>)
(i.e. with a comma before the return) will create a double-newline.
=> ide: better newline behavior within brackets

server/plugins/LFUGens.cpp
Fixes issue #1501 (of special interest: the default case when duty is 0.5).
Now, when you specify the default duty cycle (`width`) of 0.5, and a frequency that should allow an even number of "ups and downs" (e.g. an even multiple of the sampling rate, below Nyquist), it does.  Previously, it tended to drift (you'd see this if you ran an Integrator over the output).
It will still drift if the frequency is not an even multiple of the sample rate, but this can't be avoided.  This is due to the fact that it's always desired (according to a comment in the code) to output at least one sample from the "opposite polarity" in each period.  If this constraint were relaxed, then it could more closely average the correct duty over several cycles.  Right now, for a waveform period of seven samples, …
=> plugins/LFUGens: generate symmetrical waveforms in LFPulse

editors/sc-ide/widgets/code_editor/completion_menu.cpp, editors/sc-ide/widgets/code_editor/completion_menu.hpp
Dragging or copying text from the help view that pops up during completion results in a crash. It appears that QT deletes the QMimeData corresponding to the copied/dragged chunk too soon, and referencing it later on causes a crash. I attempted various overrides of createMimeDataFromSelection (returning e.g. plain text, etc), and it always crashed except when we simply return NULL. This results in text from that view not being copyable / draggable but this is better than a crash. This is probably a deep QT bug.
=> ide: Workaround for completion help view crash

SCClassLibrary/Common/GUI/Base/QView.sc
Documentation says that the char argument of keydown/keyup events is the printable character typed, or nil. We are currently passing an ascii zero character instead - the fix is to pass nil in this case.
=> classlib: Don't pass unprintables in key events

QtCollider/widgets/QcScrollArea.cpp
Setting some geometry-related properties at view creation time gets a bit weird, because layout is often not calculated immediately. In case of #823, the initial layout of the view gets calculated in a slightly deferred event fired in response to .front(), meaning that when visibleOrigin_ is called, the scrollbars still haven't been adjusted according to the layed-out window contents (specifically, at creation time the max scroll value is 0). Fixing this by getting layout to happen at the right time is hard - fortunately, it looks like scrollbar behavior is smart enough that, when we request a specific visibleOrigin, we can simply increase the scrollbar max value as needed - even when manually setting a max, the scrollbars seem to re-adjust properly as the contents of the scroll area are …
=> sclang: set max scroll according to req'd value

lang/LangPrimSource/PyrStringPrim.cpp
In case of a backslash with no following %, we want to push the backslash to the output string.
fixes #1291
=> lang: don't drop backslashes

editors/sc-ide/widgets/main_window.cpp
Hiding the toolbox causes focus to revert - in that case, Qt handles the focus logic, and seems to pick the first widget in the chain. Instead, we need to set focus to the correct editor box ourselves, and *then* hide the toolbox.
Fixes #1363
=> ide: hide toolbox after changing box focus

HelpSource/Classes/Signal.schelp, HelpSource/Classes/Wavetable.schelp, SCClassLibrary/Common/Math/Signal.sc, server/plugins/OscUGens.cpp
These are several things I found while looking at the issues raised in #1500.  Besides adding the ability to produce the "raw" Chebyshev polynomials (by passing `normalize: false`and a new option `zeroOffset: false` to Signal.chebyFill and Wavetable.chebyFill), I fixed two problems I found along the way:
1. `Signal.chebyFill` was not taking amplitudes into account when offsetting for DC.  The fix was there, but it always added or subtracted 1 in the the relevant places.  Worst of all, for amplitudes of 0 it came across (whose poly degrees would otherwise need offsetting), it was always adding and subtracting 1!  This was probably not noticed, because with `normalize: true` (default) it shifted the whole thing to lie between -1 and 1.
2. `Buffer.chebyMsg` (and `Buffer.cheby`) were not …
=> Chebyshev polynomials: various fixes (issue #1500)

QtCollider/QWidgetProxy.cpp, QtCollider/painting.h, QtCollider/primitives/prim_QObject.cpp, QtCollider/primitives/prim_QPen.cpp
This should avert a crash when setting the background color of a UserView from inside a drawFunc. In general, it seems extremely unsafe to synchronously set a property of a UserView while *inside* of it's drawFunc. Most properties will behave more or less identically if the set is deferred, and for some (i.e. changing view geometry) this avoids very undefined and dangerous-seeming behavior.
=> qtcollider: defer setPropery if called inside drawFunc

editors/sc-ide/widgets/multi_editor.cpp
This fixes #1287.
This behavior (i.e. adding documents opened via session switch) seems fine to me, but it was explicitly disabled before.
=> ide: track files opened in a session switch in the recent documents menu

HelpSource/Classes/Buffer.schelp, HelpSource/Classes/Signal.schelp, HelpSource/Classes/Wavetable.schelp, SCClassLibrary/Common/Math/Signal.sc
- added a note about the change to `Buffer.cheby`'s (fixed) behavior in 3.7, as per @telephon comment in #1504.
- added real-world waveshaping examples for `Signal.chebyFill` and `Wavetable.chebyFill`, and moved all the examples below (where they should be), in a "Discussion" section.
- the `Signal.chebyFill` and `Wavetable.chebyFill` methods **no longer offset the center value to zero by default**, as per discussion with @telephon, @porres. Notes to this effect were added to the help files.
I considered adding the "zero offset" functionality to `Buffer.cheby` as well, but decided against it, because of the way the OSC chebyMsg is created.  I would break existing functionality, because I'd need to insert a new OSC argument *before* the list of amplitudes (which must be last, since they …
=> Chebyshev: zero-offset default change plus documentation updates

SCClassLibrary/Common/Quarks/Git.sc
`git rev-list tagname` can return a large list of unneeded hash references.
this was triggering some stack corruption. glory goes to @scztt for the solution
=> fix #1476 stack corruption triggered by calling a git unixCmd

SCClassLibrary/Common/Quarks/Quark.sc
prepend tags/ if missing so that Quarks.install("thingy", "v0.2") works
unixCmd does not detect the exit code, so a failure to checkout was not detected
fixes #1531
=> validate that a refspec refers to an existing tag

server/scsynth/SC_World.cpp
This allows using standard malloc, realloc and free as needed by NRT actual implementation
=> scsynth: alow using malloc, realloc, free

CMakeLists.txt
Currently it's /usr/local, which I don't think anybody uses.
=> OSX: return to old default cmake install location ./Install

SCClassLibrary/Common/Collections/Event.sc
For some reason I can't fathom, ~latency was omitted from the messaging calls for event types 'on', 'off', 'set', 'kill', 'group', and 'parGroup' -- meaning, for these event types, any latency specified in an Event will be ignored.
It doesn't appear to be a deliberate decision. No changes here except to rectify this.
=> Classlib: Event: Add missing ~latency into ~schedBundleArray calls

HelpSource/Guides/WritingPrimitives.schelp, QtCollider/QcApplication.cpp, QtCollider/primitives/prim_QImage.cpp, QtCollider/primitives/prim_QQuartzComposer.mm, SCDoc/SCDocPrim.cpp, lang/LangPrimSource/OSCData.cpp, lang/LangPrimSource/PyrArrayPrimitives.cpp, lang/LangPrimSource/PyrFilePrim.cpp, lang/LangPrimSource/PyrListPrim.cpp, lang/LangPrimSource/PyrPrimitive.cpp, lang/LangPrimSource/PyrStringPrim.cpp, lang/LangPrimSource/SC_CoreAudioPrim.cpp, lang/LangPrimSource/SC_CoreMIDI.cpp, lang/LangPrimSource/SC_HID_api.cpp, lang/LangPrimSource/SC_Speech.mm, lang/LangSource/GC.cpp, lang/LangSource/GC.h, lang/LangSource/PyrInterpreter3.cpp, lang/LangSource/PyrObject.cpp, lang/LangSource/SC_LanguageClient.cpp, lang/LangSource/SC_TerminalClient.cpp
Okay, again a cleaned up version of #1618. Only big difference is a commit changing calls to GCWrite to GCWriteNew where appropriate, and an assert statement in GCWriteNew to help catch any future misuse of it in debug builds.
Overall this amounts to a fairly detailed review of most calls to object creation (instantiateObject, newPyr*, etc.), and write barrier (GCWrite, etc.) funcs. Although as noted in #1476 the API should probably be reworked to make these sorts of issues impossible, this was not too onerous and is probably worth doing before releases. (I can't promise I've caught absolutely everything, but it was worth doing, and more eyes are always better!) I've also updated the Writing Primitives doc, which will hopefully be of use in avoiding such mistakes for as long as the …
=> Gc fixes and doc final

server/scsynth/SC_CoreAudio.cpp, server/scsynth/SC_CoreAudio.h
This fixes #768 
Setting sample rate in CoreAudio is actually an asynchronous operation - you request a sample rate change, and some time in the future it (probably) happens and you are called back about it. This is a problem for us because (a) SC doesn't support the sample rate changes once the server is started, and (b) our startup routine is totally synchronous anyway. Prior to this change, when we requested a custom sample rate, we would do the SetProperty and then shortly after ask CoreAudio for the device sample rate. If the operation had not been completed yet, we would get the OLD rate - the device would set it's SR to the requested shortly after, and we would effectively be running the server at the wrong rate. Now, we *assume* that a successful SetProperty has changed the sample …
=> server: Assume requested SR was successfully set

SCClassLibrary/Common/Core/Boolean.sc
Without this patch True.newCopyArgs will crash the interpreter.
=> disallow newCopyArgs in Boolean

SCClassLibrary/Common/Audio/SystemSynthDefs.sc
`"rm -f '/blah/blah/synthdefs/temp__*'".unixCmd` was wrong for two reasons:
1. Shell globbing isn't guaranteed to work with a quoted path. In Ubuntu, this failed to remove temp synthdef files.
2. Not valid for Windows.
Solution: Get the paths via `pathMatch` and then use `File.delete` to remove them one by one.
=> Classlib: SystemSynthDefs: Clean up temp defs properly on all platforms

include/plugin_interface/SC_InlineUnaryOp.h
gcc's builtins are reqired to be constexpr
=> plugin interface: fix compile failure with gcc-4.9

lang/LangPrimSource/PyrSignalPrim.cpp
The method Signal.chebyFill() would often return `nan`as the final value in the array -- it depended on the size of Signal asked for.  This happened because `acos(1 + someTinyAccumulatedRoundingError)` returns `nan`.  The desired value at the end of the loop should be acos of exactly 1.0, so now I just ensure the argument never exceeds one.
=> lang: prevent Signal.chebyFill from returning nan

server/scsynth/SC_GraphDef.cpp
this error is there form 2012.
I happened working for a tcp connection on my lua client.
I dont know why it does not happens on sclang.
=> scsynth:SC_GraphDef.cpp correct d_removed packet definition

HelpSource/Classes/Document.schelp, HelpSource/Classes/View.schelp, SCClassLibrary/Common/GUI/Base/QView.sc
Per discussion under issue #1554.
=> Non-characters pass ASCII code 0 to key actions

QtCollider/widgets/QcTextEdit.cpp
Fixes a discrepancy between text selection for enterInterpretsSelection vs.
aTextView.currentLine.
Submitting formally as a PR based on @telephon's comment on issue #1637.
=> QtCollider: TextView: Get code for enterInterpretsSelection from block()

SCClassLibrary/Common/Quarks/Quark.sc, SCClassLibrary/Common/Quarks/Quarks.sc, SCClassLibrary/Common/Quarks/QuarksGui.sc
previously it was failing to load a quark set file for any quarks that were not previously cloned. it would check them out (switch to the right tag) but it wouldn't clone it if needed.
also makes Quarks.load cancelable with command-.
does load with some pauses so it does not choke the main app
and updates the gui when its done
=> fix: Quarks.load quark set

lang/LangPrimSource/OSCData.cpp, lang/LangPrimSource/SC_ComPort.cpp, lang/LangPrimSource/SC_ComPort.h
NetAddr#disconnect should close the underlying boost TCP socket in order for the port to be available again for use, and should handle the common error that happen when shuting down the TCP connection, if the connection was already terminated from the other side. After the SC_TcpClientPort is closed it is no longer usable therefore the socket variable of NetAddr should be set to null, making NetAddr#isConnected correctly report the status of the connection.
=> lang: NetAddr: correctly disconnect tcp socket

SCClassLibrary/Common/GUI/PlusGUI/Core/ClassBrowser.sc
These 2 commits fix ugly error messages that could be posted for invalid class browser searches that depend on a root class to be selected.
Usability improvement -- changes no core functionality.
=> Subclass searches

editors/scel/el/sclang-server.el
`(force-mode-line-update)`  updates only the mode-line of  the current buffer. Providing a non-nil argument updates the mode-line of all buffers. This is particularly useful when having a split view with the server buffer and another buffer where current buffer is not the server buffer. (probably  a very common use case).
=> scel: Fix mode-line update

server/plugins/LFUGens.cpp
Bug reported on the mailing list: `kr` inputs to an `ar` Clip unit produce a sawtooth wave when changed.
This is because the original author of the SIMD calculation functions (38f2d28dec52750bc22da9883a853f7b48b6ba7f) forgot to update the struct member variables with new data from the inputs, meaning that every subsequent control cycle would attempt to ramp to the new value.
```
(
/* Start the synth, everything is correct... */
a = {
arg control = 0.2;
Clip.ar(DC.ar(), control, 0.4);
}.scope;
)
/* Until I change the control value */
a.set(\control, 0.25);
/* At this point I hear and see high-pitched oscillation that's
samplerate-dependant. */
```
=> Plugins: Clip NOVA functions should update unit-> variables

SCClassLibrary/Common/Files/File.sc
tested on a case insensitive file system using this:
var pathName = "/Users/crucial/Library/Application Support/SuperCollider/downloaded-quarks/splines";
(pathName.dirname+/+"*").pathMatch.detect{|x|x.withoutTrailingSlash.compare(pathName.withoutTrailingSlash)==0}.notNil
=> fix #1668 - make existsCaseSensitive work for directories

HelpSource/Classes/CuspL.schelp, HelpSource/Classes/CuspN.schelp, HelpSource/Classes/FBSineC.schelp, HelpSource/Classes/FBSineL.schelp, HelpSource/Classes/FBSineN.schelp, HelpSource/Classes/GbmanL.schelp, HelpSource/Classes/GbmanN.schelp, HelpSource/Classes/HenonC.schelp, HelpSource/Classes/HenonL.schelp, HelpSource/Classes/HenonN.schelp, HelpSource/Classes/LatoocarfianC.schelp, HelpSource/Classes/LatoocarfianL.schelp, HelpSource/Classes/LatoocarfianN.schelp, HelpSource/Classes/LinCongC.schelp, HelpSource/Classes/LinCongL.schelp, HelpSource/Classes/LinCongN.schelp, HelpSource/Classes/LorenzL.schelp, HelpSource/Classes/QuadC.schelp, HelpSource/Classes/QuadL.schelp, HelpSource/Classes/QuadN.schelp, HelpSource/Classes/StandardL.schelp, HelpSource/Classes/StandardN.schelp
This patch is for removing unnecessary comments and homogenize the math notation with the bhob ugens (taken as example).
=> help: chaotic generators warnings removed

editors/sc-ide/widgets/code_editor/editor.cpp, editors/sc-ide/widgets/code_editor/editor.hpp, editors/sc-ide/widgets/multi_editor.cpp, editors/sc-ide/widgets/multi_editor.hpp
This patch adds to scide the well-known terminal shortcut ctrl+w. This shortcut
is applied to OSX only because of a conflict with the close shortcut.
=> scide: add OSX delete word ctrl+w shortcut

SCClassLibrary/Common/Control/HID_API.sc
There was a mixup in curly brackets in findAvailable, causing an else statement to never be reached.
This is fixed in this pull request.
=> class library: HID: fix else statement in findAvailable

SCClassLibrary/Common/Streams/Stream.sc
Bug reported on mailing list. If you re-play the same PauseStream subclass using a different clock, the PauseStream's internal `stream` variable is still pointing to the old clock. This causes errors if that clock was stopped in the meantime, e.g., by cmd-.
The fix is `stream.clock = clock` in PauseStream:play and EventStreamPlayer:play.
```
(
var myTempo = TempoClock.new(0.5);
Pdef(\test,Pbind()).play(myTempo);
)
```
Original mailing list post:
> The first time I run this code, it works, but if I stop it with Cmd+.
> and run it again, I get:
> ERROR: clock is not running.
> ERROR: Primitive '_TempoClock_BeatsToSecs' failed.
=> Classlib: Update PauseStream stream's clock upon play

SCClassLibrary/Common/Control/OSCBundle.sc, SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc, SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
this fix by @telephon fixes an annoying behaviour in NodeProxies:
```
Ndef(\sine).clear
(
Ndef(\sine, {SinOsc.ar(\freq.kr(100)!2).tanh});
Ndef(\sine).set(\freq, 200);
)
-> Ndef('sine')
FAILURE IN SERVER /n_set Node 1010 not found
```
Previous behaviour:
```
1. set source: create a bundle that:
1a. sends synth def
1b. waits for completion, then sends synth with args
2. set controls: create a bundle that:
2a. sets group
temporal order will be: 1a. 2a. 1b.
```
now, it does it different... (maybe ask @telephon for details..)
I use this branch extensively for a week now and think that it works perfectly.
=> class library: make control set atomic

HelpSource/Classes/BAllPass.schelp, HelpSource/Classes/BBandPass.schelp, HelpSource/Classes/BBandStop.schelp, HelpSource/Classes/BHiPass.schelp, HelpSource/Classes/BHiPass4.schelp, HelpSource/Classes/BHiShelf.schelp, HelpSource/Classes/BLowPass.schelp, HelpSource/Classes/BLowPass4.schelp, HelpSource/Classes/BLowShelf.schelp, HelpSource/Classes/BPF.schelp, HelpSource/Classes/BPeakEQ.schelp, HelpSource/Classes/BRF.schelp, HelpSource/Classes/LPF.schelp, HelpSource/Classes/RHPF.schelp, HelpSource/Classes/RLPF.schelp, HelpSource/Classes/Resonz.schelp
BPF LPF RLPF, RHPF., Resonz., BBandPass, BAllPass, BBandStop., BHiPass, BHiPass4, BLowPass, BLowPass4, BHiShelf, BLowShelf, BPeakEQ, BRF are potentially getting nasty at filter frequencies close to zero.
Somehow they didn't make it into the the PR for https://github.com/supercollider/supercollider/commit/ce1d22330330803918e748ce978cb5f8ea5e1b9b
=> ass Filters: warning in help-docs about filter frequencies close to zero

SCClassLibrary/Common/GUI/PlusGUI/Control/UGen-scope.sc, SCClassLibrary/Common/GUI/tools/Stethoscope.sc
before, this didn't work: { SinOsc.ar(100).scope(\SinOsc) }.play;
but this worked: { SinOsc.ar([100]).scope(\SinOsc) }.play;
=> UGen-scope.sc: fixes method to determine default server

include/plugin_interface/SC_InlineBinaryOp.h
Issue doesn't seem to come up when compiling SC, but does when compiling sc3-plugins. I'm on Ubuntu 14.04.3 LTS.
=> build: modify trunc() calls to compile on gcc 4.8.4

HelpSource/Guides/Working_with_HID.schelp
changed External control -> External Control so that it ends up in the right scdoc category
=> scdoc: typo in Working_with_HID.schelp

HelpSource/Guides/LID_permissions.schelp
changed External control -> External Control so that it ends up in the right scdoc category
=> scdoc: typo in LID_permissions.schelp

HelpSource/Guides/HID_permissions.schelp
changed External control -> External Control so that it ends up in the right scdoc category
=> scdoc: typo in HID_permissions.schelp

server/supernova/sc/sc_osc_handler.cpp
fixes a crash on exit, if the tcp connection has already been closed by the client
=> supernova: tcp - catch exceptions when sending replies via tcp

server/scsynth/SC_Jack.cpp
Looking at the jack driver I found an old codepath, for jack<0.100 (released 2005). I'm not aware of any system that's limited to such very old jackd. Furthermore, the define being tested for (SC_USE_JACK_CLIENT_NEW) is not referenced anywhere else in the project. (The old "SConstruct" used to have an option to enable it but that went away long ago and no-one noticed.)
=> jack audio driver: remove old unused codepath for jack<0.100

server/scsynth/CMakeLists.txt
If the flag AUDIOAPI takes an unrecognised value, really we should error out, rather than merely warning.
=> cmake: refuse to build if unrecognised AUDIOAPI

SCClassLibrary/Common/Math/Float.sc
This fixes old issues with Object.writeArchive. However it makes code
generated with asCompileString more “verbose”.
=> class library: store floats with full precision

HelpSource/Tutorials/Getting-Started/02-First-Steps.schelp
The last commit changed the key from ‘k’ to ‘p’ not consistently by
leaving the old ‘k’ in the parantheses.
=> FIx typo in tutorial on shortcut explanation to clear the post window

HelpSource/Tutorials/Getting-Started/02-First-Steps.schelp
Improving on correctness of First Steps section in SC Tutorial:
As discussed under issue
https://github.com/supercollider/supercollider/issues/1781#issuecomment-
170959978 I have now made an attempt to improve on the correctness of
the section "02. First Steps" of Tutorial "Getting Started With
SuperCollider”. This should give new users of SC a much more pleasant
experience and avoid the bad impression of SC not working as it
should/described. However, some sections are related to a bug/bugs
(https://github.com/supercollider/supercollider/issues/1786).
=> Incorporate these tutorial corrections

SCClassLibrary/Common/Collections/EventTypesWithCleanup.sc
I need to have event type \sync when allocating buffers in Pproto. 
I found two earlier discussion on list about this:
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/EventType-sync-was-using-Pproto-for-groups-etc-td7587867.html
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/sync-event-type-for-patterns-td4283008.html
I can't find if this was added anytime after that.
I've tried adding the event type with:
`Event.addEventType(\sync, {|server| server.sync; });`
But that doesn't work if you stop the EventStreamPlayer from code. Like this:
```
(
s.waitForBoot({
Event.addEventType(\sync, {|server| server.sync;});
SynthDef(\help_playbuf, { | out=0, bufnum = 0, rate = 1, startPos = 0, amp = 0.1, sustain = 1, pan = 0, loop = 1|
var …
```
=> Fix avoid calling nonexisting cleanup event type

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
I think it would make sense to scale Function:plot between -1 and 1. Can't see that a majority of user cases would benefit from the current behaviour. In most cases people are exploring the behaviour of UGens and expecting to see it within the clipping range. 
From an educational perspective it makes sense too, IMO. I just wrote this example in a workshop and the results were confusing (until I remembered to write minval and maxval):
{SinOsc.ar(440, 0)+SinOsc.ar(440, pi)}.plot
=> Fix range in Function:plot

CMakeLists.txt
Fixes #1802. ARM systems don't have SSE; with this patch, users on ARM don't run into problems if they forget all the `-DSSE=OFF -DSSE2=OFF`.
=> cmake: disable SSE on ARM

SCClassLibrary/Common/GUI/Base/QView.sc
Fix or workaround for https://github.com/supercollider/supercollider/issues/1506
applicable on all platforms, switches back to normal window before closing.
=> QView.sc: removes residue OS X Space after closing a fullscreen window. 

SCClassLibrary/Common/Control/Server.sc
This seems to have changed at some point, 3.6.6 is ok.
fixes https://github.com/supercollider/supercollider/issues/1825
=> Server.sc: option for scsynth's verbosity now is "V" not "v".

server/supernova/sc/sc_osc_handler.cpp
Supernova currently displays a b_allocReadChannel error when b_write fails.
=> Fix error message

include/plugin_interface/SC_SndBuf.h
This fixes compile on non-SSE2 systems - see #1819 for info. Again this PR is just for master
=> build: fix non-SSE2 compile of SC_SndBuf.h (Fixes #1819)

server/plugins/PanUGens.cpp
Simple patch that already made it to master. I was thinking of proposing this for 3.7.1 but if you see it's simple enough for 3.7.0 then go for it. Without this patch, setting NOVA_SIMD=OFF simply causes the SC build to fail.
(cherry picked from commit a630e05b67cd60d801af87db1373428f4da832ee)
=> build: fix PanUGens to build when NOVA_SIMD=OFF

SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/JITLib/ProxySpace/BusPlug.sc
This is a fix for the allocation problem that has has become exposed  in `NodeProxy`.
```
//—first example
s.reboot
(
60.do{|i|
Ndef(("asdf"++i).asSymbol.postln, {SinOsc.ar((40+i).midicps,0,0.1)!2});
};
)
Ndef(\asdf54).play  //sounding
Ndef(\asdf54).stop
Ndef(\asdf55).play  //sounding
Ndef(\asdf55).stop
Ndef(\asdf56).play  //silence
Ndef(\asdf56).stop
Ndef(\asdf57).play  //silence
Ndef(\asdf57).stop
Ndef(\asdf58).play  //silence
Ndef(\asdf58).stop
Ndef(\asdf59).play  //silence
Ndef(\asdf59).stop
//would be nice with a warning
//—second example...
//recompile
s.reboot
(
66.do{|i|
Ndef(("asdf"++i).asSymbol.postln, {SinOsc.ar((40+i).midicps,0,0.1)!2});
};
)
//loud sound without any .play.  post window say...
//"ERROR: Meta_Bus:audio: failed to get an audio bus allocated. numChannels: 2 …
```
=> Topic fix allocations

editors/sc-ide/primitives/sc_ipc_client.cpp
I think the use of vector is correct here, someone else should check. I tryed doing a cout of 'text.data()' and the text of the file is posted correctly, so slotStrVal seems to be working correctly with the pointer returned from data().
=> ide: fix memory leak

editors/sc-ide/core/sc_process.cpp, editors/sc-ide/forms/settings_sclang.ui, editors/sc-ide/widgets/settings/sclang_page.cpp
This can be useful for debugging purposes, or for devs that want to use the class library of the git local copy (would superseed the symlink option of cmake).
=> ide: Add standalone option in settings.

HelpSource/Classes/ArrayedCollection.schelp, HelpSource/Classes/SequenceableCollection.schelp
Corrected errors saying that `x[a..b]` is equivalent to `copyRange`, and added warnings explicitly describing the differences between copyRange and copySeries.
=> Improved documentation for copyRange and copySeries

SCClassLibrary/Common/Quarks/QuarksGui.sc
This is useful when there are several repositories of he same quark,
typically one in the own repo and the other one in downloaded-quarks.
If the path is too long to be displayed, it is shortened and prefixed
with “…”.
Moved from #1832.
=> class library display path in quark gui

CMakeLists.txt
Xcode and Visual studio use multi-configuration generators. For those you can only specify the build configuration in the build step.
=> Avoid misleading message for Xcode and Visual Studio

CMakeLists.txt
Use direct test to decide if SSE available, rather than guessing from the CPU name. As recommended for the sc3-plugins project at: https://github.com/supercollider/sc3-plugins/pull/73
=> build: use direct test to decide if SSE available

external_libraries/CMakeLists.txt
Found this while packaging for debian. Fixes a small bug that prevents build if cmake boost is found.
=> cmake: fix build when using system boost

SCClassLibrary/JITLib/ProxySpace/ProxySynthDef.sc
We should be informed how the proxy has adapted to a new shape, despite the warning.
=> class library: node proxy: improve shape error post

SCClassLibrary/Common/Collections/SequenceableCollection.sc, common/sc_popen.cpp, common/sc_popen.h, lang/LangPrimSource/PyrUnixPrim.cpp
fixes #1738 
Incorporated some of @timblechmann 's feedback. 
* changed from malloc/free to new/delete. I wasn't able to use unique_ptr for sc_process due to some very complicated type error.
* removed un-const castings.
* moved function to the same file as other unix primitives. There was no reason for it be in the array primitives file.
tested with:
["/bin/echo","hello","world"].unixCmd
["/bin/echo",1,"world"].unixCmd
[].unixCmd
x = ["/usr/local/bin/scsynth","-u","57128"].unixCmd
pid at x checks out with pgrep.
=> sclang: introduce unixCmd for array of arguments

SCClassLibrary/Common/GUI/Base/QSoundFileView.sc
Match sound file view arguments names to convention and documentation. This may (theoretically) break code, but still seems worth it for the next point release.
=> class library: sound file view - match argument names to convention

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
Instead, add a method `plotAudio` that does it.
=> class library: plot does not specify min and max

SCClassLibrary/Common/Audio/UGen.sc
Both 0 and nil make no sense for MultiOutUGen. This fixes #1686.
=> class library: protect MultiOutUGen from void numChannels

SCClassLibrary/Common/Control/HIDMatchers.sc
Fixes HIDFunc/HIDdef *.usageID, which did not filter incoming
HID values correctly.
=> class library: HIDMatchers: Add missing if statement

server/supernova/sc/sc_plugin_interface.cpp
=> supernova: don't delete shared memory data

SCClassLibrary/Common/Control/asScore/asScore.sc
Due to reliance on "rm" command for oscfile removal invocations of Object: render such as the one below threw an error on Windows.
Pbind(\instrument, \default).render(thisProcess.platform.recordingsDir +/+ "test.aif", 1)
The error you get on Windows is "ERROR: Invalid option ;" thrown from scsynth.exe.
I propose to rely on File.delete instead of "rm".
=> sclang: Fix to get Object: render to work on Windows

editors/sc-ide/core/settings/theme.cpp
* increase the contrast
* avoid blue as foreground color (humans have little blue color receptors
in the center of the retina)
* avoid redish colors as background color (humans have many color receptops
in the center of the retina)
there are probably quite some research papers about color perception ...
maybe something for interested academics to look into
=> scide: improve dark color scheme

HelpSource/BrokenLink.html, HelpSource/Browse.html, HelpSource/OldHelpWrapper.html, HelpSource/Overviews/Classes.html, HelpSource/Overviews/Documents.html, HelpSource/Overviews/Methods.html, HelpSource/Search.html, HelpSource/syntax_colors.html
Some static HTML help files include scdoc.css but not custom.css. This corrects them.
=> Add custom.css to help files that don't include it

SCClassLibrary/Common/Collections/SequenceableCollection.sc
In the class library, variable declarations should always happen
outside statements that can be inlined, like `if` or `while`.
Developers should have switched on the interpreter preference “Post
Inline Warnings”.
I think the preference default should be `on`, to avoid such issues.
=> class library: don't declare variables in an if statement, please.

SCClassLibrary/Common/Quarks/Quarks.sc
Update call to *asRelativePath to include dirname of file. Also fix a bug in *asRelativePath.
=> Quarks: fix save method

CMakeLists.txt, README_WINDOWS.md
To use MinGW 4.9.2 allows to use the same toolchain for sc that is used in the Qt build. The actual underlying issue is beyond my understanding, but Googling it a bit shows that it is not a trivial issue for anybody. In view of that it might simply be more careful to avoid this optimization.
It would be nice to have a quick decision on this, because I'll make a few simplifications to the Readme if this is committed.
=> Remove -fstrict-aliasing from the MinGW build to allow using MinGW 4.9.2

SCClassLibrary/SCDoc/SCDocRenderer.sc
This title is the most prominent text that appears on the screen when launching scide. Having it say "Help" looks rather unprofessional.
=> Change title of main help file from "Help" to "SuperCollider [version]"

HelpSource/Classes/ServerOptions.schelp
Would be nice to have these available in Linux and Windows for 3.8 (#305), but for now let's document it.
=> Document ServerOptions.*devices as OS X only

SCClassLibrary/Common/Quarks/Git.sc, SCClassLibrary/Common/Quarks/Quark.sc, SCClassLibrary/Common/Quarks/Quarks.sc
Even though it was doing git pull, it would not have repositioned to the tip if you had for any reason checked out a different tip (detached HEAD). This has to assume that master is the only branch where the latest update can be found. 
If somebody needs to specify a different branch then they need to do release with tags and check it out by tag.
=> fix #1895 : update Quark by `git pull` and `git checkout master`

editors/scvim/ftplugin/supercollider.vim
The Vim plugin was practically unusable before, throwing errors occasionally because it was sending everything to sclang line by line. The simple fix here fixes such problems. I have tested it for a few days. Big difference in experience.
=> Makes Vim support more reliable by sending larger buffers

lang/CMakeLists.txt, lang/LangPrimSource/OSCData.cpp
This PR reimplements the prMatchLangIP primitive.
- The existing boost::asio implementation caused problems on some platforms
- It is preferable to avoid host resolution in implemeting this
- This default version should work on Linux, OSX, and most nix-y systems
- A windows specific implementation was added using GetAdaptersAddresses
Thanks to @bagong for help testing and debugging the Windows version!
=> Reimplement match lang ip

README_LINUX.md, README_OS_X.md, README_WINDOWS.md
It can be hard to find the list of possible CMake build options; now it's in the README.
=> Add cmake options list to READMEs

HelpSource/Classes/NodeProxy.schelp, SCClassLibrary/JITLib/ProxySpace/ProxySynthDef.sc
The message `WARNING: Synth output should be a flat array` is
documented better, and the error points to the help file.
=> class library: node proxy, improve documentation

HelpSource/Tutorials/A-Practical-Guide/PG_02_Basic_Vocabulary.schelp, HelpSource/Tutorials/A-Practical-Guide/PG_06a_Repetition_Contraint_Patterns.schelp, HelpSource/Tutorials/Getting-Started/02-First-Steps.schelp, HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp, HelpSource/Tutorials/JITLib/jitlib_basic_concepts_01.schelp, HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp, HelpSource/Tutorials/JITLib/jitlib_efficiency.schelp, HelpSource/Tutorials/JITLib/recursive_phrasing.schelp, HelpSource/Tutorials/JITLib/the_lazy_proxy.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/03_Comments.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/04_Help.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/07_SynthDefs.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/15_Groups.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/17_Delays_reverbs.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/21_Syntax_errors.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/22_Runtime_errors.schelp, HelpSource/Tutorials/Streams-Patterns-Events4.schelp, HelpSource/Tutorials/Streams-Patterns-Events5.schelp
Just some minor typos and spelling fixed in the tutorial area of the help documentation
=> help: minor spell fixes in tutorials area

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
I should have submitted this ages ago... just a convenience method.
```
// Without the new method (you've got to be kidding me):
s.sendMsg(\n_trace, Ndef(\name).objects[0].nodeID);
// With the new method:
Ndef(\name).trace;
```
PS Should this be for 3.7 or master? I don't know... at this point it's all rather confusing to me. So I'm putting it into master and somebody else can decide to back port it into 3.7.
=> Classlib: Add NodeProxy:trace

external_libraries/CMakeLists.txt
Thanks Felipe Sateler (debian multimedia team) for diagnosing this. This patch fixes build failure of SuperCollider 3.7 on debian.
The error looks like this fwiw:
>>>> /usr/bin/ld: ../../external_libraries/libtlsf.a(tlsf.c.o): relocation
>>>> R_X86_64_32S against `.rodata' can not be used when making a shared
>>>> object; recompile with -fPIC
>>>> ../../external_libraries/libtlsf.a: error adding symbols: Bad value
=> Fix build on debian, add -fPIC to TLSF target

CMakeLists.txt
Some APIs require a more recent version than XP. Vista seems a reasonable compromise.
=> Make Vista the minimum required Windows version

HelpSource/Classes/Main.schelp
This should go in the helpfile of: OSXPlatform:
method::preferencesAction
note::SCApp only!::
A function to evaluate when the SuperCollider preferences menu is selected.
code::
thisProcess.preferencesAction = { arg process; SCWindow.new.front; }
::
=> removed method::preferencesAction

server/scsynth/SC_PortAudio.cpp
On Linux, SuperCollider's PortAudio driver talks to ALSA (or to PulseAudio using PulseAudio's ALSA compatibility layer).
By default, the current audio driver will use the `default` audio device and [allocate *all* channels](https://github.com/supercollider/supercollider/blob/c017920b29d3fb76b230c14411c46be39b04e9f3/server/scsynth/SC_PortAudio.cpp#L418) reported back by `Pa_GetDeviceInfo()`.
On pure ALSA, the `default` device reports 128 in/out channels.
On PulseAudio, it reports 32 in/out channels.
It isn't necessary to allocate all channels, the application only needs to request the number of channels it actually uses. I didn't find a good explanation for why PortAudio reports these many virtual channels, but [this mailing list thread](http://music.columbia.edu/pipermail/portaudio/2014-Fe …
=> Do not allocate all channels reported by Pa_GetDeviceInfo / use memcpy instead of for-loop

HelpSource/Classes/LFSaw.schelp
This reverts commit 381a3ff0a1c086eb93199149e3fbdfbf1f596c5c which was based on a wrong assumption.
All is well!
=> Revert "LFSaw.schelp: Note and example for special initial-phase behaviour"

HelpSource/Classes/HistoryGui.schelp, HelpSource/Classes/LFSaw.schelp, HelpSource/Classes/Paddpre.schelp, HelpSource/Classes/RLPF.schelp, HelpSource/Classes/SCControlView.schelp, HelpSource/Classes/SinOsc.schelp, HelpSource/Classes/SoundFile.schelp, HelpSource/Classes/Tdef.schelp
=> RLPF.schelp: adjust example to avoid exploding filter due to frequency folding when modulated.

HelpSource/Classes/RecordBuf.schelp
=> RecordBuf.schelp: corrected Synthnames for proper playback, lower volume for overdub

editors/sc-ide/SuperColliderIDE.desktop
As per the desktop entry spec[1]:
- %f: A single file name, even if multiple files are selected.
- %F:A list of files
This allows desktop environments to open multiple files in a single instance
[1] https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
=> ide: mark scide as able to handle multiple files

editors/sc-ide/widgets/multi_editor.cpp
When right -clicking in the tab area, but outside of a tab, the Close
and Close Tabs to the right options do not make sense, and in fact Close
crashes the editor.
Treat this case to offer to close all tabs.
=> sc-ide: fix behaviour of right context button when out of tab

editors/sc-ide/widgets/multi_editor.cpp
Just like in other modern editors and browsers
=> sc-ide: middle mouse button closes tab

.gitmodules, CMakeLists.txt, README_WINDOWS.md, lang/CMakeLists.txt
- use new portaudio repo in SC organization
- this repo is forked from the new pa git repo on assembla
- the additions for SC are added on a separate branch (supercollider)
- master uses dsound from MinGW now for DSound support in the MinGW build
- added small fixes to qt-less build on master
- adjusted Readme
Fixes #2027 and #1975 except fftw localization, which I think would better be solved by configuring the install of the fftw compile
I moved the portaudio submodule to a different folder (portaudio_sc_org), trying to avoid similar problems as with the introduction of the scvim submodule. For a transitional period we will therefore have two repos (one used in 3.7, the other in master/3.8). This way the switch between these branches produces a warning that the other folder cannot be …
=> Switch to portaudio repo in supercollider org

.travis.yml
El-Capitan/XCode 7.3 with deployment target 10.7
Latest master verified to run on 10.7
=> Travis: Update OSX build system and correct omissions

SCClassLibrary/Common/Control/ServerStatus.sc
Explicitly call setter on `unresponsive` in order to trigger the
notification of dependants, in this case the IDE.
This fixes #2082.
=> class library: server notify dependants correctly

include/server/SC_WorldOptions.h, server/scsynth/SC_ComPort.cpp, server/scsynth/scsynth_main.cpp
Add a new command option (-B) to bind to an specific address. The idea
is to allow to bind to the loopback port so that it does not ask for
firewall permissions.
The default is 0.0.0.0, to not change the current behaviour.
This is equivalent to #2081, but on master. I will close #2081 now.
=> scsynth: line option to bind to specific address (master)

lang/LangPrimSource/SC_PortMIDI.cpp
Some initial changes to make midi work in Windows. The main things are:
- Do not open the Microsoft MIDI Mapper device, otherwise we get
multiple allocation errors (I am guessing that the midi mapper tries to
open another device too).
- Open MIDI Input devices on init, if requested by numInputs
- Pass numIn and numOut to the init call, as received by the language
(but is gets 0, when nil, this is wrong)
- For the time being, do nothing on MIDI reset
I have not tested connecting and disconnecting discrete MIDI ports for
now.
Attached a screenshot of my session. I will post the script in the next comment.
Also note, that at least on my 3.7win compilation, I have to delete the Japanese version of Mark's tutorial, otherwise sclang dies while indexing the documentation.
=> midi: make midi work in Windows

CMakeLists.txt, editors/sc-ide/core/sc_process.cpp, lang/LangSource/SC_LanguageClient.cpp, lang/LangSource/SC_TerminalClient.cpp
On Windows (not sure in other OSs) need to cancel the pending read
operation to be able to exit. Otherwise it will wait to get a keystroke
before proceeding further. This is reported in issue #1578.
Note that this does not completely solve the problem reported, but it is not necessary to press a key anymore. We still get the status 3 on exit.
=> lang: Not wait for keystroke when exiting

platform/windows/supercollider.nsi
This allows to open nicely with double click. Without this, the server
is not found.
=> nsis: windows: add path information

editors/sc-ide/core/main.cpp, editors/sc-ide/primitives/sc_ipc_channel.cpp, editors/sc-ide/primitives/sc_ipc_channel.hpp
When you double click on an scd file, and scide was already opened,
scide was ignoring that. The issue is that the IPC mechanism to
communicate with the running instance was using a socket that was not
there yet. I have moved the allocation of the socket to the point where
the connection is made, and it is working ok now.
=> editor: windows: fix double click when app already open

lang/LangSource/PyrObject.cpp
**This is to have windows MSVC compile on master again.**
Because MSVC does not support some C++11 constructs that boost is using.
Note that we can probably streamline the code with some MACROs or
something, but I want to make it very explicit for now, to help with the
PR discussion.
=> sclang: changed some boost code to std

SCClassLibrary/backwards_compatibility/extMethods.sc
All SequenceableCollections should be adequate as arguments to synth
args.
This fixes #2096.
=> class library: fix compatibility of asOSCArgArray

SCClassLibrary/Common/Control/HIDFunc.sc
'super.element' does not have a 'key' argument. So all arguments passed
to the superclass were shifted off by one in position, meaning
the superclass would behave incorrectly.
Copy/paste bug. No reason to leave it broken in 3.7.
=> Classlib: Fix HIDdef.element arg list passed to super.element

.gitmodules
This suggestion is coordinated with @sensestage and was primarily motivated by the current initiative to get HID on Windows to work in a period where @sensestage might be too busy to pay full attention.
Just taking the repo "as is" and switching the source link in .gitmodules with the submodule set to the same commit seems to lead to a completely seamless switch. I haven't experienced any file conflicts/warnings locally when switching branches after this change...
Note that we also started a sketch of a Wiki relating to hid-information/data in the new repo within the SuperCollider organisation.
=> Switch to hidapi subomodule in sc org repo

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
this patch adds warnings and escapes when server is not running and
node proxy is passed messages that only work when server is running.
=> jitlib: better warnings when Server is not available

SCClassLibrary/Common/Core/Object.sc
A stream returned from streamArg should call next before yield. This is
to mimic the `next` that the stream-consumer calls on the stream.
This fixes #2109.
=> class library: streamArg correctly yields

SCClassLibrary/SCDoc/SCDocRenderer.sc
Requested in #2049. The purpose is to disambiguate between helpfile source and class file source.
=> Change "source" to "helpfile source" in scdoc footer

HelpSource/Classes/LFGauss.schelp
better be explicit because the offset can bite.
=> help: document range better for LFGauss UGen

CMakeLists.txt
Proposed as an alternative to #2169
=> build: don't auto-enable supernova if old cmake

server/plugins/OscUGens.cpp
This should fix #2139, but there's a bug. The phase appears to be doubled. Here's a test case:
~bufs = Buffer.allocConsecutive(2, s, 512, 1);
~bufs.do(_.sine1([1], true, true, true));
~phase = 0.25pi;
// these look the same
{ [VOsc.ar(~bufs[0], 20, DC.kr(~phase)), SinOsc.ar(20, DC.kr(~phase))] }.plot(0.1);
// these don't look the same -- why is VOsc offset by 0.5pi?
{ [VOsc.ar(~bufs[0], 20, DC.ar(~phase)), SinOsc.ar(20, DC.ar(~phase))] }.plot(0.1);
Any ideas?
**EDIT:** fixed it, ready to merge!
=> Allow audio-rate phasein argument to VOsc

lang/LangPrimSource/PyrPrimitive.cpp
asStringPerc generates an sprintf statement based on the argument
but sprintfs into a fixed sized buffer. So the value of that argument
can lead to a buffer overflow. Just check it against reasonable lower
and upper bounds.
Addresses https://github.com/supercollider/supercollider/issues/1158
=> asStringPerc SCLang Crash

external_libraries/oscpack_1_1_0/osc/OscOutboundPacketStream.h, external_libraries/oscpack_1_1_0/osc/OscReceivedElements.cpp, external_libraries/oscpack_1_1_0/osc/OscReceivedElements.h, external_libraries/oscpack_1_1_0/osc/OscTypes.h
(amd64, i386, arm64, powerpc and ppc64el...)
Upstreaming a debian patch authored by James Cowgill.
See https://bugs.debian.org/824581 for information.
The patch was new in debian supercollider package version 1:3.7.0_repack-3
I'm proposing the patch for master. It could potentially go to the 3.7 branch too but I'll assume that 3.8 is soon enough that I don't need to.
=> Fix oscpack build fail on various architectures

SCClassLibrary/Common/GUI/Base/QLayout.sc
Currently, it is needlessly difficult to use subclasses of `SCViewHolder` in Qt layouts.
Qt layouts expect all of the member views to be Qt-native objects. However, "has-a" (rather than "is-a") is a standard way to extend the behavior of an object and there is no compelling reason why Qt layouts should rule this out.
This PR adds `.asView` to the items added into a layout. Normal Qt GUI objects simply return themselves. An SCViewHolder returns the view that is being wrapped. (I also had to add an `asView` method to the abstract Layout class, as layouts may be used within other layouts.)
Example: See https://github.com/jamshark70/ddwGUIEnhancements/blob/master/LayoutValueSlider.sc
```
w = Window("test", Rect(800, 200, 400, 50)).front;
w.view.layout = VLayout(
HLayout( …
```
=> Classlib: GUI: Support "has-a" GUI objects by calling asView within Layouts

HelpSource/Guides/WritingUGens.schelp, HelpSource/Reference/ServerPluginAPI.schelp
**Work in progress, do not merge!**
The goal here is twofold -- to make the slope to ugen development much gentler, and to make the API docs more comprehensive. We start off with an explanation of pseudo-ugens, then introduce FAUST, then gradually transition to manually written C++ ugens.
Feel free to contribute and give feedback on whether this is a good approach. I would like help with porting the FAUST instructions for Windows and OS X users, since I have no experience running it on those platforms.
=> Improve "Writing UGens" documentation

CMakeLists.txt, server/CMakeLists.txt
From the documentation it seems the reason is that include_directories()
affects only include paths for targets in the current
CMakeLists.txt. Don't know why this worked before but moving to scsynth
CMakeLists.txt as target_include_directories() works for me.
Fixes #2145
=> move jackey include dir from server to scsynth

SCClassLibrary/SCDoc/SCDocRenderer.sc
Fix #837.
The method renderer checks for getters and setters, and stores the status in `mstat`:
0 = not found
1 = method name only
2 = setter only
3 = getter and setter
Without this change, it writes the method name (without `_`) in *all* cases, without checking `mstat`. But it should write this only if `mstat != 2`. So I move the `x.value` inside the `switch` branches, so that it will be omitted for case 2.
=> Classlib: SCDoc: Do not render 'getter' links for non-existent getters

SCClassLibrary/Common/Quarks/Quarks.sc
=> quarks: throw an error when updating without name

lang/LangPrimSource/OSCData.cpp, lang/LangPrimSource/SC_ComPort.cpp, lang/LangPrimSource/SC_ComPort.h
32-bit IPs from sclang are read as signed integers. They thus need to be
interpreted/cast to unsigned for IPs > 127.x.x.x to be valid. This is
already done for UDP ports, but has been forgotten to be taken care of
for TCP ports.
e.g. this raises a boost error, because an int is first cast to a long and then to an unsigned long instead of the correct detour via an unsigned int.
a = NetAddr("192.168.1.177", 3333);
a.connect;
=> Fix TCP connect for IPs > 127.x.x.x

HelpSource/Reference/Server-Command-Reference.schelp
There's a reference to an arg that doesn't exist
=> Fix /n_order documentation

HelpSource/Classes/ServerOptions.schelp, HelpSource/Guides/ClientVsServer.schelp, HelpSource/Guides/WritingUGens.schelp, HelpSource/Tutorials/Tutorial.schelp, README_LINUX.md
Many docs refer to 'scsynth' when they are talking about the server. I've fixed these in documentation. As supernova is apparently best-supported in Linux, I haven't touched the OS X or Windows READMEs.
I also fixed a path to include/plugin_interface/SC_PlugIn.h
=> Add supernova to some scsynth-specific docs

lang/LangPrimSource/OSCData.cpp
This removes the `empty` message posted when recompiling the library.
Re #2247
=> lang: Remove debug message

HelpSource/Classes/VOsc.schelp, HelpSource/Classes/VOsc3.schelp, HelpSource/Reference/Server-Command-Reference.schelp
I made explicit the fact that the Wave Fill Command flags can be combined by adding them together.  I did this because the use of the flag "7" in the VOsc.schelp example was puzzling to me until I dug into the source code to see that what was happening was that flags 1, 2, and 4 were being summed to give me the "normalize", "wavetable", and "clear" options in one number.
I added helpful comments to the code examples in VOsc.schelp and VOsc3.schelp to explain this, as well.
=> Reference: Server-Command: clarify Wave Fill flags

common/localsocket_utils.cpp, common/localsocket_utils.hpp, editors/sc-ide/CMakeLists.txt, editors/sc-ide/core/main.cpp, editors/sc-ide/core/main.hpp, editors/sc-ide/core/sc_process.cpp, editors/sc-ide/core/sc_process.hpp, editors/sc-ide/primitives/sc_ipc_client.cpp, editors/sc-ide/primitives/sc_ipc_client.hpp, lang/CMakeLists.txt
Still Work in Progress.
For now, it fixes the Windows crash, so this should enable us to move
the Windows development to master again, which we should try to do ASAP.
Since QLocalSocket under Windows is unreliable (it might cut messages),
it is not advised to use QDataStream.
I have changed it to a messaging system based on strings and REs. At the
beginning of each message I put the length of the message, so that the
receiving side knows how much to retrieve.
The change for now is only for the messages coming from SCProcess to
sc_ipc_client direction. **I don't know if something similar needs to be
done in the other direction, or where..., please advise**
=> Fix QLocalSocket problem under Windows

HelpSource/Overviews/SC3vsSC2.schelp
add note that sc3 first came out in 2002. as proposed in https://github.com/supercollider/supercollider/issues/2075#issuecomment-219208378
=> help: SC3 vs SC2: add historical note

HelpSource/Guides/Non-Realtime-Synthesis.schelp
When the user searches for "NRT", the "Non-Realtime Synthesis" help file should show up
=> Add "(NRT)" to the NRT help file title (searchability)

HelpSource/Classes/Bus.schelp, HelpSource/Classes/Env.schelp, HelpSource/Classes/InTrig.schelp, HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp, HelpSource/Tutorials/JITLib/jitlib_basic_concepts_03.schelp, HelpSource/Tutorials/JITLib/jitlib_basic_concepts_04.schelp
These anchor links were broken, mostly due to case-sensitivity
=> Fix some anchor links in help

SCClassLibrary/Common/Quarks/Quark.sc
For some checkout scenarios, we can call Quark:checkout without Quark:git being defined, resulting in an error. You can repro this before the change by running this with a clean repo:
Quark("ServerView").install
Figuring out WHY git is undefined in this case is difficult - it's very order-dependent, and seems to happen only during some nested installs. This fix is a local/safe/obvious fix: make sure git is defined.
@crucialfelix: This is pretty critical - without this, installing at least some quarks is currently blocked. It might be worth searching for a more general fix in case there are other code paths for which Quark:git is nil. It seems safe enough to just lazily create it in a getter, and change any ```git``` references to ```this.git``` - but I'd rather run things by you for a …
=> sclang: Ensure git object is defined for checkout

HelpSource/Classes/VOsc3.schelp
Changed a small typo in the description of the loop arg for the play method.
=> Signal.schelp: small typo fix in play:loop desc

HelpSource/Classes/GrainBuf.schelp, HelpSource/Classes/TGrains.schelp, SCClassLibrary/Common/Audio/BufIO.sc, server/plugins/DelayUGens.cpp, server/plugins/GrainUGens.cpp
The pan argument to TGrains has two problems, originally reported for [TGrains2 in sc3-plugins](https://github.com/supercollider/sc3-plugins/issues/81). One of them is a documentation issue, which says that it behaves like PanAz. The intended behavior is more like GrainBuf, which behaves like Pan2 when the number of channels is 2, and like PanAz for 3 or more channels.
Furthermore, the math of the pan argument is not a correct emulation of Pan2. Here is a crude way to visualize the problem, by plotting a pan from -2 to 2:
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
{ Pan2.ar(SinOsc.ar(440), Line.kr(-2, 2, 1)) }.plot(1.0)
{ TGrains.ar(2, Impulse.ar(100), b, dur: 0.01, pan: Line.kr(-2, 2, 1)) }.plot(1.0)
TGrains wraps around at +-1. Pan2 clips.
This fixes both …
=> server plugins: Unify panning behavior of granular ugens

SCClassLibrary/scide_scqt/ScIDE.sc, editors/sc-ide/core/doc_manager.cpp
Two commits:
1. Should be straightforward: fix the typo that enclosed the path array in single quotes, and add a call to `syncLangDocument` into `DocumentManager::doSaveAs`. I've tested, and this fixes the problems in #2217 with opening and saving documents.
2. Perhaps needs a little discussion. After fixing open/save, now "New document" sets the Document object's path to a string `"nil"`. This seems... shall we say... poorly thought out. My second commit here ensures that the path is a `nil` object (so you can ask `Document.current.path.isNil` and get the right answer). But it might also be useful to set it to an empty string `""`. My gut feeling is that a true `nil` is better, but I'm open to being persuaded the other way. This finishes fixing #2217.
=> Fix Document path sync problems

SCClassLibrary/Common/Audio/InOut.sc, SCClassLibrary/Common/Control/GraphBuilder.sc
This fixes issues with `\name.ar` when a lag is given.
=> class library: implement audio rate lag control

SCClassLibrary/Common/GUI/Base/QLayout.sc, SCClassLibrary/Common/GUI/Base/ext-asLayoutElement.sc
Per discussion under #2188, this adds an interface for validity checking in layouts.
I'm traveling the next 2 days, feedback will be limited, just wanted to get this out there for discussion before leaving.
It passes this very basic test:
```
w = Window("test", Rect(800, 200, 500, 400)).front;
w.layout = VLayout(
[StaticText().background_(Color.rand), stretch: 1],
[StaticText().background_(Color.rand), stretch: 2]
);
```
=> Classlib: GUI: asLayoutElement interface for non-Views that work in layouts

server/plugins/GendynUGens.cpp
The original bug is described here: http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Gendy-instability-td7627785.html
This is kind of an odd way of fixing the bug, and we should discuss it. The standard method would be to write `Gendy*_next_k(unit, 1)`, but that results in a behavior change that removes the first sample of output. Try running `{Gendy1.ar}.plot(1e-3)` and you'll see what I mean.
=> server plugins: Gendy*: fix initialization bug

SCClassLibrary/Common/Control/Spec.sc
Fixes #2318 
Using Class.initClassTree(ControlSpec) in a class could init ControlSpec before Spec causing default specs added in ControlSpec.initClass to be discarded. This is fixed by this one-liner.
=> Make sure Spec is inited before ControlSpec

HelpSource/Classes/History.schelp
Speech is OSX only and potentially slated for removal (see #208 and [this sc-dev discussion](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Time-to-get-rid-of-Speech-td7627124.html))
=> help: History: remove use of .speak in examples

editors/scel/el/sclang-language.el
Fix #132.  Incorrect regexp caused methods names with a capital letter to be interpreted as a class name.  Adding a start of word \\< seems to fix it.
=> Fix emacs show-method bug

.travis.yml, .travis/before-install-linux.sh, .travis/before-install-osx.sh, .travis/before-script-linux.sh, .travis/before-script-osx.sh, .travis/fix-non-Qt.sh, .travis/package-osx.sh, .travis/qpm-prep.sh, .travis/qpm-test.sh, .travis/script-linux.sh, .travis/script-osx.sh, .travis/test.sh
Re #2306 
This adds the following improvements:
- non-qt build for *linux only* (think *rpi*)
- speed up build time down to 28min (instead of 52min) thanks to parallel matrix-builds
- cleanup `.travis.yml` by moving a lot of code in `.travis/*` scripts
Note the following though:
- there's one *qpm* test failing [1] so I disabled `qpm` tests for the linux-non-QT build
- I couldn't get non-QT build on osx (travis) [2]
- osx package is **untested**
- I'm not sure that `QT_PLUGIN_PATH` is correctly set or used, any help on that would be much appreciated
[1] [qpm test error](https://travis-ci.org/gusano/supercollider/jobs/157491200) with `TestPlotter:test_suppliedBounds (0.0s)ERROR: Message 'new' not understood`, I guess @scztt could help ;)
[2] non-Qt will not build on osx (they fail with …
=> Add non-qt build to travis (linux)

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
Unlike ProxySpace when making a NodeProxy via a ProxySpace, Ndef
wouldn’t call this method.
reproducer by Henricus J. Holtman:
```
(
p = ProxySpace.push(s);
p.clock = TempoClock.default;
p.quant = 4;
Pdefn(\nkick, -25);
Pdefn(\nhats, 10);
~out.play;
~out = ~a + ~b;
~a[0] = Pbind(\instrument, \SOSkick, \dur, Pseq([1, Rest(3)], inf), \note, Pdefn(\nkick));
~b[0] = Pbind(\instrument, \SOShats, \dur, Pseq([1, Rest(3)], inf), \note, Pdefn(\nhats));
);
~a.quant.postln; // 4
~b.quant.postln; // 4
~out.quant.postln // 4
but:
(
Ndef(\a).proxyspace.quant = 4;
Ndef(\a).proxyspace.clock = TempoClock.default;
Pdefn(\nkick, -25);
Pdefn(\nhats, 10);
Ndef(\out).play;
Ndef(\out, Ndef(\a) + Ndef(\b));
Ndef(\a)[0] = Pbind(\instrument, \SOSkick, \dur, Pseq([1, Rest(3)], inf), \note, Pdefn(\nkick)); …
```
=> class library: add missing proxy init in Ndef

SCClassLibrary/SCDoc/SCDocRenderer.sc
Windows returns "Help" for var folder. Is this a correct fix (@snappizz?) (tried on Windows and Mac)? Currently the old "Help" is displayed as title on Windows.
=> Adjust Help title for Windows return value of folder

editors/sc-ide/core/sc_server.cpp
Per discussion under #2445, resubmitting for 3.8.
Post-3.8, this should also go into master.
=> IDE: Server status bar should send properly formatted /status message (not 'status')

SCClassLibrary/Common/Control/ServerStatus.sc
don't set client ID if notify failed, and throw an error.
This fixes #2328. Related to #1914.
=> server: don't set client id on failure

HelpSource/Classes/ArrayedCollection.schelp, HelpSource/Overviews/SymbolicNotations.schelp
After being bitten for the thousandth time by the syntax `a[x..y]` behaving differently from my expectation when y < x, I thought it would be worth clarifying in the documentation.
Also, the Symbolic Notations help file incorrectly stated that `a[x..y]` corresponds to the copyRange method. That's wrong -- it's copySeries.
=> Help: Clarify series-notation docs

SCClassLibrary/Common/Streams/Rest.sc
Without this, `Rest(1).isRest` is false!
=> Classlib: Add 'isRest' to Rest

SCClassLibrary/Common/Streams/Rest.sc
```
(
p = Pseries(0, 1, inf).collect { |x|
if(x.odd) { [x, Rest(x)] } { [x, x] }
}.asStream;
)
p.next(());  // [ 0, 0 ], ok
p.next(());  // [ 1, a Rest ] not OK
```
I never noticed this before because `Pbind` does `processRest` on array items distributed to keys -- but I had a case where a (private) pattern expects an array of values, and `processRest` on the array was returning the original array instead of the processed array.
With the fix:
```
(
p = Pseries(0, 1, inf).collect { |x|
if(x.odd) { [x, Rest(x)] } { [x, x] }
}.asStream;
)
p.next(());  // [ 0, 0 ], ok
p.next(e = ());  // [ 1, 1 ], OK
e  // ( 'isRest': true ), OK
```
=> Classlib: Collection:processRest must return the processed value

HelpSource/Reference/plot.schelp
=> scdoc: plot.schelp - fixed wrong key edit mode

HelpSource/Classes/Pstep.schelp, SCClassLibrary/Common/Streams/TimePatterns.sc
This is a fix for issue #2489. I pulled most of the description from PstepDur. While testing out the class I also noticed that it handles `levels` being a list but not `durs`, and I couldn't see a reason why not, so I added a single line to `Pstep.init` to take care of that.
=> class library: improving Pstep input handling and documentation

lang/LangPrimSource/SC_AlsaMIDI.cpp, lang/LangPrimSource/SC_CoreMIDI.cpp, lang/LangPrimSource/SC_PortMIDI.cpp
The limit of 16 was hit too easily, changing it to 128.
(increases the memory footprint of sclang by < 4 KB).
Also warn if exceeding midi in or out ports.
This warning is only posted when the arguments for MIDIClient.init(n, m); are higher than the hardcoded maximum number of midi ports.
This fixes #2492.
=> sclang: increase maximum number of midi ports

SCClassLibrary/Common/Control/asScore/ScoreStreamPlayer.sc, SCClassLibrary/Common/Streams/FilterPatterns.sc, SCClassLibrary/Common/Streams/PatternConductor.sc, SCClassLibrary/Common/Streams/Stream.sc
`event ?? { Event.default }` and NOT `event ? Event.default`
The latter creates wasted objects that may never be used.
Can't believe how many of these were still in there.
=> Classlib: Shortcut Event.default wherever possible

SCClassLibrary/Common/Audio/SystemSynthDefs.sc, SCClassLibrary/Common/Collections/Event.sc, SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc
This is a (minor) API change in the `setBus` event: it holds previous bus values only when `~hold = true`.
=> BusPlug fading to number

HelpSource/Classes/Recorder.schelp, HelpSource/Classes/Server.schelp, HelpSource/Guides/Server-Guide.schelp, SCClassLibrary/Common/Control/Buffer.sc, SCClassLibrary/Common/Control/NetAddr.sc, SCClassLibrary/Common/Control/Node.sc, SCClassLibrary/Common/Control/Recorder.sc, SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/ServerStatus.sc, SCClassLibrary/Common/Control/SystemActions.sc, SCClassLibrary/Common/Control/Volume.sc, SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc, SCClassLibrary/Common/GUI/PlusGUI/Control/server-scope.sc, SCClassLibrary/scide_scqt/ScIDE.sc, editors/sc-ide/core/sc_server.cpp, editors/sc-ide/core/sc_server.hpp, editors/sc-ide/widgets/audio_status_box.cpp, editors/sc-ide/widgets/main_window.cpp
Another PR on top of #2422. This follows @snappizz remark in the discussion that we get a notification from a killed process in sclang (thanks!).
I have tested this in some combinations, please have a look for side effects.
in terminal, call:
`killall scsynth`
this should now properly quit the server representation in sclang.
(again, only the last commit in this branch is relevant)
=> server graceful force quit

HelpSource/Classes/Object.schelp
This commit adds an example to the Object:deprecated help file to demonstrate how to recommend a class method as an alternative. (Also, minor formatting improvements.)
=> help: Object:deprecated: add example

server/plugins/FFT_UGens.cpp
This is embarrassing on two levels:
- Freaking *IFFT* has a Ctor bug and nobody noticed it.
- I somehow missed it while specifically looking for Ctor bugs for #2333.
=> plugins: IFFT initializes outputs

HelpSource/Tutorials/A-Practical-Guide/PG_08_Event_Types_and_Parameters.schelp, SCClassLibrary/Common/Collections/Event.sc
Formerly, ~callback was valid only for event type \on. But there's no reason why it shouldn't be valid for other event types. So, let's make it general.
Documented in the Practical Guide to Patterns chapter on event types. This was the only place that ever documented ~callback; for that matter, I can't find documentation on ~finish anywhere else either.
Addresses #2375 and possibly other issues.
Test case:
```
p = Pmono(\default,
\degree, Pwhite(0, 7, inf),
\dur, 0.25,
\callback, {
var resp;
if(~type == \monoNote) {
~id.debug("made node id");
resp = OSCFunc({ |msg|
msg[1].debug("stopped");
resp.free;
}, \n_end, s.addr, argTemplate: [~id]);
};
}
).play;
p.stop;
```
=> Classlib: Move default Event's ~callback into the ~play function

HelpSource/Tutorials/Getting-Started/16-Sequencing-with-Patterns.schelp
In the tutorial's final chapter on Patterns, I converted names of Px classes to links, so they can be quickly visited within the help system. just a minor cosmetic change really.
=> converted names of classes to links

HelpSource/Reference/Server-Command-Reference.schelp, include/server/SC_OSC_Commands.h, server/scsynth/SC_MiscCmds.cpp
This fixes #2544 for scsynth, but not for supernova.
=> scsynth: implement /version command

SCClassLibrary/Common/GUI/Base/QPen.sc
it seems that "quadCurveTo" should point on "quadTo" prim and not "cubTo" ??
=> replaced CubicTo with QuadTo

SCClassLibrary/JITLib/Patterns/Psym.sc
This fixes #2315. In the future, we could take a look at a way to
implement this, for now better throw an error.
=> class library: Psym1 warns if passed an array

HelpSource/Classes/Pbind.schelp
a missing newline was causing an explanation to be part of example code and making a mess
=> fix a mess caused by a missing newline

HelpSource/Classes/IdentityDictionary.schelp, SCClassLibrary/Common/Collections/Dictionary.sc
Also, clarify documentation and fix a broken link.
Fixes #2499.
=> Classlib: Fix IDict collect, select, reject to keep parent, proto and know

HelpSource/Classes/Object.schelp
This originally started off me as wanting to document the behavior of `.newCopyArgs` when the superclass's `.new` method takes arguments itself, but I ended up getting carried away with tidying up the whole file. Happy to discuss specific changes/conventions.
By the way, you can test this behavior with the following code:
```
// NewCopyArgsTest.sc
TestSuper {
var <v1;
*new {
arg arg1;
^super.newCopyArgs(arg1);
}
}
TestSub : TestSuper {
var <v2, <v3;
*new {
arg arg1, arg2, arg3;
^super.newCopyArgs(arg1, arg2, arg3);
}
}
```
And execute:
```
(
a = TestSuper("test1");
a.v1.postln; // "test1"
b = TestSub("test1", "testB", "test the third");
b.v1.postln; // "test1"
b.v2.postln; // "testB"
b.v3.postln; // "test the third"
"";
)
```
What's unclear to me is how `newCopyArgs` will behave with …
=> Format and refactor Object.schelp and provide better documentation for .newCopyArgs

HelpSource/Classes/Image.schelp, HelpSource/Classes/Interpreter.schelp, HelpSource/Classes/LinSelectX.schelp, HelpSource/Classes/NdefGui.schelp, HelpSource/Classes/ObjectGui.schelp, HelpSource/Classes/PV_Conj.schelp, HelpSource/Classes/Padd.schelp, HelpSource/Classes/PatternProxy.schelp, HelpSource/Classes/PdefGui.schelp, HelpSource/Classes/Pen.schelp, HelpSource/Classes/Pmulp.schelp, HelpSource/Classes/Pmulpre.schelp, HelpSource/Classes/ProgramChangeResponder.schelp, HelpSource/Classes/Psetp.schelp, HelpSource/Classes/Pspawner.schelp, HelpSource/Classes/Quark.schelp, HelpSource/Classes/RawArray.schelp, HelpSource/Guides/How-to-Use-the-Interpreter.schelp
I hope it's okay that I bundled these all together--most are pretty uncontroversial, and I figured it was better than making 20 separate PRs.
I've been using this code to find SCDoc warnings:
```
a = SCDoc.indexAllDocuments;
fork {a.documents.keys.do {|x| HelpBrowser.openHelpFor(x); 0.05.wait}};
```
The majority of these commits fix the issues that generate those warnings. The rest are grammar fixes and similar issues that I discovered during that process. More than happy to discuss and/or walk back changes.
=> Fix multiple .schelp files (grammar, missing args, broken links, missing methods)

HelpSource/Classes/Hasher.schelp, SCClassLibrary/Common/Audio/Noise.sc
In response to #2588.
I changed the summary because technically a hash function involves no randomness. I did leave it in the category `UGens>Random` because that's a pretty good use case; i.e., most people wouldn't actually use this UGen as an actual hashing algorithm.
=> Update Hasher: add input checking, amend helpfile

HelpSource/Classes/Array.schelp
Array.schelp throws "method not found" warnings when it's parsed. I changed the `copymethod::` requests to point to the correct help file when it exists, and deleted `copymethod::` requests for documentation that doesn't exist yet.
=> Fix Array.schelp

HelpSource/Classes/Recorder.schelp, HelpSource/Classes/Server.schelp, HelpSource/Guides/Server-Guide.schelp, SCClassLibrary/Common/Control/Buffer.sc, SCClassLibrary/Common/Control/NetAddr.sc, SCClassLibrary/Common/Control/Node.sc, SCClassLibrary/Common/Control/Recorder.sc, SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/ServerStatus.sc, SCClassLibrary/Common/Control/SystemActions.sc, SCClassLibrary/Common/Control/Volume.sc, SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc, SCClassLibrary/Common/GUI/PlusGUI/Control/server-scope.sc, SCClassLibrary/Common/Streams/Patterns.sc, SCClassLibrary/scide_scqt/ScIDE.sc, editors/sc-ide/core/sc_server.cpp, editors/sc-ide/core/sc_server.hpp, editors/sc-ide/widgets/audio_status_box.cpp, editors/sc-ide/widgets/main_window.cpp
Note: only the last two commits of this branch matter. Since the branch that this one is based on is not yet merged or on upstream, we can't compare against it.
This patch unifies the recording functionality. It makes in more uniform in terms of file names and protects it better from failure.
This patch adds one argument to pattern:record, namely the number of channels for the monitoring. This allows us e.g. to listen to a stereo mix down of a multichannel pattern while recording it on the full number of channels.
this fixes #2415
=> refactor record pattern

HelpSource/Classes/AbstractServerAction.schelp, HelpSource/Classes/Document.schelp, HelpSource/Classes/FlowView.schelp, HelpSource/Classes/LID.schelp, HelpSource/Classes/Pipe.schelp, HelpSource/Classes/SCImage.schelp, HelpSource/Classes/SCImageFilter.schelp, HelpSource/Classes/SerialPort.schelp, HelpSource/Classes/String.schelp, HelpSource/Guides/Glossary.schelp, HelpSource/Guides/News-3_5.schelp, HelpSource/Guides/Server-Guide.schelp, HelpSource/Guides/UsingQuarks.schelp, HelpSource/Guides/WritingClasses.schelp, HelpSource/Guides/WritingHelp.schelp, HelpSource/Overviews/JITLib.schelp, HelpSource/Tutorials/Getting-Started/01-Introductory-Remarks.schelp, HelpSource/Tutorials/JITLib/jitlib_basic_concepts_01.schelp, HelpSource/Tutorials/JITLib/jitlib_networking.schelp, HelpSource/Tutorials/JITLib/proxyspace_examples.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/05_The_network.schelp
This PR adds stylistic consistency by capitalizing "Linux", "Windows", "SuperCollider", and "UNIX" where appropriate.
=> Capitalize OS names in help files

server/scsynth/SC_CoreAudio.cpp
Fix for #2608. The scsynth CoreAudio driver checks to make sure that the sample rates of the input and output devices are the same, and if they are not, an error message is produced and scsynth refuses to boot. This commit skips the check if the number of input bus channels is 0. This allows the command-line option "-i 0" to serve as a simple workaround if the user would prefer to simply ignore the input device.
The driver still queries some information about the input device, so this is sort of a bandage. Also, I'm committing blind, so please test.
=> scsynth: CoreAudio: don't complain about mismatched sample rates if numInputBusChannels == 0

lang/LangSource/PyrLexer.cpp, testsuite/classlibrary/TestParser.sc
Fix for #2624.
Code in PyrLexer.cpp used to be:
```
do {
c = input0();
if (c == '/' && prevc == '*') {
if (--clevel <= 0) break;
} else if (c == '*' && prevc == '/') clevel++;
prevc = c;
} while (c != 0);
```
When the lexer encountered a string like `/* /* */*/`, it would count the `*/*/` as `--clevel` for `*/`, then `++clevel` for `/*`, then `--clevel` for `*/`. I added a few lines so that it immediately eats up any `*/` or `/*` encountered.
Also changed the interpreter messages for open-ended strings/symbols/comments to remove the spurious `...`.
This works for me now:
`/*/* */*/` -> `nil`
`/* /* */ */` -> `nil`
`/*/* */*` -> `Open ended`
`3/*/**/*/*3` -> `9`
=> Fix behavior of nested multiline comments

HelpSource/Classes/Object.schelp, lang/LangPrimSource/PyrPrimitive.cpp
In response to #2615.
Attempting to interpret `3.perform([0])` now results in:
```
ERROR: First element of array must be a Symbol selector.
Integer 0
ERROR: Primitive '_ObjectPerform' failed.
Wrong type.
```
and `3.perform(['+', 5])` still gives `8`.
Todo:
=> Add type checking in `Object.perform`

SCClassLibrary/Common/Audio/SoundIn.sc, SCClassLibrary/deprecated/3.9/AudioIn.sc
and renamed AudioIn.sc to SoundIn.sc. Fix #2429.
=> class library: deprecate AudioIn

lang/LangPrimSource/PyrPrimitive.cpp
Fixes #2540. Also, I've been running with this change for about a month, with no problem.
It might look strange to remove a state reset upon stop, but the line is redundant.
- The Routine object's oldExecutingPath variable is set only when entering the routine, by `next`. This is correct: If the routine is sleeping, then there is no oldExecutingPath.
- oldExecutingPath is, therefore, valid only when the routine is in state `tRunning`. (Routine states: https://github.com/supercollider/supercollider/blob/master/lang/LangSource/PyrKernel.h#L105 )
- The branch where I'm removing the line is only for states `tSuspended` or `tInit`.
- So, oldExecutingPath is invalid here, and we shouldn't be putting invalid data into the interpreter's state.
Note also that it's forbidden to stop a routine while …
=> lang: Do not re-reset nowExecutingPath when stopping a routine

SCClassLibrary/Common/Audio/SystemSynthDefs.sc
Most users use SynthDefs in memory, so there are no SynthDef files to be cleaned. This commit suppresses the "cleaning up temp synthdefs" message if it's not doing anything. I also capitalized "SynthDefs" and expanded "temp" to "temporary."
=> class lib: don't post "cleaning up temp synthdefs" if no SynthDefs are being cleaned up

HelpSource/Classes/Interpreter.schelp, HelpSource/Classes/Method.schelp
Fix for #871.
Most of the documentation is boilerplate from `thisFunction`. I also had to document `Interpreter:-functionCompileContext` in order to properly explain & link from the description of `thisMethod`.
=> Document thisMethod

QtCollider/widgets/QcTextEdit.cpp
So I just wrote DDWSnippets, and part of the intent was to allow its use with TextViews, but then I found:
```
t = TextView(nil, Rect(800, 200, 500, 400)).front;
t.selectedString_("test");
```
Guess what... this inserts nothing.
Why? Because QcTextEdit declares that you should not be able to insert text if there is no current selection spanning at least one character, by accidentally putting `cursor.insertText( string );` inside the `if` block.
```
void QcTextEdit::replaceSelectedText( const QString &string )
{
QTextCursor cursor( textCursor() );
if( cursor.hasSelection() ) {
cursor.removeSelectedText();
cursor.insertText( string );
}
}
```
`Document:selectedString_` does not share this restriction.
Fixed here.
=> Qt gui: Allow TextView selectedString_ to work if selection size is 0

HelpSource/Classes/DynKlank.schelp, HelpSource/Classes/Formlet.schelp, HelpSource/Classes/Klank.schelp, HelpSource/Classes/Ringz.schelp
Explain SR-related amplitude effect -- thanks to Nathan Ho for the explanation. Added to Ringz, with links in Klank, DynKlank and Formlet.
Also add a little note to Klank about a neat trick for a bank of Formlets.
=> Help: Note sr-dependent amplitude in Ringz and related filters

server/scsynth/SC_ComPort.cpp
**This could use a thorough look - I'm new to working on the servers**
> Applications that expect real time responses can react poorly with Nagle's algorithm. Applications such as networked multiplayer video games expect that actions in the game are sent immediately, while the algorithm purposefully delays transmission, increasing bandwidth efficiency at the expense of latency. For this reason applications with low-bandwidth time-sensitive transmissions typically use TCP_NODELAY to bypass the Nagle delay.
https://en.wikipedia.org/wiki/Nagle's_algorithm
sclang and supernova appear to already do this, but scsynth appears not to (and @redFrik 's results on the mailing list *seem* to be consistent with that idea)
=> Disable Nagle's algorithm for scsynth TCP

HelpSource/Classes/MIDIOut.schelp
To indicate that on Windows you must call the function with a full sysex message
=> Update sysex doc

HelpSource/Classes/LanguageConfig.schelp, HelpSource/Reference/Control-Structures.schelp
This makes the output of the code the same as the displayed one, and
make it a little more readable.
Note that the example showed code that was produced with
`Process.tailCallOptimize = false`, this is changed here. I hope that doesn't make it too complicated, but it is the output that the "average user" will see.
=> help: update byte code example

editors/sc-ide/forms/settings_editor.ui
New options were introduced in #2555 that allow using a combobox instead of tabs in the editor view. This commit improves the wording of these options in the settings window to be easier to understand. 
I prefer the term "dropdown" to "combobox." I'm sure more people understand what "dropdown" means.
=> ide: reword "Use ComboBox" options

server/plugins/DemandUGens.cpp, server/plugins/UnaryOpUGens.cpp, server/scsynth/ReadWriteMacros.h, server/scsynth/SC_ComPort.cpp, server/scsynth/SC_CoreAudio.h, server/scsynth/SC_Jack.cpp, server/scsynth/SC_MiscCmds.cpp, server/scsynth/SC_Node.cpp, server/scsynth/SC_SequencedCommand.cpp, server/scsynth/iPhone/iscsynthAppDelegate.h, server/supernova/utilities/freelist.hpp
Clean up a few ambiguous mixes of spaces and tabs. Note this is conservative: mixes for layout, like:
```
\tfoo(2
\t    5);
```
have not been removed.
=> Whitespace: fix some confusing mixes of tabs and spaces

lang/LangPrimSource/PyrPrimitive.cpp, lang/LangSource/PredefinedSymbols.h, lang/LangSource/PyrLexer.cpp, lang/LangSource/PyrMessage.cpp, lang/LangSource/PyrObject.cpp, lang/LangSource/PyrObject.h, lang/LangSource/PyrParseNode.cpp, lang/LangSource/PyrSlot.h
Major changes: 
- Removes ~15~ 19 unused variables in PyrObject.cpp
- Rearrange and label sections of `initSymbols` method for clarity
~Also, if anyone knows why specifically Object, Boolean, Collection, etc. are counted as special symbols above other class names, it would be great to get an explanation on that. Otherwise I'll do some digging on my own.~ Never mind, it's pretty obvious why now.
=> Cleanup PyrObject.cpp:initSymbols()

HelpSource/Classes/Server.schelp, HelpSource/Classes/ServerOptions.schelp
Combined PR for stale PRs #2570, #2571, #2572, #2579, #2581, #2582, #2583, #2584.
I only left off documenting `isRecording` because I think there are probably nuances to this method that neither I nor @tiagmoraismorgado had time to document. Anything I could write wouldn't be more helpful than the name of the method itself.
Also added default value info to `ServerOptions:-pingsBeforeConsideredDead`.
=> Document Server methods

SCClassLibrary/Common/Audio/InOut.sc
A test:
```
{ LocalOut.kr(0) }.asSynthDef; // works
{ LocalOut.kr([0]) }.asSynthDef; // works
{ LocalOut.kr() }.asSynthDef; // fails
{ LocalOut.kr([]) }.asSynthDef; // fails
```
=> Fix LocalOut check

SCClassLibrary/Common/Audio/InOut.sc
This is the test that was explicitly defined in the superclass for that
purpose, so use this.
```
(
var failing = [nil, []];
var working = [0, [0], [0, 0, 0]];
var stubs = [
{ |args| LocalOut.kr(*args) },
{ |args| Out.kr(0, *args) },
{ |args| ReplaceOut.kr(0, *args) },
{ |args| XOut.kr(0, 0.5, *args) },
];
var fails = failing.every { |input|
stubs.every { |func|
var fails = false;
try { { func.(input) }.asSynthDef } { |err| fails = err.isException };
if(fails.not) { "This is a case that should have failed:\n%\nOn this input:\n%\n".postf(func.cs, input) };
fails
}
};
var works = working.every { |input|
stubs.every { |func|
var works = true;
try { { func.(input) }.asSynthDef } { |err| works = err.isException.not };
if(works.not) { "This is a case that should not have failed:\n%\nOn this …
```
=> class library: XOut uses correct input test

server/plugins/FilterUGens.cpp
Fixed an initialization issue where FOS with control-rate coefficient inputs would initialize its coefficients to zero and ramp to the correct coefficients in the first control period. Fix #2656.
Test case:
{ FOS.ar(Impulse.ar(SampleRate.ir / 4), 1, 0, 0); }.plot(0.005)
Unit tests coming soon.
=> plugins: fix FOS initialization

SCClassLibrary/Common/Control/SkipJack.sc, SCClassLibrary/deprecated/3.9/Watcher.sc
Watcher is an alias for SkipJack provided for backward compatibility, emitting a post message that advises the user to use SkipJack instead. This commit puts Watcher on the official deprecation track for removal in 3.10.
=> class library: officially deprecate Watcher

HelpSource/Classes/PinkNoise.schelp, editors/sc-ide/translations/scide.ts, editors/sc-ide/translations/scide_de.ts, editors/sc-ide/translations/scide_es.ts, editors/sc-ide/translations/scide_fr.ts, editors/sc-ide/translations/scide_ja.ts, editors/sc-ide/translations/scide_pt.ts, editors/sc-ide/translations/scide_ru.ts, editors/sc-ide/translations/scide_sl.ts, editors/sc-ide/translations/scide_sv.ts, editors/sc-ide/translations/scide_zh.ts, editors/sc-ide/widgets/find_replace_tool.cpp
In addition to cleanup from #2689, this fixes a typo that's been bugging me since I first started using SuperCollider—"3 _occurrencies_ found" when executing search-and-replace.
=> Two small typo corrections

HelpSource/Classes/VDiskIn.schelp
Clarifying a point that is slightly misleading in VDiskIn help. The old wording says that the OSC message will send back the *frame index within the file*, but this is not true. It always starts with 0 at synth onset. If you cued the buffer into the middle of the file, the real file position is `cuePoint + msg[3]`.
Documentation should not assume that the user will always play the file from the beginning.
=> Help: Clarify VDiskIn's outgoing OSC is not the file position

common/SC_Win32Utils.h, external_libraries/boost/boost/thread/executors/basic_thread_pool.hpp, lang/LangSource/GC.cpp
This fixes [mingw gcc-4.9+ ICE](https://gist.github.com/bagong/0084f016cb80e61e0949c0f5b0f130a6)
I can now build HEAD supercollider with stock MSYS2 64-bit gcc compiler/libraries (no manual tools/libraries installation).
Perhaps, this should be submitted to `boost` in the first place, though.
I've also guarded this with `__MINGW32__` since I'm not sure if another platform's GCCs suffer from the problem.
=> Fix mingw gcc-6.2 ICE.

editors/sc-ide/CMakeLists.txt, lang/CMakeLists.txt, platform/windows/junctions.bat, platform/windows/symlinks.sh
For VS and MinGW native "junctions" are used
For MSYS symlinks
see #2479
=> Winbuild: link rather than copy class, help- and some other files into the target build-folder

lang/CMakeLists.txt, platform/windows/junctions.bat
There is a bad bug in the symlink feature #2708. If you build a second time some symlinks are overwritten with symlinks, and thereby the content of the linked files deleted (only relevant for Windows builders :) ). This should fix it.
=> Fix symlinks in win build system (urgent :)

HelpSource/Classes/MIDIOut.schelp
This has confused at least one user: http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/sysex-failure-td7630588.html#a7630591
It needs to be made clear that it will only accept an `Int8Array`.
=> Update documentation for MIDIOut:-sysex

HelpSource/Classes/Image.schelp
PrimitiveFailedError without this
=> Help: Add required standardizePath into Image:write example

SCClassLibrary/Common/Audio/Poll.sc, SCClassLibrary/Common/Control/Buffer.sc, SCClassLibrary/Common/Control/Bus.sc, SCClassLibrary/Common/Control/Node.sc, testsuite/classlibrary/TestBuffer.sc, testsuite/classlibrary/TestBus.sc, testsuite/classlibrary/TestCoreUGens.sc, testsuite/classlibrary/TestEvent.sc, testsuite/classlibrary/TestNode.sc
Fix #2721. Removes uses of OSCpathResponder in Buffer, Bus, and Node. Unit tests are needed here.
=> class lib: stop using OSCpathResponder

README_LINUX.md, editors/sced/CMakeLists.txt, server/plugins/CMakeLists.txt, server/scsynth/CMakeLists.txt, server/supernova/server/main.cpp
Some distributions require native binaries / libraries to be install into a library directory with a suffix, e.g. the most common one is lib64.
With cmake a common way to solve this is to use the `LIB_SUFFIX` variable, even some buildsystem use this when building with cmake (e.g. openSUSE's and fedoras RPM buildsystems define this variable for cmake calls).
=> Allow setting LIB_SUFFIX variable to install libraries into lib64 etc

editors/sc-ide/SuperColliderIDE.desktop, platform/linux/supercollider.xml
When building for openSUSE I noticed that the .desktop file was considered invalid, this can be verified by using the command line tool: `desktop-file-validate`, this is now fixed.
I also added the missing pattern to the mime xml to correctly link sc files with the ide.
=> Fixed invalid .desktop file and added missing pattern to mime xml

editors/sc-ide/widgets/code_editor/autocompleter.cpp
I have no clue what I did here but it seems to fix #1704.
=> scide: make tooltip text black on Linux

SCClassLibrary/Common/Streams/Rest.sc
I used to debug some Event issues like so:
```
(
Pbind(
\degree, Pseq([0], 1)
).collect { |ev| thisThread.clock.sched(0, { ev.keys.debug }); ev }
.play;
)
```
So... the Pbind would return an event. Event:playAndDelta would play it. Then the scheduled function would wake up and have access to the work that Event:play did.
But tonight I find that the event instance passed into collect is not identical to the one that is played...? I inserted a "this.dump" into Event:play, and:
```
(
Pbind(
\degree, Pseq([0], 1)
).collect { |ev| "collect:".debug; ev.dump; ev }
.play;
)
```
collect:
Instance of Event {    (0x6b2f0c8, gc=E0, fmt=00, flg=00, set=03) ...
Instance of Event {    (0x5347f48, gc=E4, fmt=00, flg=00, set=03) ...
So I managed to break a very useful technique by implementing …
=> Classlib: Event:processRest needs to return itself

HelpSource/Classes/AbstractServerAction.schelp, SCClassLibrary/Common/Control/SystemActions.sc
When adding an object to a server action without telling what server is
meant, it adds to “all”. This should be the same for when removing an
object.
This fixes #2747.
=> class library: make server action *remove consistent with *add

CMakeLists.txt
Required from VS2015 update 2 upwards. A discussion of the issue is linked in the comment.
=> Win: add definition for VS2015 build

server/scsynth/SC_SequencedCommand.cpp
This fixes #2474, an uninitialized memory issue in /b_read and /b_readChannel which was causing nondeterministic failures in Buffer.cueSoundFile. libsndfile's sf_open takes as input a pointer to an SF_INFO struct, to which it writes its soundfile metadata. However, the SF_INFO struct's "format" parameter of the struct must be set to zero, otherwise (as best as I can tell from the sf_open docs) the audio is read in a raw format. Failure to initialize the SF_INFO memory is therefore a bad idea, and zeroing out the memory ensures that the raw format is not accidentally invoked.
Thanks to @Sciss and @bagong for helping to investigate this issue.
=> scsynth: /b_read[Channel]: fix failure in sf_open caused by uninitialized memory

editors/sc-ide/core/sc_server.cpp
Eliminates the following error message thrown during ScIDE startup:
```
QObject::connect: No such slot ScIDE::ScServer::pauseChanged(bool) in
/Users/brianheim/git/supercollider/editors/sc-ide/core/sc_server.cpp:171
```
pauseChanged is a signal, not slot, of ScServer. (see [corresponding header file](https://github.com/supercollider/supercollider/blob/master/editors/sc-ide/core/sc_server.hpp#L91-L123) and [compare these code blocks](https://github.com/brianlheim/supercollider/blob/06c7eabb4437a375b45c33e9b5c2904f2427686a/editors/sc-ide/core/sc_server.cpp#L162-L172)).
=> Patch runtime ScIDE error

SCClassLibrary/Common/GUI/Base/QView.sc
Fixes #2804.
I was trying to back off from dev work, but... it's really really annoying when I drag a view in my standard GUI and the post window barfs up a bunch of errors.
=> Classlib: GUI: View must not throw an error for default drag methods

README_WINDOWS.md
- bold instead of italicize package names
- copyedit intro
- small copyedits elsewhere for style and tone
- fix broken links
- correct package names for Qt 5.5.1
I guess you have to escape close-parens in link descriptions; that was the main motivation for submitting this. Without a close paren, most of the links in the readme are broken, at least while reading on GitHub.
=> Windows readme: cosmetic changes

SCClassLibrary/JITLib/ProxySpace/ProxySynthDef.sc
In many situations, one would expect `proxy.ar` to return a single
channel, but it returns an array (there are good reasons for this,
discussed in NodeProxy help under routing).
But in order to avoid being overly strict, we treat a singleton channel
as a channel for a proxy _input_ (that is the result of the UGen
function).
It will still warn if there are more UGens in the nested arrays.
=> class library: NodeProxy - tolerant handling of nested output

SCClassLibrary/Common/Streams/FilterPatterns.sc
From the discussion of Pn/Pgate on sc-users, I found a little bug.
Pn's help implies that it sets the flag every time the subpattern starts. But it doesn't do this for the first repeat. Pn's logic "cheats" and sets *after* the pattern, not at the beginning. This has an unintended consequence: an immediately following Pn does *not* trigger a new value in Pgate.
```
(
p = Pbind(
\degree, Pseq([
Pn(Pseries(0, 1, { rrand(2, 5) }), 3, \nextDur),
Pn(Pseries(0, 1, 10), 1, \nextDur)
], 1),
\dur, Pgate(Pexprand(0.1, 0.25, inf), inf, \nextDur)
).trace.play;
)
( 'degree': 0, 'dur': 0.10465929123453 )
( 'degree': 1, 'dur': 0.10465929123453 )
( 'degree': 2, 'dur': 0.10465929123453 )
( 'degree': 3, 'dur': 0.10465929123453 )
( 'nextDur': true, 'degree': 0, 'dur': 0.14876536558564 )
( 'degree': 1, 'dur': …
```
=> Classlib: Patterns: Pn should set flag at onset

SCClassLibrary/Common/Streams/Patterns.sc
This is like in Object:fin. This fixes #2815.
=> class library: default argument for pattern fin

server/plugins/DelayUGens.cpp
Fixes #2807, a regression caused by #2136 (https://github.com/supercollider/supercollider/pull/2136/commits/f35a3f7f1552266fda04e326474dd678177b2ba5).
This should work correctly now:
```supercollider
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
{ // This should fade in... but starts at full volume
TGrains.ar(2, Impulse.ar(15), b, centerPos: Line.ar(0, 5, 10, doneAction: 2), amp: Line.ar(0, 1, 10));
}.play;
```
=> Fix broken TGrains `amp` handling

HelpSource/Classes/UnixFILE.schelp, SCClassLibrary/Common/Audio/SynthDef.sc, SCClassLibrary/Common/Audio/SynthDefOld.sc, SCClassLibrary/Common/Audio/UGen.sc, SCClassLibrary/Common/Streams/IOStream.sc, SCClassLibrary/Common/Unix/UnixFILE.sc
Fix for #2803.
```supercollider
SynthDef(($a!256).join, {}).add; // causes a crash
```
This was because `putPascalString` wasn't properly checking that it could properly represent its argument before printing: if a string with `size >= 256` was passed in, it would silently write `size % 256` followed by the string.
This PR adds a validation check in `putPascalString` (in both UNIXFile and CollStream) that throws an error when its input string has `str.size >= 256`. It also wraps calls to this method in the standard class lib with a try-catch. I thought this would be the best approach because it allows us to print a more relevant error message.
Originally I decided to protect the error by closing the passed-in file in the catch block, but on second thought I nixed it since the method isn't …
=> Add input validation to putPascalString

SCClassLibrary/Common/Control/Buffer.sc
Neither `Buffer:free` nor `Buffer:freeMsg` check to see if `bufnum` is valid before issuing `/b_free` to the server. This interacts badly with a "feature" of the server where a nil parameter is interpreted as 0.
```
s.boot;
b = Buffer.read(s, Platform.resourceDir +/+ "sounds/a11wlk01.wav");
a = { PlayBuf.ar(1, b, loop: 1).dup }.play;
c = Buffer.alloc(s, 4096, 1);
// c has a bufnum, so the command is ["/b_free", 1], no problem
c.free;
// c's bufnum has been cleared -- 'free' should logically be a no-op now
// Instead, the command is ["/b_free", nil]
// The server evaluates it as ["/b_free", 0]
c.free;
-> Buffer UGen: no buffer data
```
... with the result that the second `c.free` ends up releasing **b**'s data from the server!
It's a small bug fix, but I would consider this important for …
=> Classlib: Don't try to free a buffer after it was already freed

HelpSource/Classes/AllpassC.schelp, HelpSource/Classes/AllpassL.schelp, HelpSource/Classes/AllpassN.schelp, HelpSource/Classes/Buffer.schelp, HelpSource/Classes/CombC.schelp, HelpSource/Classes/CombL.schelp, HelpSource/Classes/CombN.schelp, HelpSource/Classes/Float.schelp, HelpSource/Classes/SimpleNumber.schelp
Since I'm pretty confident that these are uncontroversial, I'm grouping them all in one PR. In summary:
- Much clearer wording for SimpleNumber:coin.
- Add a note about DC bias sensitivity in Comb*.
- Expand Allpass* documentation to state explicitly that these are Schroeder allpasses ([example of use](https://ccrma.stanford.edu/~jos/pasp/Schroeder_Allpass_Sections.html)), and give difference equations.
- Elaborate some technical details on Buffer.
=> Several help improvements

HelpSource/Classes/Env.schelp, HelpSource/Classes/EnvGen.schelp, SCClassLibrary/Common/Audio/Env.sc
Fix for #2858.
The old argument names were misleading. `EnvGen.kr/ar` actually use their 'mul' and 'add' for levelScale and levelBias, which are not the same thing.
Rename them to match the corresponding arguments to EnvGen.ar/kr. Also update the documentation to reflect these changes. I chose this solution because it's the least intrusive and seemed to have general support.
=> class lib: Env:-kr/-ar : rename arguments to match functionality

editors/sc-ide/core/doc_manager.cpp
```supercollider
Document.current.selectedText_("abc");
```
Expected behavior: add `abc` to current document.
Actual behavior: nothing.
In `DocumentManager::handleSetDocTextScRequest`, which is called to set document text in the IDE, the parameter `funcID` is `Null` in many instances, which would cause the function to bail out early while trying to parse a null node as a string:
```cpp
std::string funcID = doc[1].as<std::string>(); // throws if doc[1].IsNull()
```
After this commit, `funcID` is only parsed if it is not null, and a function call to `Document.executeAsyncResponse` is, again, only made if the funcID is non-null.
I added debugging code to the try-catch blocks in this file so this is easier to diagnose in the future. I don't have time to check if any other functions are …
=> IDE: Fix YAML parsing issue affecting Document.selectedString_

.gitignore
This ignores the default directories generated by CLion.
Other projects that do this, for reference:
https://github.com/lballabio/QuantLib/blob/master/.gitignore
https://github.com/aws/aws-sdk-cpp/blob/master/.gitignore
https://github.com/zhuhaow/libnekit-c/commit/32d77b609e67e9e2f3eb27ea9a66540a4979bc3b
=> Add CLion directories to main gitignore

HelpSource/Classes/SequenceableCollection.schelp, SCClassLibrary/Common/Collections/SequenceableCollection.sc
The method `reduce` takes a binary operator selector (or an appropriate
function) and applies it to the collection’s items incrementally.
This patch allows us to pass an adverb to the operator, as commonly
expected for binary operations. If the operator is a function, the
adverb is the third argument.
These two expressions return the same value:
```
[1, 2] *.t [10, 20, 30]
[[1, 2], [10, 20, 30]].reduce('*', 't')
```
This feature is justified because it exposes the interface of binary
operators and calculations by reduce are very compact.
=> class library: adverb argument for reduce

HelpSource/Classes/Platform.schelp, SCClassLibrary/Platform/Platform.sc
This PR adds the already documented but missing class method 'recordingsDir' to Platform.sc. I also added documentation for the method 'userHomeDir'.
=> Add missing method 'recordingsDir'

lang/LangPrimSource/PyrPrimitive.cpp, lang/LangSource/VMGlobals.h
- the previous version posted exception errors in ```doPrimitive```, rather than setting them in the Error via ```prPrimitiveErrorString``` as for other primitive errors. This prevented sclang try / catch from truly catching the error.
- This could be annoying in cases like network music situations, where a stream of errors resulting from another host going down could not be handled as desired even though the problem had nothing to do with SC, or even the local machine.
- this version fixes that, and makes the error message clearer and more informative
I'd be grateful if someone can check this and confirm this is the proper/best way to handle this.
=> Fix SC try / catch behaviour for primitive exception errors

HelpSource/Classes/View.schelp, SCClassLibrary/Common/GUI/Base/QView.sc, SCClassLibrary/Common/GUI/Base/QWindow.sc
This PR improves the situation described in issue #195 by adding two new methods to QView : resizeToHint and reizeToBounds.
```
// not correct, view too small
w = Window("Test",Rect()).layout_(
QVLayout( QStaticText().string_("Hello layout"), QButton() )
).front;
// correct size
w = Window("Test",Rect()).layout_(
QVLayout( QStaticText().string_("Hello layout"), QButton() )
).view.resizeToHint.front;
```
=> Added resizeToBounds and resizeToHint methods

QtCollider/QObjectProxy.cpp, QtCollider/primitives/prim_QObject.cpp, common/SC_Lock.h, lang/LangPrimSource/OSCData.cpp, lang/LangPrimSource/PyrPrimitive.cpp, lang/LangPrimSource/PyrSched.cpp, lang/LangPrimSource/PyrSerialPrim.cpp, lang/LangPrimSource/PyrUnixPrim.cpp, lang/LangPrimSource/SC_ComPort.cpp, lang/LangSource/PyrObject.cpp, lang/LangSource/SC_TerminalClient.cpp, lang/LangSource/SC_TerminalClient.h, server/plugins/CMakeLists.txt, server/plugins/DiskIO_UGens.cpp, server/plugins/UIUGens.cpp, server/plugins/UIUGens.mm, server/scsynth/SC_ComPort.cpp, server/scsynth/SC_CoreAudio.cpp, server/scsynth/SC_CoreAudio.h
Hi. This is my second set of commits for FreeBSD compatibility. The first is for hidapi here: https://github.com/supercollider/hidapi/pull/8
With these commits you will able to build Supercollider on FreeBSD smoothly (provided you have Qt5Positioning which is not in the port collection). Btw., what is Qt5Positioning for? Is it really used in Supercollider?
=> Freebsd compat

HelpSource/Classes/Maybe.schelp, SCClassLibrary/JITLib/Patterns/Fdef.sc
=> Maybe overrides more parent methods

testsuite/classlibrary/TestBus.sc
this fixes #2758 by temporarily disabling the failing test `TestBus:test_free`. as a quick fix, i have prefixed the test name with `ignore_` so UnitTesting will not notice it.
#2760 and #2761 are the proper fixes, but with all due respect to the productive discussion and work going into them, they are taking too long. failing tests in master are pretty urgent. we shouldn't accept any PR with failing tests.
once a proper fixed is merged in, the test should be reenabled.
=> Disable failing test TestBus:test_free

lang/LangSource/PyrInterpreter3.cpp, testsuite/classlibrary/TestDictionary.sc
This can happen in corner cases. Fixes #852.
=> sclang: protect keysValuesArrayDo primitive

HelpSource/Classes/ReplaceOut.schelp
Wanted to see how difficult it was to make changes to Help. Not as fun as I though it would be...
Added missing links to Synth and Order-of-execution to ReplaceOut help file.
=> [Help-fix] add link to Synth and Orde-of-execution

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
`MixedBundle` allows to schedule a function when sending happens. This
is what was used to schedule into the future the clearing of the old
group. It is much better to just delegate this to the server. Because
group  objects are registered by NodeProxy with the NodeWatcher, it is
also released correctly. ( `NodeWatcher.newFrom(s).nodes`).
We need to add a very small offset between the bundle timestamps, so their order is guaranteed on the server.
=> class library: fix possible sync problem in NodeProxy clear

HelpSource/Classes/SoundFileView.schelp, QtCollider/widgets/soundfileview/view.cpp, QtCollider/widgets/soundfileview/view.hpp
This fixes #2033, an issue regarding the `gridResolution` and `gridOffset` behaviors of `SoundFileView` as well as a problem with selections not being visible.
```supercollider
(
w = Window.new("soundfile test", Rect(200, 300, 740, 100));
a = SoundFileView.new(w, Rect(20,20, 700, 60));
f = SoundFile.new;
f.openRead(Platform.resourceDir +/+ "sounds/a11wlk01.wav");
a.soundfile = f;
a.read(0, f.numFrames);
a.timeCursorOn_(true);
a.gridResolution = 2;
a.gridOffset = 0;
w.front;
)
// other resolution and offset values
a.gridResolution = 1;
a.gridResolution = 0.5;
a.gridOffset = 0.25;
a.gridOffset = 0.75;
// also try zooming with shift+mouse-drag
```
- The leftmost grid block was only half revealed.
- The grid blocked the selection highlight.
- Setting `gridResolution <= 1` did not work: the …
=> GUI: Fix SoundFileView grid behavior

editors/sc-ide/widgets/settings/sclang_page.cpp
The port to yaml-cpp 0.5 API had a couple of bugs in the IDE code. These are fixed by this commit.
Fixes #2878.
=> ide: fix #2878 Interpreter options blank in IDE

cmake_modules/MacOSXBundleInfo.plist.in
As discussed in https://github.com/supercollider/supercollider/issues/2471:
I opted to just put the same version information in both keys. Ideally for `CFBundleVersion` one might instead have some kind of auto-incrementing "build number" or similar, but I'm not sure there's any such data that is useable for that. With this, there's at least a logically-incrementing `major.minor.patch` in at least one consistent location for a publicly-released version, which makes it much easier to compare two versions on a system.
I omitted the second `.` to separate the version substitutions because it seemed to me that `PROJECT_VERSION_PATCH` always contains a leading dot.
Thanks for your consideration!
=> Use major.minor.patch in Info plist version keys

SCClassLibrary/SCDoc/SCDoc.sc, SCClassLibrary/SCDoc/SCDocRenderer.sc
Fixes #692.
Before, Cat>Subcat>Subsubcat would be one link. Now, each part of that
path is a separate link, with Cat going to Cat, Subcat going to
Cat>Subcat, etc.
Should I also increment the version number is SCDoc? (https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/SCDoc/SCDoc.sc#L363)
=> SCDoc: make each category breadcrumb a separate link

editors/scel/el/sclang-language.el, editors/scel/el/sclang-mode.el
Hi,
These changes should prevent Emacs from failing to fontify class names when lots of classes exist in sclang (i.e. when many quarks are installed). I've elaborated in the commit messages, but the general idea of these changes is this:
- instead of generating a huge regexp containing every class name in SuperCollider, just use a general class regexp, which is: any word starting with a capital letter. Before SuperCollider is started, all words starting with a capital letter will be highlighted as class names. After SC is started, only words starting with a capital letter that are actually class names will be highlighted.
- when sclang starts, we generate a list of classes and store it in `sclang-class-list` so we can refer back to it later during fontification (lines 223-226 in …
=> Prevent Emacs fontification failure with lots of classes - Fixes #248

HelpSource/Classes/TempoClock.schelp, HelpSource/Guides/ServerTiming.schelp, SCClassLibrary/Common/Core/Clock.sc, lang/LangPrimSource/PyrSched.cpp
This fixes #2077.
Someone with deeper insight into clock scheduling could check if the explanations in the helpfile are ok.
=> fix inconsistent state of clock when tempo is set via setTempoAtSec

HelpSource/BrokenLink.html, HelpSource/Browse.html, HelpSource/Overviews/Classes.html, HelpSource/Overviews/Documents.html, HelpSource/Overviews/Methods.html, HelpSource/Search.html, HelpSource/scdoc.js, SCClassLibrary/SCDoc/SCDocRenderer.sc
appends the suffix `| SuperCollider [version] Help` to the <title> element of every generated HTML file in SCDoc. (It's not possible to dynamically get the version in some static files like Search and Browse, so I just added `| SuperCollider Help` to those.) also, added html5 doctypes and lang attributes while we're at it.
(the new `<script>` tags don't have `type="text/javascript"` because [its no longer required](https://www.w3.org/TR/html5/scripting-1.html#attr-script-type).)
for some reason this changed the style of the links in the header, i dunno why.
=> scdoc: Append "| SuperCollider Help" to all <title> elements

HelpSource/Browse.html, HelpSource/OldHelpWrapper.html, HelpSource/Overviews/Classes.html, HelpSource/Overviews/Documents.html, HelpSource/Overviews/Methods.html, HelpSource/Search.html, HelpSource/scdoc.css, SCClassLibrary/SCDoc/SCDocRenderer.sc
towards #2943. remove horizontal line for better use of negative space, use a darker shade of gray for accessibility, uncapitalize the shouty "CLASSES," add version number to header and remove version number from footer, combine folder and categories into a single line, add thin spaces around breadcrumb `>` for better visual balance
=> scdoc: redesign label/categories

HelpSource/scdoc.css
for #2943.
make horizontal lines under `<h2>` elements less bold.
sorry, github's image upload feature is glitchin out on me and i can't upload screenshots.
=> scdoc: lighten horizontal lines

SCClassLibrary/Common/Control/Buffer.sc, SCClassLibrary/Common/Control/Bus.sc
Fixes #2851 (and see discussion #2846) 
Some methods need to check that a Buffer/Bus is still valid before doing anything potentially destructive. The Server interprets 'nil' as zero in received messages. This means that Buffer and Bus index:0 are at risk of being modified when some methods are called on previously freed Buffers/Busses. 
Hopefully, this solution is acceptable. Please review and critique away! :)
=> Buffer and Bus validity checks and Errors

server/plugins/DelayUGens.cpp
fixes #2904. test case:
{ Pitch.kr(SinOsc.ar(440 * Hasher.ar(Sweep.ar)), median: 10)[0] }.plot(0.5);
changing `median` has no effect in master, and this commit seems to fix it.
=> plugins: fix Pitch median filter size

HelpSource/Classes/Char.schelp, HelpSource/Classes/Symbol.schelp, SCClassLibrary/Common/Core/Char.sc, SCClassLibrary/Common/Core/Symbol.sc, lang/LangPrimSource/PyrSymbolPrim.cpp, testsuite/classlibrary/TestSymbol.sc
implement #2952. we're going to be using these methods in SCDoc so why not make 'em faster with primitives. also, i need some experience writing primitives.
all documented, unit tested, and ready to go.
=> Implement Symbol:isBinaryOp and Symbol:isIdentifier

lang/LangSource/PyrObject.cpp
per discussion at #2923, these are memory addresses of DebugFrame objects, not sclang objects, so they aren't useful to anyone. already looking cleaner :D
```
ERROR: hey
CALL STACK:
Exception:reportError
arg this = <instance of Error>
Nil:handleError
arg this = nil
arg error = <instance of Error>
Thread:handleError
arg this = <instance of Thread>
arg error = <instance of Error>
Object:throw
arg this = <instance of Error>
Interpreter:interpretPrintCmdLine
arg this = <instance of Interpreter>
var res = nil
var func = <instance of Function>
var code = "Error("hey").throw"
var doc = nil
var ideClass = <instance of Meta_ScIDE>
Process:interpretPrintCmdLine
arg this = <instance of Main>
^^ The preceding error dump is for ERROR: hey
```
=> lang: remove stack frame memory addresses from call stack output

HelpSource/scdoc.css, SCClassLibrary/SCDoc/SCDocRenderer.sc
towards #2943. removes cluttersome gray backgrounds and horizontal lines, displays instance methods with a leading "." (except for binary operators) and classes with a leading "ClassName.".
again i can't post screenshots, just try it. to me it's a huge improvement :)
=> scdoc: redesign method rendering

.travis.yml, .travis/before-install-linux.sh
See https://blog.travis-ci.com/2017-06-19-trusty-updates-2017-Q2 for details
In a nutshell: Travis says to add this line to config for Ubuntu builds because there'll be an update tomorrow.
=> Travis: add `group: edge` for Ubuntu builds

SCClassLibrary/Common/Control/Buffer.sc
This PR is a redo of my previous work on checking for freed Buffers. The checks now happen inside the `Msg` methods. `OSCFunc`s have also been moved inside these `Msg` methods. The `Msg` methods are now consistently called in order to construct the Server messages. 
Thank you for testing and reviewing!
=> Improve checking for nil Buffers

QtCollider/widgets/QcWebView.cpp, QtCollider/widgets/QcWebView.h
Fixes #2295
Use `int` type instead of QWebPage::LinkDelegationPolicy
The property was failing to connect because something somewhere didn't
recognize that an enum can be cast to an int.
=> QcWebView: use int instead of enum for linkDelegationPolicy

SCClassLibrary/Common/Control/ResponseDefs.sc
`getKeysForFuncProxy` should always return a collection, because of where it's used:
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/ResponseDefs.sc#L131-L132
```
keys = this.getKeysForFuncProxy(funcProxy);
keys.do({|key| active[key] = active[key].addFunc(func) }); // support multiple keys
```
All of the other MIDI***Dispatcher classes do `asArray` in getKeysForFuncProxy... MIDISysexDispatcher, uniquely, does not:
```
getKeysForFuncProxy {|funcProxy| ^(funcProxy.srcID ? \all)}
```
So, when the srcID is a very large integer, `keys` becomes a large integer, and then `keys.do` will add a new item into `active` that number of times. Millions of times. Potentially-crashy numbers of times.
Fixes #2937.
=> Classlib: MIDISysexDispatcher keys must be an array, not a large integer

HelpSource/Browse.html, HelpSource/OldHelpWrapper.html, HelpSource/Overviews/Classes.html, HelpSource/Overviews/Documents.html, HelpSource/Overviews/Methods.html, HelpSource/Search.html, HelpSource/scdoc.css, HelpSource/scdoc.js, SCClassLibrary/SCDoc/SCDoc.sc, SCClassLibrary/SCDoc/SCDocRenderer.sc
uuuugggh whens github going to fix their damn image upload feature.
anyways, so this might be a little controversial, since it "undocks" the top bar in the help files. the main advantage is reducing visual clutter (and looking a touch more modern). as discussed at #2943, there's a problem where this top bar competes with the decorations on the help window. the disadvantage is that now you have to scroll back up to find what page you're on, and to access Browse/Search/Table of contents. it is of course still possible to navigate back to the home page in one click.
before you pull out the pitchforks, i'd like to point out that no other documentation system i've seen has this `position: fixed` menu. ~~also, i don't think i've been in a situation where i need to know what page i'm on.~~ …
=> scdoc: redesign top bar

HelpSource/scdoc.css, SCClassLibrary/SCDoc/SCDoc.sc, SCClassLibrary/SCDoc/SCDocRenderer.sc
Towards #2943. This commit improves the design of the subheader. It is no longer right-aligned. The source filename is reduced to include only the file name (which can still be viewed in full by hovering over or clicking), the superclasses are incorporated into the title. The "see more..." line for subclasses is cut down from 13 classes to 4.
=> scdoc: redesign subheader

lang/LangPrimSource/PyrUnixPrim.cpp
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/What-is-QSocketNotifier-Can-only-be-used-with-threads-started-with-QThread-tp7633245p7633253.html
In short: If you use GUI objects in an action function for `unixCmd`, the GUI objects do not display.
```
"ls".unixCmd({
defer {
StaticText(nil, Rect.aboutPoint(Window.screenBounds.center, 80, 60))
.string_("Hello").align_(\center)
.front
}
});
```
Debugging details are in the mailing list post. The gist is that `doUnixCmdAction` runs the function in a thread that is marked as GUI-safe (`this.canCallOS`), but it isn't really GUI-safe. So even `defer` doesn't help, because `defer` skips scheduling on AppClock if `this.canCallOS` is true.
Debugging in a commandline script, I saw "QSocketNotifier: Can only be used with …
=> Lang: canCallOS should not be true when calling doUnixCmdAction

SCClassLibrary/Common/Streams/IOStream.sc
I've been using CollStream as part of a parser, and it's very useful to roll back 1 or more characters.
Currently:
```
stream.pos = stream.pos - 1;
```
Proposed:
```
stream.rewind(1);
```
No rush on this.
(CollStream is as yet undocumented, btw.)
=> Classlib: Add 'rewind' to CollStream

server/plugins/DiskIO_UGens.cpp
Fixes #3014 
std::bind is in \<functional\> according to the C++ ISO standard, and
gcc7.1 enforces this. otherwise, a build error [here](https://github.com/brianlheim/supercollider/blob/1eaa3fb3afbbf4708695a25361527a70e2d7a02d/server/plugins/DiskIO_UGens.cpp?utf8=%E2%9C%93#L192)
=> DiskIO_UGens: include <functional>

HelpSource/scdoc.css
towards #2943. there's no good reason for these to be right aligned, and it looks kinda messy. follow up to #2966, with apologies to julian
=> scdoc: left align extension/superclass text

lang/LangPrimSource/OSCData.cpp, lang/LangPrimSource/SC_HID_api.cpp
Toward #2927.
This initializes an uninitialized variable, simplifies logic that could return garbage, removes unused variables, and renames some proximal variables to be more descriptive.
See the commit history for more details.
This removes 2 logic issues and 2 unused variable warnings.
=> Fix logic errors and unused variables

QtCollider/image.h, QtCollider/widgets/QcGraph.cpp, QtCollider/widgets/QcKnob.cpp, QtCollider/widgets/QcLevelIndicator.cpp, QtCollider/widgets/QcLevelIndicator.h, QtCollider/widgets/image_painter.h, lang/LangSource/SC_TerminalClient.h
This reorders the initialization lists in a few headers and cpp files to avoid warnings from the compiler. None of these classes actually depend on this order of initialization, so the warning is spurious and easily fixed.
Toward #2927.
=> Clean build: Reorder constructor initialization lists to avoid compiler warnings

editors/sc-ide/widgets/help_browser.cpp
Fixes #2286. Checkboxes appear in the upper left-hand corner with
a QWebView in "Macintosh" style. See QTBUG 43366, 43070, 42948.
This sets the help browser's style to "Fusion" (matching the Qt GUI's
default) on macOS, which is the workaround other users/maintainers
have suggested.
Further reading:
https://bugreports.qt.io/browse/QTBUG-42948
https://bugreports.qt.io/browse/QTBUG-43070
https://bugreports.qt.io/browse/QTBUG-43366
=> Set help browser style to "Fusion" on macOS

lang/LangPrimSource/PyrSerialPrim.cpp
```
/home/hlolli/supercollider/supercollider/lang/LangPrimSource/PyrSerialPrim.cpp:343:25: error: ‘bind’ is not a member of ‘std’
SC_Thread thread(std::bind(&SerialPort::threadLoop, this));
^~~~
/home/hlolli/supercollider/supercollider/lang/LangPrimSource/PyrSerialPrim.cpp:343:25: note: suggested alternative: ‘find’
SC_Thread thread(std::bind(&SerialPort::threadLoop, this));
^~~~
find
```
This error message I get from compiling the master branch on Supercollider. Some short google-ing led me to https://stackoverflow.com/questions/14261013/bind-is-not-a-member-of-std which says it has to do with conflicts in c++ v 11. Boost library has a synonymous function that can be used here, which makes Supercollider compile successfully.
I'm running on Fedora 25 on gcc version 7.1.
as an extra, I was …
=> fixing std::bind not found bug

HelpSource/Classes/LevelIndicator.schelp
Hello,
every once in a while I encounter broken links in the Documentation.
I thought I might as well fix them.
Here is one fix in the LevelIndicator help file. 
(someone forgot the :: at the end of the links) 
Cheers,
Eric
=> fixed 2 broken links in LevelIndicator help file

SCClassLibrary/SCDoc/SCDoc.sc, SCClassLibrary/SCDoc/SCDocRenderer.sc, testsuite/classlibrary/TestSCDocHTMLRenderer.sc
Fixes #2337.
Some schelp links are rendered in text with `%20` in some cases and not in others. We don't want to see those.
This PR rewrites the `htmlForLink` method so that it is more readable, and factors some complicated logic into encapsulated helper methods. It also adds in-source comments so that the behavior and expectations of each method is clear. The problem was that an escaped version of the anchor text was used to fill in a missing link label, but the method should have just used the original anchor. https://github.com/brianlheim/supercollider/commit/b34d80535e3e049d88bd744c9952551f1ed8632e shows where I made the fix.
I added tests for this method to target behavior under most conditions (internal and external links, with/out anchor and/or label). They all pass for this PR, …
=> don't escape spaces in rendered link text

HelpSource/scdoc.css
This commit fixes a bug in headers in SCDoc where hovering the cursor over them turns them blue.
=> scdoc: fix headers underlining on hover

editors/sc-ide/core/settings/theme.cpp, lang/LangPrimSource/PyrArrayPrimitives.cpp, server/plugins/GrainUGens.cpp
Toward #2927. This removes some compiler warnings about unused variables by either deleting them or moving them within the relevant comment block.
=> Clean build: remove some unused variables

SCClassLibrary/Common/Core/Error.sc
This makes it easier to find where the error comes from.
For a typical case, see #3038.
=> class library: DeprecatedError posts method path

editors/sc-ide/core/doc_manager.cpp
Technically __func__ is correct according to the standard, but it's not supported by msvc
So, change it to __FUNCTION__, which our supported compilers do use
VS2013 is broken without this. I've been patching it myself when I build and it's also fixed in #2861 but thought I should handle it on master while I'm thinking about it.
=> Use __FUNCTION__ instead of __func__

SCDoc/SCDoc.tab.cpp, SCDoc/SCDoc.tab.hpp, SCDoc/SCDoc.y, SCDoc/lex.scdoc.cpp
Fixes #3040.
See #3040 for a full description/context.
The main change is 46c2a9b, to SCDoc.y, the rest was auto-generated using scdoc/build_parser.sh. All it does is check that the string after `copymethod::` has a space in it (i.e. it has 2 arguments), and throws an error if it doesn't.
=> SCDoc: throw a parser error if copymethod:: isn't followed by 2 arguments.

editors/sc-ide/widgets/multi_editor.cpp
event->pos() is relative to the widget, but menu->popup() takes an
absolute position. Using event->screenPos() displays the menu in the
correct location.
Fixes #3042
=> SC-IDE: Display the right-click tab menu in the right spot.

editors/sc-ide/widgets/help_browser.cpp
Fixes #680, using the default QKeySequence::Back & Forward.
On macOS, these map to `Cmd-[` and `Cmd-]`.
You can see what these map to per OS here: http://doc.qt.io/qt-5.9/qkeysequence.html#standard-shortcuts.
These don't seem to collide with any existing shortcuts.
=> Help browser: add shortcuts for back, forward

editors/sc-ide/core/session_manager.cpp, editors/sc-ide/widgets/code_editor/autocompleter.cpp, editors/sc-ide/widgets/code_editor/completion_menu.cpp, editors/sc-ide/widgets/code_editor/sc_editor.cpp, editors/sc-ide/widgets/style/style.cpp
Toward #2927.
I did my best to inspect the blame/log for anything that might hint at a better use for these variables, but couldn't spot anything. I think it's better to just remove them. One function is basically duplicated by another function below (fd1d2eb), the other is almost trivial to write if it's ever needed again (c9cd6f2).
=> clean build: remove unused variables and functions

SCClassLibrary/Common/Audio/Noise.sc
+ there is no ChaosNoise UGen
+ LinCong and Latoorcarfian are defined in other files as N/L/C versions
=> removed outdated comments

HelpSource/Overviews/Operators.schelp
Following on the discussion from sc-users about documenting the distort formula.
I added this change to `/Applications/SuperCollider.app/Contents/Resources/HelpSource/Overviews/Operators.schelp` and reloaded the Operator Overview page in the IDE and it seemed to be doing what I thought it should do.
I'm on SuperCollider 3.7.2 FWIW
=> document distort formula in the Operators Overview

common/SC_Apple.mm, common/SC_OscUtils.hpp, common/SC_fftlib.cpp, editors/sc-ide/core/sc_process.cpp
Toward #2927.
- use correct enum for comparison between values in IDE
- remove assignment to an unused variable
- deactivate a good but unused debugging function via `#if 0`
- move a variable inside a preprocessor guard that would otherwise be unused
This eliminates 5 clang warnings.
=> Clean build: remove some compiler warnings

HelpSource/Classes/EnvelopeView.schelp, QtCollider/widgets/QcGraph.cpp, QtCollider/widgets/QcGraph.h
This removes a compiler warning ("c") from `QcGraph::setSelectedIndex`, and documents related methods.
Toward #2927.
=> Remove a compiler warning and add documentation

lang/LangPrimSource/SC_CoreMIDI.cpp
The warning was on casting from `int` to `void*`, which is a wider type on 64-bit systems.
Also renotated the method body for clarity.
Honestly not very familiar with the C++-style casts, so I'm not sure if I used the right tool here, but in any case I wanted to leave an explanatory comment based on my research.
=> Eliminate a compiler warning in SC_CoreMIDI.cpp

QtCollider/widgets/QcGraph.cpp, QtCollider/widgets/QcScopeShm.cpp, lang/LangPrimSource/OSCData.cpp, lang/LangPrimSource/PyrArrayPrimitives.cpp, lang/LangPrimSource/PyrSched.cpp, lang/LangSource/GC.h, lang/LangSource/PyrInterpreter3.cpp
This PR removes 7 unused variables in libsclang, along with their compiler warnings.
Toward #2927.
=> Clean build: remove unused variables

QtCollider/QcWidgetFactory.h
Toward #2927.
This eliminates 27 warnings of `-Woverloaded-virtual`
=> Clean build: avoid overload of virtual function

HelpSource/Reference/Server-Architecture.schelp
This apparently is outdated, according to this closed issue:
https://github.com/supercollider/supercollider/issues/776
I see the scsynth code here:
https://github.com/supercollider/supercollider/commit/f3ac02119e214789582609e8116012fb4e308252
Does anyone know where the supernova code for this is?
=> Remove outdated info about nested bundles

SCClassLibrary/JITLib/ProxySpace/BusPlug.sc
=> add explicit default group

README.md
without this, the badge shows the build status of whatever branch was built last within the repo, even if it isn't the default branch (master)
=> readme: use master branch for travis badge

SCClassLibrary/Common/Collections/Collection.sc, testsuite/classlibrary/TestCollection.sc, testsuite/classlibrary/TestDictionary.sc
I was getting strange results with asPairs and asAssociations and I think I found some bugs. Some elements were missing after doing asPairs or asAssociations. 
When going from a dictionary to an array of associations the size should stay the same. the method in Collection was being called which was halving the size:
```
(
x = Dictionary.new;
100.do{ |i| x.put(i,i) };
x.asAssociations.size;
)
//got 64 should be at least 100
```
When going from an array of associations to an array of pairs the size should double, and the code in Collection was halving it.
```
(
x = Array.new;
100.do{ |i| x = x.add(i -> i) };
x.asPairs.size;
)
//got 64 should be at least 200
```
=> class library: fix issues with asPairs, asAssociations, asDict

SCDoc/SCDoc.cpp, SCDoc/SCDoc.h, SCDoc/SCDoc.y, common/SC_Codecvt.hpp, common/SC_Filesystem.hpp, common/SC_Filesystem_iphone.cpp, common/SC_Filesystem_macos.cpp, common/SC_Filesystem_unix.cpp, common/SC_Filesystem_win.cpp, common/sc_popen.cpp, common/sc_popen.h, editors/sc-ide/core/util/standard_dirs.cpp, lang/LangPrimSource/PyrFilePrim.cpp, lang/LangPrimSource/PyrPlatformPrim.cpp, lang/LangPrimSource/PyrPrimitive.cpp, lang/LangPrimSource/PyrStringPrim.cpp, lang/LangPrimSource/PyrUnixPrim.cpp, lang/LangSource/PyrLexer.cpp, lang/LangSource/PyrLexer.h, lang/LangSource/PyrParseNode.cpp, lang/LangSource/SC_LanguageConfig.cpp, lang/LangSource/SC_LanguageConfig.hpp, lang/LangSource/SC_TerminalClient.cpp, server/scsynth/SC_GraphDef.cpp, server/scsynth/SC_GraphDef.h, server/scsynth/SC_Lib_Cintf.cpp, server/scsynth/SC_World.cpp, server/supernova/server/main.cpp
Fixes #2441 and fixes #2444.
The Windows NT filesystem encodes paths using UTF-16. POSIX systems use UTF-8. SCIDE/SCDoc encodes all strings as UTF-8 internally. This causes a problem where scide miscodes strings passed by sclang and fails to find files when a path contains a codepoint on which these encodings differ (specifically, any character that is not in the 7-bit ASCII set).
Use the UTF-8 encoding for paths whenever they are passed to sclang, and use the native encoding whenever passing to the OS filesystem. This eliminates the encoding-agnostic behavior of sclang and also eliminates the encoding barrier between scide and sclang.
This fix also performs a couple other functions:
- Eliminate asserts thrown when debugging on Windows while parsing help files with Japanese characters. …
=> sclang: encode all filesystem paths as UTF-8 internally

include/plugin_interface/SC_Graph.h, include/plugin_interface/SC_InterfaceTable.h
as per a comment from @timblechmann - the change needed for https://github.com/supercollider/supercollider/pull/3063 required a change that also requires a change to the API version checking for plugin compatibility.
=> Plugin api change

lang/LangPrimSource/OSCData.cpp, lang/LangSource/PyrLexer.cpp
this cherrypicks the most conservative commits out of #2431. this removes the following startup posts, which are not useful at all and were probably mistakenly left in:
init_OSC
initPassOne started
initPassOne done
pass 1 done
=> Remove sclang debug posts on startup: "init_OSC", "initPassOne", "pass 1 done"

.travis.yml, .travis/before-install-osx.sh, .travis/before-script-osx.sh, CMakeLists.txt, README_MACOS.md, cmake_modules/launch-c.in, cmake_modules/launch-cxx.in
Problem: builds take a long time on travis.
Solution: use [ccache](https://ccache.samba.org/).
Problem 2: ccache + cmake + xcode doesn't work out of the box
Solution 2: workaround thanks to Craig Scott: https://crascit.com/2016/04/09/using-ccache-with-cmake/
Other changes:
- set `language: cpp` in `.travis.yml`. According to travis's docs, this is needed to access ccache caching.
- remove `compiler: gcc`. this was redundant, and wasn't being used by any of the builds.
- new files in `cmake_modules/` according to Craig Scott's post. Minimal shell scripts that do the necessary dirty jobs.
Pros:
- cached between builds
- reduces overall build time by more than 50% (and more than 75% on linux).
- ccache reproduces compiler warnings on cached compilations
- macOS devs can also use ccache to …
=> cmake/travis: use ccache, add support for Xcode+ccache

HelpSource/Classes/Git.schelp, SCClassLibrary/Common/Quarks/Git.sc, SCClassLibrary/Common/Quarks/QuarksGui.sc
opening the gihub url silently failed if remote url is of form `git@github.com:<uri>`
=> Git (class): add url composition

lang/LangPrimSource/PyrPrimitive.cpp
this commit changes the startup message
NumPrimitives = #
to
Found # primitives.
[supercollider.js does not appear to parse it.](https://github.com/crucialfelix/supercolliderjs/blob/c95740ac398b4cf50d1536289d2e8244707dfbe1/src/lang/internals/sclang-io.js#L380)
=> lang: reword "NumPrimitives =" post

README_MACOS.md
LAUNCH_RULE_COMPILE -> RULE_LAUNCH_COMPILE
sorry, i got this wrong the first time.
=> README_MACOS: correct name of cmake option

SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/Volume.sc, testsuite/classlibrary/TestVolume.sc
This PR is an attempt to fix #3105 & #3110.
The problem is that, on reboot, ServerTree calls its updateFunc (it was added the first time the server booted) before ServerBoot's initFunc is done sending the SynthDef. This causes the "SynthDef not found" error.
The fix removes the updateFunc from ServerTree when the server quits. That way, on reboot, ServerTree has nothing to call. When initFunc is finished sending the SynthDef, updateFunc gets added to ServerTree.
Also, this.updateSynth needs to be called at the end of sendSynthDef so that the volume synth gets created, if necessary.
This change also makes Server.quit call Volume.freeSynth.
The Server's volume and mute status persist across reboots. No more SynthDef not found errors posted after reboot.
```supercollider
s.volume.volume = …
```
=> Fix Server volume and mute after reboot

HelpSource/Classes/Pselect.schelp
Just general rewrites, plus the new method wasn't properly documented for Pselect.
=> Updated Pselect's help to hopefully be clearer and more comprehensive.

HelpSource/Classes/Pgate.schelp
The current help was a little confusing. This is an attempt to make it clearer, particular for people new to SuperCollider. It includes an additional example which I think is helpful in making the relationship to the key clearer.
Also pointed out that Pn can be used with Pgate (Pn mentions this, but Pgate doesn't).
=> Expanded help file for Pgate and added an additional example

HelpSource/Classes/PV_Copy.schelp, HelpSource/Guides/FFT-Overview.schelp
Updated FFT Overview and PV_Copy help files to reflect the current syntax for automatically copying FFT data for parallel PV streams.
=> Fix pv copy help

HelpSource/Classes/SimpleNumber.schelp, SCClassLibrary/Common/Math/SimpleNumber.sc, testsuite/classlibrary/TestSimpleNumber.sc
As reported by Andrea Valle on the mailing list:
---
54.678.asTimeString
-> 00:00:54:678 // OK
54.678.asTimeString(precision:0.01)
-> 00:00:54:067
54.678.asTimeString(precision:0.1)
00:00:54:006
I don’t get the padding. I was expecting 
00:00:54:670 or 00:00:54:680
and
00:00:54:600 or 00:00:54:700
---
This PR makes several changes:
- use a period instead of colon to separate seconds and milliseconds; this is the correct ISO 8601 format
- correctly pad zeros in the milliseconds field
- fix rounding in the milliseconds field in general
- add unit tests for the core functionality of this method
=> Fix SimpleNumber.asTimeString

HelpSource/Classes/UnitTest.schelp, HelpSource/Classes/UnitTestScript.schelp, HelpSource/Guides/WritingTests.schelp, testsuite/classlibrary/TestUnitTest.sc, testsuite/classlibrary/server/TestMixedBundleTester.sc, testsuite/classlibrary/server/TestUnitTest-test_bootServer.sc
Since a while, SuperCollider development increasingly relies on `UnitTest`s to secure code stability. 
Most prominently, they are part of the testing framework around  [travis](https://travis-ci.org/supercollider/supercollider).
Not having UnitTesting capabilities in the core library makes the development process rely on a Quark extension. This seems to place it out of sight of developers. 
To ease the process of UnitTesting and to encourage people to write `UnitTest`s, I propose to include the UnitTest framework (`UnitTest, UnitTestResult, UnitTestScript`) into the main repository. This will also ensure that travis builds always use the right UnitTest framework for their tests.
I copied the classes defined in the UnitTesting quark to `SCClassLibrary/Common/UnitTesting` and added the …
=> include unittest into common

HelpSource/Classes/ContiguousBlockAllocator.schelp, SCClassLibrary/Common/Control/Engine.sc, SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/ServerStatus.sc, testsuite/classlibrary/TestContiguousBlockAllocator.sc, testsuite/classlibrary/TestServerClientID.sc, testsuite/classlibrary/TestServer_clientIDBooted.sc
This is one of several smaller PR based on #3106, hopefully easier to review. 
It fixes #2940 and includes
-  ContiguousBlockAllocator adaptation for multiclients
-  safeguards to clientID_ setting
- redone calculations for Server allocator ranges  and allocator creation 
- updated help files 
- updated responses in sendNotifyRequest
-  Unittests for Allocators and clientID.
=> Topic fix client id alloc

server/supernova/CMakeLists.txt, server/supernova/server/main.cpp
Commit 547a18c introduced the CMake variable LIB_SUFFIX to determine the
system library folder, and made supernova load plugins in both /usr/lib
and /usr/lib64.
On some systems (eg archlinux64) lib64 is symlinked to lib, supernova then
tries to load the plugins twice and crashes.
We want supernova to load only the folder in which the plugins have been
installed.
=> Supernova: use LIB_SUFFIX for plugin loading

server/supernova/server/node_graph.hpp
This is a partial fix for #1717.
I took the following nodes while fixing this:
```supercollider
Server.supernova
s.boot
s.numGroups // 1
s.queryAllNodes
//NODE TREE Group 0
//   0 group
//      1 group
s.quit
Server.scsynth
s.boot
s.numGroups // 2
s.queryAllNodes
//NODE TREE Group 0
//   1 group
```
Status querying is the only time supernova's group count is actually used for an external calculation (grep for group_count_ if you don't believe me), so it doesn't matter which
value it starts with. Also, it looks like this was accidentally changed during a refactor:
5cc4615dcd (`group_count_` was moved from constructor init list to private member definition,
and changed from 1 to 0 for no clear reason).
Since the tests pass with this at 1, and since this seems to conform to what's actually …
=> supernova: change node_graph group_count_ to 1

SCClassLibrary/Common/Streams/Stream.sc, testsuite/classlibrary/TestTask.sc
Routines can’t stop in between yields. Nevertheless, `Routine`
implements a trick in `stop`: it checks if it is in the current thread
and if it is, it will yield nil, breaking calculation right where it is.
Because a `Task` has a routine and is not a routine, it needs to do
this check as well, but this time for its stream.
This fixes #3184.
=> Fix task stop

HelpSource/Classes/ContiguousBlockAllocator.schelp, HelpSource/Classes/ReadableNodeIDAllocator.schelp, SCClassLibrary/Common/Control/Engine.sc, SCClassLibrary/Common/Control/ReadableNodeIDAllocator.sc, SCClassLibrary/Common/Control/Server.sc, testsuite/classlibrary/TestContiguousBlockAllocator.sc, testsuite/classlibrary/TestReadableNodeIDAllocator.sc, testsuite/classlibrary/TestServerClientID.sc, testsuite/classlibrary/TestServer_clientIDBooted.sc
This is no. 2 of several smaller PR based on #3106, hopefully easier to review.
It is based on PR #3178, to which it adds only the last 2 commits:
ReadableNodeIDAllocator, an alternative to NodeIDAllocator, 
class file, help file and unittest, and allowing its use in Server.
=> Server: add optional ReadableNodeIDAllocator

HelpSource/Classes/HPZ2.schelp
The example at the end of this Help file is a copy of the example from the HPZ1 Help file. The variable name used for the filtered signal needed to be updated.
=> Help: Fix incorrect variable name

README_MACOS.md
The building readme for macOS does mention supernova further in the document, but I think it's beneficial to include supernova build option and the portaudio prerequisite earlier.
=> README_MACOS.md: Include supernova in Prerequisites and Build Instructions

CONTRIBUTING.md
I updated CONTRIBUTING.md to reflect the recent change to use the develop branch for development (also discussed in https://github.com/supercollider/supercollider/issues/3205). I also added a section about syncing the fork with the upstream, as well as links to git workflow wiki and Github's guide to forking/syncing.
I intended my additions to be both comprehensive and straightforward for a newcomer, as I myself am new to contributing to SC. I believe it is desirable to have such section to help people familiarize with the workflow.
I would appreciate if someone could take a look at the section about syncing the fork to make sure it reflects current workflow correctly, thanks.
=> CONTRIBUTING.md: update instructions reflecting develop branch, add fork syncing

HelpSource/Classes/BeatTrack.schelp, HelpSource/Classes/BeatTrack2.schelp, HelpSource/Classes/FFTTrigger.schelp, HelpSource/Classes/KeyTrack.schelp, HelpSource/Classes/Loudness.schelp, HelpSource/Classes/MFCC.schelp, HelpSource/Classes/Onsets.schelp, HelpSource/Classes/SpecFlatness.schelp, HelpSource/Classes/SpecPcile.schelp, HelpSource/Classes/UnpackFFT.schelp
Some Help file examples use LocalBuf's arguments incorrectly. With these changes, `LocalBuf(1, 1024)` becomes `LocalBuf(1024)`.
=> Help: fix incorrect LocalBuf arguments

HelpSource/Classes/UnpackFFT.schelp
The ouput of `PackFFT` should be assigned to the variable `chain` in this example. See discussion in #3212.
=> Help fix: assign PackFFT to var chain in example

HelpSource/Classes/ContiguousBlockAllocator.schelp, HelpSource/Classes/Group.schelp, HelpSource/Classes/ReadableNodeIDAllocator.schelp, HelpSource/Classes/Server.schelp, HelpSource/Guides/MultiClient_Setups.schelp, HelpSource/Reference/default_group.schelp, SCClassLibrary/Common/Collections/Event.sc, SCClassLibrary/Common/Control/Engine.sc, SCClassLibrary/Common/Control/ReadableNodeIDAllocator.sc, SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/asGroup.sc, SCClassLibrary/Common/Control/asTarget.sc, SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc, testsuite/classlibrary/TestContiguousBlockAllocator.sc, testsuite/classlibrary/TestEvent.sc, testsuite/classlibrary/TestReadableNodeIDAllocator.sc, testsuite/classlibrary/TestServerClientID.sc, testsuite/classlibrary/TestServer_clientIDBooted.sc
This is no. 3 of several smaller PR based on #3106, hopefully easier to review.
see just the difference to current 3.9: 
https://github.com/supercollider/supercollider/compare/3.9...topic-separateDefaultGroups
I also made a reduced version of this branch with clearer commit history here:
https://github.com/supercollider/supercollider/compare/3.9...adcxyz:reduced_separateDefaultGroups
It is based on PR #3179, to which it adds only the commit from 6c56b01 on:
- each client (Server object) gets a defaultGroup based on clientID
- It is used everywhere instead of hardcoded group 1
- each client also knows defaultGroups of all other clients that may login
- default behavior on CmdPeriod is unchanged: local client does freeAll, remote clients do not
- CmdPeriod behavior is easy to adapt (e.g. …
=> Server: create separate default groups for multiple clients

CONTRIBUTING.md
I previously tried to update git instructions for contributing to be comprehensive. It seems that the process of updating fork's state to be in sync with upstream requires to do `pull upstream develop` and not `pull --rebase`. I hope this is indeed the correct way to update with the upstream repository. I'd appreciate if someone could confirm this and sorry for the mistake previously.
=> Topic/update contributing instructions - git pull upstream develop

HelpSource/Reference/Syntax-Shortcuts.schelp
There is no method named `envirSet`. The correct method is `envirPut`.
=> Help: fix incorrect method name 'envirSet'

lang/LangPrimSource/PyrMathPrim.cpp
They conflict with --std=c++11 (additional compiler flags are required),
but are not used, so just skip using them.
This comes from the downstream debian package. I figure it could be useful upstream too.
=> Disable 128bit float constants.

SCClassLibrary/SCDoc/SCDocRenderer.sc
This gets rid of two compilation warnings that these functions cannot be inlined.
=> SCDocRenderer: move vars in if clauses up to allow inlining.

SCClassLibrary/Common/Control/Server.sc, server/scsynth/SC_GraphDef.cpp, server/scsynth/SC_HiddenWorld.h, server/scsynth/SC_Lib.cpp, server/scsynth/SC_Prototypes.h, server/scsynth/SC_SequencedCommand.cpp, server/scsynth/SC_World.cpp, testsuite/classlibrary/TestDictionary.sc, testsuite/classlibrary/TestServerClientID.sc, testsuite/classlibrary/TestServer_clientIDBooted.sc
This is a cleaned-up replacement PR for PR #3181. 
It contains 
* cherry-picked  changes to scsynth by @muellmusik and @brianlheim,
* a fix to failing unrelated UnitTest ```TestDictionary:test_keysValuesArrayDo```
which apparently got lost 
* a minimal fix to clientID_ for a bug that showed up while testing 
multiple combinations of clients and server with this script: 
https://gist.github.com/adcxyz/57c89fe1faed045e77b09a2ec1d23b34
=> Cleanup - get max logins from scsynth

SCClassLibrary/Common/Control/Server.sc, testsuite/classlibrary/TestServer_clientIDBooted.sc
initTree should only happen after server received the login response,
because clientID and maxLogins may still change there. 
this fixes #3262.
=> remove Server-initTree from bootInit

SCClassLibrary/Common/Control/Server.sc, testsuite/classlibrary/TestServer_clientIDBooted.sc
=> cherry-pick "remove Server-initTree from bootInit" onto 3.9

HelpSource/Classes/Buffer.schelp
=> Help: improve Buffer:alloc bufnum arg description

HelpSource/Tutorials/A-Practical-Guide/PG_03_What_Is_Pbind.schelp
Glancing at the pattern guide 03, I noticed that the "touches bloquées" example still used `Rest` as a class, which is now a deprecated usage. So I fixed that, and corrected the wording to note that only *instances* of Rest should be used. Also, where it used to say that rests may have a duration, now it says all rests have a value (generic).
I think we need this for 3.9. Documentation change only -- it won't break anything.
=> Help: Pattern Guide 03: Update explanation of Rests for 3.9

SCClassLibrary/Common/Control/Server.sc
According to the server command reference, these messages take triples of ints (ID, action, target). Because of supernova's implementation of this command, it treats these as badly formed and throws an exception.
I just added the missing args according to the older version of this code: 
https://github.com/supercollider/supercollider/blob/0b0b85fdfabb04d7e31521cb74757152e440e855/SCClassLibrary/Common/Control/Server.sc#L350-L355
Without this change, supernova is basically unusable on my machine.
=> Server.sc: Properly format g_new messages to server

SCClassLibrary/Common/Control/ServerStatus.sc
These messages containing "scsynth" are posted even if the server program is set to Supernova. A bit confusing, so I changed them to the more generic "server."
=> ServerStatus.sc: Replace 'scsynth' with 'server' in messages

SCClassLibrary/SCDoc/SCDoc.sc, SCClassLibrary/SCDoc/SCDocRenderer.sc
Fixes issue #3298.
Tested on macOS 10.13 (not that OS should make a difference).
I am milestoning this as 3.9.1, but if people think it's safe it could go in 3.9.0. I would say that since the issue/workaround is known, it would be safer to wait for now.
=> SCDoc: Escape single-quotes in generated javascript

.travis/before-install-osx.sh, .travis/script-osx.sh
Thanks to @scztt for this idea. 
xcpretty makes the build output from xcode much less verbose and much more readable. With this change, the log goes from being ~4 MB/16,000 lines to ~300 KB/7,000 lines. I have on occasion waited a full minute and a half to read the last few lines of the travis log, this is 
This also updates the build scripts so that if there's any failure while building the whole log is printed.
Example (passing) build: https://api.travis-ci.org/jobs/306987284/log.txt?deansi=true
Example (failing) build: https://travis-ci.org/brianlheim/supercollider/jobs/306996793
I hope nobody minds if we merge this right away. It's non-user-facing and seriously makes life easier when checking the Travis logs.
=> travis: install and use xcpretty (macos builds)

server/scsynth/SC_GraphDef.cpp, server/scsynth/SC_GraphDef.h, server/supernova/sc/sc_synthdef.cpp
In `sc_synthdef::prepare(void)`, the memory requirement for a sc_synth structure was underreported because it did not change with #3063. As a result, there was memory corruption. This commit both fixes the issue and adds clarifying comments to the calculations.
Fixes #3196, and helps #3266 as it applies to supernova. Tested on macOS 10.13.
cc @dyfer, @samaaron. Definitely doesn't change anything on sonic pi w/ scsynth.
=> supernova: reserve enough size for synthdefs

HelpSource/Tutorials/Getting-Started/04-Functions-and-Other-Functionality.schelp
An answer to #3322. (Closes #3322)
=> schelp: add parens around operators in code for clarity

HelpSource/Classes/Splay.schelp
This one was created directly off the 3.9 branch, for easy merging.
=> Help file: fix Splay stereo position formula (missing parenthesis)

SCClassLibrary/Common/Control/Volume.sc
Fixes #3326.
The envelope used by the server's `VolumeAmpControl` synth needs to have it's attack and release times set equal to the lag time. This way, the server's volume will not suddenly jump to the new value when setting the volume to/from 0Db.
I think this is safe for `3.9`, but I am OK with this being in `3.9.1`.
=> Make volume synth's envelope use lag time 

lang/LangPrimSource/PyrListPrim.cpp
This fixes a bug in prEvent_IsRest.
Initializing in static storage results in invalid pointers when symbol table is rebuilt during interpreter init. Then, during execution of `isRest`, these stagnant `PyrClass*`s cause an assert to be thrown in `isKindOf` because the symbol is no longer recognized as pointing to a valid class.
I saw this interpreter crash sporadically (first reported in https://github.com/supercollider/supercollider/pull/3275#issuecomment-350594973). I believe that's because memory allocation would occasionally allocate a class symbol in the symbol table at the same address as the pointer.
This is a pretty big mea culpa. Sorry for asking you to write it that other way, @jamshark70. :/
My errors were not realizing that (1) you can recompile the class library while keeping …
=> PyrListPrim: correctly initialize symbols

testsuite/classlibrary/TestArray.sc
In TestArray.
Testing this large an array really doesn't do much, and it adds about 5 seconds to the overall test time. I want to cut down on clutter like this so that it becomes more feasible to run the full test suite more regularly.
=> testsuite: remove long-running duplicate test

testsuite/classlibrary/TestPatternProxy.sc
Because now event == also tests the parent, these tests failed: Pevent
passes a full parent event, but the comparison was with plain events.
For testing, we pass an empty event to `nextN` instead.
=> test: adjust test for new event equality

lang/LangPrimSource/PyrSerialPrim.cpp, server/plugins/DiskIO_UGens.cpp
See PRs #3015, #3029. <functional> is needed in some files so that std::bind is found.
cc @dvzrv
=> [3.8] Add missing includes to fix build errors with gcc7

SCClassLibrary/Common/Audio/InOut.sc
In current 3.8, the following fails:
```
SynthDef(\x, { LocalOut.kr(DC.kr(0)) }).add
```
... because the check for LocalOut's inputs mistakenly assumes that LocalOut, like Out, will provide a bus number, so the input check demands at least two inputs.
There is a maintenance release of 3.8 coming up. I can't think of any compelling reason to leave this (frankly ridiculous) bug in place.
=> class library: LocalOut correctly checks input size

.travis.yml
Disables qpm test running (not great), but this is the simplest fix I could think of. I think changes have been made to qpm since this release that stop it from working correctly in this situation. Benefits are that CI passes and we will actually get an auto-uploaded binary for the 3.8.1 release.
@snappizz @scztt
=> [3.8] travis: disable qpm test running and use deprecated trusty

package/package
the regression tests add 5 MB to the tarball and are really only for developer use. the linux tarball should be kept as slim as possible, so it makes sense to exclude this.
i am ok with keeping them in the main source tarball since they are, after all, part of the source.
=> Exclude testsuite/ from Linux tarball

HelpSource/scdoc.js
Proposed fix for #3375. My apologies in advance for creating a PR which might not be complete. It fixes the issue to the best of my knowledge. Please review and suggest a better implementation if necessary.
From what I can see from [doc.sccode.org,](http://doc.sccode.org/) issue #3375 is a regression. The TOC used to be persistent when popped out. This PR is based on the previous use of  `storage` to keep the state of the popped out TOC in `HelpSource/scdoc.js`.
=> [Help] make TOC's state persistent

.appveyor.yml, .travis.yml
Appveyor breaks when Ableton link is added as a submodule because the script isn't using --recursive
.travis.yml has a typo - "after-deploy" instead of "after_deploy" (https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle)
=> Fix small bugs in CI scripts

include/server/SC_WorldOptions.h, lang/LangPrimSource/OSCData.cpp, platform/mac/SuperColliderAU/Source/SuperColliderAU.cpp, server/scsynth/iPhone/iSCSynthController.mm, server/scsynth/scsynth_main.cpp
cleaning up some scsynth code for fun. with c++11 (currently required to build anyway) we have support for structs with default arguments, so the definition of default arguments in `WorldOptions` can be expressed much more readably.
=> scsynth: refactor SC_WorldOptions.h for readability

README.md
Slack auto-invite is now directly supported by slack. No badge, but this is more reliable long-term.
=> Add new slack join link

.travis/qpm-prep.sh
qpm currently fails to download quarks with `qpm quark checkout`.
This commit replaces that command with simple git clones to achieve the
same result.
=> travis: use git clone instead of qpm

README_LINUX.md, README_MACOS.md, README_WINDOWS.md
* Unify readme headers to all have a friendly message + version number
* Update the Windows build instructions to reflect current support & build procedures
* remove a lot of information about MinGW and MSYS2 and encourage use of VS
* note that command line is not supported right now
* add note about using VS dev prompt (not cmd.exe) to execute `lib` command (this has tripped up at least one other developer, plus myself)
* remove very old info about hack for old version of MinGW + HIDAPI
* Simplify some verbosity
* Improve flow of build instructions and simplify the TOC
Reviews & suggestions welcome. I left in some info about mingw/msys2 because some of it is genuinely useful info if you're going to build with those toolchains.  However, I think for now the approach I would prefer is to …
=> Update readmes for 3.9

editors/sc-ide/SuperColliderIDE.desktop
On Gnome3, we get duplicate SC-IDE icons in the left-hand side "Favorites" dock. This only happens when SCIDE is pinned to the dock and then launched. I found the solution here:
https://askubuntu.com/questions/403766/duplicate-icons-for-manually-created-gnome-launcher-items
Basically, the .desktop file needs to have a field called `StartupWMClass` with the value `scide`. For more info, see https://standards.freedesktop.org/desktop-entry-spec/latest/ar01s06.html
This seems to also fix #2646 as a side-effect.
I also made a few additions and changes to the .desktop file based on what I read on the freedesktop.org site.
=> [SCIDE] Fix duplicate icons in Gnome3 dock

SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc
fix for a minor problem that happens when pressing cmd+period while a plotTree window is open.
```supercollider
s.boot
s.dumpOSC  //to debug
s.plotTree
//now close the window - OK - g_queryTree messages are no longer being posted
s.plotTree
CmdPeriod.run  //or typing cmd+.
//again close the window - BAD - leaking routine - g_queryTree still being posted
```
with the suggested change the second example work as expected and the internal updater routine is stopped.
=> classlib: fix for leaking routine in plotTree

SCClassLibrary/Common/Control/Recorder.sc
Fixes #3307.
Please don't merge until 3.9.1. This code is probably fine, but for stability's sake I don't want to risk it.
=> classlib: remove old workaround code in Recorder.makePath

editors/sc-ide/core/settings/manager.cpp
This fixes issue #2389 by adding a backup for the default IDE font. It
keeps the "monospace" family that currently works for Linux & Windows.
Monaco is the default font for macOS's terminal, so it's safe to assume
this will be installed for almost all users.
=> scide: set default font backup to Monaco

server/supernova/server/main.cpp
previously, plugins were loaded from /plugins within extension directories
Fixes #3391
Thanks to @florian-grond for the patch!
=> supernova: load plugins from correct directories

SCClassLibrary/Common/Control/Node.sc
- The method “subclassMustImplementThisMethod” has never existed.
- Renamed `addNum` to `addActionID` and replaced `inTarget` by a direct
conversion.
- brought code to a more standard form.
=> node fixes: correct a call and improve variable names

tools/guard/.gitignore, tools/guard/Gemfile, tools/guard/Guardfile
Configure Guard and the guard-sclang plugin to allow UnitTest classes to be run automatically whenever they or the classes which they test change.
See also #3368.
=> add Guard configuration for automatically running SC tests

editors/sc-ide/widgets/help_browser.cpp, editors/sc-ide/widgets/lookup_dialog.cpp
Fixes #1036, tested and works (on macOS 10.13 high sierra).
1. Start scide.
2. Type the line `"broken`
3. Select-all, and Cmd-D (to search documentation) or Cmd-U (to look up references).
Errors:
```
ERROR: syntax error, unexpected NAME, expecting ')'
in interpreted text
line 1 char 32:
HelpBrowser.openHelpFor(""broken") 
^^^^^^
-----------------------------------
ERROR: Command line parse failed
ERROR: syntax error, unexpected NAME, expecting ')'
in interpreted text
line 1 char 88:
ScIDE.request("{ec39ccb4-c981-43ac-a72e-a75439af6b6c}",'findReferencesToSymbol',""broken") 
^^^^^^
-----------------------------------
ERROR: Command line parse failed
```
Also freezes the help browser.
Works without error/complaint.
I noticed similar opportunities for this issue to arise in other IDEs (search …
=> Escape quotes in strings sent from SCIDE to lang

.appveyor.yml, README_MACOS.md, README_WINDOWS.md
This PR adds S3 deployment to our Appveyor setup so that "bleeding-edge" builds can be downloaded and tested by interested users and developers. Most of this was copied/adapted from `.travis.yml`. Thanks to @scztt for helping with S3 access and general usage.
This should be accompanied by an appropriate PR to the website making these builds available.
With the current config, builds are uploaded both for 32-bit and 64-bit builds.
I haven't tackled the automatic release asset uploading part of the script. If it isn't too hard to add that in, we can merge both at once. Might take some testing with temp tags created on this branch, if you're ok with that @snappizz.
=> Add S3 deployment to appveyor setup

.appveyor.yml
This replaces the credentials in appveyor.yml with credentials that are more restricted than what we were using previously. This is good because now appveyor will only be able to do the bare minimum of what it needs to do.
=> appveyor: use more restricted s3 credentials

editors/sc-ide/core/settings/theme.cpp, editors/sc-ide/core/settings/theme.hpp
=> scide - theme: add dracula

server/supernova/audio_backend/portaudio_backend.hpp
Enable choosing different buffer size (s.options.hardwareBufferSize in sclang) for supernova on macos. Previously on macos supernova was always using the largest available buffer size (the buffer size switch was ignored).
I understand this was in order to ensure glitch-free audio, however now with possibility of choosing buffer size (introduced in https://github.com/supercollider/supercollider/commit/0c3d4c999253204a288c18482eab0d432e33412a) one can make a conscious choice about it. And it still defaults to a large buffer size when hardwareBufferSize is nil.
=> supernova - portaudio_backend macos: enable buffer size choice on macos

editors/sc-ide/core/settings/theme.cpp
\#3410 had some mis-copied code. This PR patches that.
=> ide: fix issue in copy-pasted code block

lang/LangPrimSource/PyrUnixPrim.cpp
This commit removes the "RESULT = #" posting in String:unixCmd. Since
the programmer already has access to the exit code in the "action"
callback, it's much better to leave it up to them to handle this exit
code and provide configurable, user-friendly output.
This addresses #2452.
#3458 is a requirement if this is to be merged -- if the server process quits, it's pretty important for the user to know the exit code.
=> lang: Remove "RESULT = #" posting for .unixCmd

server/plugins/OscUGens.cpp, testsuite/classlibrary/TestIndexUGenRates.sc
- `Index_next_k()` accesses index `ZIN0(1)` once per control cycle -- i.e., assumes a kr index.
- `Index_next_a()` accesses index `ZIN0(1)` `inNumSamples` times per control cycle -- ar index.
Both calculation functions do `GET_TABLE` only once per control cycle -- so the bufnum input does not support ar under any circumstances.
But, the Ctor chooses next_k for a control-rate *bufnum*, regardless of the rate of the input that matters (index). So this PR changes `INRATE(0)` to `INRATE(1)`.
Five other UGens follow the same pattern: IndexL, FoldIndex, WrapIndex, IndexInBetween and DetectIndex.
Test: without the fix, the following displays an obvious sample-and-hold. With the fix, Index.ar is correctly equivalent to BufRd.ar without interpolation.
```
(
s.waitForBoot {
b = Buffer.alloc(s, 512, …
```
=> Plugins: Choose Index.ar calc function based on phase arg

HelpSource/Classes/Server.schelp, SCClassLibrary/Common/Control/Server.sc
This commit adds a new message when the server process quits:
Server ___ exited with return code ___.
This is much less cryptic than `RESULT = 0`.
It also improves the "'/quit' sent" message.
=> class library: Improve post output on server quit

lang/LangSource/PyrLexer.cpp, lang/LangSource/SC_LanguageConfig.hpp
Fixes \#3468.
During library compilation, try to create any missing default directories
And, don't warn if these don't exist or can't be created
Solves much user confusion and annoyance
Also added some doc comments
=> sclang: create default compilation directories automatically

SCClassLibrary/Common/Control/Server.sc
This fixes #3485. I've also remove the colon (in failstr) that appeared before the clientID number in the warning text.
=> Fix off-by-one error in posted warning message

SCClassLibrary/Common/Audio/BasicOpsUGen.sc, testsuite/classlibrary/TestSynthDefOptimizations.sc
This PR addresses the issues raised in #972.
- `a + b.neg` should optimize to `a - b` *only* if `b.neg` has only one descendant. But the prior logic was to perform some sort of optimization, no matter how many descendants needed the `b.neg` result. This caused required UGens to be lost to dead code optimization.
- Scott C. correctly pointed out that the "optimize" methods use `descendants` to decide whether the optimization is legitimate, but they do not update the descendants sets belonging to inputs of the replaced or deleted units. This PR introduces a method to update the descendants of all relevant input UGens.
- It also adds some preliminary unit tests for SynthDef optimizations. Currently testing each binary-op optimization method for the correct types of remaining operators. The …
=> Classlib: Correct 'a+b.neg' ugen optimization, and fix descendants

SCClassLibrary/Common/Collections/Event.sc, testsuite/classlibrary/TestEvent.sc
Fixes: #3481.
Quick test:
```supercollider
(type:\grain).play;
g = Group(s);
(type:\grain, group: g).play;
```
=> class library: event - fix group in grain event

server/scsynth/SC_GraphDef.cpp
In GraphDef_Read(), sizeof is applied to incorrect types - int* and
int32* instead of int and int32. This doesn't appear to have caused any
problems so far, but is a mistake and could cause issues on systems
where these sizes differ.
=> scsynth: use correct types for allocation sizes

.travis/script-osx.sh
in my experience so far this is unnecessary, as xcpretty doesn't seem to hide any part of the build message.
in addition, the previous configuration has the drawback that it makes build logs very hard to navigate if there is a failure.
=> travis: don't print raw build log on failure

common/sc_popen.cpp
fix #2317
This commit changes a call to execve to execvpe in SequenceableCollection:unixCmd, so that PATH is now respected.
This only affects *nix systems. SequenceableCollection:unixCmd is not currently supported on Windows, or so I hear.
test case:
["which", "scsynth"].unixCmd
once this method is working on Windows, i suggest that we refactor all calls to String:unixCmd to use this method. it is much better to call actual command line arguments as an array rather than formatting shell strings, which is vulnerable to injections.
=> sclang: SequenceableCollection:unixCmd respects PATH

HelpSource/Reference/Synth-Definition-File-Format.schelp
Please correct me if this is factually inaccurate/incomplete! It appears most ints are signed, but I'm not sure of that. Nearly all of the ints don't actually have a need to express negative numbers (e.g. the number of UGens is never negative), but they appear to anyway.
The only exception I see is ```input-spec```, which uses ```-1``` as a special case.
=> SynthDef File Format: note (un)signed ints

HelpSource/Classes/Dialog.schelp, HelpSource/Classes/FileDialog.schelp, QtCollider/widgets/QcFileDialog.cpp, QtCollider/widgets/QcFileDialog.h, SCClassLibrary/Common/GUI/Base/QDialog.sc
Fixes \#874.
See also \#3505, unfortunately @snappizz and I started working on this at the same time without knowing :/
This branch has extra documentations so I thought it might be preferable (also Nathan said in PM that he was OK with it).
=> qt gui: add "path" option to FileDialog and Dialog

external_libraries/CMakeLists.txt, lang/CMakeLists.txt, server/scsynth/CMakeLists.txt
- add `boost_regex` lib as a separate target
- link `sclang` and `scsynth` against boost libs so they aren't built twice (filesystem is build 3 times right now)
- scsynth is already linked against necessary libs so its `target_link_libraries` call doesn't need to be modified
Fixes #2192.
=> CMake: don't rebuild boost libs

HelpSource/Classes/Platform.schelp, SCClassLibrary/Platform/Platform.sc, SCClassLibrary/Platform/windows/WindowsPlatform.sc
this PR adds a crossplatform kill method to allow killing specific process ids (in addition to killAll).
this is useful for ending specific cmdline programs from within SC. E.g. in a current UnitTest where a server program is started by hand, #3486, this is useful to make that test run crossplatform.
not tested on windows yet - windows devs please check :-)
=> add crossplatform kill method

SCClassLibrary/Common/Core/Color.sc, SCClassLibrary/Common/Streams/History.sc
this PR optimise Color.fromHexString and History.unformatTime. both these were using .interpret and here they are replaced with much faster variants.
one caveat though that these methods now break differently...
```supercollider
Color.fromHexString("#ggg")  //deliberate user error
```
with the original .interpret method we get this cryptic error...
```
ERROR: syntax error, unexpected NAME, expecting $end
in interpreted text
line 1 char 4:
0xgg
^^
```
and while with the variant in this PR it doesn't fail but rather overflow...
```supercollider
-> Color(1.0666666666667, 1.0666666666667, 1.0666666666667)
```
and similar for History.unformatTime...
```supercollider
History.unformatTime("01:XY:03")  //deliberate user error
```
with original method...
```
ERROR: Class not defined.
in …
```
=> classlib: optimise and remove some .interpret

editors/sc-ide/CMakeLists.txt, lang/CMakeLists.txt
See https://stackoverflow.com/questions/4749155/passing-quotes-in-quotes-to-cmd-exe
The whole command needs to be wrapped in quotes in order for cmd to take quotes around paths
This makes it possible to build on windows with a source path containing spaces.
=> Cmake: quote commands given to cmd (windows)

editors/sc-ide/CMakeLists.txt, external_libraries/CMakeLists.txt, lang/CMakeLists.txt
Include its dirs last for libsclang, and use the YAMLCPP_LIBRARY variable for linking.
Fixes #3557.
cc @Apteryks. This works for me on macOS, using v0.6.1 of yaml-cpp.
Edit - oops, think I broke linking when SYSTEM_YAMLCPP=OFF. will keep investigating.
=> cmake: correctly include yaml-cpp

CMakeLists.txt, build_sclang.cfg.in, testsuite/sclang/CMakeLists.txt
Fixes #3555 (the part that isn't duplicated by #1717) by addressing a few intermingled issues.
Issue 1: We have targets in testsuite/sclang that are pretty broken - they use a full path as the test name, and also use a hacky approach to launch sclang.
- use [get_filename_component](https://cmake.org/cmake/help/latest/command/get_filename_component.html) to get simplified test names
- use the COMMAND form of [add_test](https://cmake.org/cmake/help/latest/command/add_test.html) to automatically launch the sclang executable
- note that this means you have to run the tests with `ctest -C <config>` if you're using a multi-config toolchain (i.e. VS, Xcode)
- launch with `-a` so that we only pull the class library from the repo (no extensions)
Issue 2: build_sclang.cfg doesn't end up being a …
=> cmake: fix doc, sclang-test targets

.travis/before-install-linux.sh, QtCollider/CMakeLists.txt, README_LINUX.md, editors/sc-ide/CMakeLists.txt, lang/CMakeLists.txt
PR to see if these Qt5 dependencies can be removed as discussed in #3471
=> Remove potentially unused qt5 dependencies

SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/ServerStatus.sc, testsuite/classlibrary/TestServer_clientID_booted.sc
*** PR Info text completely redone ***
Thanks to questions by @muellmusik and @brianlheim,
the cases covered in this PR became much clearer to me.
The general issue is handling repeated logins in network performance situations,
to recover as gracefully as possible from loss of connection between client and server,
whether by network glicht or client crash.
(server crash is outside the scope of this PR, but should be fully thought through elsewhere.)
Case 1: network connection is lost,
and the same client, same client-side server object logs in again.
* the server program remembers the client, and sends its previous clientID back
* then the client knows it is connected again,
* and it can keep all its known buffers, nodes, synths as they are.
-> so, just post that connection is back, and …
=> fix re-login behavior of remote clients to a server

CONTRIBUTING.md
Provides detailed instructions on updating the topic branch after the upstream gets updated.
This tries to clarify issues raised by @mtmccrea in https://github.com/supercollider/supercollider/pull/3198
Credit goes to @mtmccrea for making this as polished as we can :)
Please review especially the section about using git for rebasing after committing changes.
=> docs: update CONTRIBUTING.md with rebase caveats and general clarifications

lang/LangPrimSource/PyrListPrim.cpp, testsuite/classlibrary/TestAbstractFunction.sc
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/3-9-1-and-isRest-tp7638027.html
A user made the unfortunate inference that `\isRest, true` in a Pbind was a supported way to mark an event as a rest, not realizing that it was a private implementation detail that was subject to change. Unfortunately, his private code base now contains some 20,000 occurrences of \isRest.
I could make a strong case that this is *de facto* a legacy way to write rests, and we shouldn't burn users who got the wrong idea. (It is, in fact, not the users' fault that sclang does nothing to prevent public use of private entities.) Hence, this PR.
One could also make a case that `\` and `\r` were previously legitimately supported, but `\isRest, true` was not.
I think on balance, the …
=> Lang: Add event[\isRest] == true test to Event_IsRest primitive

HelpSource/Classes/LanguageConfig.schelp, SCClassLibrary/Common/Core/LanguageConfig.sc, lang/LangPrimSource/PyrPrimitive.cpp, lang/LangSource/SC_LanguageConfig.cpp, lang/LangSource/SC_TerminalClient.cpp
Fixes \#2919.
- Create the language config dir on startup. This step is skipped if run in standalone mode or a non-standard config file is specified with `-l`. This addresses issues raised by @jamshark70.
- Modify `SC_LanguageConfig::writeLibraryConfigYAMLFile` (C++) to return false if writing fails
- Modify `LanguageConfig.store` (SC) to throw a descriptive error on failure
Open to discussing alternate approaches. This doesn't feel perfect to me but I can't really put my finger on why. Either way, tested on macOS and works fine.
=> sclang: create config dir on startup, report errors from LanguageConfig.store

HelpSource/Classes/TreeView.schelp, QtCollider/widgets/QcTreeWidget.cpp, QtCollider/widgets/QcTreeWidget.h, SCClassLibrary/Common/GUI/Base/QTreeView.sc
This adds the `setColumnWidth` method to TreeView. This was requested by a user on the mailing list (Stefano Franchi) and I see no reason not to add it.
=> QTreeView: add setColumnWidth

HelpSource/Classes/Platform.schelp, SCClassLibrary/Common/Quarks/Git.sc, SCClassLibrary/Platform/Platform.sc, SCClassLibrary/Platform/windows/WindowsPlatform.sc
This PR adds a new function `Platform:-formatPathForCmdLine` that handles path formatting for command line calls across platforms. On Platform, it throws a subclass responsibility error. On WindowsPlatform, it quotes the string. On UnixPlatform, it escapes spaces.
The new function is used to solve an issue where bad paths are passed to the Windows shell in `Git.sc`—see https://github.com/supercollider/supercollider/pull/2722#issue-208840763 for details.
Hasn't been tested yet.
=> Windows: fix incorrectly escaped paths passed to shell

SCClassLibrary/Common/Quarks/QuarksGui.sc
Before:
- go to `Quarks.gui`
- click on the URL of any Quark that has not been checked out
- BOOM
With this patch:
- opening the URL goes by default to the `quark.url` without relying on
a git repo
=> open git URL without fetch

lang/LangSource/DumpParseNode.cpp, testsuite/classlibrary/TestFloat.sc
Fixes #3573
Floats that are equal to an integer are printed with .0
I couldn't find a way to do this without actually scanning the string to
see if '.0' needs to be appended. "%.9f" will print extra significant
digits; and "%#.14g" will do the same. I think _possibly_ switching on
the point where numbers change to scientific notation (1e14) and then
using "%#.14f" would work, but I'm not sure if that's a portable
solution and this seems a bit cleaner.
---
Before:
```
sc3> 3.0
-> 3
```
After:
```
sc3> 3.0
-> 3.0
sc3> 3.0000
-> 3.0
sc3> 3 - 0.0000000000000001
-> 3.0
```
=> sclang: print floats with at least 1 decimal place

SCClassLibrary/Common/GUI/Base/QRangeSlider.sc, testsuite/classlibrary/TestRangeSlider.sc
also add tests
I noticed setDeviation was relying on the same broken logic so I reimplemented it in terms of setSpan.
Fixes \#3616
=> RangerSlider: fix setSpan, setDeviation

HelpSource/Classes/UnitTest.schelp, SCClassLibrary/Common/UnitTesting/UnitTest.sc
Supersedes #3569.
When assertions succeed, we don't usually need to see the details; they just clutter up the output and make it harder to see the details of the failures.  So extend `UnitTest` and `UnitTestResult` in a backwards-compatible manner:
- Default behaviour does not change.
- Output from anything other than passing assertions does not change.
- If `UnitTest.passVerbosity` is set to the constant `UnitTest.brief`, passing assertions only output the summary, not the details.
In a future release it may be considered acceptable to switch the default for `passVerbosity` to `brief`.
Additionally perform some other cosmetic cleanups on the test framework output.
Partially addresses #3365.
=> UnitTest: brief reporting for passing tests via passVerbosity = brief

SCClassLibrary/Common/Control/asScore/ScoreStreamPlayer.sc, SCClassLibrary/Common/Control/asScore/asScore.sc, testsuite/classlibrary/TestScore.sc
The `flop` was problematic for `schedBundleArray`. While `schedBundle`
takes the bundle in the form of an ellipsis argument, the former takes
it as an array. Then, the function multichannel expands on the bundle.
=> class library: fix bug in score multichannel-expansion

HelpSource/Guides/Polymorphism.schelp, HelpSource/Guides/WritingClasses.schelp, HelpSource/Reference/Assignment.schelp
- improve helpfile wording
- remove confusing examples
- explain class variable initialisation and scope
- explain constants
- improve and simplify example code
- remove wrong explanation of "slottedÓ: this was completely wrong, so I rewrote it.
(this replaces #3583).
=> help: writing classes corrections

lang/LangSource/SC_LanguageClient.cpp
On UNIX-like systems, if SuperCollider is compiled from source into the user's home directory via:
cmake -DCMAKE_INSTALL_PREFIX=$HOME
make install
then `Platform.systemAppSupportDir` and `Platform.resourceDir` will be set to
$HOME/share/SuperCollider
This is due to `CMakeLists.txt` containing the definition of `SC_DATA_DIR`:
elseif(UNIX)
add_definitions(-DSC_DATA_DIR="${CMAKE_INSTALL_PREFIX}/share/SuperCollider")
endif()
which is then consumed by `common/SC_Filesystem_unix.cpp`.
Unfortunately, this resulting path is identical to the old location for the *user* support directory, so it triggers a misleading warning.  However this deprecation was introduced by 2b77ef67 in August 2011, so it should be safe to remove it by now.
Fixes #3367.
=> Remove misleading deprecation of old support directory

editors/sc-ide/widgets/util/docklet.cpp, editors/sc-ide/widgets/util/docklet.hpp
Fix #3287 
This fixes what seems to be a weird race condition: when starting the IDE, a detached (and closed) docklet container can be raised just after it has been hidden, leading into a *ghost* unresponsive window (see linked issue).
I'm not sure this is the most elegant fix so I'm open to any hint if this needs to be done differently.
cc @jamshark70
=> [IDE] Fix detached docklet visibility bug

HelpSource/Classes/UGen.schelp, SCClassLibrary/Common/Audio/UGen.sc
A while ago I created a pseudo-ugen version of SimpleNumber.quantize method, which I used for processing sensor data. In the meantime, the .quantize method became obsoleted and replaced by .snap (https://github.com/supercollider/supercollider/pull/3160).
This creates a pseudo-ugen version for both .snap and .softRound (I'm not sure if the latter is useful as a pseudo-ugen, but I added it for the sake of completeness).
I added brief entry in the help as well. Does this need anything else to be merged?
also, here's a rough test of the language vs ugen version
(the values won't be exact due to timing, but the plots should look similar)
```
s.boot;
//snap test
(
Routine.run({
~time = 5; //seconds
~numSamples = 1000;
~maxValue = 10;
~bus = Bus.control(s, 1);
~bus.setSynchronous(0);
~list = …
```
=> Add pseudo-ugen implementation of snap and softRound

HelpSource/Classes/String.schelp, SCClassLibrary/Common/Collections/String.sc, testsuite/classlibrary/TestString.sc
Specifically, `+/+`, `withTrailingSlash`, `withoutTrailingSlash`
This is a fix for a bug reported on the mailing list (link forthcoming). Basically, the way we were testing for path separators wasn't very portable or robust.
Also adds tests and documentation.
Shoutout to @aspiers - I was using guard for this and it made the whole process so much smoother!
=> classlib: fix String methods that use path separators

HelpSource/Guides/FFT-Overview.schelp
At some point, the PV_Copy example was incorrectly copy/pasted from another example. Here's a new example that demonstrates conclusively that PV_Copy is added automatically (and which would fail if PV_Copy weren't there).
=> Help: FFT-Overview: Replace auto-pvcopy example, and explain

HelpSource/Classes/AllpassC.schelp
[docs] - supercollider/supercollider/helpsource/classes/alpassc.schelp - minor tweals (grammar, punctuation, formatting, et. al)
=> [docs] - supercollider/supercollider/helpsource/classes/alpassc.schelp - minor tweals (grammar, punctuation, formatting, et. al)

HelpSource/Classes/Buffer.schelp, SCClassLibrary/Common/Control/Buffer.sc, testsuite/classlibrary/TestQuery.sc
Fixes #3611 
Use **argTemplate** to filter query responses based on the Buffer's bufnum. This needs a UnitTest. I can write try and write one later. I've opted to based this on `develop` since `3.9.3` is set for tomorrow. We can always cherry-pick this into `3.9` if we want.
=> filter OSC response based on bufnum

HelpSource/Classes/String.schelp, SCClassLibrary/Common/Collections/String.sc, testsuite/classlibrary/TestString.sc
after #3634, +/+ would fail if the RHS was a symbol.
+/+ now converts the RHS to a string (unless it was a PathName) before
attempting to concatenate it.
Fixes #3699.
=> classlib: patch String:+/+

HelpSource/Classes/SoundFile.schelp, SCClassLibrary/Common/Files/SoundFile.sc
I initially wanted to update SoundFile's `cue` method documentation to correctly indicate the use of VDiskIn inside it's SynthDef. What I ended up doing is rewriting the SynthDef in the class file and in the documentation. The major difference is the removal of the redundant `Linen`. I couldn't understand why there needed to be two envelopes (one sustaining with gate, the other fixed duration without gate, both set to `doneAction:2`). Maybe I'm misunderstanding...? The rest of the changes are mostly cosmetic.
=> SoundFile: fix SynthDef and Helpfile to match

SCClassLibrary/Common/Files/SoundFile.sc, testsuite/classlibrary/TestSoundFile.sc
__Update:__ This PR adds a basic UnitTest for SoundFile. It also fixes a small error in an OSCFunc found inside this class.
OSCFunc's `argTemplate` can either be `nil`/`0` or an Array of intergers and/or functions. The SoundFile class contains an OSCFunc who's `argTemplate` is set to an Integer. For this reason, the OSCFunc will never fire. The following fixes the OSCFunc by making it's `argTemplate` into an _Array_ containing an Integer.
Consider the following:
```supercollider
e = (dur:0.01).play
e[\id] // Array containing Integer
e[\id][0] // Integer
(
n = NetAddr.localAddr;
a = OSCFunc({ |...args| "A fires".postln }, '/test', n, argTemplate: e[\id]).oneShot;
b = OSCFunc({ |...args| "B never fires".postln }, '/test', n, argTemplate: e[\id][0]).oneShot;
)
n.sendMsg("/test", e[\id][0]) …
```
=> SoundFile: add basic UnitTest, and small OSCFunc fix

HelpSource/Classes/Buffer.schelp, HelpSource/Classes/Function.schelp, SCClassLibrary/Common/Core/Function.sc, SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
Sometimes, one needs to plot values from a synth that depends on node
order. E.g. a synth that reads from a bus. This patch allows us to
determine the point at which the plotting synth is inserted in the node
order. It is inserted _after_ the target node. By default, this is the
default group of the default server. This follows the `asTarget`
interface, as documented in scdoc.
=> class library: plot relative to target synth

SCClassLibrary/Common/Collections/SequenceableCollection.sc, SCClassLibrary/Common/Math/SimpleNumber.sc, testsuite/classlibrary/TestClockScheduling.sc
The message schedBundleArrayOnClock is sent to a number in order to
send off an OSC bundle a after certain time. If that time equals zero,
there is no need to add the task to the clock’s queue. This commit adds
a case where the bundle is send right now without scheduling it on the
clock in that case.
This fixes #3533.
We should discuss the possible implication for the case that a specific clock is expected as the context of scheduling.
=> class library: only schedule messages if necessary

SCClassLibrary/Common/Collections/Event.sc, testsuite/classlibrary/TestEvent.sc
OK, this is a howler.
https://github.com/supercollider/supercollider/commit/f570219ac1b320639fab944e695c2900de35b7a6#diff-d6dd1b5f66b384ff6c730a82fb0710aaR25
Before the change, we correctly `put` into the parentTypes dictionary `(type, protoEvent)`.
After the change, the `put` moved into a new method `addParentType` with method signature `type, parentEvent` (reasonable) but *the call to this method omits the `type` argument*. So, where it used to work, now it's attempting to put into the parentTypes dictionary where the protoEvent is the key, and nil is the value. So the parentTypes dictionary is always empty, and user-supplied default values are never accessible.
Which means the author of this change committed, pushed, and pull-requested without running even the most rudimentary test. …
=> Fix event parent type regression

SCClassLibrary/Common/Streams/Patterns.sc
Without the fix:
```
(
p = Pbind(
\stuff, Pwhite(30, 36, inf),
\midinote, Pseq([Pkey(\stuff), 62, 64, 65], inf)
).asStream;
)
4.do { p.next(()).postln };
( 'stuff': 34, 'midinote': 62 )
( 'stuff': 35, 'midinote': 64 )
( 'stuff': 36, 'midinote': 65 )
( 'stuff': 31, 'midinote': 62 )
```
Pkey is skipped because: `repeats.value(inval).do` but the default `repeats` is nil :man_facepalming:
We should substitute `inf` repeats -- Pkey with no repeats specified should be infinite-length. In fact, I had suggested this at one point, but then somebody removed the nil check.
I think we shouldn't assign a default in the class. Currently we're using `nil` as an optimization, to avoid checking the stream length if it's going to be infinite anyway.
=> Classlib: Patterns: Pkey embedInStream must provide a default repeats

HelpSource/Classes/ArrayedCollection.schelp, HelpSource/Reference/plot.schelp, SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
ArrayedCollection plot used to throw hard to understand errors when it
contained a nil value. ~~Now it warns and plots anyway, replacing the
value by zero.~~ edit: now it throws a better error
This fixes #3725.
=> class library: throw proper error when plotting an array with nil (edited)

testsuite/classlibrary/TestUGen_Duty.sc
This PR brings TestUGen_Duty's tests up to date with our current
practices:
use a new server object instead of default
boot and quit server inside tests
Use condition variable to avoid races
Fixes #3209.
=> testsuite: update tests for Duty

README_MACOS.md
Hi there,
This is my first contribution in this repo, and one of my first OS contrib... My apologies for everything I'm doing wrong!
This PR is to fix a typo in a path in README_MACOS.md. In the part about accessing sclang and scsynth from the Terminal, the path for SC_PLUGIN_PATH is incorrect (missing "Contents/").
Looking forward to more substantial PRs!
=> readmes: fix path to plugins

common/SC_Filesystem_win.cpp
This pathname was incorrectly translated when moving from CSIDL to FOLDERID constants
Closes #3750
=> sclang: fix windows defaultSystemAppSupportDirectory

HelpSource/Classes/Document.schelp, HelpSource/Classes/TextView.schelp, HelpSource/Classes/View.schelp
these functions were incorrectly documented on both Document and View
quick test script showing that the arguments passed to the function are in fact the ones I've documented:
```supercollider
w = Window.new.front
w.view.mouseDownAction_ { |...args| args.postln; };
w.view.mouseUpAction_ { |...args| args.postln; };
Document.current.mouseDownAction_ { |...args| args.postln; };
Document.current.mouseUpAction_ { |...args| args.postln; };
// mouse down actions are passed 6 args, mouse up actions are passed 5
```
=> docs: mouse(Up|Down)Action

SCClassLibrary/Common/Collections/EnvironmentRedirect.sc, SCClassLibrary/scide_scqt/ScIDE.sc, testsuite/classlibrary/TestDocument.sc, testsuite/classlibrary/TestDocumentEnvir.sc
This fixes #3717.
The basic assumption is that only one document can be in focus.
1. when a document comes to focus that has an envir bound to it, it should make that envir the `currentEnvironment`. Whatever envir that was current at that time should be saved.
2. when a document loses focus (either by closing or because one moves to another one), it should restore the envir that was currentEnvironment before.
3. when we set the envir of a document that has no focus, it should not do anything but store the envir for the moment it comes to focus.
4. when we set the envir of a document that has focus, the envir should by default become `currentEnvironment`, so that it is in a consistent state.
=> fix link doc to envir

lang/LangSource/MiscInlineMath.h
This is to fix the issue described in #3784
=> Fix a maths bug in expexp() in MiscInlineMath.h

editors/sc-ide/widgets/code_editor/autocompleter.cpp
This causes the autocompleter to add a space between colon and insertion
point when autocompleting keyword arguments to a function.
ex. "Array.fill(size: <CURSOR>"
Fixes #831
Thanks to @patrickdupuis for finding the solution in #831!
To test:
Open the IDE, wait for introspection to load, and type `Array.fill(`. Then cycle through the options with tab.
Another good test case is trying it with text to the right of the cursor: inserting `Array.fill)` first, then placing the cursor to the left of the `)`, typing `(`, and cycling through the options.
=> IDE: add space after colon in autocompletion

HelpSource/Classes/Plotter.schelp, SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
This adds a basic "bar graph" type to PlotView. It also fixes the wrong index returned during editing for step-like representations when the mouse cursor is in the right half of the "step" and it updates the Plotter documentation to include the new functionality.
=> class library: Add bar graph mode to PlotView

lang/LangPrimSource/PyrArrayPrimitives.cpp, testsuite/classlibrary/TestArray.sc
Regarding issue #3716, this fixes two bugs:
a) Calls to lace with no length argument would fail if any elements in the
array weren't subarrays. Now lace will assume the max length of each
subelement is one.
b) Calls to lace with empty subarrays would crash due to a divide-by-zero
error in running modulo to calculate the lace index on a subarray of length
zero. Now the code simply copies the empty subarray into place in the ouput
array.
=> sclang: fixes crash on call to Array::lace with empty subarrays

QtCollider/style/ProxyStyle.cpp
Temporary workaround for issue #3552.
Automatically-faded scroll bars do not work well in Linux or Windows. Unfortunately, if the user touches the scroll wheel, then scroll bars start to fade out and become unreachable.
Under issue #3552, we were discussing research into Linux and Windows system preferences for fading scrollbars, and per-view control. That's an extensive enhancement request.
In the meantime, I was recently in the position of trying to explain to a classroom of students why the scrollbars disappear if you touch the scroll wheel, but not before. Let's just say that the rationale for the current behavior was met with universal incomprehension.
Currently, we have a situation that simply doesn't make sense to typical users in Windows and Linux. So, at the very least, for 3.10, …
=> QtGUI: Remove scroll wheel check for scrollbars in Windows and Linux

README_MACOS.md
Fixes a minor `brew` command omission and adds info regarding macOS deployment target in cmake.
=> Update macOS build readme

.appveyor.yml
This wasnt feasible before with the version of boost that we had, but weve updated now and it
builds locally. I think this is the version we should be using for CI; it will produce faster
executables.
=> appveyor: update to vs2017

QtCollider/widgets/soundfileview/view.cpp, QtCollider/widgets/soundfileview/view.hpp, common/SC_SndFileHelpers.hpp, lang/LangPrimSource/PyrFilePrim.cpp, server/scsynth/SC_SequencedCommand.cpp, server/scsynth/SC_SequencedCommand.h, server/scsynth/SC_World.cpp, server/supernova/audio_backend/sndfile_backend.hpp, server/supernova/sc/sc_plugin_interface.cpp, server/supernova/server/buffer_manager.cpp
See prev work in #3683 
Fixes #3673, fixes #3719.
After the big PR awhile ago there were still some uses of libsndfile's sf_open function that didn't handle Unicode strings for the Windows FS API. This cleans that up.
Moved common logic to the SC_SndFileHelpers header so there are fewer ifdefs everywhere.
Fixed spots are:
- supernova's sndfile backend, buffer manager, and plugin interface
- scsynth's NRT and b_read-related commands
- Qt soundfileview's soundfile loading
some of the refactoring also touched the sclang soundfile primitives
=> remove remaining unsafe usage of sf_open

HelpSource/Classes/Recorder.schelp, HelpSource/Classes/Server.schelp, SCClassLibrary/Common/Control/Recorder.sc
Recorder class should mkdir the user's chosen location in all cases
Yesterday, I gave some code that looks like this to a classroom full of students:
```
if(view.value == 1) {
Server.default.record(
Platform.recordingsDir +/+ "%-%.wav".format(
idField.string, groupField.string
),
numChannels: 2
);
}
```
When I ran it in the classroom, the server complained that it couldn't open the output file.
Then I found out why:
- If the default recording location doesn't exist, it is created for you in `Recorder:makePath`.
- `makePath` is called only if you don't specify a path.
Therefore, if the user wants to override the default filename but not the recording location, then the user has a gotcha -- "every other time I tried to record, there was no problem, but when I do it for the first time on a …
=> Classlib: Recorder: Create user's recording directory if it doesn't exist

lang/LangSource/SC_TerminalClient.cpp
this cherrypicks @giuliomoro's fix for #2144, the infamous "CPU hog when built without Qt" issue. this fix has been used for a long time in the bela fork of SC. see his comment here for explanation: https://github.com/supercollider/supercollider/issues/2144#issuecomment-320401926.
the fix seems quite logical to me, and i've tested and verified that it corrects the behavior. ~~what is mysterious is not the bug itself, but the fact that it *doesn't* happen when sclang is built *with* Qt.~~ **EDIT:** it's actually hilariously simple, there's an `#ifdef SC_QT` which redirects `SC_TerminalClient` to the completely separate `LanguageClient` code in QtCollider. so this is symptomatic of a larger problem: fragmentation of code depending on whether SC_QT is on or off, which is most likely a …
=> sclang: Fix excessive calls to SC_TerminalClient::tick when SC_QT is off

lang/LangSource/dumpByteCodes.cpp
While exploring bytecodes I realized some of these messages are
incorrect, possibly from older stages of development of the language.
The method used to calculate indices for PushTempVarX, PushTempZeroVarX,
and PushTempVar was incorrect, which led to misleading output from
dumpByteCodes.
The posting for PushClassVar was misleading, as it printed 3 bytes
instead of the actual 2.
Some test code:
```supercollider
{ var a = 1, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r = 5; q.squared}.def.dumpByteCodes
{ var a = 1, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r = 5; r.squared}.def.dumpByteCodes
{ var a = 1, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r = 5; { a.squared }.def.dumpByteCodes }.value
{ var a = 1, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r = 5; { r.squared …
```
=> sclang: fix issues in dumpByteCodes

editors/sc-ide/widgets/help_browser.cpp
Reload button presses must pass through onLinkClicked to trigger reparse in case the file was modified externally
Fixes #3812
=> ide: fix help browser reload button

server/scsynth/SC_Jack.cpp, server/supernova/audio_backend/jack_backend.hpp, server/supernova/audio_backend/portaudio_backend.hpp, server/supernova/sc/sc_osc_handler.hpp, server/supernova/server/server.hpp
There is currently a ~~heated~~ debate on the [Ableton Link PR](https://github.com/supercollider/supercollider/pull/3351) on how to implement accurate ~~sample-level~~ synchronization between instances. While doing some tests I noticed some inconsistencies regarding latency compensation in scsynth and supercollider for timestamped events:
* scsynth with jack audio backend has a sign error when computing true output time, which leads into a doubling of the latency ! (I can't believed that I never noticed this).
* supernova has no mechanism for latency compensation.  I implemented it similarly to how it's done in scsynth.
=> Latency compensation in scsynth & supernova

HelpSource/Classes/Platform.schelp, SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Platform/Platform.sc, SCClassLibrary/Platform/windows/WindowsPlatform.sc, server/scsynth/scsynth_main.cpp, server/supernova/server/server_args.cpp
This PR fixes `asOptionsString` to use correct concatenation (as described in `scsynth -h`) for `ugenPluginPath` (`scsynth -U <path>[:<path>[:<path>]]`) (`":"` instead of `"; "`).
Like most developers, I have built SC and sc3-plugins from source. This means I have two valid paths.
Test that pluginpath works
```
(
// plugin paths without plugins
s.options.ugenPluginsPath = thisProcess.platform.helpDir
)
s.options.asOptionsString;
s.reboot
```
results in (anticipated) errors
```
-> Booting server 'localhost' on address 127.0.0.1:57110.
*** ERROR: open directory failed '/localvol/sound/src/supercollider/Help': No such file or directory
exception in GraphDef_Load: UGen 'Control' not installed.
[...]
```
Test general plugin paths
```
(
// fill your own plugin paths here …
```
=> ServerOptions:asOptionsString: fix to use correct concatenation

common/SC_Filesystem.hpp, server/CMakeLists.txt, server/scsynth/CMakeLists.txt, server/scsynth/SC_Lib_Cintf.cpp, server/supernova/CMakeLists.txt, server/supernova/sc/sc_ugen_factory.cpp, server/supernova/server/main.cpp
this fixes #2290 and #3446. here are the supernova plugin path problems:
- the `SC_PLUGIN_PATH` environment variable is not respected
- on linux systems, a fixed set of hardcoded paths are tested, and that's it
- tries *all* files, not just ones with the correct extension
now supernova should have identical behavior in plugin path loading compared to scsynth. #2290 in particular was barring me from using supernova.
some variables had to be moved from scsynth to avoid code duplication.
=> supernova: Unify scsynth/supernova plugin loading

server/supernova/sc/sc_ugen_factory.cpp
A previous PR broke supernova compilation on macOS; this allows Supernova to build when SC_PLUGIN_EXT has not been defined in compiler options.
=> supernova: include header to get SC_PLUGIN_EXT

HelpSource/Classes/File.schelp, lang/LangPrimSource/PyrFilePrim.cpp
Fixes #3635.
Per https://www.boost.org/doc/libs/1_49_0/libs/filesystem/v3/doc/reference.html#Error-reporting, all that is necessary to get an error to be thrown is to remove the error_code argument from the call to `bfs::create_directories()`. On success, it drops through to `return errNone`; on failure, a C++ exception is raised, caught, and passed along to a sclang PrimitiveFailedError.
Test:
```
File.mkdir("/usr/oh-no-you-cant");
ERROR: Primitive '_FileMkDir' failed.
caught exception 'boost::filesystem::create_directory: Permission denied: "/usr/oh-no-you-cant"' in primitive in method Meta_File:mkdir
```
Also, I added a short section to the File documentation about error handling for the boost functions.
=> File.mkdir now throws an error

HelpSource/Classes/Function.schelp, HelpSource/Classes/SynthDef.schelp, HelpSource/Reference/play.schelp, SCClassLibrary/Common/Control/GraphBuilder.sc
Currently, the GraphBuilder that wraps the UGens in function.play
always makes a fade envelope, unless the output is a scalar.
Instead, this should be done only when absolutely necessary. When the
Ugen graph has already an envelope that is able to release the synth,
we avoid making another envelope.
This fixes #3768.
#testing: this may have an impact on some past workarounds tha uses
{ }.play, or internally makes use of the GraphBuilder. This is an API
change.
=> class library: function play fade envelope when necessary

HelpSource/Classes/Server.schelp
below follows an attempt at:
- improving the quality of Server.schelp documentation file
my atttempt goes in the the direction of fixing issues related to:
- typing
- words mispelling
- grammar
- syntax
- puntuation
- other issues
---
i acknowledge that:
- the document may need some bugs to be fixed;
- my contribution may need some revisions;
- i may have accidentaly broken some community guidelines (currently contrbuting to several projects);
if that is the case:
- be honest
- don't hesitate in telling me what you think
- i will make sure i will fix everything to meet our standards
looking forward
kind regards/ best wishes
T.
---
=> [docs] - supercollider/supercollider - supercollider/HelpSource/Classes/Server.schelp - minor attempts at fixing some typos and grammar

HelpSource/Classes/Done.schelp, SCClassLibrary/Common/Audio/EnvGen.sc, server/scsynth/SC_Node.cpp, server/supernova/sc/sc_plugin_interface.cpp, testsuite/classlibrary/TestDoneActions.sc
This PR adds a new `doneAction`, namely `Done.freeSelfResumeNext` (number 15). It is analogous to `freeSelfPauseNext` (number 10).
This PR is motivated by the lack of sample based scheduling in sclang. The done action allows us to build a  queue of paused synths that resume each other in a series, while new paused synths can be added. 
Here is an example that streams sclang generated values to scsynth:
```supercollider
(
var n = 2048;
SynthDef(\seq, { |out = 0|
var array, signal;
array = \array.ir(0 ! n);
signal = Duty.ar(SampleDur.ir, 0, Dseq(array, 1), doneAction:Done.freeSelfResumeNext);
ReplaceOut.ar(out, signal)
}).add
)
(
var block = 2048;
var dt = 1/s.sampleRate;
var dur = dt * block;
var synths;
var nextN = value {
var c = 0;
var freq = 64.midicps;
var r = 2pi * freq * dt;
{ |n|
{ …
```
=> Add freeSelfResumeNext done action

testsuite/classlibrary/TestNode_Server.sc
Node:getn is broken in supernova, which makes this test hangs forever.
Adding a timeout makes the test fail correctly. 
(Working towards making all server tests work with supernova...)
=> Letting TestNode_Server:test_getn time out and fail

HelpSource/Classes/Buffer.schelp, HelpSource/Reference/Server-Command-Reference.schelp, SCClassLibrary/Common/Control/Buffer.sc, server/scsynth/SC_SequencedCommand.cpp, server/supernova/sc/sc_osc_handler.cpp, server/supernova/sc/sc_plugin_interface.cpp, testsuite/classlibrary/TestBuffer.sc
Regarding #3631, implements @jamshark70 suggestion to correctly append
completion argument in array. Also fixes supernova so it doesn't
hardlock when channel and completion arguments absent.
=> comp: allocReadChannel no longer requires last argument in supernova

testsuite/classlibrary/TestInteger.sc
Per agreement in #3811, now that exception throwing testing is supported,
adds tests to make sure forBy throws exceptions when a zero-valued step
is supplied or when non-integer-or-float types supplied for either step
or end arguments.
=> sclang: adds exception tests for Integer:forBy

.appveyor.yml
Current appveyor builds are failing because I was pointing at 5.11.0 directly. It looks like Appveyor have now removed that in favor of 5.11.1.
=> appveyor: use symlink to current qt version

HelpSource/lang-sc.js, HelpSource/scdoc.css
syntax highlighting for code in the help/docs is different (but confusingly similar) from the default theme in the editor. for consistency, colors and font weights are adjusted to be the same.
before:
after:
the careful eye will notice that the editor has slightly lighter tone than the docs. 
i wasn't able to translate that from qt into css, but if it's significant i might do it.
the default theme: https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/core/settings/theme.cpp#L101. testing the docs theme: https://github.com/supercollider/supercollider/blob/develop/HelpSource/syntax_colors.html
=> docs: match code syntax highlighting from the default theme

QtCollider/widgets/QcCanvas.cpp, QtCollider/widgets/QcScopeShm.cpp
The QPainter::drawPixmap we were using does scaling. We need to use the version that clips, in case the thing we're painting extends beyond the surface of the canvas.
Also, fix two places where we demote float pixelRatio to int - this would have broken fractional pixelRatios.
Fixes #3822
=> sclang: Fix scaling of canvas painting

server/supernova/sc/sc_osc_handler.cpp
TL;DR It's a typo. No risk to include in 3.10.
Supernova currently omits newline for "unallocated buffer" error messages.
Supernova also flushes log output to the post window only when it prints `\n`.
This means posting these particular error messages is delayed until the next log post from supernova. This may be anywhere from seconds to minutes later, making it impossible to troubleshoot (if you don't know when the error really happened, you can't narrow it down in the code).
Easily corrected.
```
Server.supernova;
s.boot;
// unallocated buffer but no posting
s.sendMsg(\b_setn, 0, 0, 3, 1, 2, 3);
a = { PlayBuf.ar(1, 0) }.play;
-> /b_setn called on unallocated bufferBuffer UGen: no buffer data
a.free;
```
=> Supernova: Add missing \n to buffer command error messages

SCClassLibrary/Common/Streams/FilterPatterns.sc, testsuite/classlibrary/TestPattern.sc
Pstretch did not correctly apply to events using \delta rather than \dur for rhythm -- including all Ppars.
The original code, when checking if the event has a delta, checked `event[\delta]` -- which seems reasonable, until you read it more closely and see that `event` is the event prototype that was passed in. The event-in-progress (including information from Pstretch's child pattern) is `inevent`, in a really bizarre reversal of semantics.
I don't have time to review all filter patterns today, but we really should make sure to be consistent: `inevent` should always be the event prototype (`arg inevent`; `inevent = blahblah.yield`) and `event` should always be the event being prepared for yield. That should avoid this sort of confusion in the future.
Simple tests, ensuring that basic …
=> Classlib: Pstretch(p): Correct bug resulting from variable name confusion

HelpSource/Classes/Ndef.schelp, HelpSource/Classes/NodeProxy.schelp, HelpSource/Tutorials/JITLib/jitlib_fading.schelp, HelpSource/Tutorials/JITLib/proxyspace_examples.schelp, SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
Setting the gate of an envelope to a negative value makes a forced release. What remained unnoticed here was that the forced release shape is always linear, regardless of the envelope’s shape. This commit replaces the forced release by a normal release. The fadeTime is set,
so forcing wasn’t necessary.
This fixes #3775.
It changes how crossfading sounds.
testing:
- test how node object replacement and freeing sounds.
- this may change the behaviour of SynthDefs that are separately made
and which *do not use the `fadeTime` parameter to specify the release
time*.
=> Fix nodeproxy release shape

README_WINDOWS.md
fixin' some issues i encountered following along the windows readme.
add note explaining where libsndfile exists by default when you install it.
remove references to readline. since readline is not functional, it simply adds confusion.
explain how to get visual c++, which is required when installing visual studio.
=> Clarify windows readme

server/supernova/sc/sc_osc_handler.cpp
This PR fixes #3839: 
supernova now returns correct responses to correct s_getn calls, 
which fixes the failing test in TestNode_Server.
```
Server.supernova;
TestNode_Server.run; // no failures now
```
Explicit testing raises a followup question: scsynth and supernova handle \s_getn calls with odd arg numbers (which are wrong) differently: scsynth sends back wrong values, supernova does not answer. 
Which behavior should that be unified to? 
```
// longer tests:
OSCFunc.trace(true, true); s.dumpOSC;
// switch to supernova
Server.killAll; Server.supernova; s.waitForBoot { x = Synth(\default, [\out, 0, \freq, 234, \amp, 0.125, \pan, 0.5]) };
//  multi-getn is now correct in both: 
s.sendMsg(\s_getn, x.nodeID, 1, 1, 2, 3);
// OK: [ /n_setn, 1000, 1, 1, 234.0, 2, 3, 0.125, 0.5, 1.0 ]
// …
```
=> supernova_getn: fix getn response

HelpSource/Classes/Server.schelp, SCClassLibrary/Common/Control/Server.sc, SCClassLibrary/Common/Control/ServerStatus.sc, testsuite/classlibrary/TestNodeProxy.sc, testsuite/classlibrary/TestServer_boot.sc
currently supernova servers tends to hang on reboot (macOS 10.13.4):
```
Server.supernova; 
s.reboot; // first time usually works
s.reboot; // second time usually hangs, because notify does not happen.
```
this is a timing issue: supernova sends back the quit message early, but the supernova process still lives long enough to interfere with the boot messaging traffic with the rebooted instance. 
Thus, this PR adds waiting for release of the (previous) process PID when booting, which fixes the hang condition.
This PR includes
* waiting for quitting process to release server.pid
* safer testing for notify clientID info from server (supernova messages are not identical yet)
* new unit tests for reboot method 
* fix to cycleNotify which tends to hang up TestServer_boot methods
Result: All …
=> Fix supernova reboot bug, add reboot tests

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
This PR recovers the implementation of `plot` before it was changed to use OSC messages instead of writing files. We now only use OSC when the server is remote so that plot wouldn't work otherwise.
This is a temporary fix, in a later version we agreed on cleaning up the interface involving methods like `loadToFloatArray` and `getToFloatArray`.
=> class library: function plot switches method

SCClassLibrary/Common/Collections/Collection.sc, SCClassLibrary/Common/Collections/Dictionary.sc, SCClassLibrary/Common/Collections/SequenceableCollection.sc, SCClassLibrary/Common/Collections/String.sc
This PR adds an identity check-based early exit to the '==' methods of 
Collection, SequenceableCollection, String and Dictionary (and thus indirectly to IdentityDictionary).
Collections that will be compared often may be identical, or may contain identical subcollections, and for these cases there aresignificant speedups. 
Given that identity testing is really fast, the potential add cost is minimal.
No changes in behavior except speedups when objects are identical or partially identical.
Examples for measured speedups:
```
a = (1..1000);
b = a.copy;
bench { 1000.do { a === b } }; // ca 0.00012
bench { 1000.do { a ==  b } }; // ca 0.234
b = a;
bench { 1000.do { a ==  b } }; // ca 0.0010 <- as fast as === when …
```
=> Collection:== : add early exit for identity, also in subclasses

HelpSource/Classes/String.schelp, SCClassLibrary/Common/Collections/String.sc, SCClassLibrary/Common/Math/SimpleNumber.sc, testsuite/classlibrary/TestString.sc
This corrects the behavior of ```String -asSecs``` to expect the format ```hh:mm:ss.sss```. This is consistent with the documentation and the reverse method ```SimpleNumber -asTimeString```.
Fixes https://github.com/supercollider/supercollider/issues/3818.
Before merging this, I have one question:
The original implementation warns when number of seconds/minutes/hours exceeds respectively 60/60/24, and _clips these values to their maximum_. IMO the clipping should not happen and I removed that in this PR. 
So previously
```"62:1".asSecs; //warns and returns 60.1```
and now
```"62.1".asSecs; //warns and returns 62.1```
What do you think should be the right behavior?
=> class library: fix String -asSecs

HelpSource/Classes/File.schelp, SCClassLibrary/Common/Files/File.sc, lang/LangPrimSource/PyrFilePrim.cpp, lang/LangPrimSource/PyrFilePrim.h
Recursive delete of a pathname. Fixes #3651.
Checklist
---------
=> [class library] new _FileDeleteAll primitive

editors/sc-ide/core/main.cpp, editors/sc-ide/core/main.hpp
Fixes #3792, this forces the UI colors to track the changes to the colors
in the settings menu. We set the colors on startup as well as update the colors
each time the settings are applied.
- New feature (non-breaking change which adds functionality) 
Checklist
---------
Remaining Work
-------------
None known.
=> [scide] ui colors now reflect editor colors in settings

editors/sc-ide/widgets/main_window.cpp
Fixes #3975.
Added a function-static atomic to determine whether or not a settings
window is already open. Since I'm sure some of our stuff and the Qt
stuff is not noexcept, I added a try-catch to avoid the atomic becoming
stuck at true.
Checklist
---------
Remaining Work
--------------
=> ide: only allow one preferences window open at a time

editors/sc-ide/CMakeLists.txt
Fixes #3971 by making sure macdeployqt is run on the QtWebEngineProcess binary.
I am not sure if a similar change needs to be applied on Windows.
For the record, a way to reproduce #3971 is by simply renaming the directory containing the Qt libs found by CMake after the build is complete.
Checklist
---------
=> cmake: run macdeployqt on qtwebengineprocess binary as well

.travis/before-install-linux.sh, HelpSource/editor.js, HelpSource/scdoc.js, README_LINUX.md, SCClassLibrary/SCDoc/SCDoc.sc, SCClassLibrary/SCDoc/SCDocRenderer.sc, editors/sc-ide/CMakeLists.txt, editors/sc-ide/core/main.cpp, editors/sc-ide/widgets/util/IDEWebChannelWrapper.hpp, editors/sc-ide/widgets/util/WebSocketClientWrapper.hpp, editors/sc-ide/widgets/util/WebSocketTransport.cpp, editors/sc-ide/widgets/util/WebSocketTransport.hpp
shift-enter needs to be intercepted at the JS level and call a slot on a
C++ object in order to evaluate a line. This shortcut isn't propagated
normally. This commit adds QWebChannel and QWebSockets to the dependencies
and uses them to allow JS to request the help browser C++ code to evaluate
a line.
Also some changes to JS code and SCDoc renderer code
Note that the WebChannel should only be loaded on pages with code to
execute.
The WebChannel is constructed in the IDE's main() and then the help browser
is published to it. On the JS side, evaluateSelection(false) is called
whenever shift-enter on a code snippet is detected.
Note that I based this off @htor's other branch, since that will be
merged soon and since I needed to interface with some …
=> [IDE] fix shift-enter behavior in IDE

HelpSource/Classes/Quarks.schelp, SCClassLibrary/Common/Quarks/Quarks.sc, SCClassLibrary/Common/Quarks/QuarksGui.sc
In `Quarks.gui`, if the user clicks the "Check for updates" button, the feedback to the user is misleading -- even up to the point of making the user think that SC is stuck in an infinite loop.
Checking updates involves two steps: 1/ fetching the directory listing and 2/ iterating over all quarks and, for each downloaded quark, `git fetch`-ing updates.
Upon reviewing the code, I found that it was always intended to provide a status update to the user for both steps. But, when I tried it just now, I saw the status for the first step but not the second. Meanwhile, the second step was running in the background, launching synchronous system processes (`Pipe.callSync`) that block the interpreter until each one is finished.
So the GUI tells the user …
=> Classlib: Quarks: Correct the user feedback in GUI "Check for updates"

HelpSource/editor.css, HelpSource/editor.js
the syntax highlighter in the docs doesn't correctly handle primitives, doesn't highlight `currentEnvironment` or `topEnvironment`, and also misses hex ints. colors for tokens are not matching the ide theme either.
this pr fixes the syntax highlighter to correctly match the above tokens, and adjusts the color theme to match the default color theme in the settings file `sc_ide_conf.yaml`. i've used the [main ide lexer](https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/core/sc_lexer.cpp#L41) as the reference for the syntax and token names. 
note that css class names are adjusted to the names used in `sc_ide_conf.yaml` so they can easily be set in js later when we have access to the theme from settings, by using the css …
=> docs: improve syntax highlighter

HelpSource/editor.js
may fix #3924. needs to be tested, because i can't reproduce it here.
otherwise this should be merged anyway, since the keybinding isn't needed.
(only shift-enter keybinding is needed in javascript and cmd/ctrl-enter keybindings are already intercepted in c++)
Checklist
---------
Remaining Work
--------------
test this pull, those who can reproduce #3924
=> help-browser: rm keybinding used for js debugging only

SCClassLibrary/Common/Control/Buffer.sc
Scsynth quietly accepts the (incorrect) non-integer starting frame parameter in Buffer messages, while Supernova does not. This PR adds `.asInt` before sending buffer messages to the server and makes the behavior consistent between scsynth and supernova, at least in sclang.
I know that this parameter should be an integer according to the specification, but again, scsynth makes sound, while supernova doesn't. This is especially likely to happen when using `.cueSoundFile` where we calculate starting frame as `time * sample rate` (time likely being a float).
I vaguely remember a similar discussion about the `numFrames` parameter, but I can't find it now. This parameter is already being converted to an integer before sending the message to the server.
Also, is there a recommendation on using …
=> class library: Buffer: convert starting frame to integer before sending to server

server/plugins/Convolution.cpp
Fixes this old issue that made hear clicks in Convolution2L
Correction of unit->m_tempbuf DC and Nyquist uninitialized.
=> Convolution2L: fixes #723

HelpSource/Classes/PV_ChainUGen.schelp
b4b70b4f43 introduces a copy/paste error into the documentation for `pvcollect`.
The function for this method should take the magnitude and phase for a single bin, and return either a new magnitude or a magnitude/phase pair for this bin only.
The revision adds an "example function" that takes `| magnitude, phase, bin, index |` as arguments but then returns `[mags.reverse, phases.reverse]`. `mags` and `phases` are undeclared, so this will never work. Also, it's conceptually inconsistent. `pvcollect` operate on individual bins, not on all of them at once: `reverse` doesn't make sense in this context. But it does make sense for `pvcalc`.
The PR replaces the return with a simple per-bin randomizer. …
=> Help: Correct the 'pvcollect' example function

editors/sc-ide/widgets/style/style.cpp
sometimes the tab overline gets drawn wrong for really dark themes:
because i forgot that `QRect`'s arguments are x-y-width-height, not x1-y1-x2-y2.
the overline only shows up when the theme has a really dark background, so use e.g. the default "dark" theme if you want to see the effects.
cosmetic bug fix
Checklist
---------
=> [scide] Fix tab overline

SCClassLibrary/Common/Control/ResponseDefs.sc, testsuite/classlibrary/TestOSCFunc.sc
Fix bug noted in issue #1482 in which OSCArgsMatcher would show a match with fewer args than the template.
Checklist
---------
(There's no new functionality, so I've not added a test for this, though I can if needed)
=> class library: Check message is >= template size in OSCArgsMatcher

editors/sc-ide/CMakeLists.txt, editors/sc-ide/core/settings/default_themes.cpp, editors/sc-ide/core/settings/theme.cpp, editors/sc-ide/core/settings/theme.hpp
the default IDE theme is quite ugly. providing a professional looking default theme improves first impressions of SC. also if SC educators don't have to look at #ffffff white backgrounds when helping students, that's a plus.
this PR supplies a new default theme. here's what it looks like with some SynthDef code:
here is the full gamut of code colors and the syntax elements they correspond to:
i wanted to keep it a light theme to avoid making the change too radical from 3.9. the colors are lifted from [Kary Pro Color](https://github.com/pmkary/kf-theme-vscode), but i switched them around considerably to keep an attractive balance of hues in typical SC code.
the background is light gray and not white like the old theme. however, it is still …
=> [scide] Change default theme

HelpSource/editor.js, editors/sc-ide/core/sc_lexer.cpp, editors/sc-ide/widgets/code_editor/highlighter.cpp, editors/sc-ide/widgets/code_editor/tokens.hpp
fix #2545. scide and scdoc now correctly highlight scale degree literals.
Checklist
---------
=> [scide] [scdoc] Add syntax highlighting for scale degree literals

.appveyor.yml
Appveyor builds are currently failing because of an update to VS 15.8
which breaks lots of things.
As documented on Appveyor's site, use the previous (working) VS 2017
image.
=> appveyor: use previous images

.travis/before-install-osx.sh, .travis/before-script-osx.sh
This turns on building SuperNova for macOS Travis builds, and makes two further changes:
- don't send analytics to homebrew (really? yes...)
- don't let brew auto-update, which takes forever when installing/upgrading
- CI change
- change to release assets
Note that _release builds will now include Supernova_. This is something we've discussed at dev meetings and on the ML, and nobody has opposed it, so I thought I should make this change now that we're close to releasing 3.10!
Checklist
---------
=> travis: build supernova for MacOS

SCClassLibrary/Common/Streams/Pspawner.sc
Fixes #1084.
Checklist
---------
Note
----
As a sidenote -- in #1084, Julian said:
> To fix this, we can use a direct lookup event[\method] but in order to make it fully backward compatible, it would have to be:
> 
> ```
> method = event[\method];
> method !? { method = method.functionPerformList(\value, event) }
> ```
I don't think we have to be that fussy. Pspawn is not used very much, and `method` should be chosen algorithmically using patterns, and the other pseudo-method (`spawner`) must not be overridden or the whole thing breaks. I'd be content to say that putting functions there is incorrect usage.
=> Classlib: Remove pseudo-method calls from Pspawn:embedInStream

CMakeLists.txt
this fixes an issue where experiencing a cmake config-step error would leave install prefix set to /usr/local
Seen in https://github.com/supercollider/supercollider/issues/3931 and elsewhere.
Checklist
---------
You can test this issue this way:
Before this PR (off 3.10 or develop):
1. `git submodule deinit --all`
2. starting from a fresh build directory, run the cmake configure step
3. configuring will fail because certain files are not found in external_libraries
4. at this point, run `cmake -L` to see that `CMAKE_PREFIX_PATH` is set to /usr/local
5. if you want to recreate #3931, re-initialize submodules and build the `install` target
After this PR:
1. …
=> Cmake: force set install prefix on macos

SCClassLibrary/JITLib/GUI/NdefGui.sc
in NdefGui:checkUpdate, the update to the typeView was accidentally commented out. 
this PR reenables it, so NdefGuis again display the rate (ar/kr) and numChannels of its proxy.
just a minimal bug fix, so it introduces no new features, and no need to add tests or documentation.
=> NdefGui: re-enable typeView update

HelpSource/Classes/SoundFile.schelp, SCClassLibrary/Common/Files/SoundFile.sc, testsuite/classlibrary/TestSoundFile.sc, testsuite/classlibrary/TestSoundFile_Server.sc
This PR introduces a few fixes and documentation improvements to SoundFile's cue method.
- This PR fixes a mistake introduces in a previous PR (#3713) by correctly renaming the event key to `~sustainTime`
- The main fix here is related to the `closeWhenDone` argument. Previously, this arg had no effect. Now, the OSCFunc correctly fires which closes the buffer ~and SoundFile~.
- The documentation was improved to indicate the closing of the buffer by `closeWhenDone`.
- `bufferSize` used to be hardcoded to a value, even though the documentation suggested that it was settable. This control is now settable and the documentation has been improved.
- The sample rate is now obtained by `server.sampleRate` instead of looking it up in server.options.
- An unnecessary Condition was removed.
- A test …
=> SoundFile: fix cue method

.travis/before-script-osx.sh, README.md, README_MACOS.md
We discovered during the beta that our min required version for a full build with QtWebEngine is 10.10 (noted https://doc.qt.io/qt-5/qtwebengine-platform-notes.html#macos). This PR updates documentation and also the min deploy target used in Travis builds.
Also took out a bit of the readme that was related to macOS <= 10.6.
- CI change
Checklist
---------
Remaining Work
--------------
=> docs/travis: note that macOS >= 10.10 is required

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
It was not possible to plot control rate signals in a bus.
For instance, in SC 3.10 beta 2
```supercollider
(
(
~debugBus = Bus.control(s, 1);
SynthDef(\test2, { |out, debug|
var pulse = LFPulse.kr(1);
Out.kr(debug, pulse);
Out.ar(out, SinOsc.ar(440) * Lag.kr(pulse,1));
}).add;
)
Synth(\test2, [out: 0, debug: ~debugBus.index]);
~debugBus.plot(3);
```
plots an audio signal or nothing, but not the signal from the control rate bus.
This PR solves that and you get the right signal plotted.
Bus.plot was assuming the signal was audio rate.
Now we check if the signal is control rate or audio rate and use In.kr or InFeedback.ar accordingly.
Checklist
---------
Remaining Work
--------------
I don't know how to unit …
=> [sclang] Fixes wrong bus plotting with control rate signals

server/supernova/sc/sc_osc_handler.cpp, server/supernova/sc/sc_synth.cpp, server/supernova/sc/sc_synth.hpp, server/supernova/server/synth.hpp, testsuite/server/supernova/test_synth.hpp
As noted in https://github.com/supercollider/supercollider/issues/3210, scsynth and supernova respond differently to the the queryTree request. This changes the behavior of supernova to match the behavior of scsynth - controls's names are being reported in the reply message.
```
(
Server.supernova;
// Server.scsynth;
s.waitForBoot({
SynthDef(\prTest, {arg amp = #[0.1, 0.12], freq = 300, out = 0;
Out.ar(out, SinOsc.ar(freq, 0, amp))
}).add;
s.sync;
x = Synth(\prTest);
OSCFunc({arg msg;
msg.postln;
x.free;
}, '/g_queryTree.reply').oneShot;
s.sendMsg("/g_queryTree", 0, 1);
})
)
//supernova - no patch
// [ /g_queryTree.reply, 1, 0, 1, 1, 1, 1000, -1, prTest, 4, 0, 0.10000000149012, 1, 0.11999999731779, 2, 300, 3, 0 ]
//supernova - with patch
//[ /g_queryTree.reply, 1, 0, 1, 1, 1, 1000, -1, …
```
=> supernova: include argument names in queryTree

SCClassLibrary/JITLib/ProxySpace/NodeMap.sc, SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc, testsuite/classlibrary/TestNodeMap.sc
NodeProxy interprets `set` as a mapping when the argument is another NodeProxy or BusPlug. Other objects are converted using `asControlInput` and passed as `/n_set`. The implementation assumed that other objects would only be numbers or arrays. Now it is possible to use any object that would also work with `Synth`.
Fixes #4087.
Bug Fix and tests
```
// this works now
(
b = Buffer.alloc(s, 128, 1);
p = NodeProxy(s);
p.set(\buffer, b);
p.controlNames
)
```
Checklist
---------
Remaining Work
--------------
=> NodeProxy set can be used with arbitrary objects

HelpSource/Classes/Plotter.schelp, SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc, testsuite/classlibrary/TestPlotter.sc
Under various conditions, the behavior of `Plotter` was either broken or not fully supported when `domain` values and `domainSpec` are set. 
In one such case, updating the `domainSpec` updates grid lines and domain labels correctly, but the internal umapping of domain values (which would default to `0->size-1`) is inconsistent with the updated `domainSpec`. The problem with examples will be provided later in this thread.
In addition to fixing this underlying issues, a couple other minor bugs are fixed, including the behavior of `plotColors` and `findSpecs` when toggling the `superpose` flag.
This fixes issues observed in the course of documenting #3672. …
=> [classlib] Plotter: fix domain and superpose behavior.

testsuite/classlibrary/TestEvent.sc
Generally, UnitTests should reset global state after finishing. 
TestEvent:test_event_addParentType does not : 
It adds an eventType which stays there, and creates a cyclic reference loop. 
This causes TestPattern, which runs after TestEvent in .runAll, hang - see #3938.
Short reproducer: 
```
// TestPattern alone passes fine
TestPattern.run
(
// TestPattern hangs when TestEvent ran first
UnitTest.forkIfNeeded {
UnitTest.reset;
[ TestEvent, TestPattern ].do ({ |testClass|
testClass.run(false,false);
0.1.wait;
});
UnitTest.report;
}
)
```
This PR resets the global state of event types after the test, 
and thus TestPattern does not hang when running after TestEvent.
- [x ] All tests are passing
fix hangs by cyclic references in implementations of  ==, as discussed in #3938.
=> TestEvent - remove added eventType after test

HelpSource/Classes/VarLag.schelp
Per bug #3958, `VarLag.ar` is currently unsafe unless you're sure all frequencies in the input are below the control rate Nyquist frequency `s.sampleRate / s.options.blockSize * 0.5`.
The help file states only that VarLag is "Useful for smoothing out control signals." But, the existence of an audio-rate implementation suggests that this is not a serious warning.
The finding in the bug report is that the fix goes pretty deep into EnvGen internals. I don't believe this will happen quickly. At the very least, then, the help file should advise users not to expect true audio-rate behavior.
Checklist
---------
=> Help: VarLag: Explicitly note the kr input limitation [skip ci]

SCClassLibrary/Common/Core/Kernel.sc
```argumentString``` did not handle varArgs correctly, adding a default of ```[ ]```. varArgs cannot have defaults.
One side effect of this is that archives containing open Functions would be uninterpretable. The correct behaviour is that the open function is archived with args but does nothing. (This is what happens without varArgs. In that case it is readable.)
For example:
```
(
var f, g;
f = {arg ... args; g };
f.writeTextArchive("/tmp/testarch")
)
Object.readTextArchive("/tmp/testarch")
```
ERROR: syntax error, unexpected ‘[’
in interpreted text
line 1 char 12:
{ | args = [  ] | “open Function” }
^
-----------------------------------
ERROR: Command line parse failed
With this change the archived func is correctly rendered:
{ | ... args | …
=> Fix FunctionDef:argumentString

server/scsynth/SC_GraphDef.cpp, server/scsynth/SC_Group.cpp, server/scsynth/SC_Lib.cpp, server/scsynth/SC_SequencedCommand.cpp
Use `snprintf` for mitigation against possible buffer overflows.
This seems especially important when dealing with filenames provided by a client.
Clarified buffer sizes with constants.
I did not create a constant for the change in SC_Group.cpp, though it may benefit from one in the future.
Have yet to run the test suite, though these are fairly minimal changes.
Checklist
---------
Remaining Work
--------------
=> [scsynth] Use snprintf, add constants for buffer sizes

CMakeLists.txt
This causes fp math to behave incorrectly
Instead, enable optimizations for the worst offenders (no signaling nan, no math errno)
Fixes #4116
- Breaking change (possibly, needs evaluation)
Checklist
---------
Remaining Work
--------------
Tests should be run after building with this change to ensure nothing
else in the main language test suite has broken as a result of this
change.
=> cmake: turn off -ffast-math for gcc

QtCollider/QcApplication.cpp, QtCollider/interface.cpp
In QtCollider::notify(), explicitly accept all handled events so they
don't propagate outside the application.  This is a hack; for a
not-fully-understood reason Qt past 5.7 sends these events to the native
window if they aren't accepted here. This caused issue #4058. Accepting
them here seems to solve the problem, but might cause other issues since
it is a heavy-handed way of doing this.
Based on looking at Qt's source code I have a strong guess this happens
because we set AA_MacPluginApplication on the QtCollider application.
See https://code.qt.io/cgit/qt/qtbase.git/tree/src/plugins/platforms/cocoa/qnsview.mm?h=5.11#n1472
AFAICT we shouldn't be setting that flag because it is meant for Qt
_plugins_ only, and QtCollider is an application, not a plugin using the
Qt QPluginLoader system. …
=> qtcollider: swallow events

HelpSource/Classes/Pconst.schelp
The Pconst help file includes an example that shows how to use Pconst as a sequence of durations. However the comment just above the example indicates Pconst is used as a sequence of pitches. The text of the comment has been updated to:
"Pconst used as a sequence of durations"
=> fix Pconst help file

HelpSource/Classes/Knob.schelp
Mouse modes for the Knob control deserve emphasis as the the \vert and \horiz modes are probably more user-friendly than the default \round mode.
Update help file to include an additional example showcasing the different modes.
=> Update Knob help to better showcase mouse modes

HelpSource/editor.js, editors/sc-ide/core/sc_lexer.cpp
hex numbers starting with 0X are actually not allowed, so don't highlight them
Checklist
---------
=> scide: fix hex int highlighting

editors/sc-ide/core/settings/default_themes.cpp
fixes #4102. the classic theme now has hardcoded colors rather than depending on the Qt palette. it also should look the same on all platforms now.
Checklist
---------
=> [scide] Fix colors in "classic" theme

SCClassLibrary/Common/Quarks/Quarks.sc
Fixes #4109 
This will check when trying to install a quarks from local path if it is a directory, otherwise fails. 
Without the patch, it will add bad paths (any files) to the configuration and then always fail when compiling the class library.
Checklist
---------
=> class library: checks if quarks local path is a dir before installing

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md
many issue reports could be made better if we had crash logs/reports.
this PR adds info on crash reports and how to generate them, and prompts
reporters for one in the GitHub issue template.
Checklist
---------
=> docs: add info on crash logs

server/supernova/sc/sc_osc_handler.cpp
(new version of PR #4137, based on 3.10 branch)
noticed that `/b_fill` commands didn't seem to be doing anything in supernova. 
checking the source revealed that the sample index into the buffer data wasn't being incremented, so i added this.
i additionally added a bounds check for the index. surprisingly this doesn't happen in other command handlers like `/b_set`. it is possible to smash memory and crash supernova using these OSC commands.
Checklist
---------
i haven't added any unit tests, but of course would be happy to do so with a little more guidance.
=> fix bfill handler for supernova

CONTRIBUTING.md
while `git clone ...` and `git remote add upstream ...` work both with and without the extension `.git`, the output of `git remote -v` reflects the state of the repo's originally given URI (w/ or w/o `.git`).
In this doc `git remote add upstream ...` was issued w/ `.git` at the end of the URI.
=> CONTRIBUTING.md: correct URIs of `git remote -v` output

HelpSource/Classes/AbstractResponderFunc.schelp, HelpSource/Classes/BusPlug.schelp, HelpSource/Classes/Env.schelp, HelpSource/Classes/Environment.schelp, HelpSource/Classes/Event.schelp, HelpSource/Classes/LID.schelp, HelpSource/Classes/MIDIFunc.schelp, HelpSource/Classes/MIDIdef.schelp, HelpSource/Classes/Monitor.schelp, HelpSource/Classes/Pair.schelp, HelpSource/Classes/Pspawn.schelp, HelpSource/Classes/SCImageKernel.schelp, HelpSource/Classes/Thread.schelp, HelpSource/Classes/UserView.schelp, HelpSource/Classes/View.schelp, HelpSource/Overviews/Operators.schelp, HelpSource/Tutorials/Mark_Polishook_tutorial/17_Delays_reverbs.schelp
2nd try. restarted from scratch. previous PR https://github.com/supercollider/supercollider/pull/4227 lost trying to rebase onto 3.10
used a regexp script and found many helpfiles that had broken links - mainly for instance methods but also a few class methods and section links.
all changes tested manually and confirmed to work.
```supercollider
.findAllRegexp(" link::#[^-*]*::");
```
=> help: fix broken links in multiple helpfiles

common/SC_Filesystem_macos.cpp, testsuite/classlibrary/TestSerialPort.sc
fixes an infinite hang in SC_Filesystem::resolveIfAlias on certain input
files (unknown cause).
also add regression test, update message in TestSerialPort
fixes #4131
- *Note: this affects macOS only*
Checklist
---------
Notes on testing
--------------
This affects all places `standardizePath` is used, and class library
compilation. I don't know for certain whether the old behavior is
maintained under all cases. Here are the cases that do stay the same:
- normal files
- directories
- devices/pipes
- valid alias
- broken alias
I'm not enough of a macOS filesystem expert to know if there are corner
cases this misses. It's really unfortunate that this code now …
=> sclang: fix resolveIfAlias [skip appveyor]

.travis/before-install-osx.sh, .travis/script-osx.sh
latest version of travis seems to be barfing when trying to install
ccache. dunno why, but either way forcing homebrew not to update seems
to fix it. we intended to do this anyway but mistyped the environment
variable names! this shaves quite a bit of time off the build.
also cat the un-xcpretty'd build log when there's a failure, which in this case would
have helped to diagnose the problem more quickly.
=> travis macos: don't update brew, fix build error

server/plugins/TestUGens.cpp
fix #4238. this can't really be unit tested because the bug was only in post window printing, so here's a test case:
{ CheckBadValues.ar(LFPulse.ar(10)); DC.ar(0) }.play; // this shouldn't post anything
{ CheckBadValues.ar(1 / LFPulse.ar(10)); DC.ar(0) }.play; // this should
=> plugins: Fix CheckBadValues for zeros on MSVC

include/common/SC_fftlib.h, include/plugin_interface/Hash.h, include/plugin_interface/SC_InlineBinaryOp.h, include/plugin_interface/SC_InterfaceTable.h, include/plugin_interface/SC_PlugIn.hpp, include/plugin_interface/SC_SndBuf.h, include/plugin_interface/Unroll.h, include/plugin_interface/sc_msg_iter.h, server/scsynth/SC_Str4.h, tools/cmake_gen/CMakeLists_header.template, tools/cmake_gen/SuperColliderCompilerConfig.cmake, tools/cmake_gen/SuperColliderServerPlugin.cmake, tools/cmake_gen/generate_server_plugin_cmake.py
There are a couple problems revealed by using CI in the cookiecutter
repo that can only be fixed in this repo. In no particular order:
- CMake warnings on Linux: https://github.com/supercollider/cookiecutter-supercollider-plugin/issues/8
- Building with all warnings on causes build error due to warnings in SC
repo headers: https://github.com/supercollider/cookiecutter-supercollider-plugin/issues/9
- Windows CI fails due to bad path separators in CMakeLists.txt: https://github.com/supercollider/cookiecutter-supercollider-plugin/issues/7
- Bad extension for built plugins due to broken target property logic:
https://github.com/supercollider/cookiecutter-supercollider-plugin/issues/1
(see also …
=> various fixes to support cookiecutter repo

.travis.yml, .travis/package-osx.sh
from `SC-<long-commit-hash>.zip` to `SuperCollider-<version>-macOS.zip`
=> travis: Use human-readable name for macOS release upload

CONTRIBUTING.md
based on recent PR reviews it's become clear that we need clear and
direct documentation on how to use `git rebase` in a couple of common
scenarios. understanding how to rebase correctly will save maintainers and contributers loads of time.
Checklist
---------
=> Contributing.md: add info on rebasing

HelpSource/Classes/Score.schelp, SCClassLibrary/Platform/Platform.sc, SCClassLibrary/Platform/osx/OSXPlatform.sc
Fixes #1271
- documentation of Score
- changed `Platform.defaultTempDir` because `/tmp` is not writeable on OSX and is used in Score rendering
Checklist
---------
Remaining Work
--------------
=> fix Score examples and Platform.defaultTempDir on OSX

HelpSource/Classes/String.schelp, lang/LangPrimSource/PyrStringPrim.cpp, testsuite/classlibrary/TestString.sc
Fixes #4239.
Previously, an empty search result would cause `prString_FindRegexp()` to exit early, resulting in stack corruption and an incorrect return value. We remove the early exit, so that this function always goes through the proper stack unwinding at the end.
Checklist
---------
=> sclang: Fix 'findRegexp' empty-result case

lang/LangSource/PyrLexer.cpp
fixes #3352; previously would cause bad behavior with escaped double quotes
inside strings and escaped single quotes inside symbols.
what is essentially happening is that there are two separate lexing
routines - one that lexes individual tokens, and one that performs a
fast look-ahead to find a closing bracket. this bug is in the latter.
when lexing a line like:
```supercollider
"\"".cs
```
the lookahead lexer routine starts at the first double quote, then
considers the second double quote (the escaped one) to be the end of the
string. then the third double quote is considered the opening of a new
string. however, the normal lexing routine doesn't have this bug, so it
can still succeed.
- Bug fix (non-breaking …
=> sclang: fix string/symbol lexing

.github/PULL_REQUEST_TEMPLATE.md
i've found that the PR template, while made with great intentions, is pretty awkward to use on a daily basis. there's too much text, and it's just kinda cluttered and overwhelming. i feel that it can be made way shorter, reducing it to just the gist of the process, and still provide most of the necessary slots for a newcomer to fill out. any ambiguities or missing details can be easily worked out through regular conversation.
i'm aware some might object to the amount of detail i'm removing. my answer is that i think it's better to err on the side of brevity when it comes to these templates.
=> Shorten pull request template

editors/sc-ide/core/main.cpp, editors/sc-ide/widgets/main_window.cpp
fixes #3905 -- SCIDE is missing an icon. turns out it was something silly, the `QIcon` path should be `:icons/blah` rather than `:/icons/blah`.
unfortunately we can't use the svg icon because of #2646 (icon appears tiny on some linux DEs), so i just used the PNGs.
Checklist
---------
=> scide: Fix missing icon

HelpSource/Classes/MainMenu.schelp, SCClassLibrary/Common/GUI/Base/Menu.sc
changes to MainMenu for 3.10.2
make behavior opt-in only, leave a warning note in the documentation.
add some documentation.
- Breaking change (fix or feature that would cause existing functionality to change)
Checklist
---------
=> main menu: don't init menu actions in initClass; document

CONTRIBUTING.md
It is useful to signal what is an arbitrary names and what is part of the git language.
I propose to change `topic` to `topic/foo`
=> rename topic to topic-foo to communicate that this is an arbitrary name

HelpSource/Guides/Multichannel-Expansion.schelp
Multichannel expansion in SC follows simple rules. Nevertheless there are peculiarities e.g. in Patterns. This commit amends the multichannel expansion guide with a heads-up and an explanatory example.
=> Amend multichannel expansion guide

SCClassLibrary/Common/Control/Server.sc
This is a small enhancement to `ServerOptions.asOptionsString`. The number of In/Out channels should always be set, even when using the default values.
- Enhancement
=> Always set server's number of In/Out channels

SCClassLibrary/Common/Audio/SystemSynthDefs.sc, SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc, testsuite/classlibrary/TestNodeProxy.sc
class library: fix `setbus_control` Event type 
The Event type `\setbus_control` is intended to be used for crossfading between values on a control bus. There are cases in which a previously
playing synth still writes on the bus after the `fadeTime` (this can happen due to a slightly later release of the other crossfade envelope). Then the target value that the control bus should have after
transition is lost.
Adding one control period to the envelope as a hold value is a way to
avoid this glitch.
This fixes  #4295.
- Bug fix
=> Topic fix setbus glitch

HelpSource/Classes/AbstractFunction.schelp, HelpSource/Classes/Object.schelp, HelpSource/Classes/SequenceableCollection.schelp, SCClassLibrary/Common/Collections/SequenceableCollection.sc, SCClassLibrary/Common/Core/Object.sc, SCClassLibrary/Common/Math/Signal.sc, SCClassLibrary/Common/Math/SimpleNumber.sc, SCClassLibrary/deprecated/3.11/deprecated-3.11.sc, lang/LangPrimSource/PyrPrimitive.cpp, lang/LangSource/Opcodes.h, lang/LangSource/PyrMathOps.cpp, lang/LangSource/PyrParseNode.cpp, server/plugins/UnaryOpUGens.cpp, testsuite/sclang/lpc/TestCompilerBrutal.sc
Fixes #4015 
Checklist
---------
Remaining Work
--------------
I added an entry in the `Object` help file with a note that `asInt` is deprecated. There was no previous documentation of `asInt` so maybe I shouldn't have added this? The method is still available in Object though.
Also, I'm not sure I did optimization for the sclang compiler correctly, so this would need to be reviewed by someone who knows more about this. My tests after building from this branch shows no performance improvements after my change, so most likely I did not manage to get this right. Code …
=> Use asInteger instead of asInt. Fix #4015

SCClassLibrary/Common/GUI/Base/Menu.sc
`prUpdateServersMenu` would have non-inlineable variables, this moves
their definition up to allow inlining.
- Bug fix
=> Fix menu inline warnings

HelpSource/Classes/TDuty.schelp, HelpSource/Classes/TDuty_old.schelp
Some docs were left around that referred to TDuty_old.
Checklist
---------
=> remove refs to TDuty_old

lang/LangPrimSource/PyrSched.cpp, lang/LangPrimSource/SC_Ableton_Link.cpp, lang/LangPrimSource/SC_Ableton_Link.hpp
Addresses review concerns on the ongoing Ableton Link PR #4331 .  Moves init routines of LinkClock into a static member of the LinkClock class.  This requires a bunch of re-ordering and thus makes most sense to have LinkClock defined in a header file.
- New feature
FYI @jamshark70
=> Moved definition of LinkClock into hpp, use static methods for init

HelpSource/Classes/FFT.schelp
Users very frequently overlook the requirement to use multiple single-channel buffers for n-channel FFT. This is documented in the FFT Overview, but a/ users read the FFT class help file and stop there, never making it over to the overview and b/ the multichannel section is quite far down in the overview, easy to miss.
So, I'd like to add a short note block to FFT class help explaining briefly how to handle multichannel signals ("don't do this -- do that instead"), so that it's almost the first thing users see.
=> Help: Classes/FFT should highlight correct multichannel approach

SCClassLibrary/JITLib/GUI/ProxyMixer.sc
Bug fix, Fixes #4335.
A ProxyMixer has a proxyspace that it shows, so all named it displays are within that proxyspace.
The editGui in the mixer did not use the proxyspace, but relied on either using Ndefs, or the 
mixer's proxyspace being the currentEnvironment. 
Thus, when the mixer's proxyspace is not current, proxy names would be displayed as anonymous.
This PR ensures that the editGui shows all names as found within the mixer's proxyspace. 
Tests for correct functioning: 
```
p = ProxySpace.new.push(s.boot);
// make some proxies
~out = { \in.ar(0!2) };
~osc = { SinOsc.ar(440).dup };
// map a proxy to an ar input
~osc <>> ~out;
// make p != currentEnvironment
p.pop;
// make a mixer: should show names of proxies within p
g = p.gui;
// send ~out to editGui: editGui name should show …
```
=> Proxy mixer edit gui should use proxyspace

server/plugins/Convolution.cpp
You can actually find this bit of code in `Convolution2_Ctor` (https://github.com/supercollider/supercollider/blob/master/server/plugins/Convolution.cpp#L338):
```
unit->m_prevtrig = 0.f;
unit->m_prevtrig = ZIN0(2);
```
1. That's funny. Really, really funny.
2. It also initializes the plug-in to an incorrect state. Everywhere else in the core plug-ins, the Ctor does `unit->m_prevtrig = 0.f;`. No exceptions. There is no reason to break the rule here (esp. when it's obviously an editing mistake).
Simple, no-brainer fix: just delete the second line.
- Bug fix
Test code:
```supercollider
(
s.waitForBoot {
var bufs = Buffer.allocConsecutive(2, s, 2048, 1),
synthsCompleted = 0,
cond = Condition({ synthsCompleted == 2 });
s.sync;
bufs.do { |buf, i|
{
RecordBuf.ar(
RLPF.ar(Impulse.ar(0), 400 * …
```
=> Plugins: Convolution2_Ctor: Remove incorrect prevtrig init line

testsuite/classlibrary/TestSanitize.sc
This PR fixes a bug in `TestSanitize` which caused it to fail. The failure happened when calling `256 / s.sampleRate`. Immediately after starting sclang, `s.sampleRate` is nil. To fix the error, I've made use of `setUp` and `tearDown` to manage booting/quitting the server.
I've also replaced the use of 4 spaces with tabs as per SC class library style.
- Bug fix
=> Properly manager Server in TestSanitize

testsuite/classlibrary/TestFloat.sc
This PR improves `TestFloat.test_asString_nan` to allow it to handle the case on some platforms where zero division equals `-nan`.
- Bug fix
=> TestFloat: handle "-nan" in test

SCClassLibrary/Common/Control/SkipJack.sc, SCClassLibrary/JITLib/GUI/EnvirGui.sc
This fixes two related bugs: 
- EnvirGui:new always created a skipjack (accidental overwrite of the makeSkip flag)
- When a SkipJack stopped by its stopTest, it would not remove itself properly. 
```
///// Tests:
z = SkipJack({ "..".postln }, 1, { a == 0 }, \test);
// test stop with .stop method:
z.stop;
SkipJack.all.includes(z).not;  // true is OK
CmdPeriod.objects.includes(z).not; // true is OK
z.start;
// test stopping with stoptest
a = 0; // stoptest becomes true
SkipJack.all.includes(z).not;  // true is OK
CmdPeriod.objects.includes(z).not; // true is OK
```
=> EnvirGui: fix accidental overwrite of flag, SkipJack: fix stop method.

CODE_OF_CONDUCT.md
An extra space character in the CoC prevents a link rendering correctly.
=> Update CODE_OF_CONDUCT.md to fix broken link

HelpSource/Classes/Document.schelp
Automatic execution of the code in the ```Document``` expects ```/*RUN*/``` at the beginning of the file, and not ```"/*RUN*/"```, as the documentation suggested.
Also fixed a typo further down in the description.
=> help: clarify Document.autoRun

SCClassLibrary/Common/Control/Buffer.sc
About a year ago, #3507 deprecated `File.openDialog`. However, one reference to this method remains in the core class library (`Buffer.loadDialog`).
This PR replaces that reference with `Dialog.openPanel`.
I would argue that `Buffer.loadDialog` itself should be deprecated, but that's a bigger discussion about which convenience methods should make the cut. In the meantime, it's a no-brainer to fix a deprecation warning.
Not done here: `Dialog.openPanel` supports a starting directory (!), but `Buffer.loadDialog` doesn't expose that as an argument. That would be an API change. Easy enough, I suppose, to add `, path` to the end of the argument list, but "just add an argument" has also caused other problems in the past -- so I'll raise it as a point for discussion but I won't unilaterally do …
=> classlib: Remove usage of deprecated method File.openDialog

SCClassLibrary/Platform/windows/WindowsPlatform.sc
fixes issue #4412.
Changes Platform.recordingsDir on Windows to return:
`C:\Users\<username>\Documents\SuperCollider\Recordings`
Before this commit - `C:\Users\<username>\Documents\SuperCollider\SuperCollider\Recordings`
- Bug fix
=> Windows: fix for #4412 - extra SuperCollider directory in Platform.recordingsDir

QtCollider/QWidgetProxy.cpp
Fixes #4422.
Previously, interpretMouseWheelEvent only used QWheelEvent::pixelDelta().
pixelDelta is only valid on systems with hi-res trackpads, whereas angleDelta() is always available.
https://doc.qt.io/qt-5/qwheelevent.html#details
- Bug fix
Checks if pixelDelta().isNull(), uses QWheelEvent::angleDelta() instead.
=> fix for #4422: use mousewheel angleDelta if pixelDelta not available

editors/sc-ide/widgets/help_browser.cpp
missing else in if-else in HelpBrowser::evaluateSelection()
Fixes  #3924
- Bug fix
=> fix for issue #3924 (Help Browser executing selected code twice)

HelpSource/Classes/String.schelp, HelpSource/Guides/standalones.schelp, SCClassLibrary/Common/Collections/String.sc, SCClassLibrary/Platform/osx/OSXPlatform.sc, SCClassLibrary/deprecated/3.11/deprecated-3.11.sc, platform/mac/Standalone Resources/SCClassLibrary/modifyStartup.sc
`String.scDir` is an old alias for `Platform.resourceDir`. this PR fixes all erroneous uses of it in the SC code base and causes the method to emit a deprecation warning.
=> class library: Deprecate String.scDir

HelpSource/Overviews/Event_types.schelp
The table of the parameters for the `\midi` event type simply copied/pasted the parameters for `\group` (which are, of course, irrelevant for MIDI).
Replaced the table with the real parameters, and included a link to the more complete documentation in the practical guide to patterns.
=> Help: Correct erroneous copy/paste in Event Types help

testsuite/classlibrary/TestNodeProxy.sc, testsuite/classlibrary/TestNodeProxy_Server.sc
This PR refactors UnitTests for NodeProxy. Tests that require a booted server have been moved to a new UnitTest called `TestNodeProxy_Server.sc`. Tests have been separated into individual test methods containing a single `assertEquals`.
- UnitTest refactoring
=> Refactor NodeProxy UnitTests

SCClassLibrary/Common/Core/Color.sc
Achromatic colors (black, white, grey) return `nan` from `Color -asHSV` method. That makes calculations problematic. Correct me if I'm wrong, but I believe that 0 is an appropriate value for hue and saturation in these cases.
```supercollider
//before fix
Color.black.asHSV
// -> [ nan, nan, 0.0, 1.0 ]
Color.white.asHSV
// -> [ nan, 0.0, 1.0, 1.0 ]
Color.grey.asHSV
// -> [ nan, 0.0, 0.5, 1.0 ]
//after fix
Color.black.asHSV
// -> [ 0.0, 0.0, 0.0, 1.0 ]
Color.white.asHSV
// -> [ 0.0, 0.0, 1.0, 1.0 ]
Color.grey.asHSV
// -> [ 0.0, 0.0, 0.5, 1.0 ]
//also:
Color.hsv(*Color.black.asHSV) == Color.black; //false before fix, true after fix
```
- Bug fix
- Breaking change (?)
=> [lang] Color -asHSV: Achromatic colors return nan

testsuite/classlibrary/TestTempoClock.sc
`TestTempoClock:test_nextTimeOnGrid_negativePhaseWraps` is badly written:
- It uses a condition, hang and unhang where nothing is happening except a `wait`. Should remove the extra complexity.
- It fails when running the entire `TestTempoClock` because, in that case, the beats when entering the test are non-zero. It should set the beats explicitly.
- Bug fix
=> testsuite: Fix TestTempoClock:test_nextTimeOnGrid_negativePhaseWraps

HelpSource/Classes/Signal.schelp, SCClassLibrary/Common/Math/Signal.sc, testsuite/classlibrary/TestSignal.sc
Corrected Signal.hammingWindow implementation. 
Old method moved to Signal.hammingWindow_old. 
See https://github.com/supercollider/supercollider/issues/4323
=> Corrected Signal.hammingWindow implementation. 

server/scsynth/SC_SequencedCommand.cpp
Without this, World_Free is called on the same memory twice, as SequencedCmd also frees this pointer. This then causes the FIFO queue on the thread to get into trouble and render the server unresponsive.
Fixes #4338
- Bug fix
=> synth: Prevent data from being freed twice in AsyncPlugInCmd

HelpSource/Guides/UsingQuarks.schelp
Updates Quarks documentation and removes the suggestion to add @refspec's to the git URL.
=> Quarks Doc: remove suggestion to use @refspec in git URL

server/supernova/server/server_args.cpp
clang-format ruined the layout of this code that used boost::program_options,\nrevert it and and comment pragmas
- Formatting change only
Checklist
---------
=> revert clang-formatting for hand-formatted code

HelpSource/Classes/Event.schelp, HelpSource/Overviews/Event_types.schelp, HelpSource/Tutorials/A-Practical-Guide/PG_08_Event_Types_and_Parameters.schelp, SCClassLibrary/Common/Collections/Event.sc, testsuite/classlibrary/TestEvent.sc
Within the last month or so, I've seen 4 or 5 separate questions (on the mailing list, the forum, and today on Facebook) asking how to make one event take multiple actions.
I propose to add a `composite` event type to handle this.
Example -- `types: [\note, \midi]` sends a synth message and MIDI.
```
MIDIClient.init;
MIDIIn.connectAll;
// Linux MIDIOut usage, change this for Mac/Windows
// it's only to print the MIDI, not critical
m = MIDIOut(0);
m.connect(2);
MIDIFunc.trace(true);
s.waitForBoot { s.dumpOSC(1) };
(type: \composite, types: [\note, \midi], midiout: m, degree: 0, dur: 3).play;
->
[ "#bundle", 16187144061062032979, 
[ 9, "default", 1001, 0, 1, "out", 0, "freq", 261.626, "amp", 0.1, "pan", 0 ]
]
MIDI Message Received:
type: noteOn
src: 8454148
chan: 0
num: 60
val: 12
// note …
```
=> Classlib: Add 'composite' event type to default Event prototype

HelpSource/Guides/UsingQuarks.schelp
`UnitTesting` quark won't install in SC version >3.9+. It would be beneficial to provide examples of a working quark in the help files.
I have chosen `MathLib` since it's fairly generic and doesn't seem to be abandoned. However, if you feel that another quark would be a better candidate for an example in the help file, I'd be happy to update this PR.
=> scdoc: remove reference to UnitTesting in the Quarks guide

HelpSource/editor.js, HelpSource/scdoc.js, editors/sc-ide/core/main.cpp, editors/sc-ide/core/util/HelpBrowserWebSocketServices.hpp, editors/sc-ide/widgets/help_browser.cpp, editors/sc-ide/widgets/help_browser.hpp
fix #4177 and #4256 with the following changes:
- the web socket server finds an open port rather than hardcoding port 12344.
- if the web socket server setup fails, SCIDE still starts. i'm not sure it's good to allow multiple IDE's running, but the regression in 3.10 shouldn't have happened. there's no need for a failed web socket connection to be a fatal error!
- scdoc.js is smarter about recognizing whether it's in the IDE, and doesn't print errors.
Testing
-----
- if there is already an instance of SCIDE open, you should be able to open another SCIDE without the latter crashing at start.
- you should be able to run code from the help browser in any open instance of SCIDE.
- if you have SCIDE open and you fire up a command-line sclang and …
=> scide: Find an open port for WebSocket communication with SCDoc rather than hardcoding port 12344
