supercollider/supercollider

server/scsynth/SC_GraphDef.cpp

GraphDef_ReadVer1 now reads via ParamSpec_ReadVer1, fixing GrafDef_Load: name too long errors.
This duplicates code, but in the end, in this case, it is better to have separate sets of methods.

server: GraphDef_ReadVer1 now reads via ParamSpec_ReadVer1

---

SCClassLibrary/JITLib/GUI/NdefParamGui.sc
SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc

This is a minimal way to provide an appropriate interface for the case when NodeProxy / Ndef have numbers or arrays as sources.

Topic nodeproxy gui for numbers

---

HelpSource/Classes/LanguageConfig.schelp
SCClassLibrary/Common/Core/LanguageConfig.sc
SCClassLibrary/Common/Quarks/Quarks.sc
editors/sc-ide/widgets/settings/sclang_page.cpp
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/SC_LanguageConfig.cpp
lang/LangSource/SC_LanguageConfig.hpp

Now there is a method in LanguageConfig that returns the current config file path.

Topic language config current path

---

HelpSource/Classes/Collection.schelp
SCClassLibrary/Common/Collections/Collection.sc
SCClassLibrary/Common/Core/AbstractFunction.sc
SCClassLibrary/Common/Core/Nil.sc

class library: collectCopy method implementation

---

SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc

server GUI: fix initial volume button value

---

HelpSource/Guides/FFT-Overview.schelp

Added the words "Fast Fourier Transform" to the FFT Overview guide to help documentation search results.

[Help] add words "Fast Fourier Transform" to guide

---

server/scsynth/scsynth_main.cpp

Re #1322 but that one uses `-v` instead.

Scsynth: print version with -v

---

server/scsynth/scsynth_main.cpp

scsynth: print version and exit with option -V

---

server/supernova/server/main.cpp
server/supernova/server/server_args.cpp
server/supernova/server/server_args.hpp

supernova: print version with -v and use -V for verbose

---

SCClassLibrary/scide_scqt/ScIDE.sc

This matches View behavior. Fixes #952.

classlib: translate modifier keys on mac

---

include/server/SC_WorldOptions.h
lang/LangPrimSource/OSCData.cpp
server/plugins/DiskIO_UGens.cpp
server/scsynth/SC_Lib_Cintf.cpp
server/scsynth/SC_Lib_Cintf.h
server/scsynth/SC_World.cpp
server/scsynth/scsynth_main.cpp
server/supernova/sc/sc_ugen_factory.cpp
server/supernova/server/server.cpp

this three commits complete commit 87e26cd (number 3) from PR https://github.com/supercollider/supercollider/commit/0f5abf47f71359407cfcb77b1f7a87be237d9408
other solution would be:
https://github.com/supercollider/supercollider/pull/1472
so one should be choosen

Pluginsunload2

---

SCClassLibrary/scide_scqt/ScIDE.sc

for document key and mouse actions.

sclang: Fix incorrect modifiers

---

editors/sc-ide/widgets/help_browser.cpp

ide: Switch focus to help docklet on help request

---

QtCollider/primitives/prim_misc.cpp

sclang: fix default fonts

---

SCClassLibrary/Common/Quarks/Quark.sc

quarks: protect during eval of isCompatible fix #1463

---

SCClassLibrary/Common/Control/MIDIOut.sc
SCClassLibrary/Platform/linux/extMIDIOut.sc
lang/LangPrimSource/SC_AlsaMIDI.cpp

Fix MIDIIn.connectAll on Linux to only connect to external sources and not internal ones

---

SCClassLibrary/Common/Quarks/Quark.sc
SCClassLibrary/Common/Quarks/Quarks.sc

Fix: #1475 absolute path detection and conversion for windows

---

HelpSource/Classes/SimpleNumber.schelp
SCClassLibrary/Common/Math/SimpleNumber.sc

class library: fuzzy equal with relative precision

---

SCClassLibrary/Common/Quarks/Quarks.sc

fix: https://github.com/supercollider/supercollider/issues/1476
this is much more efficient
but does not fix the underlying issue in LanguageConfig

Quarks: avoid a stack overflow from LanguageConfig.includePaths

---

editors/sc-ide/core/sc_lexer.cpp

scide: fix float regexp

---

HelpSource/Classes/SequenceableCollection.schelp

Signed-off-by: Stefan Nussbaumer <st9fan@gmail.com>

SequenceableCollection help: fix some erroneous links

---

SCClassLibrary/Common/Collections/String.sc
SCClassLibrary/Common/Files/File.sc
SCClassLibrary/Common/Quarks/Git.sc
SCClassLibrary/Common/Quarks/Quarks.sc
SCClassLibrary/Common/Quarks/QuarksGui.sc

adds Pipe-exec
Detect and warn if git is not installed
do not fetch directory each time
Update status bar more often

Misc Quarks fixes

---

SCClassLibrary/scide_scqt/ScIDE.sc
editors/sc-ide/primitives/sc_ipc_client.cpp

class library:  defer calls to ide

---

README_OS_X.md

the []() around the link to travis didn't render correctly so made it a plain url

fixed two broken links

---

editors/sc-ide/widgets/multi_editor.cpp

fix lost keyevents

---

server/supernova/dsp_thread_queue/dsp_thread_queue.hpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp
server/supernova/sc/sc_plugin_interface.cpp
server/supernova/sc/sc_synth.cpp
server/supernova/sc/sc_synth.hpp
server/supernova/sc/sc_synth_definition.hpp
server/supernova/sc/sc_synthdef.cpp
server/supernova/sc/sc_ugen_factory.cpp
server/supernova/server/buffer_manager.hpp
server/supernova/server/dependency_graph_generator.hpp
server/supernova/server/group.hpp
server/supernova/server/memory_pool.hpp
server/supernova/server/node_graph.cpp
server/supernova/server/server.cpp
server/supernova/server/server.hpp
server/supernova/server/server_scheduler.hpp
server/supernova/server/sync_commands.hpp
server/supernova/server/synth.hpp
server/supernova/server/synth_factory.hpp
server/supernova/utilities/freelist.hpp
server/supernova/utilities/malloc_aligned.hpp
server/supernova/utilities/simple_pool.hpp
server/supernova/utilities/sized_array.hpp

automated conversion via clang-modernize, no functional change

modernize supernova

---

common/SC_StandAloneInfo_Darwin.cpp
editors/sc-ide/core/sc_server.cpp
editors/sc-ide/core/settings/theme.cpp
editors/sc-ide/widgets/code_editor/autocompleter.cpp
lang/LangPrimSource/PyrSignalPrim.cpp
server/plugins/IOUGens.cpp
server/plugins/UnaryOpUGens.cpp
server/scsynth/Rendezvous.cpp
server/supernova/sc/sc_osc_handler.cpp
testsuite/supernova/simple_pool_test.cpp
testsuite/supernova/static_pool_test.cpp

unused variables, undefined behaviour and missing obj-c reference counts

fix issues found by clang's static analyzer

---

lang/LangPrimSource/PyrPrimitive.cpp
lang/LangPrimSource/SC_AlsaMIDI.cpp
server/supernova/sc/sc_osc_handler.cpp

fixes for master

---

include/common/SC_Types.h

this makes the codebase much more robust ...

refactoring

---

lang/LangSource/PyrSlot.h

preprocessor symbols according to:
* http://sourceforge.net/p/predef/wiki/Architectures/
* http://sourceforge.net/p/predef/wiki/DataModels/
* http://sourceforge.net/p/predef/wiki/OperatingSystems/
Signed-off-by: Tim Blechmann <tim@klingt.org>

sclang: slot - improve architecture detection

---

HelpSource/Classes/Filter.schelp
HelpSource/Classes/FreqScopeView.schelp
HelpSource/Classes/ListView.schelp
HelpSource/Classes/Stethoscope.schelp
examples/GUI examples/ScopeExample.scd

... and simplify server handling

example & help files: fix reference to default server 

---

HelpSource/Classes/Pspawner.schelp

Please forgive me if this is an overstep but I have a suggestion for simplifying example 3 in the Pspawner help file.
Based on my personal experience the original example is a bit to complex for illustrating the point the example tries to make.
I have taken the liberty of modifying it in order to make the point a bit (in my opinion) more succinct, and  added some comments.
I hope I have managed to keep most of the nuances from the original example.
This simplification is by no means an improvement in any musical sense.

Simplify pspawner example

---

HelpSource/Classes/MIDIClient.schelp
HelpSource/Classes/MIDIIn.schelp
HelpSource/Classes/MIDIOut.schelp
SCClassLibrary/Common/Control/MIDIOut.sc
SCClassLibrary/Platform/linux/extMIDIOut.sc
lang/LangPrimSource/SC_AlsaMIDI.cpp

Midi connect all

---

SCDoc/SCDoc.h
SCDoc/SCDoc.tab.cpp
SCDoc/SCDoc.tab.hpp
SCDoc/SCDoc.y
SCDoc/lex.scdoc.cpp
lang/LangSource/Bison/lang11d
lang/LangSource/Bison/lang11d_tab.cpp
lang/LangSource/Bison/lang11d_tab.h
lang/LangSource/PyrLexer.cpp
lang/LangSource/PyrLexer.h
lang/LangSource/PyrParseNode.cpp
lang/LangSource/PyrParseNode.h
lang/LangSource/SimpleStack.cpp
lang/LangSource/SimpleStack.h

this is the good part of the windows patch. extracting took about 15 minutes
--->8---
based on a patch by Lucas Cornelisse
Signed-off-by: Tim Blechmann <tim@klingt.org>

scdoc/sclang lexers: use intptr_t tof compatibility with LLP64 archtectures

---

HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/String.sc
lang/LangPrimSource/PyrStringPrim.cpp

Fix string find

---

include/plugin_interface/SC_SndBuf.h

c++11 provides everything to write good reader-write spinlocks these days

plugin interface: avoid dependency on nova-tt

---

editors/sc-ide/core/doc_manager.cpp

Re #1190 
@timblechmann @muellmusik @telephon

scide: don't sync documents if language was not compiled

---

include/plugin_interface/SC_PlugIn.hpp
server/plugins/LFUGens.cpp
server/plugins/MulAddUGens.cpp

typesafe alternative to DEFINE_XTORS and DefineSimpleUnit/DefineDtorUnit

c++ interface: introduce templated registerUnit

---

HelpSource/Guides/Multichannel-Expansion.schelp

help guides: fix typo

---

server/plugins/MulAddUGens.cpp

plugins: fix plugin registration for sum3/sum4

---

HelpSource/Classes/Font.schelp

sorry, again, wrong branch before

fixes #1811, also, allowing for more space for the last two examples

---

lang/LangSource/PyrObject.cpp

Fixes #1797 
Note: this NEEDS TESTING because the build fail doesn't happen on my system. Someone who has problem #1797 needs to confirm that this fixes it.

build: fix an integer type mismatch that caused build fail for some

---

HelpSource/Classes/Balance2.schelp
HelpSource/Classes/MultiSliderView.schelp
HelpSource/Reference/plot.schelp

Help source syntax fix

---

CMakeLists.txt
README_LINUX.md

Fixes #1820.
This is ONLY FOR MASTER (not for 3.7).

build: bump GCC version requirement up from 4.7 to 4.8

---

editors/sc-ide/primitives/sc_ipc_client.cpp

ide: fix issue with large documents

---

HelpSource/Classes/Vibrato.schelp
SCClassLibrary/Common/Audio/Osc.sc
server/plugins/LFUGens.cpp

This allow Vibrato to be reseted with a trig argument.
I need this to allow vibrato starting again without freeing the synth.

plugins: allow Vibrato to be triggered

---

editors/sc-ide/core/sc_process.cpp
editors/sc-ide/core/sc_process.hpp
editors/sc-ide/widgets/main_window.cpp

This adds a "Show Quarks" menu entry in the "language menu", after the first divider.

ide: menu option "Show Quarks"

---

lang/LangSource/SC_TerminalClient.cpp

sclang: add explanation of standalone mode.

---

SCClassLibrary/Common/Quarks/Git.sc

thanks detective @miguel-negrao

fix #1864 Quarks Git not detecting latest she correctly

---

SCClassLibrary/Common/Math/SimpleNumber.sc

class library: poll treats numbers as signals

---

editors/sc-ide/widgets/multi_editor.cpp

Signed-off-by: Tim Blechmann <tim@klingt.org>

scide: add qt-creator style shortcut sequence to visualise whitespaces

---

server/plugins/UIUGens.cpp
server/plugins/UIUGens.mm

uiugens: correctly terminate input threads

---

SCClassLibrary/Common/Files/PathName.sc

Some deprecation and some refactoring.

clean up PathName code

---

SCClassLibrary/Common/GUI/Base/QView.sc
SCClassLibrary/Common/GUI/tools/Stethoscope.sc

Fix Scope Window Error

---

README_OS_X.md

See issue #1931
And a few tiny adjustments...

Update OSX Readme to warn about Qt5.6

---

.travis.yml

Test if the build uses libsndfile from homebrew

Add libsndfile to travis build

---

HelpSource/Classes/OSCdef.schelp

See discussion in https://github.com/supercollider/supercollider/issues/1890

Clarified nil argument behavior in OSCdef help

---

SCClassLibrary/Common/Quarks/Git.sc
SCClassLibrary/Common/Quarks/Quarks.sc

- detect git
- modify git command to list refspecs
- exclude URLs from path detection
(includes code form crucialfelix' pr #1954 )

Quarks Windows fixes

---

SCClassLibrary/Common/GUI/Base/QView.sc

Removed unused variable. Changed argument name to "font".

Remove unused variable

---

server/scsynth/HashTable.h
server/scsynth/SC_AU.h
server/scsynth/SC_Graph.cpp
server/scsynth/SC_GraphDef.cpp
server/scsynth/SC_Group.cpp
server/scsynth/SC_Jack.cpp
server/scsynth/SC_Lib_Cintf.cpp
server/scsynth/SC_MiscCmds.cpp
server/scsynth/SC_Node.cpp
server/scsynth/SC_PortAudio.cpp
server/scsynth/SC_Rate.cpp
server/scsynth/SC_SequencedCommand.cpp
server/scsynth/SC_World.cpp
server/scsynth/scsynth_main.cpp

Whitespace fixes,**only** for functions which have a mix of spaces and tabs -- i.e. only where mixed tabs and spaces cause problems when reading the code.

Fix lines and functions with mixed tabs and spaces

---

SCClassLibrary/Common/Audio/Osc.sc

thanks go to Daniel Mayer
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/choosing-random-value-in-synth-tp7624784p7624799.html

Osc.sc: fix audio rate TChoose

---

server/supernova/audio_backend/portaudio_backend.hpp

supernova: portaudio_backend changed #elif for #else

---

HelpSource/Guides/ClientVsServer.schelp
HelpSource/Guides/GUI-Introduction.schelp
HelpSource/Guides/GUI-Layout-Management.schelp
HelpSource/Guides/More-On-Getting-Help.schelp
HelpSource/Guides/News-3_6.schelp
HelpSource/Guides/News-3_7.schelp
HelpSource/Guides/News-Qt-GUI.schelp
HelpSource/Guides/NodeMessaging.schelp
HelpSource/Guides/Non-Realtime-Synthesis.schelp
HelpSource/Guides/SCIde.schelp
HelpSource/Guides/SuperColliderAU.schelp
HelpSource/Guides/Tour_of_UGens.schelp
HelpSource/Guides/UserView-Subclassing.schelp
HelpSource/Guides/UsingQuarks.schelp
HelpSource/Guides/Working_with_HID.schelp
HelpSource/Guides/WritingClasses.schelp
HelpSource/Guides/WritingHelp.schelp
HelpSource/Guides/WritingPrimitives.schelp
HelpSource/Guides/WritingUGens.schelp
HelpSource/Guides/standalones.schelp

Just some minor spelling fixes in the Guides subdirectory

help: fixed some typos and spelling

---

HelpSource/Classes/NodeProxy.schelp
SCClassLibrary/JITLib/ProxySpace/ProxySynthDef.sc

Cherry pick telefon's nodeproxy documentation enhancements

---

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc

Make sure NodeProxy generates unique name.

---

HelpSource/Classes/MouseY.schelp
HelpSource/Classes/T2K.schelp
HelpSource/Classes/TChoose.schelp
HelpSource/Classes/TWChoose.schelp
HelpSource/Classes/TabletView.schelp
HelpSource/Classes/Tap.schelp
HelpSource/Classes/TextField.schelp
HelpSource/Classes/Thunk.schelp
HelpSource/Classes/Trig1.schelp
HelpSource/Classes/UnaryOpFunction.schelp
HelpSource/Classes/UnpackFFT.schelp
HelpSource/Classes/UserView.schelp
HelpSource/Classes/VDiskIn.schelp
HelpSource/Classes/View.schelp
HelpSource/Classes/Warp1.schelp
HelpSource/Classes/Window.schelp

This updates Classes doc, T*-Z*.

help: and some more help typos and spell fixes

---

README_WINDOWS.md

The changes to master will be different and follow in a few days.

Windows Readme: tiny enhancements

---

editors/scel/sc/extBuffer.sc

Installing the 3.8dev, I had an issue with Emacs editor. The variable serverRunning, avgCPU and others in the "extBuffer.sc" file was undefined.
Adding "this" to them solved the problem

bug with scide_scel

---

HelpSource/Classes/Convolution2.schelp
common/SC_fftlib.cpp
include/common/SC_fftlib.h
server/plugins/Convolution.cpp

this allow growing fftsize correcting bug that avoids it

SC_fftlib: allow ensurewindow to be called

---

server/plugins/PartitionedConvolution.cpp

correction of issue #2014 
please test error and correction

PartConv avoid using first ir section twice

---

HelpSource/Classes/LFSaw.schelp

LFSaw.schelp: Note and example for special initial-phase behaviour

---

HelpSource/Classes/HistoryGui.schelp
HelpSource/Classes/LFSaw.schelp
HelpSource/Classes/Paddpre.schelp
HelpSource/Classes/SCControlView.schelp
HelpSource/Classes/SinOsc.schelp
HelpSource/Classes/SoundFile.schelp
HelpSource/Classes/Tdef.schelp

4 little fixes that SCDoc.renderAll complains about.

Helpfile fixing

---

HelpSource/Classes/Pmul.schelp

I used the same description style as 'Pset'

added Pmul arguments name & pattern

---

HelpSource/Classes/Pulse.schelp

Pulse.schelp: added missing .kr method, beautified examples

---

HelpSource/Classes/AudioIn.schelp

AudioIn.schelp: tamed feedback in example, removed "patching" example

---

HelpSource/Classes/DynKlank.schelp
HelpSource/Classes/Git.schelp
HelpSource/Classes/HistoryGui.schelp
HelpSource/Classes/Klank.schelp
HelpSource/Classes/LFSaw.schelp
HelpSource/Classes/Message.schelp
HelpSource/Classes/Paddpre.schelp
HelpSource/Classes/RLPF.schelp
HelpSource/Classes/SCControlView.schelp
HelpSource/Classes/SinOsc.schelp
HelpSource/Classes/Tdef.schelp
HelpSource/Reference/SCDocSyntax.schelp

ok, I'm getting confused here, so I'll now merge the helpfile-fixing branch into master and then get rid of the branch.

Helpfile-fixing branch, final merge

---

lang/LangPrimSource/PyrSched.cpp
lang/LangSource/SC_LanguageClient.cpp

lang: correctly join resync thread

---

SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Control/ServerStatus.sc

Topic fix server notify

---

common/SC_fftlib.cpp

fftlib: remove duplicate defines

---

platform/windows/supercollider.nsi

@crucialfelix, as we agreed, this is the same as #2028, but for master.

nsis windows for master branch

---

lang/LangPrimSource/SC_PortMIDI.cpp

@crucialfelix, as agreed, Windows MIDI work over master.

Midi windows master

---

editors/sc-ide/core/doc_manager.cpp

scide: update document path also if nil

---

SCClassLibrary/SCDoc/SCDocRenderer.sc

fix link to class file source in scdoc header

---

lang/LangSource/PyrInterpreter3.cpp

This fixes https://github.com/supercollider/supercollider/issues/669
1 Object: 2
If you use a registered classname as a selector it would think it was a method, but resolve the object as the symbol and not check. Then if it actually looked it up you got segfaulted.
So this checks and puts you in the same error path that you get with
1 FooBazNotObject: 2
or
1 fooBazNotAMethod: 2

Classname as Selector crashes

---

CHANGELOG.md
README_LINUX.md
README_WINDOWS.md
SCClassLibrary/Common/Control/HIDFunc.sc
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
external_libraries/CMakeLists.txt

Merge 3.7.2 to master

---

HelpSource/Classes/DelTapRd.schelp
HelpSource/Classes/DelTapWr.schelp
HelpSource/Classes/MultiTap.schelp

document DelTapWr/DelTapRd/MultiTap delay time caveats

---

server/plugins/DemandUGens.cpp

I apologize for the bad merge before. This merge addresses Bug 1355 and also compiles.
Sorry again for pull requesting code which didn't build. Sloppy.

Bug 1355 demand env overshoot

---

SCClassLibrary/Common/Control/ServerStatus.sc

class library: update link when server failed to start

---

HelpSource/Classes/RangeSlider.schelp

help: RangeSlider: correct dragging instructions

---

SCClassLibrary/Common/Quarks/Quarks.sc

quarks: sort list by name

---

HelpSource/Classes/Document.schelp

help: update Document.schelp to match current API

---

SCClassLibrary/Common/Control/ServerStatus.sc

Fix #2202 
Credits go to @jamshark70 =)

ServerStatus - watcher notifies the server

---

HelpSource/Classes/Server.schelp
HelpSource/Tutorials/Getting-Started/04-Functions-and-Other-Functionality.schelp

Help: small fixes

---

README.md

Add supernova to the list of components

---

cmake_modules/DeployQt5.cmake

build: fix qt configuration for case-sensitive OS X

---

README_LINUX.md

i feel rather silly filing separate PRs for changes to a single file, but they're orthogonal problems and smaller changes get merged faster

Document Qt >= 5.6 not working in Linux

---

HelpSource/Classes/ScIDE.schelp

Very minimal right now, but it's better than nothing. partial fix for #670
I tried to document some methods but I couldn't figure most of them out.

help: create help file for ScIDE

---

HelpSource/Classes/Dialog.schelp

Explain that all paths are absolute, and savePanel will ask to confirm if you select a file that already exists.

help: Dialog: expand explanation of openPanel and savePanel

---

HelpSource/Classes/TreeView.schelp
SCClassLibrary/Common/GUI/Base/QTreeView.sc

http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/TreeView-Item-interface-td7626983.html

class library: TreeView: add alias methods addChild, insertChild, childAt

---

HelpSource/images/sc_logo.svg

handwritten svg. shows up fine in every svg viewer i've tried, but for some reason inkscape doesn't like to open it...

help: add SVG logo to images dir

---

editors/sc-ide/core/sc_process.cpp
lang/LangSource/SC_TerminalClient.cpp

@crucialfelix, this is PR #2012 over master, as agreed.
Note this was a bit more difficult to cherry-pick since @timblechmann made some enhancements to resync in a better way when exiting. This made some of my changes not necessary.
It is probably worth testing this one a bit, just in case.

Windows exit nicely master

---

lang/LangSource/SC_TerminalClient.cpp
server/scsynth/scsynth_main.cpp
server/supernova/server/main.cpp

The work for https://github.com/supercollider/supercollider/issues/2242

Add commit to version info

---

SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc

class library: server gui updates better

---

HelpSource/scdoc.js
SCClassLibrary/SCDoc/SCDocRenderer.sc

Conflict fixed from https://github.com/supercollider/supercollider/pull/2135 and reposted here

Handle spaces in SCDoc internal links

---

HelpSource/Classes/SoundFileView.schelp

help: SoundFileView: fix argument names

---

HelpSource/Classes/Quarks.schelp
HelpSource/Classes/String.schelp
HelpSource/Guides/UsingQuarks.schelp

Yeah, I know these are unrelated changes, but they should be uncontroversial, and we're all overworked, it's such a PITA to create two PRs.
After 3.8, obviously.

Help updates: String regexp, Quarks.addFolder

---

SCClassLibrary/JITLib/GUI/extSoftSet.sc

small typo preventing the class lib from compiling

remove redundant curly bracket

---

HelpSource/Help.schelp

trying to pay attention to small details. please tell me if these amendments are not relevant

help: main help page: change wording

---

HelpSource/Classes/SinOsc.schelp

hey guys. acording to the suggestion of dan (am i right?), i would like to propose the change to the typpo of the sinosc supercollider documentation. hope you find my insight meaningful and relevate. looking forward to hear from you and get some feedback. best wishes. tiago

fixing typpo

---

SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc

this is in master already, but should also be in 3.8.

Add missing proxy init 3.8

---

HelpSource/Help.schelp

Updated the lead to match the description used in GitHub. Fixed minor formatting errors in Licensing section.

help: revise main page

---

SCClassLibrary/Common/Collections/String.sc

Add default value to second argument in string replace

---

HelpSource/Classes/Ndef.schelp

comments welcome.
Signed-off-by: Stefan Nussbaumer <st9fan@gmail.com>

Add multi-channel Pdef example to Ndef helpfile

---

external_libraries/boost/boost/interprocess/detail/win32_api.hpp

See issue #2409.
Applied patch as suggested by Valentin Shtronda. See
https://svn.boost.org/trac/boost/ticket/12137.

Fix problem with boost interprocess module on Win

---

SCClassLibrary/Common/Control/Server.sc

Fix printing filepath at end of recording

---

SCClassLibrary/JITLib/GUI/ParamView.sc

ndef gui paramview backwards compatibility

---

HelpSource/Classes/Convolution.schelp
HelpSource/Classes/Convolution2.schelp
HelpSource/Classes/LocalIn.schelp
HelpSource/Classes/LocalOut.schelp
HelpSource/Classes/PV_ConformalMap.schelp
HelpSource/Classes/PitchShift.schelp

help: use SoundIn instead of AudioIn

---

HelpSource/Classes/Latch.schelp

It was not clear, if Latch would initially output a signal or not.

help: improved Latch help file

---

server/plugins/LFUGens.cpp

tested and seems to be working

plugins: LFGauss: initialize output

---

server/plugins/BeatTrack2.cpp

probably should have done these as one PR.... oh well

server plugins: BeatTrack2: initialize outputs

---

server/plugins/NoiseUGens.cpp

Let me know if the large number of small PRs is getting annoying.

plugins: CoinGate: initialize outputs

---

server/plugins/FilterUGens.cpp

This fixes #2374. Also removes comments which are now unnecessary.

plugins: DetectSilence allows a change of doneAction

---

HelpSource/Classes/GUI.schelp
SCClassLibrary/Common/Core/Object.sc

Along the lines of https://github.com/supercollider/supercollider/pull/2500

Remove odds and ends that refer to ViewRedirect (removed)

---

SCClassLibrary/Common/Core/Function.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

_Please code-review!_
Function.loadToFloatArray is currently in a GUI module -- this means that non-Qt builds don't have access to it. This fixes that.

Move Function.loadToFloatArray out of GUI class

---

HelpSource/Classes/CombC.schelp
HelpSource/Classes/CombL.schelp
HelpSource/Classes/CombN.schelp

A handy formula that should really be public knowledge.

help: Comb*: add info on feedback coefficients

---

SCClassLibrary/Common/Core/Object.sc

class library: move Gen method to Generator Quark

---

HelpSource/Classes/Recorder.schelp
HelpSource/Classes/Server.schelp
HelpSource/Guides/Server-Guide.schelp
SCClassLibrary/Common/Control/Buffer.sc
SCClassLibrary/Common/Control/NetAddr.sc
SCClassLibrary/Common/Control/Node.sc
SCClassLibrary/Common/Control/Recorder.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Control/ServerStatus.sc
SCClassLibrary/Common/Control/SystemActions.sc
SCClassLibrary/Common/Control/Volume.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/server-scope.sc
SCClassLibrary/scide_scqt/ScIDE.sc
editors/sc-ide/core/sc_server.cpp
editors/sc-ide/core/sc_server.hpp
editors/sc-ide/widgets/audio_status_box.cpp
editors/sc-ide/widgets/main_window.cpp

Here is the last version of the server refactoring.

class library and ide: refactor server

---

HelpSource/Classes/Recorder.schelp
HelpSource/Classes/Server.schelp
HelpSource/Guides/Server-Guide.schelp
SCClassLibrary/Common/Control/Buffer.sc
SCClassLibrary/Common/Control/NetAddr.sc
SCClassLibrary/Common/Control/Node.sc
SCClassLibrary/Common/Control/Recorder.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Control/ServerStatus.sc
SCClassLibrary/Common/Control/SystemActions.sc
SCClassLibrary/Common/Control/Volume.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/server-scope.sc
SCClassLibrary/scide_scqt/ScIDE.sc
editors/sc-ide/core/sc_server.cpp
editors/sc-ide/core/sc_server.hpp
editors/sc-ide/widgets/audio_status_box.cpp
editors/sc-ide/widgets/main_window.cpp

This commit (just the last of this branch) is based on the branch for #2422. It is a first attempt at making a more graceful restart of the sclang interpreter after a crash.
This fixes #2397.

sclang and server recover more gracefully

---

HelpSource/Classes/Recorder.schelp
HelpSource/Classes/Server.schelp
HelpSource/Guides/Server-Guide.schelp
SCClassLibrary/Common/Control/Buffer.sc
SCClassLibrary/Common/Control/NetAddr.sc
SCClassLibrary/Common/Control/Node.sc
SCClassLibrary/Common/Control/Recorder.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Control/ServerStatus.sc
SCClassLibrary/Common/Control/SystemActions.sc
SCClassLibrary/Common/Control/Volume.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/server-scope.sc
SCClassLibrary/scide_scqt/ScIDE.sc
editors/sc-ide/core/sc_server.cpp
editors/sc-ide/core/sc_server.hpp
editors/sc-ide/widgets/audio_status_box.cpp
editors/sc-ide/widgets/main_window.cpp

This is a small change on top of #2422 – as the branch is almost in the merge, I've kept it separate.

server allows multiple recorders

---

server/plugins/DiskIO_UGens.cpp

Just initialize with zeros for now.

plugins: DiskIOUGens: initialize outputs

---

HelpSource/Classes/Speech.schelp
HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/String.sc
SCClassLibrary/deprecated/3.9/osx/Speech.sc

Deprecate Speech

---

HelpSource/Help.schelp

help: main page: add link to index of tutorials

---

SCClassLibrary/Common/Audio/Demand.sc
SCClassLibrary/deprecated/3.9/Donce.sc

plugins: deprecate Donce

---

HelpSource/Classes/HenonC.schelp

Add a closing `::` to HenonC.schelp so it parses.

Fix HenonC.schelp

---

HelpSource/Reference/Server-Command-Reference.schelp

Also link from b_gen to buffer fill commands section.

Help: Buffer.schelp /b_close completion message, /b_gen clarify no completion msg

---

HelpSource/Classes/Button.schelp
HelpSource/Classes/Dswitch.schelp
HelpSource/Classes/EZListView.schelp
HelpSource/Classes/FreqScope.schelp
HelpSource/Classes/Interpreter.schelp
HelpSource/Classes/Monitor.schelp
HelpSource/Classes/NdefGui.schelp
HelpSource/Classes/Paddp.schelp
HelpSource/Classes/Pmulp.schelp
HelpSource/Classes/ProxyMixer.schelp
HelpSource/Classes/RecNodeProxy.schelp
HelpSource/Classes/SCDocHTMLRenderer.schelp
HelpSource/Classes/Server.schelp
HelpSource/Classes/TempoBusClock.schelp
HelpSource/Classes/TextView.schelp
HelpSource/Classes/UserView.schelp
HelpSource/Classes/Volume.schelp
HelpSource/Classes/WiiMote.schelp
HelpSource/Classes/Window.schelp
SCClassLibrary/JITLib/GUI/NdefGui.sc
SCClassLibrary/SCDoc/SCDocRenderer.sc

Fixes lots of little glitches that SCDoc.renderAll complains about.

Topic clean helpfiles

---

HelpSource/Classes/FreqScopeView.schelp
HelpSource/Classes/InterplEnv.schelp
HelpSource/Classes/Onsets.schelp
HelpSource/Classes/Pattern.schelp
HelpSource/Classes/Signal.schelp
HelpSource/Classes/SimpleNumber.schelp
HelpSource/Classes/TdefGui.schelp
HelpSource/Classes/TempoClock.schelp
HelpSource/Classes/Tuning.schelp
HelpSource/Classes/Wavetable.schelp
SCClassLibrary/Common/GUI/Base/EZgui.sc
SCClassLibrary/Common/GUI/Base/QView.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/FreqScope.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

fix more little render complaints in various help files, improve text details where needed.

Topic more help cleanup

---

HelpSource/Reference/Server-Command-Reference.schelp
server/supernova/sc/sc_osc_handler.cpp

I'm pretty new to server dev -- this could definitely use more sets of eyes!
@timblechmann if you want, let me know if this looks okay or needs any work!

Add /version command for supernova

---

HelpSource/Guides/Debugging-tips.schelp

including little-known advanced polling

Document polling

---

README_LINUX.md
README_OS_X.md

I've seen at least two people omit this, so we should probably call more attention to it

readmes: add note about ".."

---

HelpSource/Classes/LeastChange.schelp
HelpSource/Classes/MostChange.schelp

This commit adds more helpful documentation for two UGens, MostChange and LeastChange.

help: better docs for MostChange, LeastChange

---

SCClassLibrary/Common/Audio/Splay.sc
SCClassLibrary/deprecated/3.9/deprecated-3.9.sc

class library: officially deprecate SplayZ

---

server/plugins/DemandUGens.cpp

plugins: fix Dibrown length

---

SCClassLibrary/Common/Audio/InOut.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Control/Volume.sc
SCClassLibrary/Common/Files/PathName.sc
SCClassLibrary/deprecated/3.9/InterplEnv.sc
SCClassLibrary/deprecated/3.9/deprecated-3.9.sc

classlib: move some deprecations to deprecated folder

---

README.md

Added 3.8 release and reformatted dates to YYYY-MM-DD as prescribed by ISO 8601.

readme: add 3.8 release date, reformat dates

---

HelpSource/Classes/NetAddr.schelp
HelpSource/Guides/OSC_communication.schelp

help: docs for sclang OSC type tags

---

HelpSource/Classes/Char.schelp
HelpSource/Classes/DoubleArray.schelp
HelpSource/Classes/Float.schelp
HelpSource/Classes/FloatArray.schelp
HelpSource/Classes/Object.schelp
HelpSource/Classes/String.schelp
HelpSource/Classes/Symbol.schelp
HelpSource/Reference/Literals.schelp
SCClassLibrary/Common/Core/Char.sc

help: Update documentation concering raw types

---

testsuite/classlibrary/TestCoreUGens.sc

Should work after #2657 and #2659 have been merged.

Add test out ugens

---

HelpSource/Classes/PinkNoise.schelp

Additional information on PinkNoise as gathered in #2678.

---

SCClassLibrary/Common/Audio/Demand.sc
SCClassLibrary/JITLib/ProxySpace/InBus.sc
SCClassLibrary/JITLib/ProxySpace/NodeMap.sc
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
SCClassLibrary/deprecated/3.9/JITLib.sc
SCClassLibrary/deprecated/3.9/TDuty_old.sc

class lib: more deprecations

---

SCClassLibrary/deprecated/3.9/WII.sc

class lib: deprecate remaining Wii classes

---

HelpSource/Classes/CombC.schelp
HelpSource/Classes/CombL.schelp
HelpSource/Classes/CombN.schelp
HelpSource/Classes/DelayC.schelp
HelpSource/Classes/DelayL.schelp
HelpSource/Classes/DelayN.schelp

Should be mostly uncontroversial. I also added notes that "delay" usually refers to what we call a comb filter, maybe unnecessary?

help: improve docs for Comb* and Delay*

---

HelpSource/Classes/File.schelp

This commit adds documentation to four newly introduced class methods in File. It also adds documentation for two existing instance methods.

help: document File.readAll*

---

HelpSource/Classes/PV_HainsworthFoote.schelp
HelpSource/Classes/PV_JensenAndersen.schelp
HelpSource/Guides/SuperColliderAU.schelp
examples/demonstrations/HarmonicsVoice.html
examples/demonstrations/SC2-examples_2.scd
examples/demonstrations/TriggerBufferGranulator.scd
examples/pieces/Little_Man_From_Another_Place.scd

Replaced occurrences of AudioIn with SoundIn in Help and Examples. Also corrected the channel indexing for use with SoundIn.

[Help] Replace usage of AudioIn with SoundIn

---

package/git-archive-all.py

I made this script python 2/3 compatible. Fixes #2156.

[packaging] make script python 2/3 compatible

---

editors/sc-ide/widgets/help_browser.cpp

fix for double trigger return key in help find box

---

SCClassLibrary/JITLib/ProxySpace/BusPlug.sc

class library: BusPlug play can take bus object

---

SCClassLibrary/Common/Collections/ArrayedCollection.sc
SCClassLibrary/Common/Collections/String.sc
SCClassLibrary/Common/Core/Boolean.sc
SCClassLibrary/Common/Core/Char.sc
SCClassLibrary/Common/Core/Clock.sc
SCClassLibrary/Common/Core/Kernel.sc
SCClassLibrary/Common/Core/LanguageConfig.sc
SCClassLibrary/Common/Core/Object.sc
SCClassLibrary/Common/Core/Symbol.sc
SCClassLibrary/Common/Core/Thread.sc
SCClassLibrary/Common/GUI/Base/QFont.sc
SCClassLibrary/Common/GUI/Base/QPen.sc
SCClassLibrary/Common/GUI/Base/QtGUI.sc
SCClassLibrary/Common/Math/Date.sc
SCClassLibrary/Common/Math/Float.sc
SCClassLibrary/Common/Math/Integer.sc
SCClassLibrary/DefaultLibrary/Main.sc
SCClassLibrary/Platform/Platform.sc
SCClassLibrary/Platform/windows/WindowsPlatform.sc
SCClassLibrary/scide_scqt/ScIDE.sc

Fixes #2879. We should all go over these changes carefully to see if there are any mistakes.

Added missing ^this.primitiveFailed

---

SCClassLibrary/Common/Core/Kernel.sc
SCClassLibrary/Common/Core/Thread.sc

class library: cosmetics

---

HelpSource/Classes/Complex.schelp
SCClassLibrary/Common/Math/Complex.sc
testsuite/classlibrary/TestComplex.sc

division with 1 is the same, but less efficient.

class library: complex reciprocal

---

editors/sc-ide/widgets/editor_box.cpp

This is an attempt to fix issue #2934. It may also solve issues #2933, #2797, #2823. Could the submitters of those four issues please test this?

Fix for Issue #2934

---

SCClassLibrary/Common/Control/Buffer.sc

This is a test to see what will happen if I push a new commit into my buffer-bus-check branch. See discussion in #2936.

Fix whitespace

---

HelpSource/Classes/SendReply.schelp

example on sending audio feature extraction in osc. i came across with a doubt on how to do this. and eventually was able to practically fix this. however, i think it is important that this scenario is covered within the documentation of this class

example on sending audio feature extraction in osc

---

HelpSource/OldHelpWrapper.html

took some time to re-indent the file

re-indenting oldwrapper.html

---

SCClassLibrary/Common/Control/Bus.sc

This PR improves checking for nil Busses. It also replaces a call to `.getnMsg` with it's corresponding server message.

Improved checking of freed Busses

---

HelpSource/Classes/Symbol.schelp

clarify the differences between symbol and sring

help: improve Symbol docs

---

HelpSource/Classes/SendReply.schelp

Add explanatory comments & fix logic. Addresses deficiencies in #2974.
@redFrik how does this look?

Update example in SendReply.schelp

---

include/plugin_interface/SC_InlineBinaryOp.h
testsuite/classlibrary/TestLcmGcd.sc

This combines a simple fix for `gcd` and unit tests.
The tests were inspired by:
https://en.wikipedia.org/wiki/Least_common_multiple#Lattice-theoretic
and the simpler ones of:
http://www.jsoftware.com/papers/eem/gcd.htm
This fixes the current state and prepares for a potential future extension.

gcd for zero and negative numbers, including unit tests 

---

server/plugins/BeatTrack2.cpp

Toward #2927 
Read the commit history for more details

ML_UGens: remove unused variable

---

HelpSource/scdoc.css
HelpSource/scdoc.js

towards #2943. the logo is clickable, lightens when you put your cursor on it, and scales to match the text size (up to 128x128px, which should be sufficient for normal text sizes).

scdoc: add a cute little logo to the upper left

---

editors/sc-ide/widgets/main_window.cpp

SCIDE: Separate server actions into Server menu

---

HelpSource/Classes/Function.schelp
SCClassLibrary/Common/Core/Function.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

Refactor Function plot and loadToFloatArray

---

editors/sc-ide/widgets/multi_editor.cpp

SC-IDE: Open new tabs to the right of the currently active tab.

---

server/plugins/IOUGens.cpp
server/scsynth/SC_Graph.cpp

the rest of the file uses tabs.

code formatting

---

SCClassLibrary/Common/Collections/Dictionary.sc
testsuite/classlibrary/TestCollectionEquality.sc

dictionary equality

---

CONTRIBUTING.md
README.md

- remove Gitter badge
- add Slack badge
- add Slack info to CONTRIBUTING.md
See what the new badge looks like here: https://github.com/brianlheim/supercollider/blob/update/readme-slack/README.md

Documentation: add info about Slack

---

HelpSource/Classes/Fdef.schelp
HelpSource/Classes/Ndef.schelp
HelpSource/Classes/Pdef.schelp
HelpSource/Classes/Tdef.schelp

A proposed documentation change to make it a bit more newbie friendly.

Add an easier to understand introduction paragraph to the Xdef classes.

---

server/plugins/PanUGens.cpp

fix pan az ar in control rate.

---

HelpSource/Classes/Pclump.schelp

Pclump didn't have help before. Now it does.
My first attempt at creating a help file - let me know if I did anything wrong.

Added a new help file for Pclump

---

HelpSource/Classes/Pcollect.schelp

Added a reference to Collection::collect in the help for Pcollect.

Added a reference to Collection's collect in Pcollect's help

---

HelpSource/Classes/Preject.schelp

The initializer wasn't documented properly. Also expanded the documentation generally to hopefully be clearer.

Updated help for Preject

---

README_MACOS.md

See the commit history for more details.
Please let me know if any of this is inaccurate; i made these changes in response to issues reported by @cianoc in slack.

macOS readme: update decaying info about Qt & Xcode

---

HelpSource/Classes/UGen.schelp

help: Fix typo in UGen:curverange help

---

HelpSource/scdoc.css

fixes an issue discussed in #2943, in particular [this comment](https://github.com/supercollider/supercollider/issues/2943#issuecomment-318895606).

scdoc: Fix rippling links on hover

---

server/plugins/DemandUGens.cpp
testsuite/classlibrary/TestUGen_Duty.sc

Duty fixes

---

package/.gitignore

i get some untracked files whenever i run the package script, so this fixes it

build: add .gitignore to package directory

---

.travis/qpm-prep.sh
SCClassLibrary/Common/UnitTesting/MixedBundleTester.sc
SCClassLibrary/Common/UnitTesting/UnitTest.sc
travis_test_run_proto.json

This was missed in https://github.com/supercollider/supercollider/pull/3168
It wasn't caught by CI because it checks out the UnitTesting quark while building. So actually including it in the class library would have broken CI with a duplicate class error.

Add UnitTest.sc to class library

---

SCClassLibrary/Common/Collections/Event.sc

class library: make sure the event server is set when played

---

lang/LangPrimSource/PyrSched.cpp

Bug-Debian: https://bugs.debian.org/853671

PyrSched.cpp: #include <functional> to fix FTBFS

---

HelpSource/Classes/Pen.schelp

hid some private methods, adjusted layout for capStyle example, SCPopUpMenu -> PopUpMenu, added missing ::

scdoc: Pen.schelp a few minor improvements

---

HelpSource/Classes/PitchShift.schelp
server/plugins/DelayUGens.cpp

fixes #3183 by setting minimum windowsize to 3 sample periods

plugins: Fix PitchShift windowSize freeze

---

package/contributor-list-generator/.gitignore
package/contributor-list-generator/README.md
package/contributor-list-generator/contributors.js
package/contributor-list-generator/fetch-data.sh
package/contributor-list-generator/package.json

imports @crucialfelix's contributor list generator, originally at https://gist.github.com/crucialfelix/c37441a2381efbfe97fbcc8ca286f061. made the scripts a little easier to use and added a little bit of documentation. also, the list is now alphabetical by github username rather than by number of contributions.

Add contributor list generator to package/

---

HelpSource/scdoc.css
HelpSource/scdoc.js
SCClassLibrary/SCDoc/SCDoc.sc
SCClassLibrary/SCDoc/SCDocRenderer.sc

fixes #3176. instead of going through the awkward and cramped dropdown, this PR makes the TOC always pop out to the left. also makes improvements to appearance, and some code cleanliness (although this part of SC is an absolute mess and there's only so much i can do).

scdoc: make TOC popout-only

---

HelpSource/Classes/UnitTest.schelp
SCClassLibrary/Common/UnitTesting/UnitTest.sc

Forward-port of https://github.com/supercollider-quarks/UnitTesting/pull/3
Various small tweaks which aim to make the UnitTest documentation clearer and more accurate.

Some cleanup of UnitTest documentation

---

.travis/qpm-prep.sh

travis: use git clone instead of qpm [skip ci]

---

CHANGELOG.md

Closes #3381
Please review, not sure if this is the correct place for this.

add 'known issues' section to Changelog

---

README.md

don't know how I missed this...

readme: update svg source for appveyor badge

---

.appveyor.yml
README.md

Ported from develop branch. If we're going to be merging more things to 3.9, it makes sense to be building this as well so that we don't miss anything.

[3.9] Add .appveyor.yml and appveyor badge

---

editors/sc-ide/widgets/code_editor/sc_editor.hpp

- Removes an unused member and unused, undefined function
- Documents several indentation-related elements

scide: small cleanup in ScCodeEditor class

---

CHANGELOG.md

[docs] - supecollider/changelog.md - fixing changelog [updating the url for my contributions]

[docs] - supecollider/changelog.md - fixing changelog [updating the url for my contributions]

---

HelpSource/Classes/Unpack1FFT.schelp

[3.9] scdoc: fix helpfile example in Unpack1FFT

---

SCClassLibrary/Common/Quarks/Git.sc

classlib: Git.checkForGit returns boolean

---

HelpSource/Classes/UnitTest.schelp

- remove docs for private methods
- document `*run` class method

more tweaks to UnitTest.schelp

---

editors/sc-ide/core/settings/theme.cpp
editors/sc-ide/core/settings/theme.hpp

Cherry-pick of \#3410, \#3412, \#3465

scide: add dracula and solarized themes

---

SCClassLibrary/Common/Control/asScore/ScoreStreamPlayer.sc

class library: Server:set is deprecated.

---

SCClassLibrary/Common/Control/asScore/ScoreStreamPlayer.sc

This is a rebase of PR #3538 onto the 3.9 branch
Created via script: https://gist.github.com/brianlheim/7809f7a062362f0ea3ff1490ae12694b

Rebasing #3538 onto 3.9

---

CONTRIBUTING.md

Btw, I've confirmed that changing the locale on my computer actually does load and use the correct translation file. I'm not sure anyone ever tested it, there are no files with actual translated text 😢

Contributing: add info about adding translations

---

HelpSource/Classes/File.schelp
SCClassLibrary/Common/Files/File.sc
SCClassLibrary/Common/GUI/PlusGUI/Files/FilePlusGUI.sc
SCClassLibrary/deprecated/3.10/File.sc
SCClassLibrary/deprecated/3.10/GUI/File.sc

Deprecate File.saveDialog, openDialog, openDialogs

---

lang/LangSource/PyrLexer.cpp

This changeset fixes a regression that eliminated tilde-expansion on
paths specified in library configuration files.
This fixes #3547.

PyrLexer: expand "~" in pathnames in passOne_processDir

---

HelpSource/Classes/Float.schelp

I find this information useful …

help: using floats as integers

---

SCClassLibrary/SCDoc/SCDoc.sc
SCClassLibrary/SCDoc/SCDocRenderer.sc

This fixes #3576. I've also increased the `SCDoc.sc` version accordingly.

[Help] remove appended "table of contents"

---

editors/sc-ide/CMakeLists.txt
external_libraries/CMakeLists.txt
lang/CMakeLists.txt

This is a rebase of \#3558 on 3.9

Rebase #3558 on 3.9

---

README.md

Previous one expired for whatever reason
Fixes #3639

Readme - update slack invite link

---

HelpSource/Classes/String.schelp

help: Adjust String.compare doc to actual behavior

---

SCVersion.txt

[enhancement] - supercollider/supercollider/SCVersion.txt - tweaking tiny little details in the script

[enhancement] - supercollider/supercollider/SCVersion.txt - tweaking tiny little details in the script

---

HelpSource/Browse.html

[docs] - supercollider/supercollider - supercollider/helpsource/browse.html - review formatting

[docs] - supercollider/supercollider - supercollider/helpsource/browse.html - review formatting

---

HelpSource/OldHelpWrapper.html

[docs] - supercollider/supercollider - supercollider/helpsource/oldhelperwrapper.html - improving indentation

[docs] - supercollider/supercollider - supercollider/helpsource/oldhelperwrapper.html - improving indentation

---

HelpSource/Search.html

[enhancement] - supercollider/supercollider/helpsource/search.html - improving indentation of the overall html document

[enhancement] - supercollider/supercollider/helpsource/search.html - improving indentation of the overall html document

---

HelpSource/Classes/TGrains.schelp

[docs] - supercollider/supercollider/helpsource/classes/tgrains.schelp - minor tweaks in documentation

[docs] - supercollider/supercollider/helpsource/classes/tgrains.schelp - minor tweaks in documentation

---

README_LINUX.md

[docs] - supercollider/supercollider/README_LINUX.md - fixing tiny little issues with grammar, punctuation and other issues

[docs] - supercollider/supercollider/README_LINUX.md - fixing tiny little issues with grammar, punctuation and other issues

---

SCClassLibrary/Common/Streams/Patterns.sc
SCClassLibrary/Common/Streams/Ppar.sc
testsuite/classlibrary/TestPattern.sc

>This fixes #3002.
[edited]
This does *not* fix  #3002. It merely permits patterns to be skipped if their repeats/length value is zero.

Permit pattern zero repeats

---

CMakeLists.txt
QtCollider/CMakeLists.txt
README_LINUX.md
editors/sc-ide/CMakeLists.txt
lang/CMakeLists.txt
server/plugins/CMakeLists.txt
server/supernova/CMakeLists.txt

As discussed on the ML. (https://www.listarc.bham.ac.uk/lists/sc-dev/msg58154.html)

cmake: set minimum version to 3.5

---

SCClassLibrary/Common/Audio/BufIO.sc

class library: BufWr checks also inputArray for rates

---

README.md

Copy some licensing info from help source licensing doc. Note that SC project as a whole is GPL 3.
Fixes #3729.

readme: add licensing info

---

README_LINUX.md

based on #3762 -- don't merge until that one is merged.
update for qt 5.7+, make writing more professional, and improve clarity of steps for beginners.
not 100% there yet, but it's definitely way better than before.

Revise Linux README

---

HelpSource/Tutorials/Getting-Started/02-First-Steps.schelp

docs: command key has no apple symbol anymore

---

HelpSource/Classes/UGen.schelp
SCClassLibrary/Common/Audio/UGen.sc

Fixes #3817 
This PR add the methods `degrad` and `raddeg` to the UGen class. I can add a UnitTest in the coming days if necessary.

Implement degrad & raddeg for UGen

---

HelpSource/Classes/MIDIOut.schelp
SCClassLibrary/Common/Control/MIDIOut.sc

Fixes #3806.
Also adds comments and fixes some code style in MIDIOut.sc. No functional changes, only cosmetic.

Update MIDIOut documentation for Linux

---

HelpSource/Classes/MIDIOut.schelp

help: OSX -> macOS

---

SCClassLibrary/Common/GUI/Base/Menu.sc

Incorrect arguments passed to invokeMethod.

sclang: Fix insertAction

---

README.md

update slack invite link

---

CONTRIBUTING.md

This PR is a cherry-pick of #3884 into `3.10`.

Cherry #3884 into 3.10

---

HelpSource/lang-sc.js
HelpSource/scdoc.css

This is a cherry-pick of #3883 into `3.10`.

Cherry-pick #3883 into 3.10

---

HelpSource/scdoc.css

respacing lines
resizing font size
I closed #3865 and deleted the branch. It has some problems.
This new PR seems to be ok!

Update scdoc.css (reupload of #3865)

---

CONTRIBUTING.md

I've gone through the text and made some wording and Markdown changes.

[Org Docs] Improve CONTRIBUTING.md

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
DEVELOPING.md

This PR adds an issue template, PR template, and the DEVELOPING.md file
we've had in incubation on the Wiki for awhile. I want to make some more
changes after this to tidy up our front-facing documentation; this is a
start.

Add issue/PR template, DEVELOPING.md

---

DEVELOPING.md

Add info on deprecation to developing.md
Checklist
---------

Add info on deprecations

---

HelpSource/Classes/Pipe.schelp
HelpSource/Classes/SequenceableCollection.schelp
SCClassLibrary/Common/Collections/SequenceableCollection.sc
SCClassLibrary/Common/Files/File.sc
common/sc_popen.cpp
common/sc_popen.h
lang/LangPrimSource/PyrFilePrim.cpp
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangPrimSource/PyrUnixPrim.cpp
lang/LangSource/PyrObject.cpp
lang/LangSource/PyrObject.h
lang/LangSource/PyrSlot.h
testsuite/classlibrary/TestProcessCreation.sc

This adds a method unixCmdGetStdOut to SequenceableCollection similar to the method in String. Internally it uses Pipe#*argv . A new primitive was added to Pipe for this. Also added documentation.

Add SequenceableCollection#unixCmdGetStdOut

---

README.md

Imprements to project documentation.
Documentation (non-code change which corrects or adds documentation for existing features)
Checklist
---------

[Project Docs] wording fix for README.md

---

HelpSource/Classes/BusPlug.schelp

Remove stray path. Fixes #3928
Documentation
Checklist
---------

remove stray path

---

HelpSource/BrokenLink.html

[enhancement] - supercollider/supercollider - supercollider/helpsource/brokenlink.html - humble attempt at improving document indentation

[enhancement] - supercollider/supercollider - supercollider/helpsource/brokenlink.html - humble attempt at improving document indentation

---

HelpSource/Classes/BusPlug.schelp

#3929 was filed to develop. it is appropriate for 3.10.
cherrypicks #3929 onto 3.10.
Checklist
---------

Cherrypick #3929

---

editors/sc-ide/widgets/help_browser.cpp

This gets the following shortcuts working again in the help browser:
- Zoom in
- Zoom out
- Reset zoom
- Close
May also be a fix for #3829, not sure.
Checklist
---------
I've tested on macOS and Windows. Someone should test this on at least
one Linux distro.

help browser: fix shortcut handling

---

SCClassLibrary/Common/Control/Buffer.sc

Fixes #3933
`Buffer.free`/`freeMsg` should check for freed buffers and throw errors.
Bug fix (non-breaking change which fixes an issue)
Checklist
---------

fix free/freeMsg nil buffer check

---

HelpSource/Classes/Dictionary.schelp

Fixes #3617
Documentation
Checklist
---------

Improve Dictionary getPairs / asPairs doc, solves #3617

---

SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Core/Kernel.sc
SCClassLibrary/scide_scqt/ScIDE.sc

This PR fixes incorrect usage of the method `isNil` as a way of checking that a file was opened successfully.  Calling `isNil` on a file always returns `false`. The correct method to use is `File.isOpen`.
This PR fixes no issue that I can find.
Bug fix (non-breaking change which fixes an issue)
Checklist
---------

[Bug fix] Check success using File.isOpen

---

HelpSource/Guides/Sync-Async.schelp

Fixes #3896
Documentation
Checklist
---------

fix Sync-async guide, solves #3896

---

HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/String.sc

Fixes #3609
New feature : just add parseJSON as a shortcut to parseYAML
Checklist
---------

add parseJSON and parseJSONFile shortcuts, fixes #3609

---

HelpSource/Classes/SynthDef.schelp

[schelp] fixes SynthDef documentation, makes clearer differences between the ways to write SynthDef arguments
Fixes #3920 and makes more clear that for t_ parameters, there's a difference between setting the synth and setting parameter in Pbind or Pmono
Documentation
Checklist
---------

Fixes Synthdef documentation, solves #3920

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Based on feedback I've decided to make a couple tweaks to these
templates. Mainly, reduce prose and reorder sections of issue template.
Checklist
---------

improve PR & issue templates

---

lang/LangSource/PyrSignal.cpp
testsuite/classlibrary/TestSignal.sc

Fixes #3963 
Bug fix (non-breaking change which fixes an issue)
Checklist
---------

[bug] fix Signal equality

---

editors/sc-ide/widgets/util/docklet.cpp
editors/sc-ide/widgets/util/docklet.hpp

fixes a typo in a class name in the IDE.
refactor in internal C++, no user impact.
Checklist
---------

[scide] Rename "DocketToolButton" to "DockletToolButton"

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
HelpSource/Classes/SerialPort.schelp
HelpSource/Classes/SimpleNumber.schelp
HelpSource/scdoc.css
SCClassLibrary/Common/Control/Buffer.sc
SCClassLibrary/Common/Control/SerialPort.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Core/Function.sc
SCClassLibrary/Common/Core/Kernel.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
SCClassLibrary/scide_scqt/ScIDE.sc
editors/sc-ide/widgets/help_browser.cpp
editors/sc-ide/widgets/util/docklet.cpp
editors/sc-ide/widgets/util/docklet.hpp
lang/CMakeLists.txt
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangPrimSource/PyrSerialPrim.cpp
lang/LangSource/PyrSignal.cpp
testsuite/classlibrary/TestBuffer.sc
testsuite/classlibrary/TestSerialPort.sc
testsuite/classlibrary/TestSignal.sc

in my fork, i merged 3.10 into develop and fixed the conflict. this PR fast-forwards our develop branch so it matches mine. hope that makes sense.
the conflict was completely inconsequential, it was just a measurement being written as `0em` vs `0` in scdoc.css.

Merge 3.10 into develop (conflict fixed)

---

CHANGELOG.md

it's the changelog.
it adds the changelog.
Checklist
---------

[help] Add 3.10.0-beta1 changelog

---

.appveyor.yml

Fixes #3996 . Re-encrypted the Appveyor token now that we've moved to a legit account :)
Checklist
---------
Remaining Work
--------------

appveyor: use correctly encrypted github token

---

README_LINUX.md

minor revisions to Linux README, specifically to reflect the merging of #3738 (`NO_X11`) and the fact that webengine is currently not optional
Checklist
---------

[help] Update Linux README

---

HelpSource/Tutorials/Streams-Patterns-Events7.schelp

Fixes #3964 
A rather small issue. Not the best improvement, but a place to start contributing :-)
Checklist
---------
Remaining Work
--------------
None.

Fixes a small typo on "Understanding Streams, Patterns and Events - Part 7" 

---

server/supernova/server/buffer_manager.cpp

All is expained in issue #4017

comment bad include to sndfile to let windows compile supernova

---

HelpSource/Guides/Tour_of_UGens.schelp

At some point an additional arg was added to GrainSin, but the Tour examples were not updated.
Make examples actually work
Checklist
---------

Fix Tour of UGens GrainSin examples

---

HelpSource/Guides/Tour_of_UGens.schelp

This is a cherry-pick of #4057 into `3.10`.

Cherry-pick #4057 into 3.10

---

HelpSource/Classes/Impulse.schelp

[docs] - supercollider/HelpSource/Classes/Impulse.schelp - fixing grammar

[docs] - supercollider/HelpSource/Classes/Impulse.schelp - fixing grammar

---

HelpSource/Reference/EmacsEditor.schelp

[docs/enhancement] - supercollider/HelpSource/Referece/emacseditor.schelp - improving grammar, et. al

[docs/enhancement] - supercollider/HelpSource/Referece/emacseditor.schelp - improving grammar, et. al

---

server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_synth.cpp
server/supernova/sc/sc_synth.hpp
server/supernova/server/synth.hpp
testsuite/server/supernova/test_synth.hpp

This PR cherry-picks #3221 into `3.10`.

Cherry-pick #3221 into 3.10

---

.travis/before-script-osx.sh
README.md
README_MACOS.md

This PR merges #4068 into `3.10`.

Merge #4068 into 3.10

---

SCClassLibrary/Common/Control/ResponseDefs.sc
testsuite/classlibrary/TestOSCFunc.sc

This PR cherry-picks #4027 into `3.10`.

Merge #4027 into 3.10

---

HelpSource/Classes/SoundFile.schelp
SCClassLibrary/Common/Files/SoundFile.sc
testsuite/classlibrary/TestSoundFile.sc
testsuite/classlibrary/TestSoundFile_Server.sc

This merges #3728 into `3.10`. Please pay special attention. I had to resolve some conflicts and whatnot. Thanks :)

Merge #3728 into 3.10

---

SCClassLibrary/Common/GUI/Base/QImage.sc

Fixes #3947
Bug-fix
Checklist
---------
Remaing work
---------
I should have added a test for the Image constructor but I am not familiar enough with testing yet. I will try soon.

Fixes image constructor with a filename as argument, solves #3947

---

SCClassLibrary/Common/GUI/Base/QImage.sc

thats right folks. im cherry pickin #3949 onto 3.10. whatcha gonna do about it huh

Cherrypick #3949 onto 3.10

---

SCClassLibrary/JITLib/GUI/NdefParamGui.sc
SCClassLibrary/JITLib/ProxySpace/NodeMap.sc
SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc
testsuite/classlibrary/TestNodeMap.sc

This fixes  #4092, see description there. This includes  #4090, which it needs.

Topic ndef param gui simplify drag

---

HelpSource/scdoc.css

scdoc: remove merge conflicts

---

HelpSource/Classes/FileDialog.schelp

Fixes #4086
Documentation (non-code change which corrects or adds documentation for existing list

[docs] Fix typo in FileDialog help file

---

HelpSource/Classes/MIDIOut.schelp

[docs] - supercollider/HelpSource/Classes/MIDIOut.schelp - reviewing grammar

---

SCClassLibrary/Common/Audio/SystemSynthDefs.sc
SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
SCClassLibrary/JITLib/ProxySpace/ProxySynthDef.sc
testsuite/classlibrary/TestNodeProxy.sc

This PR fixes #4060.
This is a redo of #4101 with `SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc` taken from #4065.
@telephon please review and make sure all your changes from previous PRs are included.
Checklist
---------
Remaining Work
--------------

Fix Ndef fadeTime

---

CONTRIBUTING.md

The link to the Code-Style-Guidelines document was wrong.
Checklist
---------

docs: Fix the link to the Code-style-guidelines document [skip ci]

---

.appveyor.yml

Hoping the newer release of VS 2017 builds Qt 5.9...

appveyor: use newer vs2017 image

---

HelpSource/Classes/Knob.schelp

Cherry pick4144

---

HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/String.sc
testsuite/classlibrary/TestString.sc

Cherry pick https://github.com/supercollider/supercollider/pull/3819 into 3.10
Does not include https://github.com/supercollider/supercollider/pull/3819/commits/6d078a3df2a24a2a68d3da410d9509c4ee132367 as it seems to have been already cherry picked into 3.10

Cherry pick #3819

---

HelpSource/Classes/QtGUI.schelp

QtGUI was previously undocumented, but contains some really useful methods.
Checklist
---------

help: add QtGUI.schelp

---

HelpSource/Classes/ProxyMixer.schelp

A typo in a code example in the help file for ProxyMixer does not cause an error but does not result in the expected behavior.
Fix typo to change variable from "n" to "m"
Checklist
---------
Remaining Work
--------------

fix typo in ProxyMixer help

---

HelpSource/Classes/ProxyMixer.schelp

Cherry-pick #4204  into `3.10`

Cherry pick #4204 into 3.10

---

common/SC_Filesystem_unix.cpp

cherry-pick #4203
https://github.com/supercollider/supercollider/issues/4200#issuecomment-445445096

[cherry-pick] add OpenBSD to SC_Filesystem_unix

---

.github/ISSUE_TEMPLATE.md
CONTRIBUTING.md
HelpSource/BrokenLink.html
HelpSource/Browse.html
HelpSource/Classes/QtGUI.schelp
HelpSource/OldHelpWrapper.html
HelpSource/Other/HelpDocsLicensing.html
HelpSource/Other/Licensing.html
HelpSource/Overviews/Classes.html
HelpSource/Overviews/Documents.html
HelpSource/Overviews/Methods.html
HelpSource/Search.html
HelpSource/editor.js
HelpSource/scdoc.css
HelpSource/scdoc.js
README_LINUX.md
README_MACOS.md
SCClassLibrary/Common/Control/Score.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Quarks/Quarks.sc
SCClassLibrary/Common/Streams/Patterns.sc
SCClassLibrary/SCDoc/SCDoc.sc
SCClassLibrary/SCDoc/SCDocRenderer.sc
editors/sc-ide/core/sc_lexer.cpp
editors/sc-ide/core/settings/default_themes.cpp
lang/LangPrimSource/PyrSerialPrim.cpp
server/supernova/sc/sc_osc_handler.cpp
testsuite/classlibrary/TestPprotect.sc
testsuite/classlibrary/TestSerialPort.sc

there was a conflict in `scdoc.css` (consequences of me accidentally committing conflict markers). merged 3.10 into develop in my fork, so merging my develop into main develop is equivalent to merging 3.10 into develop.

Merge 3.10 into develop

---

HelpSource/Guides/Tour-of-Special-Functions.schelp

This PR simply updates some of the parameters of the examples for which some plot ranges weren't displaying, and also trims on some of the captions below the plots in the case where argument lists are long.
There's also a small amount of whitespace and formatting cleanup.

Update Guide: Tour of Special Functions parameters

---

HelpSource/Classes/Buffer.schelp
HelpSource/Classes/Image.schelp
HelpSource/Classes/NodeMap.schelp
HelpSource/Classes/NodeProxy.schelp
HelpSource/Classes/Pipe.schelp
HelpSource/Classes/Platform.schelp
HelpSource/Classes/UnitTest.schelp
HelpSource/Classes/View.schelp
HelpSource/Guides/NodeMessaging.schelp
HelpSource/Guides/UGens-and-Synths.schelp
HelpSource/Guides/WritingTests.schelp
HelpSource/Tutorials/Mark_Polishook_tutorial/05_The_network.schelp
SCClassLibrary/JITLib/ProxySpace/NodeMap.sc

Fixes #3998 
```supercollider
// get the list: 
unixCmd("rm" + quote(SCDoc.helpTargetDir));
SCDoc.renderAll;
```
should return
```supercollider
-> 11204
SCDoc: Rendering all documents
SCDoc: Done!
-> SCDoc
```
Checklist
---------
Remaining Work
--------------
I don't know if we want to rewrite "Server Tutorial" or at least add a warning such as "Some stuff in this doc might be outdated."

Small fixes to help files, solves #3998

---

SCClassLibrary/Common/Audio/FFTUnpacking.sc

This is a fix for using regular Buffer with FFT UGens. I take no credit for this - @jamshark70 provided the solution in the linked issue; I wanted to get the ball rolling though, as his solution has solved the problem I had. I hope I'm not breaking etiquette by doing this...
Fixes #3399.
Checklist
---------
Remaining Work
--------------
I have no thorough understanding on the details of FFT processing in SC, so I can't comment on the validity of the solution, other than that it did fix an issue I had. It would be good to test this more to see if it breaks anything else with FFT.
See the reproducer below. Without this fix, if you swap ```LocalBuf``` for …

[classlib] FFT: fix for using regular Buffer

---

HelpSource/Classes/Buffer.schelp
HelpSource/Classes/Image.schelp
HelpSource/Classes/NodeMap.schelp
HelpSource/Classes/NodeProxy.schelp
HelpSource/Classes/Platform.schelp
HelpSource/Classes/UnitTest.schelp
HelpSource/Classes/View.schelp
HelpSource/Guides/NodeMessaging.schelp
HelpSource/Guides/UGens-and-Synths.schelp
HelpSource/Guides/WritingTests.schelp
HelpSource/Tutorials/Mark_Polishook_tutorial/05_The_network.schelp
SCClassLibrary/JITLib/ProxySpace/NodeMap.sc

Cherry-pick 4265 onto 3.10

---

HelpSource/Classes/Platform.schelp
SCClassLibrary/Common/GUI/Base/Menu.sc
SCClassLibrary/Common/GUI/Base/QFont.sc
SCClassLibrary/Common/GUI/Base/QtGUI.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
SCClassLibrary/Common/GUI/tools/HelpBrowser.sc
SCClassLibrary/Platform/Platform.sc
lang/LangPrimSource/PyrPlatformPrim.cpp
lang/LangPrimSource/PyrPrimitive.cpp

Fixes #1209
Checklist
---------

[SCClassLibrary] Do not load Qt dependent classes on Qt-less builds

---

SCClassLibrary/Common/GUI/Base/Menu.sc

This fixes issues where server menu flashes when updating because we were detroying the entire thing to rebuild it - now we just incrementally update.

sclang: refactor server menu

---

HelpSource/Classes/MainMenu.schelp
HelpSource/Classes/Platform.schelp
HelpSource/Classes/TempoClock.schelp
HelpSource/Guides/Non-Realtime-Synthesis.schelp
QtCollider/widgets/QcWebView.cpp
SCClassLibrary/Common/Core/Clock.sc
SCClassLibrary/Common/GUI/Base/Menu.sc
editors/sc-ide/core/main.cpp
editors/sc-ide/widgets/main_window.cpp
lang/LangSource/PyrLexer.cpp
server/plugins/DiskIO_UGens.cpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_synth_definition.cpp
server/supernova/server/dependency_graph_generator.hpp
server/supernova/server/main.cpp
testsuite/classlibrary/TestTempoClock.sc
testsuite/server/supernova/timetag_test.cpp

3.10 -> develop (conflicts fixed)

---

examples/research_and_tools/SeminaireMusical.scd

A bit of restructuring, renaming variables, and an option to use Harry
Partch’s tone system.
General Improvement
A bit of restructuring, renaming variables, and an option to use Harry
Partch’s tone system.
- New feature

examples: improved aural comprehension

---

testsuite/classlibrary/TestCoreUGens.sc

This PR improves `TestCoreUGens` by making it use a unique Server instance rather than `Server.default`. This test still has failures. This PR is just the first of many.
- UnitTest refactoring

TestCoreUGens: replace Server.default

---

tools/clang-format.py

Suggested in https://github.com/supercollider/supercollider/issues/4428#issuecomment-497998992
this makes it easier for non-PATHed installs and also
allows the same options to be used from the cmake targets
and ./lint.py and ./format.py scripts
Checklist
---------
Tested this locally, works for me.

clang-format.py: allow program names to be set from env vars

---

README_LINUX.md

Cherry-pick of #4397. Changed the url to Debian Multimedia team in README.md.

Cherry-pick #4397 into 3.10 branch

---

HelpSource/Classes/Document.schelp

Cherry-pick #4355 into `3.10`.
- Cherry-pick

Cherry-pick #4355 into 3.10

---

SCClassLibrary/Common/Audio/FFTUnpacking.sc

Cherry-pick #4050 into `3.10`. We might have neglected to so for `3.10.2`. 
- Cherry-pick

Cherry-pick #4050 into 3.10

---

SCClassLibrary/Common/Collections/Event.sc

This patch Fixes #4405 issue with strum parameter for Event as described there.
- Bug fix

Classlib: Event: Fix strum, issue #4405

---

HelpSource/Guides/Randomness.schelp

help: correct randomness on signal example

---

DEVELOPING.md

Cherry-pick #4439 into `3.10`
- Cherry-pick

Cherrypick #4439 into 3.10

---

editors/sced/scedwin/py/ScLang.py
editors/sced/scedwin/py/Settings.py
testsuite/sclang/launch_test.py

Fix python code for python3 only environment.
- Bug fix

Fix python3 print statement

---

HelpSource/scdoc.css

Takes care of https://github.com/supercollider/supercollider/issues/3880

[schelp CSS] Fixes footnotes triggering new lines

---

HelpSource/scdoc.css

Cherry-pick #4365 into `3.10`
- Cherry-pick

Cherry-pick #4365 into 3.10

---

testsuite/classlibrary/TestTempoClock.sc

Cherry-pick #4334 into `3.10` [skip ci]
- Cherry-pick

testsuite: Fix TestTempoClock:test_nextTimeOnGrid_negativePhaseWraps

---

SCClassLibrary/Common/Collections/Event.sc
SCClassLibrary/Common/Control/SkipJack.sc
SCClassLibrary/JITLib/GUI/EnvirGui.sc
SCClassLibrary/JITLib/GUI/ProxyMixer.sc

cherrypick:
- #4376 - EnvirGui/SkipJack fixes
- #4339 - ProxyMixer GUI
- #4406 - Event strum

Cherrypick #4376, #4339, #4406 onto 3.10

---

HelpSource/Guides/Randomness.schelp

Cherry-pick #4389 into `3.10`
- Cherry-pick

Cherrypick #4389 into 3.10

---

server/supernova/utilities/time_tag.hpp

This change is required to build supernova with a system boost version >1.66
Checklist
---------

Fix compilation with boost-1.67

---

HelpSource/Classes/Platform.schelp
SCClassLibrary/Common/GUI/Base/Menu.sc
SCClassLibrary/Common/GUI/Base/QFont.sc
SCClassLibrary/Common/GUI/Base/QtGUI.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
SCClassLibrary/Common/GUI/tools/HelpBrowser.sc
SCClassLibrary/Platform/Platform.sc
lang/LangPrimSource/PyrPlatformPrim.cpp
lang/LangPrimSource/PyrPrimitive.cpp

Cherry-pick of #4219 into `3.10`. Required some surgery. Please review carefully.
- Cherry-pick

Cherrypick 4219

---

server/scsynth/SC_SequencedCommand.cpp

This is a cherry-pick of PR #4456 into `3.10`
- Cherry-pick

Cherrypick #4456 into 3.10

---

server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp

This is as PR #4410 after clang format.

supernova: add mutex to tcp send function

---

HelpSource/Overviews/Operators.schelp

Fix documentation of ** operator, solves #3621

---

HelpSource/Guides/UsingQuarks.schelp

ext_dependancy -> ext_dependency
Fixes #4502.
It's a minor typo fix. I've done it against 3.10 so it can go into the release ASAP. If that's not desirable, I'll redo it against develop.

help: update quarks guide

---

README_LINUX.md

This PR replaces #4414 and adds to it by making obtaining the source code the first step. Thanks @enrike!

Update Linux Readme Build Steps

---

HelpSource/Classes/Platform.schelp
SCClassLibrary/DefaultLibrary/Main.sc
SCClassLibrary/Platform/Platform.sc
lang/LangPrimSource/PyrPlatformPrim.cpp

if built without QtWebEngine, the IDE should not print "for help press
Ctrl-D/Cmd-D" since this shortcut won't do anything. Changing this
message from Main.sc requires programatically knowing whether this
feature is available.
Checklist
---------
Remaining Work
--------------
Maybe we could post a message that leads to doc.sccode.org? Or give
instructions (or a link to instructions) for rendering documentation yourself?

add Platform:*hasQtWebEngine, don't mislead about help browser

---

DEVELOPING.md

This PR is a cherry-pick of #4471 for `3.10`
- cherry-pick

Cherry-pick 4471

---

HelpSource/Guides/UsingQuarks.schelp

This is a cherry-pick of #4515 for `3.10`
- Cherry-pick

Cherry-pick #4515

---

HelpSource/Classes/Pbindf.schelp

This is a cherry-pick of #4563 for `3.10`
- Cherry-pick

Cherry-pick 4563

---

server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp

This is a cherry-pick of #4435 into `3.10`.
- Cherry-pick

Cherry-pick #4435

---

HelpSource/Classes/ScopeView.schelp

This is a cherry-pick of #4466 into `3.10`.
- Cherry-pick

Cherry-pick #4466 into 3.10

---

HelpSource/Tutorials/Getting-Started/13-Buffers.schelp
HelpSource/Tutorials/Getting-Started/15-Sequencing-with-Routines-and-Tasks.schelp
HelpSource/Tutorials/Getting-Started/16-Sequencing-with-Patterns.schelp

docs: adjust getting started tutorial

---

.travis.yml
.travis/before-install-osx.sh
.travis/qpm-prep.sh

See https://github.com/supercollider/supercollider/pull/4622 for more details

travis: update osx to xcode9.4 [develop]

---

HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp
SCClassLibrary/Common/Control/Recorder.sc
SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc
common/server_shm.hpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp
server/supernova/utilities/osc_server.hpp
testsuite/classlibrary/TestNodeProxyRoles.sc
testsuite/classlibrary/TestRecorder.sc

There were merge conflicts in #4629 so I did this one myself locally, resolving in favor of `develop`.

3.10 -> develop

---

README.md

Slack invite link doesn't work
- Bug fix

readme: update slack invite link

---

README.md

Fixes #4603.
Checklist
---------

Readme: add info about RFCs

---

external_libraries/CMakeLists.txt

With the addition of Ableton Link, we now have recursive git modules in
this project, so simply running update isn't going to work.
- Bug fix

CMake: update error message

---

.appveyor.yml

Fixes #4627. This makes it possible to use Appveyor on a separate account.
- Bug fix

Appveyor: only deploy to s3 on main repo

---

tools/clang-format.py

clang-format.py: Do not throw if files have been deleted

---

tools/clang-format.py

This is a cherry-pick of #4638 into 3.10.
- cherry-pick

cherry-pick #4638

---

HelpSource/Tutorials/Getting-Started/13-Buffers.schelp
HelpSource/Tutorials/Getting-Started/15-Sequencing-with-Routines-and-Tasks.schelp
HelpSource/Tutorials/Getting-Started/16-Sequencing-with-Patterns.schelp

This is a chreey-pick of #4610 into 3.10.
- Cherry-pick

Cherrypick #4610

---

testsuite/classlibrary/TestOSCBundle.sc
testsuite/classlibrary/server/TestMixedBundleTester.sc

In preparation for #3132, this PR fixes some issues with a couple unit tests. This PR isn't concerned with how/what these tests do, but rather how they use the server.
- Fixes use of Server.default
- Tests no longer leave the server running when finished 
- Cosmetic fixes
- UnitTest improvemets

Server related fixes for some UnitTests

---

.travis/qpm-prep.sh

Fixes https://github.com/supercollider/qpm/issues/6
Now that we have supercollider-org qpm, we should use it.
- Bug fix

Travis: use the SuperCollider org fork of QPM

---

testsuite/classlibrary/TestUnitTest.sc
testsuite/classlibrary/server/TestUnitTest-test_bootServer.sc

This PR refactors `TestUnitTest`. It is no longer broken up into two files, `Server.default` is not used, and the booted server quits.
- UnitTest fix

Refactor TestUnitTest

---

HelpSource/Classes/Pdef.schelp
HelpSource/Classes/Pdefn.schelp
HelpSource/Classes/Tdef.schelp

This fixes #4667.
Improve documentation

help: explain usage of key in proxies

---

.appveyor.yml
.travis.yml

not used by any command as far as i can tell, and is currently breaking the macOS travis builds
Checklist
---------

CI: don't use git fetch --tags

---

HelpSource/Classes/NodeProxy.schelp
HelpSource/Classes/ProxySpace.schelp
HelpSource/Tutorials/JITLib/jitlib_asCompileString.schelp
SCClassLibrary/JITLib/ProxySpace/extStoreOn.sc
testsuite/classlibrary/TestNodeProxy.sc

This is a cleanup PR that replaces #4469, which was cluttered with accediental commits. 
Fixes the bug described in #4329, where nodeproxy/Ndef posting as code fails in some cases.
Please read full background in #4469 
- Bugs fixed
- Tests added for all cases
- Documentation updated

Fix ndef as code2

---

testsuite/classlibrary/TestUnitTest.sc

this fixes the merge conflict between 3.10 and develop (tested locally
by merging 3.10 into this branch cleanly)
- Bug fix (technically?)

[test suite] remove commented-out test

---

server/plugins/LFUGens.cpp

plugins: take care of EnvGen not started

---

SCClassLibrary/Common/Math/SimpleNumber.sc
testsuite/classlibrary/TestSimpleNumber.sc

sclang: fix rounding in SimpleNumber -asTimeString

---

HelpSource/Classes/NodeProxy.schelp
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
testsuite/classlibrary/TestNodeProxy.sc

Cleaned up copy of #4462. See there for information and discussion.

fix proxy fadetime copy and improvemnts to unit tests

---

CHANGELOG.md
SCClassLibrary/Common/Math/SimpleNumber.sc
SCVersion.txt
testsuite/classlibrary/TestSimpleNumber.sc

This PR merges master into develop via an intermediate branch, resolving conflicts in SCVersion.txt introduced by #4706 .
all I did was take develop's version of that file and remove the 'rc-1' from SC_VERSION_TWEAK.

master -> develop [resolving conflicts]

---

lang/LangSource/SC_LanguageConfig.cpp
lang/LangSource/SC_LanguageConfig.hpp

triggers compiler warning -Wignored-qualifiers -- these have no effect
Checklist
---------

remove ignored consts

---

README.md
README_BEAGLEBONE_BLACK.md
README_RASPBERRY_PI.md

These should be in the main repo, not on the website. Edited them for style and simplified a few commands.
After this PR is complete I'll also make a corresponding PR to the website.
cc @redFrik 

Move RPi and BeagleBone readmes into the main repository

---

README_WINDOWS.md

This escaped paren was mucking up a bunch of footnote links
- Bug fix

Windows readme: fix broken footnote

---

tools/clang-format.py

thanks to @jrsurge for reporting this!
- Bug fix

Fix bad variable name in clang-format.py

---

HelpSource/Classes/Maybe.schelp

fix typo in Maybe.schelp

---

HelpSource/Overviews/JITLib.schelp

this fixes #4758 and removes old email address

JITLib overview fixes

---

CHANGELOG.md
SCVersion.txt

Prep for 3.11 beta release
- [x ] Updated documentation

Prep 3.11 beta1

---

tools/cmake_gen/SuperColliderServerPlugin.cmake

Helpfile got installed to `Help` directory, should be `HelpSource/Classes`.
- Bug fix

corrected helpfile install

---

SCClassLibrary/Common/Audio/SynthDef.sc

improve readability and fix inline warnings in SynthDef code
- Bug fix

class library: improve readability and fix inline warnings

---

server/plugins/LFUGens.cpp

ENVGEN_NOT_STARTED check moved after check for mDone in 3.11

---

QtCollider/QtDownload.h
editors/sc-ide/translations/scide_de.ts
editors/sc-ide/translations/scide_es.ts
editors/sc-ide/translations/scide_fr.ts
editors/sc-ide/translations/scide_ja.ts
editors/sc-ide/translations/scide_pt.ts
editors/sc-ide/translations/scide_ru.ts
editors/sc-ide/translations/scide_sl.ts
editors/sc-ide/translations/scide_sv.ts
editors/sc-ide/translations/scide_zh.ts
editors/sc-ide/widgets/main_window.cpp
external_libraries/TLSF-2.4.6/COPYING
lang/LangPrimSource/PyrSymbolPrim.cpp
server/scsynth/scsynth_main.cpp
server/supernova/server/server_args.cpp

Fix spelling errors

---

HelpSource/Classes/Pfindur.schelp
HelpSource/Classes/Psync.schelp
SCClassLibrary/Common/Streams/FilterPatterns.sc
SCClassLibrary/JITLib/Patterns/Pdef.sc
testsuite/classlibrary/TestPattern.sc

Discussion see #4779
- Bug fix
- New feature

Topic/fix pdef clear using Psync

---

SCClassLibrary/Common/Audio/UGen.sc
SCClassLibrary/Common/Math/SimpleNumber.sc

This PR simplifies methods `degrad` and `raddeg`.
- slight improvement

optimize degrad/raddeg

---

CHANGELOG.md
SCVersion.txt

Update to SCVersion and Changelog for 3.11 RC1. This is expected to be the only RC before the 3.11 release.

RC1 prep documentation and version updates

---

.travis/before-install-linux.sh

Fixes #4820 
Otherwise this fails on Travis
High priority - please merge ASAP if this passes
- Bug fix

travis: add https to clang download URL

---

SCVersion.txt

Missing bump. After this, double checking all the release steps, and merging to `master`, I would recommend
re-releasing 3.11, since we will want a tag on the master branch anyway.
- Bug fix

SCVersion: bump to 3.11.0

---

HelpSource/Classes/Plotter.schelp
HelpSource/Guides/Tour-of-Special-Functions.schelp
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
testsuite/classlibrary/TestPlotter.sc

Cherry-pick #4459, per discussion on the recent skype dev call
- New feature

cherry pick 4459

---

HelpSource/Guides/Understanding-Errors.schelp
server/scsynth/SC_ComPort.cpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/server/main.cpp
server/supernova/server/server.cpp

- scsynth: refactor port binding into single function, add verbose
explanation for common issue
- supernova: add try-catch around main, add verbose explanation for same
issue
- help: remove unnecessary documentation
Replacement for #4703 since i accidentally nuked my branch earlier today. thanks @dyfer for catching it.
- Bug fix

servers: better explain UDP/TCP port binding fail

---

.travis/qpm-prep.sh
testsuite/classlibrary/TestAbstractFunction.sc

additions to @patrickdupuis 's PR #4749 
1. bring QPM to master after merging https://github.com/supercollider/qpm/pull/10
2. fix unescaped backslash in string
- Bug fix

[CI] additions to #4749

---

.travis/before-install-osx.sh
CMakeLists.txt
HelpSource/Classes/LFCub.schelp
HelpSource/Classes/LFPar.schelp
HelpSource/Classes/LFTri.schelp
HelpSource/Classes/Pdiff.schelp
HelpSource/Classes/Pdrop.schelp
HelpSource/Classes/Pfindur.schelp
HelpSource/Classes/Psync.schelp
QtCollider/interface.cpp
QtCollider/widgets/QcCanvas.cpp
README_MACOS.md
SCClassLibrary/Common/Audio/SynthDef.sc
SCClassLibrary/Common/Math/SimpleNumber.sc
SCClassLibrary/Common/Streams/FilterPatterns.sc
SCClassLibrary/JITLib/Patterns/Pdef.sc
common/SC_fftlib.cpp
editors/sc-ide/CMakeLists.txt
editors/sc-ide/core/main_function.cpp
include/plugin_interface/SC_PlugIn.hpp
server/CMakeLists.txt
server/scsynth/CMakeLists.txt
server/scsynth/scsynth_main.cpp
server/supernova/CMakeLists.txt
testsuite/classlibrary/TestPattern.sc
testsuite/classlibrary/TestSimpleNumber.sc

this cherry-picks the following PRs listed in https://github.com/supercollider/supercollider/projects/19:
#4710                                                                                                                
#4796                                                                                                                
#4792
#4762
#4802
#4583
#4479
#4804
#4815
#4850
#4810
#4782
#4811
I processed them using the following script:
```
MERGE=$(git rev-list -n 1 :/"Merge pull request #$1 ")
COMMITS=$(git rev-list --reverse $MERGE^1..$MERGE^2)
git cherry-pick $COMMITS
```

cherry-pick 3.11.1 PRs

---

QtCollider/widgets/QcTextEdit.cpp

Fixes #3279
SC if/else syntax is addictive
- Bug fix

TextView: enter interprets selection fix

---

HelpSource/Classes/Pen.schelp
HelpSource/Classes/SCImage.schelp
HelpSource/Classes/UserView.schelp

docs: remove notes about outdated macOS versions

---

HelpSource/Classes/Object.schelp

This PR fixes a small error in the `tryPerform` example.

[Help] fix error in tryPerform example

---

HelpSource/Classes/EnvGen.schelp
HelpSource/Classes/Node.schelp
server/plugins/LFUGens.cpp
testsuite/classlibrary/TestEnvGen_server.sc

Fixes #3782 
- Bug fix
- New feature

EnvGen gate < -1 now respects curve

---

README.md

this is part of implementing github.com/supercollider/rfcs/pull/1

readme: add platform support info

---

server/supernova/sc/sc_synth_definition.cpp

Fixes #4916
It seems to work on my system but I'd appreciate if others take a look whether this is a correct fix.
- Bug fix
- there are no tests for this...

supernova: ignore non-scsyndef files

---

server/plugins/LFUGens.cpp

Fixes a serious typo in  #4793 
- Bug fix

server: EnvGen: fixes serious typo in initSegment

---

.travis.yml
.travis/before-install-linux.sh
server/supernova/sc/sc_synth_definition.cpp

Routine merge. I wanted to do this quickly to get #4920 into develop.

Merge 3.11 into develop

---

SCClassLibrary/Common/UnitTesting/UnitTest.sc
testsuite/classlibrary/TestUnitTest.sc

Fixes #4385, see discussion there.
- New feature

class library: Add setUpClass/tearDownClass features to UnitTest

---

SCClassLibrary/Common/Core/Object.sc
testsuite/classlibrary/TestObject.sc

check for empty string in Object -writeDefFile

---

lang/LangPrimSource/PyrArrayPrimitives.cpp
testsuite/classlibrary/TestArray.sc

sclang: fix mirror/1 behavior on empty array

---

editors/sc-ide/primitives/sc_ipc_client.cpp

Fix Document.text when using non-ascii characters

---

HelpSource/Tutorials/Getting-Started/03-Start-Your-Engines.schelp

Revisiting SuperCollider after a long time away and making doc edit suggestions as I go. Previous chapter PR: #4854

Update "Getting Started" chapter 3

---

editors/sc-ide/core/sc_process.cpp

This PR is a cherry-pick of #5015 into `3.11`
- cherry-pick

Cherry-pick #5015 into 3.11

---

HelpSource/Overviews/Operators.schelp

This PR is a cherry-pick of #4995 into 3.11.
- cherry-pick

Cherry-pick #4995 into 3.11

---

HelpSource/Classes/Routine.schelp

This PR is a cherry-pick of #5006 into `3.11`
- cherry-pick

cherry-pick #5006 into 3.11

---

README.md

Slack says this one 'never expires', but it said that about the last one too..
- Bug fix

REAMDE: update slack link

---

HelpSource/Classes/MenuAction.schelp

docs: fix MenuAction typo

---

HelpSource/Guides/Debugging-tips.schelp

fix typo in Debugging Tips guide file (seperate -> separate)

docs: fix debugging tips typo

---

HelpSource/editor.js

helpbrowser: fix rightParens match-token check

---

SCClassLibrary/Common/Quarks/Quarks.sc

Cherry-pick #4404 into 3.11
- Cherry-pick

Cherry-pick #4404 into 3.11

---

HelpSource/Classes/Object.schelp

Cherry-pick #4888 into 3.11
-Cherry-pick

Cherry-pick #4888 into 3.11

---

HelpSource/Classes/Pipe.schelp

Cherry-pick #4881 into 3.11
- Cherry-pick

Cherry-pick #4881 into 3.11

---

QtCollider/LanguageClient.cpp

Cherry-pick #5039 into 3.11
- Cherry-pick

Cherry-pick #5039 into 3.11

---

README.md

Cherry-pick #5023 into 3.11
- Cherry-pick

Cherry-pick #5023 into 3.11

---

testsuite/classlibrary/TestPatternProxy.sc

Cherry-pick #4962 into 3.11
- Cherry-pick

Cherry-pick #4962 into 3.11

---

editors/sc-ide/core/doc_manager.cpp

Cherry-pick #4948 into 3.11
- Cherry-pick

Cherry-pick #4948 into 3.11

---

HelpSource/Reference/Syntax-Shortcuts.schelp

Cherry-pick #5001 into 3.11
- Cherry-pick

Cherry-pick #5001 into 3.11

---

HelpSource/Guides/Debugging-tips.schelp

Cherry-pick #5029 into 3.11
- Cherry-pick

Cherry-pick #5029 into 3.11

---

HelpSource/Classes/MenuAction.schelp

Cherry-pick #5028 into 3.11
- Cherry-pick

Cherry-pick #5028 into 3.11

---

SCClassLibrary/Common/Collections/String.sc
testsuite/classlibrary/TestString.sc

Cherry-pick #4960 into 3.11
- Cherry-pick

Cherry-pick #4960 into 3.11

---

HelpSource/Classes/Pfunc.schelp

Cherry-pick #5010 into 3.11
- Cherry-pick

Cherry-pick #5010 into 3.11

---

HelpSource/Classes/Server.schelp
HelpSource/Guides/Server-Guide.schelp

Cherry-pick #4988 into 3.11
- Cherry-pick

Cherry-pick #4988 into 3.11

---

HelpSource/Classes/Monitor.schelp

Cherry-pick #4923 into 3.11
- Cherry-pick

Cherry-pick #4923 into 3.11

---

SCClassLibrary/Common/Audio/BasicOpsUGen.sc
testsuite/classlibrary/TestUGenMathOptimization.sc

Classlib: Fix UGen optimization of (a+b) + (a+b)

---

lang/LangSource/Bison/make_parser.sh

Cherry-pick #5032 into 3.11
- Cherry-pick

Cherry-pick #5032 into 3.11

---

HelpSource/Classes/EventPatternProxy.schelp
HelpSource/Classes/Pdef.schelp
HelpSource/Classes/TaskProxy.schelp
HelpSource/Classes/Tdef.schelp
SCClassLibrary/JITLib/Patterns/Pdef.sc
testsuite/classlibrary/TestEventPatternProxy.sc
testsuite/classlibrary/TestTaskProxy.sc

Cherry-pick #4903 and #4996 into 3.11
- Cherry-pick

Cherry-pick #4903 and #4996 into 3.11

---

SCClassLibrary/Common/Audio/UGen.sc
testsuite/classlibrary/TestComplex.sc

Cherry-pick #5000 into 3.11
- Cherry-pick

Cherry-pick #5000 into 3.11

---

SCClassLibrary/Common/GUI/tools/HelpBrowser.sc

Cherry-pick #4932 into 3.11
- Cherry-pick

Cherry-pick #4932 into 3.11

---

QtCollider/primitives/prim_QPen.cpp
QtCollider/widgets/QcGraph.cpp
QtCollider/widgets/QcLevelIndicator.cpp
QtCollider/widgets/QcMultiSlider.cpp
QtCollider/widgets/QcScopeShm.cpp
QtCollider/widgets/soundfileview/view.cpp

Cherry-pick #4986 into 3.11
- Cherry-pick #4986 into 3.11

Cherry-pick #4986 into 3.11

---

editors/sc-ide/primitives/sc_ipc_client.cpp

Cherry-pick #4978 into 3.11
- Cherry-pick

Cherry-pick #4978 into 3.11

---

SCClassLibrary/JITLib/ProxySpace/extStoreOn.sc
testsuite/classlibrary/TestProxySpace.sc

Cherry-pick #4316 into 3.11
- Cherry-pick #4316 into 3.11

Cherry-pick #4316 into 3.11

---

lang/LangPrimSource/OSCData.cpp

Cherry-pick #4927 into 3.11
- Cherry-pick

Cherry-pick #4927 into 3.11

---

server/scsynth/CMakeLists.txt
server/supernova/CMakeLists.txt

Cherry-pick #4926 into 3.11
- Cherry-pick

Cherry-pick #4926 into 3.11

---

SCClassLibrary/Common/Core/Object.sc
testsuite/classlibrary/TestObject.sc

Cherry-pick #4953 into 3.11
- Cherry-pick

Cherry-pick #4953 into 3.11

---

HelpSource/Guides/Glossary.schelp

docs: fix glossary typo

---

external_libraries/oscpack_build.cpp

Cherry-pick #4983 into `3.11`
- Cherry-pick

Cherry-pick #4983 into 3.11

---

common/SC_ServerBootDelayWarning.cpp
common/SC_ServerBootDelayWarning.h
server/scsynth/CMakeLists.txt
server/scsynth/scsynth_main.cpp
server/supernova/CMakeLists.txt
server/supernova/server/main.cpp

Cherry-pick #4984 into 3.11
- Cherry-pick

Cherry-pick #4984 into 3.11

---

HelpSource/Guides/Glossary.schelp

Cherry-pick #5082 into `3.11`
- Cherry-pick

Cherry-pick #5082 into 3.11

---

HelpSource/Classes/LinkClock.schelp
HelpSource/Classes/Platform.schelp

Fixes a few broken links in help docs, found by running platform/renderAllHelp.scd

help: fix broken links [skip ci]

---

HelpSource/Classes/Main.schelp

.recompile works on all platforms and is not equivalent to restarting SC 
(e.g. wrt LanguageConfig)
Fixes #5108

help: Main: correct .recompile [skip ci]

---

HelpSource/Classes/BEQSuite.schelp

doc: fix BEQSuite typo

---

HelpSource/Classes/BAllPass.schelp

doc: fix BAllPass.schelp typo

---

tools/release/make_release.py

small typo i just noticed while running it
- Bug fix

[skip ci] tools: fix typo in make_release.py

---

README.md

updating README.md per release process instructions

[skip ci] readme: update platform support guarantees

---

CMakeLists.txt
HelpSource/Guides/Non-Realtime-Synthesis.schelp
SCClassLibrary/Common/GUI/Base/QView.sc
testsuite/classlibrary/TestView.sc

cherry-picks the remaining PRs from the TODO column of https://github.com/supercollider/supercollider/projects/19
\#5094, \#5107, \#5093, \#5095
two are tested bugfixes and two are documentation changes
- Bug fix

[3.11] cherry-pick 3.11.1 PRs

---

SCVersion.txt

preparing for 3.11.1 release!
- New feature

Bump project version to 3.11.1-rc1

---

CHANGELOG.md

there were 93 PRs merged for this patch release! including 24 documentation PRs.
when a PR was cherry-picked, i used the original PR number.

[Release] Update changelog for 3.11.1

---

SCClassLibrary/Common/UnitTesting/UnitTest.sc

Test suite: Fix printed output of assertFloatEquals

---

HelpSource/Classes/Onsets.schelp

Fix broken link to research paper in OnSets.schelp
- [ x] Code is tested
- [ x] All tests are passing
- [ x] Updated documentation
- [ x] This PR is ready for review

docs: Fix broken link to research paper.

---

.appveyor.yml

~~If seems that QT 5.15 fixes #5033. I'm guessing it will also on Windows and would like to try updating QT on our CI.~~
5.15 fix seems to apply to macOS, but hasn't been confirmed yet to fix this issue on Windows
- Breaking change (possibly? you never know when updating QT)

update qt to 5.15 for Windows x64 builds

---

HelpSource/Classes/LinuxPlatform.schelp
HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/linux/extString_linux.sc
SCClassLibrary/Platform/linux/LinuxPlatform.sc

classlib: LinuxPlatform: findTerminalEmulator

---

.appveyor.yml

Temporarily disables deployment for AppVeyor and uploads builds to Amazon S3.
Solution stolen from @brianlheim :-) see #5120
Fixes #5184
- Temporary Bug fix

AppVeyor: temporary workaround for artifact storage limit

---

server/supernova/sc/sc_osc_handler.cpp

supernova: fix s_getn

---

editors/sc-ide/CMakeLists.txt

Cherry pick of #5178 for 3.11 branch. Should make Travis pass

cmake: fix deploy of qtwebengine w/ qt 5.15.1

---

HelpSource/Classes/Set.schelp
HelpSource/Classes/SortedList.schelp

Added information to the help files Set.schelp and SortedList.schelp, if a function checks for equality or identity.
Connected to #4573 (not fully fixing the issue yet)

Docs: Set / SortedList added details regarding equality checks.

---

HelpSource/Classes/Dictionary.schelp
HelpSource/Classes/LFSaw.schelp
HelpSource/Classes/MIDIFunc.schelp
HelpSource/Classes/MIDIdef.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/Onsets.schelp
HelpSource/Classes/Set.schelp
HelpSource/Classes/SortedList.schelp
HelpSource/Guides/UsingMIDI.schelp
HelpSource/Reference/AudioDeviceSelection.schelp
HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp
HelpSource/Tutorials/Getting-Started/11-Busses.schelp
HelpSource/Tutorials/Getting-Started/15-Sequencing-with-Routines-and-Tasks.schelp

cherry-pick documentation PRs from https://github.com/supercollider/supercollider/projects/19
original PRs:
#5131 
#5137 
#5136 
#5141 
#5142 
#5173 
#5203

[3.11] cherry-pick documentation PRs for 3.11.2

---

editors/sc-ide/CMakeLists.txt

cmake: with macOS+QtWebEngine+Qt5.15.1, mark all manually deployed files writeable

---

tools/clang-format.py

fixes #5205
tested locally and works fine. unfortunately too late for @giuliomoro, but may help someone in the future
- Bug fix

clang-format.py: handle binary files better

---

.travis.yml

Create download link for non-legacy build only. Fixes #5233
Please note: I'm not sure how to test this fix, as the nightly develop link is only triggered for the develop branch, AFAIU.
- Bug fix

travis: fix macos latest develop download link

---

.travis.yml

cherry-picking #5234
- Bug fix

cherry pick #5234 (travis: fix macos latest develop download link)

---

HelpSource/Classes/Complex.schelp
SCClassLibrary/Common/Math/Complex.sc

Addresses issue #5213 sclang: Complex.sqrt is missing
- New feature

class library: add Complex:-sqrt

---

CHANGELOG.md
SCVersion.txt

Last PR for 3.11.2, please review and merge after #5242 is merged as the changelog currently assumes it will be.
- Release process

update version+changelog for 3.11.2

---

include/plugin_interface/SC_Constants.h
include/plugin_interface/SC_InlineBinaryOp.h
include/plugin_interface/SC_InlineUnaryOp.h
include/plugin_interface/SC_RGen.h

Fixes https://github.com/supercollider/supercollider/issues/5249
This PR adds doxygen style comments to important headerfiles that are facing plugin developers. With these, LSP based tools should be able to pick up the information from the source code and automatically give the developer hints when doing "code hover" or similar.
Where possible I have used the original comments and/or documentation from the schelp system. 

Improve doxygen style documentation in header files for plugin developers

---

HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp

Fixing small typos while I'm going through the tutorial 👍 
- Documentation Only

Fix small typo in Getting-Started Tutorial.

---

.github/workflows/actions.yml

Some cleanup for the recently added github actions script
- re-add linux gcc5 build (original issue has been fixed upstream)
- add better job names
- rename actions file (I meant to do this in the original PR)
- remove unneeded package install (xcpretty is included by default)

github actions: re-add linux gcc5 build

---

HelpSource/Classes/Dictionary.schelp

add a warning about nil in Dictionary help

---

HelpSource/Tutorials/A-Practical-Guide/PG_08_Event_Types_and_Parameters.schelp

velocity is amp *times* 127

---

HelpSource/Classes/Pmono.schelp

help: Fix duplicate word in Pmono

---

.github/workflows/actions-macos.yml
cmake_modules/MacOSXBundleInfo.plist.in
server/scsynth/SC_CoreAudio.cpp

The PR applies patches that creates SC functionally equivalent to version 3.11.2, that runs on macOS Big Sur. This build also seems compatible with macOS Catalina.
For context see:
https://github.com/supercollider/supercollider/issues/5168#issuecomment-778898320
https://github.com/supercollider/supercollider/issues/5168#issuecomment-779081643
- Bug fix

Big Sur patches for 3.11

---

HelpSource/Classes/Recorder.schelp

added another usage example for Recorder with some additional options

doc: another usage example for Recorder

---

.github/workflows/actions.yml
CMakeLists.txt

Fixes #4664 and #5188, AFAIU.
Thanks @brianlheim for [suggesting the fix](https://github.com/supercollider/supercollider/issues/5188#issuecomment-780884749)
- Bug fix

cmake: disable codesigning on macos

---

HelpSource/Classes/Array.schelp

docs: fix array typo

---

server/plugins/Convolution.cpp
server/plugins/DelayUGens.cpp
server/plugins/FFT_UGens.cpp
server/plugins/IOUGens.cpp
server/plugins/ML_SpecStats.cpp
server/plugins/PV_UGens.cpp
server/plugins/PartitionedConvolution.cpp

plugins: use nullptr

---

README.md

README.md: update CI badge for GHA

---

.github/workflows/actions.yml

Shorter name should be more readable in logs etc. 
- Cosmetic change

gha: change the main action's name

---

README.md

This is the final touch on implementing #5261. 
Since all previously mentioned steps are completed, I believe this _fixes #5261_!
I haven't updated supported platforms, I think we will be reviewing that before 3.12 release anyway.
EDIT: I stopped CI since I forgot to add `[skip ci]` in the commit message.

Update README.md with information about current build environment

---

HelpSource/Guides/Non-Realtime-Synthesis.schelp

Replace with PV_MagFreeze, which is in the standard distribution and produces a similar effect
Fixes #5401

docs: remove use of sc3-plugins ugen

---

.github/workflows/actions.yml

Fixes #5413
To confirm - S3 links from this branch:
https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-fb97f6644530ee25c00673add038d29fffdcd11d.dmg
https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/win32/SC-fb97f6644530ee25c00673add038d29fffdcd11d.zip
https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/win64/SC-fb97f6644530ee25c00673add038d29fffdcd11d.zip
- Bug fix

GitHub Actions: fix macOS s3 upload

---

HelpSource/Tutorials/JITLib/recursive_phrasing.schelp
package/contributor-list-generator/package.json
server/supernova/dsp_thread_queue/dsp_thread.hpp
server/supernova/dsp_thread_queue/dsp_thread_queue.hpp
testsuite/sclang/lpc/LPCTestUtils.sc
tools/clang-format.py
tools/release/make_release.py

mostly master->main
part of https://github.com/supercollider/supercollider/issues/5251

update uses of master/slave terminology

---

SCClassLibrary/Common/Core/CondVar.sc

CondVar: Only pass in one empty array

---

HelpSource/Classes/ArrayedCollection.schelp
HelpSource/Classes/SequenceableCollection.schelp

Clarified documentation regarding element checks for equality / identity
Connected to #4573, but not completely fixing it yet.

Docs: ArrayedCollections / SequencableCollections clarified

---

.github/workflows/actions.yml

Set macOS deployment target in accordance with OS versions supported by Qt. Fixes #5318
- Bug fix

github actions: differentiate deployment target on macOS

---

HelpSource/Classes/BPF.schelp

Fix Documentation to BPF Q Parameter

---

SCClassLibrary/Common/Control/Server.sc
server/supernova/audio_backend/portaudio_backend.hpp
server/supernova/server/main.cpp
server/supernova/server/server_args.cpp
server/supernova/server/server_args.hpp

Clip loud signals on macOS on supernova. See scsynth version #5412 for the detailed description. Thanks @elgiano !
I've taken @elgiano 's WIP branch and ~~his implementation seems to work as expected for me so I'm submitting this PR~~ made some changes. 
Fixes #5412
- New feature

macos: clip output values on supernova

---

HelpSource/Classes/Pseed.schelp

docs: fix Pseed typo

---

HelpSource/Classes/ToolBar.schelp

Again just a small fix, which resolves unnecessary and unwanted link to the same page.

docs: removed classes/Toolbar link from related links in ToolBar helpfile

---

HelpSource/Tutorials/A-Practical-Guide/PG_Cookbook08_Swing.schelp

I think describing the playing of a bassist as *idiotic* should not be part of the documentation.

Fix insulting phrasing on Tutorial

---

HelpSource/Classes/Pseed.schelp

I felt this help file was significantly burying the lead in terms of how Pseed can be used to organize sound and make music, so
I added a few examples that I think would be of use to folks who are looking to hit the ground running.  

docs: Add Pseed examples

---

CHANGELOG.md

I hope I included all important changes, I'm open to suggestions! Please review carefully :)
I've also added a commented-out entry "template" - I think that's helpful, but I can also remove that if desired.

Update CHANGELOG for 3.12.0-rc1

---

HelpSource/Guides/News-3_12.schelp
HelpSource/Help.schelp
package/changelog_to_schelp.sh
tools/release/make_release.py

I've updated the changelog in help from the CHANGELOG.md
I've also made two changes to scripts:
- make_release includes a note where the conversion script is
- conversion script accepts `### name` section names

Update help for 3.12

---

CHANGELOG.md
HelpSource/Guides/News-3_12.schelp
HelpSource/Help.schelp
README.md
SCVersion.txt
package/changelog_to_schelp.sh
tools/release/make_release.py

3.12 -> develop

---

HelpSource/Guides/FFT-Overview.schelp

standardize capitalization of 'UGen' in FFT Overview guide

standardize capitalization of UGen

---

CHANGELOG.md
SCVersion.txt

Updates for 3.12.0-rc2

---

HelpSource/Classes/Phasor.schelp

docs: fix Phasor typo

---

CHANGELOG.md
HelpSource/Guides/News-3_12.schelp
SCVersion.txt

update for 3.12.0

---

CHANGELOG.md
HelpSource/Guides/News-3_12.schelp
SCVersion.txt

Prepare for 3.12.1-rc1

---

HelpSource/Classes/BusPlug.schelp

Fix typo in BusPlug.schelp

---

HelpSource/Classes/Server.schelp
HelpSource/Classes/SynthDef.schelp
HelpSource/Guides/GUI-Introduction.schelp
HelpSource/Guides/UserFAQ.schelp
HelpSource/Help.schelp

Following the discussion with @dyfer in https://github.com/supercollider/supercollider.github.io/issues/247, this adds the `UserFAQ` page from the website WIKI to the doc.

Add wiki content to doc

---

CHANGELOG.md
SCVersion.txt

Prepare 3.12.1 release

---

HelpSource/Classes/Buffer.schelp
HelpSource/Classes/GUI.schelp
HelpSource/Classes/MultiSliderView.schelp
HelpSource/Classes/ProxyMonitorGui.schelp
HelpSource/Classes/UserView.schelp
HelpSource/Classes/Window.schelp
HelpSource/Guides/How-to-Use-the-Interpreter.schelp
SCClassLibrary/Common/GUI/Base/QWindow.sc
SCClassLibrary/Common/GUI/backwardsCompatibility/GUI.sc
SCClassLibrary/JITLib/GUI/ProxyMonitorGui.sc
SCClassLibrary/JITLib/ProxySpace/extStoreOn.sc
editors/sced/sced/WindowHelper.py
editors/sced/sced3/supercollider.py
editors/sced/scedwin/py/WindowHelper.py
examples/GUI examples/GUI_examples1.scd
examples/GUI examples/GUI_examples2.scd

Closes #4313
Also deleted the `server` argument of the method SCClassLibrary/Common/GUI/Base/QWindow.sc
- [] All tests are passing
Currently the tests are not passing but this is not linked to the changes?
edit: deleted test logs

remove SwingOSC references

---

HelpSource/Guides/J-concepts-in-SC.schelp

typo in documentation causing broken external link

docs: fix jsoftware link

---

HelpSource/Tutorials/Getting-Started/05-Functions-and-Sound.schelp

Grammar fix: "principal" should be "principle"

---

SCClassLibrary/Common/Control/Score.sc
server/supernova/audio_backend/jack_backend.hpp
server/supernova/audio_backend/portaudio_backend.hpp
server/supernova/audio_backend/sndfile_backend.hpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp
server/supernova/sc/sc_plugin_interface.cpp
server/supernova/server/nrt_synthesis.hpp
server/supernova/server/server.cpp
server/supernova/server/server.hpp

NRT synthesis is broken in Supernova.
Fixes https://github.com/supercollider/supercollider/issues/5270
Also contains a change that prevents duplicate creation of the default Group in the `Score.section` method.
- Bug fix

Supernova NRT fixes

---

HelpSource/Classes/Float.schelp
HelpSource/Classes/Pfindur.schelp
HelpSource/Classes/SynthDef.schelp
HelpSource/Guides/J-concepts-in-SC.schelp
HelpSource/Tutorials/Getting-Started/05-Functions-and-Sound.schelp

In preparation for version 3.12.2, here's a cheery-pick of documentation commits merged to `develop` since 3.12.1.

3.12.2 cherry pick documentation

---

SCVersion.txt

Update SCVersion.txt for 3.12.2-rc1

---

SCClassLibrary/Common/UnitTesting/GUI/UnitTestGUI.sc

this is just a convenience.
This gives a convenient way to have a line of code for a given test.
- New feature

class library: add a way to post the code for calling unit test

---

HelpSource/Classes/SinOscFB.schelp

Fixes #5641
This is my first pull request ever, and although I have read the contributing guidelines and watched Eli's video on "Contributing with Git and GitHub", I am not sure if it is enough of a description to reference to an existing issue. Please let me know if this is sufficient, or if more information should be provided in the pull request. Thanks!

SinOscFB.schelp: added FM behavior description

---

SCClassLibrary/Common/GUI/PlusGUI/Control/FreqScope.sc

result and add not needed for the FreqScope synthdefs.
very minor cleanup

class library: remove superfluous variables

---

server/supernova/sc/sc_osc_handler.cpp

Fixes https://github.com/supercollider/supercollider/issues/5590
- Bug fix

supernova: fix crash when passing audio/control bus mapping to arrayed Group control

---

tools/release/make_release.py

make_release.py: add note about updating SCVersion.txt

---

server/CMakeLists.txt

This makes the option of `LIB_SUFFIX` visible with `cmake -L`

Add option for LIB_SUFFIX

---

testsuite/classlibrary/TestPanAz.sc
testsuite/scripts/gha_test_run_proto.json

Fix errors in PanAz tests that made them impossible to pass. Also change Condition in CondVar.
- Bug fix

testsuite: PanAz fix assertFloatEquals and CondVar

---

examples/research_and_tools/SeminaireMusical.scd

Improvements to the aural comprehension application "séminaire musical" in the examples folder.
There were bugs fixed in time and beats test.

Topic update seminaire

---

HelpSource/Classes/Symbol.schelp

Document Symbol -isPrefix

---

HelpSource/Classes/Float.schelp
HelpSource/Classes/Integer.schelp

Documented methods are morally superior.

document Float#{clip,fold,wrap}

---

HelpSource/Classes/Integer.schelp

fix Integer#wrap docs

---

server/plugins/NoiseUGens.cpp

Some formatting is also improved. This fixes #1278.
Fixes #1278
Supersedes https://github.com/supercollider/supercollider/pull/5336

fix audio rate versions of triggered random ugens

---

HelpSource/Classes/ControlRate.schelp

More examples makes help/documentation better. I have added two examples that demonstrate well what is the difference between control rate and audio (sampling) rate.

adding two examples to ControlRate.schelp

---

HelpSource/Classes/EventPatternProxy.schelp

EventPatternProxy help files had typos in the example section, compromising code blocks execution

Help: EventPatternProxy fix example code execution

---

.gitmodules

This will make pulling 3.12 branch possible again. We are just adding the single commit without creating a new tag/release. See https://github.com/supercollider/supercollider/issues/5695#issuecomment-1100920416 for previous discussion.
- Bug fix

[main branch] Git submodules: update urls to use https

---

HelpSource/Classes/Git.schelp
HelpSource/Guides/UsingQuarks.schelp
HelpSource/Guides/WritingHelp.schelp
README_BEAGLEBONE_BLACK.md
README_RASPBERRY_PI.md
SCClassLibrary/Common/Quarks/Git.sc

Fixes #5765 
@jamshark70 asks:
> Should the JACK instructions be likewise updated? As I understand it, github discourages git:// addresses, so I suppose so should we.
Yes. 

Docs: replace git:// with https://

---

.github/workflows/actions.yml
CMakeLists.txt
README_WINDOWS.md
cmake_modules/FindReadline.cmake
lang/LangSource/SC_TerminalClient.cpp

I checked what's the current status of GNU Readline on Windows and I found out that it is available through vcpkg. After small adjustments I was able to add it to our Windows build. ~~However, there is still an issue with the keyboard input, see below.~~ I think I also fixed the keyboard input. (My initial findings were inaccurate: I think the issue was with trying to read input when there was nothing to read.) 
Readline from vcpkg currently works with msvc builds only, since build errors occur when it's being built with mingw in vcpkg.
This will fix #2171 I think.
(outdated comments hidden below)
<details>
~~Outstanding issue with `stdin`~~
~~Even though readline seems to work fine, the keyboard requires pressing a key _twice_ in order for it to be registered. This is consistent with …

Readline on Windows

---

HelpSource/Classes/DiskOut.schelp
HelpSource/Classes/Recorder.schelp
HelpSource/Classes/Score.schelp
HelpSource/Classes/Server.schelp
HelpSource/Guides/Non-Realtime-Synthesis.schelp
SCClassLibrary/Common/Control/Server.sc

Fixes #5557
Enhancement 
Hi @madskjeldgaard, how does this look?
Let me know if this needs any changes.
Thanks

replace aiff with wav as the default value for recHeaderFormat

---

SCClassLibrary/Common/Audio/BufIO.sc

this fixes #5722
See discussion on #5722.
- Bug fix

class library: guarantee that SetBuf gets an array

---

HelpSource/Classes/Error.schelp

This is a proposal to remove the reference to suicide in the SC help. I'm open to suggestions how to improve this further.
Fixes #5798

Error.schelp: update example's wording

---

HelpSource/Classes/NodeProxy.schelp
HelpSource/Classes/Pdef.schelp
HelpSource/Classes/Pgtpar.schelp
HelpSource/Classes/Ppar.schelp
HelpSource/Classes/Pprotect.schelp
HelpSource/Classes/Pproto.schelp
HelpSource/Classes/Ptpar.schelp

just some minor fixes and a helpfile for Pgtpar.

Topic/help minor fixes   mainly patterns

---

HelpSource/Classes/PfadeIn.schelp
HelpSource/Classes/PfadeOut.schelp

This adds documentation for the PFadeIn and PFadeOut classes
- [x ] Updated documentation
- [ x] This PR is ready for review

Add help files for PFadeX classes

---

QtCollider/QObjectProxy.cpp
QtCollider/primitives/prim_QObject.cpp
server/supernova/server/main.cpp

Was trying to run SC on OpenBSD. With these changes I managed to make it build and run.
- Bug fix

build: Make it build on OpenBSD.

---

HelpSource/Classes/EZRanger.schelp
HelpSource/Classes/Group.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/Pdef.schelp
HelpSource/Classes/ProxySpace.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_03.schelp

moved s.boot so it appears before a SynthDef instead of after.

docs: fixing various typos and add general improvements

---

HelpSource/Classes/EZRanger.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/ProxySpace.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp

fix phrasing and typo in comment in example e)

docs: jitlib basic concepts 02 typo

---

HelpSource/Classes/EZRanger.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/ProxySpace.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_03.schelp

docs: jitlib basic concepts 03 typo

---

HelpSource/Classes/EZRanger.schelp
HelpSource/Classes/Group.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/ProxySpace.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_03.schelp

```Server Command Reference``` should be linked in ```Group``` help file

docs: group doc add link

---

HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/ProxySpace.schelp

fix typo in NotificationCenter.schelp

docs: notification center typo

---

HelpSource/Classes/EZRanger.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/ProxySpace.schelp
HelpSource/Tutorials/JITLib/jitlib_basic_concepts_02.schelp

signal clips in example c. amplitude value changed to remove clipping and for consistency with other examples.

docs: jitlib basic concepts 02 signal clipping

---

HelpSource/Classes/Server.schelp
HelpSource/Classes/SimpleNumber.schelp

add specific options for ```recSampleFormat``` in ```Server``` help file

docs: server rec sample format additional info

---

server/plugins/OscUGens.cpp

Previously, `TWindex` would _always_ output index `0` if no trigger was received on the first sample, regardless of the probability assigned to that index by the user. 
Specifically, the line:
```
unit->m_trig = -1.f; // make it trigger the first time
```
doesn’t actually ensure it triggers the first time; the trigger input may not fire, in which case it defaults to `unit->m_prevIndex = 0;` (which might violate the assigned probability).
This PR fixes that, as well as ensuring that the initialization sample matches the first sample (by preventing the generation of a new random value on a first-sample trigger).
Another change was made so that the `maxSum` variable is only updated internally on a received trigger , it's not needed otherwise. It's also checked so that it's updated no more …

TWindex: Ensure the random first sample matches init sample

---

SCClassLibrary/Common/Audio/BasicOpsUGen.sc
testsuite/classlibrary/TestUGenMathOptimization.sc

This is an attempt to fix issue #5405
- Bug fix

class library: Fix BinaryOpUGen optimization for a === b cases

---

HelpSource/Classes/Exception.schelp
HelpSource/Classes/Function.schelp
HelpSource/Reference/Control-Structures.schelp

try syntax is hard to find, I improved its discoverability

Improve try syntax discoverability and add warnings

---

HelpSource/Classes/Function.schelp

Fixes typo in Function help file.

Fixes typo in Function help file

---

README.md

fix downloads url in readme

---

HelpSource/Classes/DrawGrid.schelp
SCClassLibrary/Common/GUI/Base/Grid.sc

This is a follow-on to #5827, which changed the behavior of `DrawGrid:*test`.
Help docs are also brought up to date and errors there were corrected, hyperlinks added, etc.

[classlib] DrawGrid: update *test and label positioning

---

HelpSource/Classes/Plotter.schelp

help: improve example

---

HelpSource/Classes/AppClock.schelp
SCClassLibrary/Common/Core/Clock.sc
testsuite/classlibrary/TestTask.sc

Fixes #5700.
- Bug fix
- New feature

AppClock schedAbs

---

HelpSource/Reference/Server-Architecture.schelp

Fix typo in Server Architecture help

Typo in Server Architecture help file

---

HelpSource/Reference/Literals.schelp

Fix a couple of typos in the "Literals" help file

HelpSource: Fix typos in Literals help file

---

HelpSource/Classes/BusPlug.schelp

Fixes typo in help file of BusPlug

Typo in BusPlug

---

common/SC_Filesystem_win.cpp

Expand tilde to users home directory on Windows

---

HelpSource/Classes/Pspawn.schelp
HelpSource/Classes/Pspawner.schelp
HelpSource/Classes/Spawner.schelp
SCClassLibrary/Common/Streams/Pspawner.sc

This adds some basic documentation.
- Argument name change. This class is likely not used directly anywhere.

Basic Documentation for Spawner Class

---

.github/workflows/actions.yml

This PR updates deprecated functionality in our GHA workflow.
The only deprecations that are not fixed pertain to our test runner and need to be solved separately.
- Bug fix

GHA: update deprecated functionality

---

server/scsynth/SC_SequencedCommand.cpp

Signed-off-by: Scott Wilson <i@scottwilson.ca>
As noted in #5238 /d_load and /d_loadDir provide no error warning or /fail reply when a file or directory doesn't exist. This adds both
NB I've not updated the doc, as individual command docs don't usually indicate if they reply with /fail. This is arguably not ideal, but if we want to change that I'd propose doing that for all at once.
- Bug fix

scsynth: Add error warnings and /fail replies to /d_load and /d_loadDir

---

HelpSource/Classes/Integer.schelp

Add description to undocumented methods of the Integer class.

docs: Add description to undocumented methods of the Integer class.

---

HelpSource/Tutorials/Getting-Started/04-Functions-and-Other-Functionality.schelp

Revisiting SuperCollider after a long time away and making doc edit suggestions as I go. Previous chapter PR: #4868

Update "Getting Started" chapter 4

---

SCClassLibrary/Common/Streams/Patterns.sc

Fixes https://github.com/supercollider/supercollider/issues/5879
- Bug fix

fix: Pattern.record

---

HelpSource/Classes/Collection.schelp
HelpSource/Classes/Object.schelp
HelpSource/Classes/Signal.schelp
HelpSource/Classes/SimpleNumber.schelp
HelpSource/Guides/WritingPrimitives.schelp
SCClassLibrary/Common/Collections/Collection.sc
SCClassLibrary/Common/Core/Function.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

This PR contains updates to a random batch of scdocs. It's an experiment to fix and improve things as I come across them, which I may not otherwise circle back to.
The commits are organized to clearly show the contents of the PR. I try to keep these batch updates to scdocs only, but occasionally minor classlib changes make their way in. In this case there is a change to:
- `Collection:-plotHisto` - correct the range to include full last bin, add labels
(Feedback is welcome on this approach to random/minor fixes.)
- Bug fix

Docs: misc updates and formatting

---

SCClassLibrary/Common/Streams/Rest.sc

Rest asEvent returns Event.silent fixing #5853

---

server/plugins/IOUGens.cpp

Fixes the `OffsetOut_Ctor` is with supernova mentioned in #5899
- Bug fix

fix OffsetOut_Ctor

---

CHANGELOG.md
HelpSource/Guides/News-3_13.schelp
HelpSource/Help.schelp

This is based off of a list of PRs between the 3.12.2 release and the tip of the `develop` branch and combined with some [notes I've taken](https://github.com/supercollider/supercollider/wiki/3.13-Changelog-notes) while reviewing recent PRs. Please give it a read-through and make suggestions.
The URLs were automatically generated (I used a GH feature to automatically generate release notes when drafting a release) so I left them as is instead of converting them to proper markdown links. On GH websites they are rendered as short links (#PR_NUMBER) anyway.
<details>
</details>
Most of the messaging is rather dry and the list is somewhat flat. Most items are in mostly chronological order. I'd be grateful for any advice how to make the more important messages stick out.

Update CHANGELOG.md for 3.13.0-rc1

---

SCVersion.txt

Update SCVersion.txt for 3.14-0-dev (develop branch)

---

SCClassLibrary/Common/Control/Buffer.sc

class library: *cueSoundFile keeps path

---

SCVersion.txt

Update SCVersion.txt for 3.13.0-rc2

---

CHANGELOG.md
HelpSource/Guides/News-3_13.schelp

This PR updates `CHANGELOG.md` and `News-3_13.schelp` with changes since 3.13.0-rc1.

Update the Changelogs for 3.13.0-rc2

---

README_LINUX.md

I've recently tested building on Fedora 34 and I'd like to write document the package names I had to install in order to build SC. I might've missed something, but this should get people much closer than no information.
I'm intentionally pointing it at 3.13, so that it makes it to the release tarball.

LINUX_README.md: add information for Fedora

---

testsuite/classlibrary/TestNodeProxy.sc

Just a test for an ambiguous situation.

test: proxy as source should be initialised by receiver

---

SCClassLibrary/Common/Streams/Stream.sc

this removes inline warnings
Note: as a developer, please set:
```supercollider
LanguageConfig.postInlineWarnings = true;
```
- Bug fix

removes inline warnings

---

SCClassLibrary/Platform/windows/WindowsPlatform.sc

Fixes #2719
I tried booting the server in SC IDE, as well as command line (started from a non-resourceDir directory) and it seems to work fine.
Please test on Windows before approving.
- Bug fix
~~- [ ] Updated documentation~~

classlib: find server program on Windows

---

SCClassLibrary/Common/Audio/Trig.sc

mark ToggleFF explicitly as unipolar

---

HelpSource/Classes/Pfunc.schelp

Pfunc only works with values but the documentation does mention how to return a pattern, that is Plazy

Pfunc doc should reference Plazy for returning patterns

---

HelpSource/Classes/UnitTest.schelp

fix #5541
- [ x] Code is tested
- [ x] All tests are passing
- [ x] Updated documentation
- [ x] This PR is ready for review

fixed UnitTest help example 

---

HelpSource/Classes/DiskIn.schelp
HelpSource/Classes/DiskOut.schelp

Only to make it easier for users to find VDiskIn.
- ~~[ ] Code is tested~~
- ~~[ ] All tests are passing~~

Help: DiskIn/Out should link also to VDiskIn

---

.gitignore

Would it be okay to ignore config files created by Visual Studio Code?

Ignore vscode files

---

.github/workflows/actions.yml

`ccache` was updated in chocolatey past version 4.8, which did not work properly for MSVC, so we can un-pin the version now.
- Bug fix
- ~~Updated documentation~~ n/a

GHA: update ccache on Windows

---

HelpSource/Classes/LFGauss.schelp

Add clarifications, formatting and generally clean up `LFGauss` descriptions and examples.

docs: LFGauss: clarify, format, add links, cleanup

---

HelpSource/Classes/StackNumberAllocator.schelp

Documenting an undovumented class. 
missing documentation

Docs -> StackNumberAllocator (new file)

---

HelpSource/Classes/Char.schelp

Documenting some minor methods in class `Char`

DOC: Topic/char documentation

---

HelpSource/Classes/Env.schelp

This improves formatting adds and clarifies examples to the `Env` help page. In particular wrt the looping functionality.

docs: Env: clarify, format, make looping example more explanatory

---

HelpSource/Classes/CombC.schelp

CombC.schelp typo (missing white space)

---

lang/LangSource/PyrSched.h

Change `lockLanguageOrQuit` to use `std::atomic<bool> const&`
Modified the `lockLanguageOrQuit` function in PyrSched.h to take a constant reference to std::atomic<bool>. 
The actual problem was that the function took the atomic flag by value instead of by reference. This made the repeated checks entirely redundant and as a consequence it would not notice when the flag has changed in between, undermining the very purpose of this function.

Add atomic bool const to lockLanguageOrQuit in PyrSched.h

---

HelpSource/Classes/HLayout.schelp
HelpSource/Classes/LineLayout.schelp
HelpSource/Classes/VLayout.schelp
HelpSource/Guides/GUI-Layout-Management.schelp

This adds some links, comments, and examples to the LineLayout related help files. In particular this addresses the absence of a ScrollView related example.

LineLayout related doc improvements

---

HelpSource/Classes/PV_ChainUGen.schelp

fix typo in PV_ChainUGen.schelp

docs: fix PV_ChainUGen typo

---

HelpSource/Classes/RingNumberAllocator.schelp

DOC: RingNumberAllocator

---

SCClassLibrary/Common/Audio/Splay.sc

normalize spread in SplayAz

---

SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
testsuite/classlibrary/TestNodeProxy.sc

class library: fix buildProxy

---

HelpSource/Classes/Ndef.schelp
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc

class library: in Ndef, call proxyspace dispatch explicitly

---

HelpSource/Classes/Buffer.schelp

This is a trivial documentation style change to illustrate the PR process for a tutorial. So I might as well submit it :)

Docs: Buffer: code style update

---

.github/workflows/actions.yml
README_MACOS.md

Potential fix for Github action build errors.
- Bug fix

github: update homebrew qt version specifier

---

SCClassLibrary/Common/Audio/SystemSynthDefs.sc
SCClassLibrary/Common/Control/Score.sc

This will allow to send them to an NRT server
Fixes #5967 
- New feature

class library: keep SystemSynthDefs in dictionary

---

HelpSource/Overviews/MidiPatterns.schelp

```
[Streams-Events-Patterns](javascript:GotoPath("Streams-Events-Patterns")) (1)
[Streams-Patterns-Events](javascript:GotoPath("Streams-Patterns-Events")) (165)
```
Let's be consistent.

Help: Correct categories for pattern vs MIDI help file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

The contributing.md file hasn't existed for a while, it is now on the wiki.
Makes some of the wording a little more explicit to hopefully improve the quality of the bug reports.
- gh issues/pr templates

GitHubIssue/PR Templates: update link and make wording more explicit.

---

.github/workflows/actions.yml

The current build process generates some warnings by using outdated GH actions - this PR upgrades the actions from `v3` to `v4`. The  currently used`v3` version [will be deprecated in a few months](https://github.com/actions/upload-artifact/tree/v4/?tab=readme-ov-file#actionsupload-artifact).
See also https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
Maybe it would be a good idea to let a dependabot watch over this - I could set this up.
- Bug fix

Bump GH actions to node 20 versions

---

HelpSource/Classes/Dictionary.schelp
testsuite/classlibrary/TestDictionary.sc

This adjusts the tests and documentation to the change in trueAt / falseAt, see #6001 
- Tests

adjust trueAt/falseAt documentation and tests to change of behaviour

---

HelpSource/Classes/SoundFile.schelp
SCClassLibrary/Common/Files/SoundFile.sc

Quality of life for writing multichannel sound files.
- New feature

SCClassLib make SoundFile easier write multichannel files.

---

.github/workflows/actions.yml
.github/workflows/test_linux.yml
.github/workflows/test_macos.yml
.github/workflows/test_windows.yml

In a similar way to #6354 this PR splits the `test` step in separate reusable workflows for each platform.
I also renamed some existing steps for clarity.

Split test step in multiple reusable workflows

---

include/plugin_interface/SC_SndBuf.h
server/supernova/dsp_thread_queue/dsp_thread_queue.hpp

- Update nova-tt to get bug fix for `nova::detail::pause`.
- Improve `rw_spinlock::pause` function in `SC_SndBuf.h` (add support for MSVC and ARM platforms)
- Supernova: avoid division by zero in back off calibration
Fixes https://github.com/supercollider/supercollider/issues/5899.
- Bug fix

Supernova fix

---

testsuite/scripts/test_run_proto_gha.scd

Our CI has been broken for a few weeks due to an RTAlloc test. Since no one has come up with a fix yet (see #6410), and since this breaks the CI and thus any further PRs, I'd suggest disabling this test for now. 
- Bug fix (well, not really...)

Disable RTAlloc test in CI

---

HelpSource/Classes/UGen.schelp

Help file spacing fix

---

HelpSource/Classes/Object.schelp

Add documentation for `performArgs`.

Help: add performArgs entry.

---

CMakeLists.txt
common/SC_PaUtils.cpp
server/scsynth/CMakeLists.txt

fixes https://github.com/supercollider/supercollider/issues/6435
Please merge ASAP :)

Fix for GCC 14

---

testsuite/classlibrary/TestCoreUGens.sc

Reduces time from around 25 seconds to around 2 seconds by removed random wait time and lower the rendered time from 0.1 seconds to 0.01 seconds.
Please review if the random time or the longer length is actually necessary here. Tests still seem to run.
https://github.com/supercollider/supercollider/actions/runs/10687826107/job/29626830696?pr=6441#step:7:5528
```
TestCoreUGens:test_muladd (2.73s)
```
https://github.com/supercollider/supercollider/actions/runs/10681804483/job/29606801735#step:7:5529
```
TestCoreUGens:test_muladd (25.4s)
```
- Bug fix
- Performance fix

Speed up CoreUGens muladd test

---

testsuite/classlibrary/TestCoreUGens.sc

In many unit tests, wait times are ad hoc, which accumulates quite a bit of time when lots of tests are run. This also points to uncertainties about how the tests are scheduled and run.
This PR tries to make the logic more strict and rational, and effectively reduces the run time from ~115 sec to ~45 sec. The “test on x” CI jobs take between 13-15 minutes for each of Mac and Linux tests. So if this approach is robust, it may be able to be applied to tests more broadly.
Improvements so far:
- add a `classvar` to have a default number of blocks to run for tests. Defaults to 10 blocks. (It’s still up to the test author to use this variable.)
- The largest improvement comes from revising the `wait` scheme
- Removed random wait times.
- Rely on `server.sync` to throttle looping during …

Testsuite: Speed up CoreUGens tests

---

.github/workflows/build_macos.yml

Verifying the build seems to work again. The original issue was likely due to inconsistencies with cached "universal" brew packages.
Reverts #6358
- Bug fix

gha: macos: verify the build

---

.github/workflows/actions.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml

We need to update the build matrix for the upcoming Qt updates that I'm planning to submit.
I loosely followed our [toolchain support documentation](https://github.com/supercollider/supercollider/wiki/Platform-Support#toolchains) and included the last 4 versions of GCC and Clang, plus additionally the oldest versions that still work without issues.
I wanted to submit GHA changes separately, also including GHA commits from #6331, so that Qt updates don't need to wait for the other PR to be merged.
Note: this update includes entries for clang 16, 17, 18, but these builds currently fail due to outdated boost. I left them in, but they are commented out and should be enabled once we update boost (I believe that's the same issue as #6224 on macOS).
Also note: I wanted to update the test runner …

GHA: update build matrix

---

server/supernova/sc/sc_osc_handler.cpp

https://github.com/supercollider/supercollider/pull/6467 was merged with a formatting error. This fixes the issue.
- Bug fix
- New feature

Fix formatting of `sc_osc_handler.cpp`

---

.github/workflows/actions.yml

This should remove the warning in GHA about the action `cache@v3` and deprecated node.js version.
BTW, the [readme of the pre-commit action](https://github.com/pre-commit/action) says it's in maintenance mode... Does it mean it might need to be replaced at some point?
- Maintenance

GHA: update pre-commit action

---

.github/workflows/build_macos.yml

I updated the script for creating "universal" homebrew binaries, fixing some bugs...
I removed the HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK variable, as things should now work without it. This will remove many of the warnings posted underneath the build actions.
Note: this may or may not help with recent build failures on macOS.
EDIT: I'm not certain how solid this fix is, but it does seem that installing all the libraries in homebrew first and enabling dependents checking resulted in a properly finished and linked build.
We might be also hitting against stopping support in homebrew for macOS 12 - when running `brew update` (which this PR does NOT currently add), we get messages that it's not supported anymore, see the [build job here](https://github.com/supercollider/supercollider/actions/r …

GHA: macOS: update universal script

---

testsuite/classlibrary/TestUGen_RTAlloc.sc
testsuite/scripts/test_run_proto_gha.scd

Fixes #6410 
These tests are meant as an exhaustive (as much as possible) coverage of UGens using RTAlloc. They have been failing more or less unpredictably and got recently disabled (https://github.com/supercollider/supercollider/pull/6429).
I'm working on it to hopefully get these tests back, and I'm mainly making this PR to test on CI (if anyone knows a better method, please let me know!).
Refactoring and trying to make CI pass for these tests, especially the test_allUGens ones:
- refactored away async logic, hopefully it gets a bit more readable now
- changed strategy: instead of filling RT memory with a LocalBuf, we try to make each UGen fail by itself by allocating too much memory
And if anyone has any better idea to test RTAlloc pass/fail behavior, that would be welcome as well! …

testsuite: RTAlloc refactor and fix

---

testsuite/classlibrary/TestBus.sc

`TestBus.test_controlFree` is slow. This reduces the number of control busses on the server to make this test faster. 
Reason being that since the logic does not depend on size, it can be small.
```
Old : time to run: 8.9728592389997 seconds.
New : time to run: 0.0006905000000188 seconds.
```
A part of #6439.
- Performance

UnitTest, TestBus: improve performance, reduce number of control busses.

---

.editorconfig

The curly braces are mismatched. I believe this was a typo? I found it because my editor complained about it. 
NOTE: I'm not sure if this change will affect our linting behavior.
- Bug fix

correct .editorconfig syntax

---

README.md
README_LINUX.md
README_MACOS.md
README_WINDOWS.md

[qt6] update project docs

---

testsuite/scripts/print_results.scd

Fixes #6432
This is how failures now look:
```
[-]	<last test without error/result>
Failed tests:
[0/1]	<failed test group> (0.0s)
! <failed test>
----------------------------------------
1 TESTS FAILED, 44 skipped, out of 4361
----------------------------------------
```
See it in action [here](https://github.com/dyfer/supercollider/actions/runs/11509043278/job/32038532293) and [here](https://github.com/dyfer/supercollider/actions/runs/11509043278/job/32038808388) (I updated the number of dashes `----` since these jobs were run)

List failed tests before the results

---

HelpSource/Guides/GUI-Introduction.schelp

fix typos in Introduction to GUI

docs: fix GUI Intro typos

---

.github/workflows/actions.yml
.github/workflows/test_linux.yml
.github/workflows/test_macos.yml
.github/workflows/test_windows.yml

When I was updating test jobs, I found it cumbersome to have to modify the artifact name in a different file than the test job itself. I think the proposed change is cleaner to maintain.
If others don't like it I won't push for it, but this would be my preference.
- Maintenance

GHA workflow: move the definition of artifacts

---

.github/workflows/lint_non_code.yml

Currently the CI only runs when
https://github.com/supercollider/supercollider/blob/e49e42cbf42be6dc9ff4806cf14ff9b9d14e0bb5/.github/workflows/actions.yml#L1-L14
Though we may want to also run linting checks on these ignored files, see e.g. #6346 which would introduce such checks and #6451 which could benefit from such checks. If we enforce checks via pre-commit which are not checked in CI, this can cause a failing pre-commit to propagate once we actually run the check on these files. As pre-commit is quite lightweight, it should be run every time.
__UPDATE__: Instead of running an additional lint workflow every time I simply added a new workflow which runs on the files we normally ignore, see https://github.com/capital-G/supercollider/actions/runs/12206666964/job/34056591335 of a test …

Dedicated lint workflow to verify all files in CI

---

CHANGELOG.md
HelpSource/Guides/News-3_13.schelp
SCVersion.txt

This post will be kept up to date to reflect the state of the PR
Implements https://github.com/supercollider/supercollider/issues/6547 by cherry picking https://github.com/supercollider/supercollider/commit/5e6bf9bdf93e5070e7ec60fcacc32dee67cfd9eb onto the 3.13 branch.
~~IIUC (https://github.com/supercollider/supercollider/wiki/Releasing-cycle-and-process) it would be best if this PR also implements the version upgrade to `3.13.1-rc1`, so this would still need to be done/discussed.~~ => This PR also includes all necessary version bumps and changelogs according to https://github.com/supercollider/supercollider/wiki/Releasing-cycle-and-process
This branch should be merged into the `3.13` branch and afterwards tagged as `version-3.13.1-rc1`.
If after some more testing everything seems fine, …

Patch 3.13 release with hidapi update

---

.github/workflows/actions.yml

See https://github.com/supercollider/supercollider.github.io/issues/285
PR for website which should be merged after this PR has been merged: https://github.com/supercollider/supercollider.github.io/pull/286
Please double-check the CI changes - they only run on main/develop and we should not use those branches for CI debugging :)
- New feature

Add macOS arm nightly build upload to s3

---

HelpSource/Classes/UGen.schelp

Fix typo, see https://github.com/supercollider/supercollider/pull/6595#issuecomment-2613711989

help: fix typo

---

HelpSource/Classes/Buffer.schelp
HelpSource/Classes/EZNumber.schelp
HelpSource/Classes/Klank.schelp
HelpSource/Classes/Pair.schelp
HelpSource/Classes/Pdef.schelp
HelpSource/Classes/Quarks.schelp
HelpSource/Classes/SCEnvelopeEdit.schelp
HelpSource/Classes/Stethoscope.schelp
HelpSource/Guides/News-3_12.schelp
HelpSource/Guides/Sync-Async.schelp
HelpSource/Reference/Control-Structures.schelp
HelpSource/Tutorials/Getting-Started/11-Busses.schelp

- Correction of typos in some schelp.
- The style of writing tag and adding space and/or empty line follows the style in paragraph.
This is part of #6534 and contains some typo corrections to the schelp files.
1. `Traverse` in line 34 should be 'method: traverse':
https://github.com/supercollider/supercollider/blob/a4ffd92d88e4f89d426318ac35b21ad12bd8a11f/HelpSource/Classes/Pair.schelp#L30-L36
2. `valueAction` on line 109 should be `method::valueAction`:
https://github.com/supercollider/supercollider/blob/a4ffd92d88e4f89d426318ac35b21ad12bd8a11f/HelpSource/Classes/EZNumber.schelp#L103-L114
3. `embedInStream` on line168 should be `method:: embedInStream`:
https://github.com/supercollider/supercollider/blob/a4ffd92d88e4f89d426318ac35b21ad12bd8a11f/HelpSource/Classes/Pdef.schelp#L165-L171
4. …

Correct typos.

---

HelpSource/Classes/BufRd.schelp
HelpSource/Classes/DelTapRd.schelp

Primarily to get a hang of the contribution workflow ("my first PR"). 
(EDIT: now I notice I accidentally added empty lines after the explanatory note, so I guess now I gotta learn how to modify PRs or ... whatever it is that I need to do. I thought I could just add another commit on top of the existing ones and then add it to the PR (or even not), or amend the previous commits. But both of these things don't seem to work, for reasons I don't fully understand; can't seem to push this new commit to my fork. I'll call it quits today but would appreciate guidance...).
As concerns the documentation: 
Clarify that the choice of 1,2,4 for the interpolation arg is intentional, and why.  
This confused me at one point, I thought it was a typo, as 1,2,3 would have seemed more intuitive; 
but then …

docs: BufRd, DelTapRd: interpolation argument: explanatory note

---

HelpSource/Classes/BusPlug.schelp
HelpSource/Classes/Float.schelp
HelpSource/Classes/Number.schelp

typo correction and match style

typo correction and match style

---

SCClassLibrary/Common/Core/Function.sc

This restores a fix from #6200, which was mistakenly reverted by #6217.
- Bug fix
- [ - ] Updated documentation

classlib: Function:-asBuffer restore doneAction via RecordBuf

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

See #6566. Tested with all multichannel examples from Env.help.

class library: fix regression from "more tolerant plot"

---

testsuite/classlibrary/TestLcmGcd.sc

Add test for fundamental theorem of arithmetic.
This is an important property of gcd and lcm, make sure it passes.
- Bug fix
- New feature

tests: add test in lcm/gcd

---

HelpSource/Classes/Download.schelp

Coses #6637
The example codes in Download.schelp do not work on all platforms, and the URL for the first example is broken.
See #6637 for details.
This PR fixes both of these issues.

Fix the example codes in Download.schelp

---

HelpSource/Guides/WritingUGens.schelp

doc fix:
fixed em-dashes, spaces, and updated URLs to https://... in "WritingUGens.schelp"

docs: fix em dash, typo, update urls to https

---

HelpSource/Classes/SequenceableCollection.schelp
SCClassLibrary/Common/Collections/SequenceableCollection.sc

After a longer discussion, here:
https://scsynth.org/t/choosing-how-to-choose-with-self-normalising-weights/9557/69?u=julian
this is a proposal.
Thanks [Asmatzaile](https://github.com/Asmatzaile) for proposing this direction.
- New feature

class library: wchoosen implementation

---

HelpSource/Classes/Collection.schelp

- Change explanation for sum with KaTex
- Add explanation for mean with KaTex
While finding average method for Array, I feel the documentation is missing and not so friendly to find the method with use case:
https://github.com/supercollider/supercollider/issues/6533#issuecomment-2477595224
- [] This PR is ready for review 
#6534 should be approved.

Add/Modify Explanation for .sum, .product and .mean in Collection Documentation with KaTex

---

include/plugin_interface/SC_InlineUnaryOp.h
testsuite/classlibrary/TestSimpleNumber.sc

Based on the discussion in #5016 I think this is an innocuous change, but please review carefully.
Fixes #5016. 
- Bug fix
- ~~[ ] Updated documentation - should this be noted in the docs? I think not, but I'm open to suggestions.~~

InlineUnaryOp.h: increase precision of constants

---

external_libraries/CMakeLists.txt

~~Update yaml-cpp to version 0.8.0 (tag `0.8.0`) _using the [upstream yaml-cpp repo](https://github.com/jbeder/yaml-cpp)_.~~
~~The underlying reason for this is not an update in functionality, but in CMake. This PR is a partial fix for #6696 (fixes building on Linux).~~
~~Note: **This PR changes the submodule URL to use the upstream version instead of the supercollider-hosted fork**. I don't see the reason for us to host [our own fork](https://github.com/supercollider/yaml-cpp), as it doesn't have any custom changes on it. I propose that we use the upstream repository as the submodule and that we archive our fork if this PR gets merged.~~
~~We will need to run **`git submodule sync`** in order to update our local repositories afterwards.~~
EDIT: This PR now only adds a cmake 4 workaround. …

Patch yaml-cpp for cmake 4

---

HelpSource/Classes/Collection.schelp

Collection.schelp: tweak wording

---

SCClassLibrary/Common/Audio/Line.sc
SCClassLibrary/Common/Audio/Trig.sc

Fixes #5547, #4261
Added checkSameRateAsFirstInput to InRange and added checkValidInputs to AmpComp
- Bug fix

Add checkSameRateAsFirstInput to InRange and checkValidInputs to AmpComp

---

README.md

Was doing some backtracking and saw that the links to the mailing list archives seem to have changed—they time out. Found up-to-date links on Google.
I also went ahead and removed the link to the list sign-up, since it, as expected, 404s.
- Documentation (README.md)

 Update mailing list links in README

---

testsuite/classlibrary/TestServer_clientID_booted.sc

Like with .quitSync, we should wait for the scsynth to exit before continuing with the tests.
- Bug fix (?)

TestServer_clientID_booted: wait for the process to exit

---

lang/LangSource/PyrMessage.cpp
testsuite/classlibrary/TestUniqueMethod.sc

Closes #6745 — a regression in unique methods.
Also adds tests to ensure this feature is not broken again.
- Bug fix

sclang: fix unique method regression and rename variables to something useful

---

HelpSource/Classes/GrayNoise.schelp

closes #6718
@HotwheelsSisyphus: Thank you for your kind and detailed instructions, including the mathematical explanation and code example.

Topic/schelp add gray noise explanation & example

---

HelpSource/Classes/PathName.schelp
HelpSource/Classes/String.schelp

Caught a few references to hardcoded '/tmp' path.
EDIT: also corrected a typo.

help: replace "/tmp" with Platform.defaultTempDir

---

.github/workflows/build_macos.yml
.github/workflows/build_windows.yml

It seems that v3 of the action generates a number of warnings like [this one](https://github.com/supercollider/supercollider/actions/runs/14680976191/job/41203592477#step:12:100). Additionally, it appears to take extra time because of trying and failing to save cache.
An update ~~should fix~~ fixes it.
- Bug fix

GHA: update jurplel/install-qt-action to v4

---

.gitignore

I was experimenting with clangd and it creates cache files, which would be good to ignore.
I added this before the .vscode ignores in order to not create a conflict with #6351, but I'm not sure if it'll work that way. Maybe this should wait for #6351 to be merged first...

git: ignore clangd cache

---

lang/LangPrimSource/SC_ComPort.cpp
server/scsynth/SC_ComPort.cpp

The fix is based off of @jamshark70's [comment in a linked PR](https://github.com/supercollider/supercollider/issues/4352#issuecomment-471115447).
This might silence errors listed in the linked PRs. Needs testing **on Windows**, where these issues were reported.
EDIT: I also added the error to be silenced in an analogous place in scsynth. I don't see a similar mechanism in supernova though.
- Bug fix

lang: silence more UDP errors

---

HelpSource/Help.schelp

Fixes regression due to combined efforts of #6751 and #6141 
Also changed/modified surrounding `\n` to keep every sentence in its dedicated LOC.

Replace beagle with bela in start help file

---

HelpSource/themes/monokai.css
editors/sc-ide/core/settings/default_themes.cpp

Minor improvements, making the theme more consistent with other editors which support the monokai theme.
- Bug fix

Minor improvements for monokai theme

---

.github/workflows/test_linux.yml
.github/workflows/test_macos.yml

This is a small script simplification enabled by #6640
- Maintenance

GHA: use --include-path in the testsuite

---

editors/sc-ide/widgets/audio_status_box.cpp
editors/sc-ide/widgets/audio_status_box.hpp
editors/sc-ide/widgets/lang_status_box.cpp
editors/sc-ide/widgets/lang_status_box.hpp

A friend asking "why is the status bar not following the theme" resulted in a small hackathon this evening...
Old style
New idle
New boot
New booted
New on Monokai theme
- New feature

Make status bar themed

---

HelpSource/static/scdoc.css

Fixes https://github.com/supercollider/supercollider/issues/6861 which is a regression of #6627
- Bug fix

Fix classtree image path

---

HelpSource/Overviews/Classes.html

Fixes https://github.com/supercollider/supercollider/issues/6859 which is a regression of #6627
Thanks @prko for reporting! :)
- Bug fix

Fix docmap link for classes overview

---

HelpSource/Classes/Peak.schelp

Clarification of the behavior of `Peak`.
Follow up on discussion here: https://github.com/supercollider/supercollider/pull/6816#issuecomment-2870531617.
Aside: I used this as an experiment to try making the change from the GitHub interface... I see it creates a branch not on my fork but the origin repo, which I know isn't ideal, so I'll be sure to clean up that branch.

Help: Peak - clarify description

---

SCClassLibrary/Common/Collections/windows/extString_windows.sc

Fixes #6312. Code designed by @Spacechild1. Thank you!
Fixes https://github.com/supercollider/supercollider/issues/6312. Code designed by @Spacechild1. Thank you!
- Bug fix

Correct openOS behaviour on Windows

---

HelpSource/static/scdoc.css
HelpSource/static/scdoc.js
SCClassLibrary/Common/GUI/tools/HelpBrowser.sc
SCClassLibrary/SCDoc/SCDoc.sc
SCClassLibrary/SCDoc/SCDocRenderer.sc
editors/sc-ide/widgets/help_browser.cpp

Dear SC  devs,
Here is my refactored PR, based on my earlier one ( #6168 ).
I had to revisit the topic with a fresh perspective due to the new theme system that emerged in the meantime.
Everything should work as expected — exactly as discussed in  #6168 .
It also behaves correctly when switching themes: the icon colors adapt based on the active theme.
Apologies for submitting a completely new PR — I’m closing the old one.
Thanks!

Copy icons in schelp examples

---

server/scsynth/SC_CoreAudio.cpp

A common setup on macOS is to use built-in speakers and built-in mic. These devices may be set to different sample rates.
Instead of bailing out on such configuration, let's try to actually set the input to match the output.
EDIT: now we additionally **check if the input device is already open**, and if it is, we post an error with a slightly different error message instead of changing its sample rate and then exit. This should prevent the accidental interruption of e.g. recording happening in the background, while still provide the desired functionality when no audio capture is running.
To test:
- (quit the server)
- in Audio MIDI Setup set built-in mic and built-in output as default audio devices
- in Audio MIDI Setup set built-in mic to a _different_ sample rate than the output
- start …

CoreAudio: try setting sample rate of output device when input and output sample rates are mismatched

---

HelpSource/static/codemirror.css
HelpSource/static/editor.js
HelpSource/static/scdoc.js

merge note: squash on merge
Supersedes #6207 with a simpler implementation. Please review and test @prko :)
w/o line numbers (default)
w/ line numbers
Not the most beautiful implementation, but the docs template will hopefully be rewritten soon though^^
- New feature

Add line number switch to SCDoc theme settings

---

lang/LangPrimSource/PyrPrimitive.cpp

Adds a little helper for reallocstack as most of the time you want to append something to the stack and calculating all the offsets is error prone.
Also applies this in objectPerformArgsImpl, where I had missed this causing a segfault.
```supercollider
2.performArgs(\pow, {1.0.rand}!2048, [])
```
- Helper method
- Bug fix

sclang: add helper for reallocstack and correct objectPerformArgsImpl

---

SCClassLibrary/Common/Collections/Dictionary.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Core/Error.sc
SCClassLibrary/SCDoc/SCDoc.sc
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/PyrParseNode.cpp
lang/LangSource/PyrParseNode.h
testsuite/classlibrary/TestCollection.sc
testsuite/classlibrary/TestNoUninlinedFunctions.sc
testsuite/classlibrary/TestUGen_RTAlloc.sc

Uninlined functions are slow, don't use them in the class library. From now on, if you do, you will break this test.
Closes #1926
Closes #6889
- new test

sclang, unittest: assert no uninlined functions in class lib.

---

HelpSource/Classes/SimpleNumber.schelp
HelpSource/Overviews/Operators.schelp

updates SimpleNumber and Operators docs. the randomness guide seems a bit haphazard so i didn't touch it.
documentation is good

clarify documentation for randomness methods

---

platform/linux/online.supercollider.SuperCollider.metainfo.xml

Add Version-3.14.0 tag to flatpak metainfo

---

SCVersion.txt

Update SCVersion.txt to 3.14.0-rc1

---

CHANGELOG.md
HelpSource/Guides/News-3_14.schelp
HelpSource/Help.schelp

add changelog for 3.14

---

CHANGELOG.md
HelpSource/Guides/News-3_14.schelp

Minor typo.
I think this should target the 3.14 branch which will then later be merged w/ dev again? If this would be merged onto develop there wouldn't be a way to get this into 3.14 again? (But this will also add the additional merge commits again which we don't want? - maybe we need to cherry pick here?)
Should be merged by @dyfer who is most familiar w/ the release process.
- Bug fix

Fix typo in the 3.14 changelog

---

HelpSource/Help.schelp

Improve layout and structure of help.schelp

---

HelpSource/Guides/News-3_14.schelp

fix changed doc

---

HelpSource/Classes/Document.schelp
HelpSource/Classes/Platform.schelp
HelpSource/Classes/Routine.schelp
HelpSource/Guides/Internal-Snooping.schelp

Remove some use of SCWindow and SCButton from the documentation code

---

SCClassLibrary/Common/GUI/PlusGUI/Control/NodeTreeView.sc

#6294 introduces the following error
```
ERROR: Message 'view' not understood.
Perhaps you misspelled 'asView', or meant to call 'view' on another receiver?
RECEIVER:
Instance of View {    (00000298416839C8, gc=F4, fmt=00, flg=00, set=06)
instance variables [34]
qObject : RawPointer 000002983DF33270
finalizer : instance of Finalizer (00000298420542F8, size=2, set=1)
virtualSlots : nil
wasRemoved : false
font : nil
resize : Integer 1
alpha : Float 1.000000   00000000 3FF00000
decorator : nil
layout : nil
userCanClose : true
deleteOnClose : true
action : nil
mouseDownAction : nil
mouseUpAction : nil
mouseEnterAction : nil
mouseLeaveAction : nil
mouseMoveAction : nil
mouseOverAction : nil
mouseWheelAction : nil
keyDownAction : nil
keyUpAction : nil
keyModifiersChangedAction : nil
keyTyped : …
```

NodePlotView: fix a bug &  add scroll to view parent

---

HelpSource/Classes/Document.schelp

Remove unsupported methods from Document.schelp code examples to reduce the errors

Remove unsupported methods from Document.schelp code examples

---

HelpSource/Classes/UnitTest.schelp

A space was missing in the help file. 
HelpFile improvements

help: UnitTest: fix typo

---

.github/workflows/build_macos.yml

GHA: separate uninstall hombrew packages

---

.github/workflows/build_linux.yml

This should speed up our linux pipeline by using every available core.
Currently these are 4 (see https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) but this may change - with this we should scale dynamically according to our environment.
- New feature

GHA: use all cores on linux build

---

HelpSource/Classes/Function.schelp
HelpSource/Classes/IdentityDictionary.schelp
HelpSource/Guides/ObjectPrototyping.schelp
HelpSource/Guides/WritingClasses.schelp
HelpSource/Reference/Functions.schelp

Adds a guide explaining object prototyping using IdentityDictionary.
Expands the documentation for IdentityDictionary and Functions to include information about its usage in object prototyping and variable arguments.
Clarifies class writing documentation, including newCopyArgs and init methods.

Help: update guides to reflect kwargs.

---

HelpSource/Guides/Tour-of-Special-Functions.schelp

Various fixes and tweaks to the Tour or Special Functions Guide.
Bug fix: an error in the bounds of Elliptic Integrals is now fixed.
Formatting updates:
- update code to conform to style guidelines
- track plot palette globally to retain user selection on new plots
- update some plotting bounds, fixing error in elliptic integrals and for clarity others
- plot fewer series in some cases for speed
- switch text labels to monospace font
- Bug fix

Guide: Special functions: correct bounds, code formatting, appearance

---

README_MACOS.md

clarify build instructions with qt5 on macOS (#7025)

---

CHANGELOG.md

improve wasapi line on markdown changelog as well

---

HelpSource/Classes/Fdef.schelp
HelpSource/Classes/Function.schelp
HelpSource/Classes/FunctionDef.schelp
HelpSource/Classes/Maybe.schelp
HelpSource/Classes/Object.schelp
HelpSource/Classes/Pbind.schelp

There was still some documentation missing for the new keyword argument collection.

help: kwargs

---

HelpSource/Guides/News-3_14.schelp

Correct typo in `News in SuperCollider version 3.14`

---

HelpSource/Classes/Window.schelp
SCClassLibrary/Common/GUI/Base/QWindow.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/FreqScope.sc
SCClassLibrary/Common/GUI/tools/ServerMeter.sc

Adjust the bottom position of the FreqScope and the bottom position of the ServerMeter for all platforms (a clean PR)

---

common/SC_PaUtils.cpp

It seems that #6994 introduced an issue: when WASAPI device is not present/available, but ASIO is, ASIO was not selected by default anymore. See https://github.com/supercollider/supercollider/pull/6994#issuecomment-3079941850
- Bug fix

Fix default device selection on Windows when no WASAPI devices are available

---

SCVersion.txt

Update SCVersion.txt to 3.14.0-rc3

---

CHANGELOG.md
HelpSource/Guides/News-3_14.schelp

Add changelog for 3.14.0-rc3

---

CHANGELOG.md
HelpSource/Guides/News-3_13.schelp

Merge 3.14 to main
