supercollider/supercollider

server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_plugin_interface.cpp
server/supernova/sc/sc_plugin_interface.hpp

This PR tries to achieve deterministic message ordering for asynchronous commands on Supernova. For more background, see: https://github.com/supercollider/supercollider/issues/4424
It makes sure that `/done` messages are *always* sent to the `io_interpreter` so that
a) `/synced` will always arrive *after* `/done` and 
b) replies from synchronous completion messages will always arrive *before* `/done`.

Supernova OSC message ordering

---

HelpSource/Tutorials/A-Practical-Guide/PG_Cookbook05_Using_Samples.schelp

A forum question revealed that the discussion of sample looping in the Pattern Guide is unclear. It uses a "magic number" for tempo, without explaining how to derive it.
The discussion was also incomplete -- no information about how to adjust to a different playback tempo.
Remedied by splitting the procedure up into three steps.

Help: Pattern Guide: Better explanation of loop sample tempo handling

---

QtCollider/widgets/QcWebView.cpp

This PR fixes an error message that is posted when opening `HelpBrowser.instance` in command line sclang.
```
QObject::connect: No such slot QtCollider::WebView::onRenderProcessTerminated(RenderProcessTerminationStatus, int)
```
~Adding a new SLOT called `onRenderProcessTerminated` to the  `WebPage` class seems to fix this. I've also specified that this SIGNAL and corresponding SLOT take a `QWebEnginePage::RenderProcessTerminationStatus` as first argument.~
@jrsurge posted a proper fix in his [comment](https://github.com/supercollider/supercollider/pull/4488#pullrequestreview-267479404). I've updated the PR accordingly.
~Possibly related to some behaviour mentioned in #4256~ This PR isn't a fix for any specific issue.
- Bug fix

add missing SIGNAL renderProcessTerminated

---

SCClassLibrary/Common/Collections/Dictionary.sc

The `doesNotUnderstand` warning in Dictionary about pre-existing methods contained two grammatical errors:
- At the beginning, `as a` omitted the preposition.
- At the end, `as a` omitted the indefinite article.
No other changes -- just make the warning not sound awkward.
- Bug fix

Classlib: Correct grammar in a Dictionary warning [skip ci]

---

common/SC_Filesystem_unix.cpp
common/SC_StringBuffer.cpp
common/sc_popen.cpp

This continues on from and replaces #4391.
> Currently musl does not support GLOB_TILDE but it is on their roadmap [1]. This
> patch is no fix and changes functionality for musl. A slightly changed
> functionality seems better than being unable to build.
> 
> For glibc and future versions of musl this change is a noop.
> 
> [1] [https://wiki.musl-libc.org/roadmap.html](https://wiki.musl-libc.org/roadmap.html)
Tests 10 (server_test_run) and 16 (perf_counter_test_run) from `make test` fail on my machine but they also fail without these changes.
- Bug fix
- New feature

 Work around build errors on musl libc

---

.travis/before-install-osx.sh

Mea culpa -- I had formerly added this to avoid a really long wait time while homebrew updated on macOS Travis builds, but as pointed out by Christophe and present-day me, we probably want to use the latest version to get any bugfixes. Note however that homebrew auto-update does take a really long time, something like 5 minutes. Would love any info on how to avoid that, since we only ever need these few formulas.
Open to discussion -- it is not a great look to upgrade a major dependency like this between release candidates, but Qt has seemed pretty stable so I'm fine doing this.
- Bug fix

travis: use latest packages on osx

---

HelpSource/Classes/Pbindf.schelp

was: "keys to valueskeys to values"

Fix a typo in description of Pbindf help file

---

HelpSource/Classes/Env.schelp

Removed an extra `p` in `envelope`.
To keep the documentation as awesome as possible :wink: 

Fix typo in Env help file

---

SCClassLibrary/Common/Control/Recorder.sc
testsuite/classlibrary/TestRecorder.sc

Before this fix, recorded file paths would always have extensions according to `s.options.recHeaderFormat`, even if recHeaderFormat of `s.recorder` was different, possibly creating files with wrong extension.
Use Recorder's own `recHeaderFormat` variable when generating the path, which should make sure header format and extension is in sync.
- Bug fix

Fix extension in path generated by Recorder

---

HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp

The tutorial gives `'tutorial-SinOsc'` and `\tutorial-SinOsc` as examples of symbol literals.
The first one is a symbol literal. The second one is really the expression `\tutorial - SinOsc` which evaluates to `\tutorial`.
Backslash symbols should contain only characters that are valid in identifiers: letters, digits and underscore. Hyphen doesn't count.
So this PR simply replaces both with `tutorial_SinOsc`.

Help: Fix incorrect symbol literal in tutorial chapter 10

---

.travis.yml
.travis/before-install-osx.sh
.travis/qpm-prep.sh

to fix build failures with Homebrew
also reorder homebrew installation steps, otherwise ccache isn't
installed properly, not sure why. possibly needs further testing.
Fixes #4621
- Bug fix
I'm not sure what will be affected by switching over to a 10.13 macOS image, but since it seems fairly impossible to use homebrew on macOS 10.12 anymore, I'm not sure we have a choice.

travis: update osx to xcode9.4 [3.10]

---

SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc
testsuite/classlibrary/TestNodeProxyRoles.sc

A change in `EnvGen` (#4060) wasn’t completely fixed in #4114.
This commit fixes #4266.
```supercollider
// some tests
a = NodeProxy.new.play;
a.fadeTime = 4;
a[1] = { Saw.ar ! 2 * 0.1 };
a[2] = \filterIn-> {|sig| Resonz.ar(sig, LFDNoise1.kr(30).range(200, 1900), 0.99) };
a[2] = \filter-> {|sig| Resonz.ar(sig, LFDNoise1.kr(30).range(400, 900), 0.99) };
a[2] = \mix -> {|sig| SinOsc.ar(1230) * 0.02 };
a[2] = nil;
a[1] = nil;
```
- Bug fix

class library: some NodeProxy roles fade in and out correctly again

---

CMakeLists.txt
common/server_shm.hpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp
server/supernova/utilities/osc_server.hpp

See commit messages for details
- Bug fix
- Breaking change  -- boost >= 1.66 is now strictly required by the build system. Technically, this is not true as you don't absolutely need to build sclang to use the project. However, Boost is easy to obtain and this saves headaches later in the common case.

Xcode 11 support

---

QtCollider/QcApplication.cpp
QtCollider/QcApplication.h

Fixes #3824 
Like in PR #4500 the fix consists in adding an `Action` with `QAction::QuitRole` so that this action registers cmd+q on macOS.
I disable this menu action so that Quit menu item is greyed out in the interpreter window.
MainMenu is not affected, it still works, I checked.
- Bug fix

On macOS, register cmd+q on sclang interpreter main menu, solves #3824

---

tools/clang-format.py

see https://github.com/supercollider/supercollider/pull/4379#issuecomment-551161971
also encountered with with @ClareMacrae -- it's probably better in this
situation to be permissive, and restrict later if problems arise.
Checklist
---------

clang-format.py: accept any 8.y.z version

---

tools/clang-format.py

sometimes the output of clang-format's linting operation is an empty string instead of newline
Checklist
---------

clang-format.py: don't consider empty output an error

---

editors/sc-ide/widgets/code_editor/editor.cpp
editors/sc-ide/widgets/code_editor/editor.hpp

Fixes #4133, supersedes #4363. When a GenericCodeEditor is destroyed but a Document refers to it via
mLastActiveEditor, said pointer is dangling and can cause a crash. For
example, creating a split, removing all splits, and then recompiling the
class library can cause a crash.
This commit is a quick bandage, simply setting mLastActiveEditor to a
null pointer in the GenericCodeEditor's destructor. A more thorough
solution would be a stack of the most recently active editors, but the
point is to just prevent an IDE crash right now.
- Bug fix

scide: Fix a dangling pointer when removing splits

---

SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc
testsuite/classlibrary/TestNodeProxy_Server.sc

Fixes  #4506
```supercollider
// test, shouldn't post " FAILURE IN SERVER /s_new duplicate node ID "
Ndef(\y, { |zz| Blip.ar(zz * 5) }).xset(\zz, 2).play;
Ndef(\y, { |zz| Blip.ar(zz * 5) }).xset(\zz, 4).play;
```
- Bug fix

JITLib: fix a duplicate node ID error in NodeProxy:xset

---

QtCollider/primitives/prim_QImage.cpp
QtCollider/primitives/prim_misc.cpp
QtCollider/widgets/QcWindow.cpp
editors/sc-ide/core/doc_manager.cpp
editors/sc-ide/core/sc_introspection.cpp
editors/sc-ide/widgets/code_editor/line_indicator.cpp
editors/sc-ide/widgets/doc_list.cpp
editors/sc-ide/widgets/doc_list.hpp
editors/sc-ide/widgets/main_window.cpp
editors/sc-ide/widgets/main_window.hpp
editors/sc-ide/widgets/multi_editor.cpp
editors/sc-ide/widgets/multi_editor.hpp
editors/sc-ide/widgets/post_window.cpp
editors/sc-ide/widgets/util/icon_list_widget.hpp

Qt has started issuing deprecation warnings - this PR addresses as many of them as possible while maintaining compatibility.
These aren't particularly high priority, but just to get ahead of it where possible.
~~Everything here uses 5.0 compatible fixes.~~
~~For those that need a more recent Qt version, I've added TODO notes with the code to uncomment when the time comes - some things need 5.10, etc. and I wasn't sure we were ready to enforce that.~~
EDIT: Compile-time checks of Qt versions switch in newer code where required.
Commit history outlines the details - most of them relate the use of QSignalMapper, which hasn't been necessary since 5.0 with C++11.
Features affected/to test:
```supercollider
Window.availableBounds; // should be screen size - a bit for toolbars etc …
```

[scide][qtcollider] Fix Qt deprecations

---

tools/cmake_gen/CMakeLists_header.template

Purpose and motivation
-------------------------
This fixes
https://github.com/supercollider/cookiecutter-supercollider-plugin/issues/17
having a non-cache var with the same name as a cache var leads to
problems. also use FORCE so users can change it with ease.
Checklist
---------
certain this fixes the issue

[tools] Cmake gen: fix caching of SC_PATH

---

testsuite/classlibrary/TestUnitTest.sc

remove tests that rely on faulty assumptions. in particular, tests
should not assume that anything other than `setUp` should run before the
test, and `tearDown` after the test.
remove commented out tests.
Checklist
---------

tests: cleanup TestUnitTest.sc

---

.travis.yml
.travis/before-install-osx.sh

may fix an issue discussed on sc-users. we always want to be using the libsndfile
from homebrew. if it's not installed, CMake will still find the system
installed one which does not have FLAC support among other things.
Checklist
---------

Travis: use travis_retry and force correct installation of dependencies

---

HelpSource/Classes/LanguageConfig.schelp
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/SC_LanguageConfig.cpp
lang/LangSource/SC_LanguageConfig.hpp

Use the currently specified config file when saving language configuration
Fixes #4595 
I couldn't get the [proposed fix](https://github.com/supercollider/supercollider/issues/4595#issuecomment-534786390) to work - adding anything in the language method before calling the sclang primitive causes errors - there doesn't seem to be a way to modify the argument in sclang before calling the primitive.
~~This seems like a proper fix, but there's one area for improvement, see below.~~
- Bug fix

sclang: LanguageConfig store fix

---

CMakeLists.txt
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp
server/supernova/sc/sc_synthdef.hpp
server/supernova/utilities/utils.hpp

Fixes https://github.com/supercollider/supercollider/issues/4576, https://github.com/supercollider/supercollider/issues/4490
I looked for a nicer way to to this, but couldn't find anything -- there appears to have been a single boost release (1.70) where this class hierarchy was somewhat compatible in both directions.
- Bug fix

Support for Boost 1.71

---

HelpSource/Classes/Platform.schelp
SCClassLibrary/Platform/Platform.sc
lang/LangPrimSource/PyrPlatformPrim.cpp

allows programmatically getting the platform architecture as a symbol
motivated by https://scsynth.org/t/how-do-i-tell-from-sclang-if-the-win-environment-is-32-bit-or-64-bit/1168
see for similar implementation https://docs.python.org/2/library/platform.html#platform.machine
Checklist
---------

add Platform.architecture

---

HelpSource/Classes/NetAddr.schelp
SCClassLibrary/Common/Control/NetAddr.sc

Fixes #4482 
It turns out that we were [failing to store a list of TCP connections](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/NetAddr.sc#L143) when the `disconnectHandler` was `nil`, which prevented the connection from being added to the `IdentityDictionary`.
My fix replaces `nil` for the `disconnectHandler` with an empty function `{}`. I'm not sure if there's a better object to use here and I'm open to suggestions.
In the process of debugging this, I temporarily exposed `NetAddr *connections`. ~~I think it would be beneficial to keep it available, so I added a getter to it (as well as an entry in the docs) in a separate commit. It this is not desirable here, I'm happy to take this out. On one hand, it would be useful to have this …

fix closing TCP connections in sclang on recompile

---

cmake_modules/MacOSXBundleInfo.plist.in
editors/sc-ide/CMakeLists.txt

reported by @redfrik.
the end of the copyright range should definitely always be the current
year for a release.
Checklist
---------

CMake: always use current year for end date of copyright range

---

tools/cmake_gen/CMakeLists_header.template

The cookiecutter plugin build workflow doesn't currently support nova-simd or include the boost library.
- New feature
This adds the `NOVA_SIMD` build option ~~and includes the `boost` library~~ by default so it's available to the cookiecutter plugin build workflow.
**Note**: The default `DNOVA_SIMD` flag is `ON`.
This gets the job done for making these libraries available to plugins, but I'm open to other options for optionally including these.
- plugin built using both libraries
- SC built just fine
- I didn't see any build flag documentation in the cookiecutter repo to update.

CMake plugin template (used by cookiecutter): add NOVA_SIMD build option and include boost.

---

HelpSource/Classes/Routine.schelp
HelpSource/Reference/randomSeed.schelp

A mailing list discussion revealed that some of the documentation about routines "inheriting" state from the parent thread is unclear, and possibly misleading. This PR attempts to clarify a few points.

Help: Clarify Routine's "inheritance" of clocks, times and RNGs [skip ci]

---

common/SC_PaUtils.cpp

In the process of working on #4009, I discovered CoreAudio-specific flags in PortAudio, that make it run on macOS with settings tuned for pro-audio applications. What it means in practice is that now PortAudio will ask the audio device to run at the requested sample rate, instead of allowing CoreAudio to resample. This matches scsynth's behavior with the native CoreAudio driver.
By default it will only benefit supernova on macOS (which uses PortAudio), however it is possible to build scsynth with PortAudio as well. ~~so the changes were applied for both scsynth and supernova.~~ The changes are applied to a common file that can be used by both scsynth and supernova.
~~EDIT: this will be re-worked after #4614 is merged.~~ This is ready for review.
- New feature

[portaudio:macos] avoid resampling when talking to audio hardware

---

editors/sc-ide/core/settings/theme.cpp
editors/sc-ide/widgets/settings/editor_page.cpp

Fixes #4033 
As noted on the issue above, scide crashes when you try to copy a theme that was just copied.
It happens because the newly copied theme is not stored until the changes are applied.
This patch disables the copy button when a new theme is created by copying an old one, until the changes are applied.
Also, internally, it falls back to the default theme if, somehow, we try to create a new Theme based on a theme that doesn't exist. I'm not 100% sure about that since errors should not be silenced, so an warning is still issued.
Checklist
---------

scide:  disables copy theme if theme is a new theme not yet saved

---

include/plugin_interface/SC_PlugIn.hpp

The `registerUnit` function conveniently combines registering constructors and destructors, but hard codes the flag that prevents buffer aliasing. Many UGens require non-aliased buffers. The [older defines](https://github.com/supercollider/supercollider/blob/63783aeca007c1e1d2a7cf73b3f3da056913f077/include/plugin_interface/SC_InterfaceTable.h#L213-L218) allowed this. This omission is noted in the [example-plugins](https://github.com/supercollider/example-plugins/blob/d0622ac6a4919bc7db134561d292d71337a9823d/02b-MySaw/MySaw2.cpp#L134).
- New feature
This flag simply allows preventing buffer aliasing. The default value of `0` should be a good choice because it's more common, and ensures backwards compatibility.
Questions for review:
- Does anyone know if this was an oversight or if it was …

SC_Plugin.hpp: registerUnit, add no buffer aliasing flag.

---

HelpSource/Classes/UnitTest.schelp
SCClassLibrary/Common/UnitTesting/UnitTest.sc

This allows TestCases to provide debug which will be displayed in the results report along with any details from assertions, except for passing tests where brief reporting has been requested via
UnitTest.passVerbosity = UnitTest.brief;
This is very similar to [the `addDetail` method in Python's testtools](https://testtools.readthedocs.io/en/latest/for-test-authors.html#details).
Unfortunately UnitTest doesn't provide isolation between test cases as per https://github.com/supercollider/supercollider/issues/3572, so we have to reset the debug state after each test method, otherwise debug from one test method can bleed into the next if brief reporting is enabled and all the tests in the first one pass.
Partially addresses #3365.

UnitTest: add debug method

---

HelpSource/Classes/EnvGen.schelp
HelpSource/Classes/LFDNoise1.schelp

There seems to be a corner-case in PROSE handling which leads to missing 
spaces.  In particular, if there is a code::word::
followed by normal text on a new line, HTML omits a space between
the closing tag and the text of the new line.
I can't tell how other browsers react, but here is how Lynx currently 
renders Classes/EnvGen. My in-development Emacs SCDoc renderer exposes the
same problem. Note the "word" "timeScaleare". Also note the extra spaces in
"levelScale , levelBias ,".
Description
Plays back break point envelopes. The envelopes are instances of the
Env class. The envelope and the arguments for levelScale , levelBias ,
and timeScaleare polled when the EnvGen is triggered and remain
constant for the duration of the envelope.

Fix some instances of broken spacing

---

server/scsynth/SC_Time.hpp

By default, std::chrono::duration measures time in seconds (std::ratio<1, 1>). 
The correct way to convert to fractional seconds is to use duration_cast with
std::chrono::duration<T> where T is some kind of floating point type.

Eliminate a magic number

---

testsuite/classlibrary/TestPattern.sc
testsuite/classlibrary/TestReadableNodeIDAllocator.sc
testsuite/classlibrary/TestServer_boot.sc
testsuite/sclang/lpc/AbstractLPCBrutalTest.sc
testsuite/sclang/lpc/LPCTestUtils.sc

Some UnitTest subclasses post unnecessary debug info,
some have var declarations that post compiler inline warnings.
This PR removes both, so unit tests run as quietly as possible.
- cleanup for UnitTests.
*That is, TestPattern, TestServer_boot, TestReadableNodeIDAllocator run fine.
On my setup, I cannot get the LPCtests to run properly, 
with or without the changes proposed here...

UnitTest - remove debug posts and inline warnings

---

SCClassLibrary/JITLib/ProxySpace/extStoreOn.sc
testsuite/classlibrary/TestNodeProxy.sc

Fix a bug in NodeProxy.asCode, where default fadeTime is posted as code.
(even though it should be suppressed). this is an update on #4717.
This also fixes the currently failing TestNodeProxy asCode-related tests.
- Bug fix

Ndef as code fix fadetime

---

SCClassLibrary/Common/Control/Server.sc

Tested on macOS 10.13.
In the process of testing #4435, I realized that supernova takes considerably more time to boot than scsynth, which is a problem with we wait for the tcp connection to be established.
`NetAddr -tryConnectTCP`, called by `Server -boot` by default makes a maximum of 10 attempts every 0.2s, and then says that the connection failed. That means that the server needs to respond within 2 seconds. 
On my system supernova takes about 1.8s to respond to the tcp connection (~8 connection attempts) when the system is idle. When I stress my system, the server often boots after we run out of connection attempts (supernova responds after more than 2 seconds). 
This PR increases number of connection attempts to 20, in practice giving server 4 seconds to respond. It is a workaround …

[classlib] increase maxAttempts for tcp connection to the server

---

CMakeLists.txt
HelpSource/Classes/Main.schelp
HelpSource/Reference/Server-Command-Reference.schelp
SCClassLibrary/DefaultLibrary/Main.sc
SCClassLibrary/deprecated/3.10/Main.sc
SCVersion.txt
cmake_modules/MacOSXBundleInfo.plist.in
common/SC_Version.hpp.in
editors/sced/sced3/supercollider.plugin.in
lang/LangPrimSource/PyrPrimitive.cpp
platform/windows/CMakeLists.txt
server/scsynth/SC_MiscCmds.cpp
server/supernova/sc/sc_osc_handler.cpp
testsuite/classlibrary/TestMain.sc
tools/cmake_gen/CMakeLists_header.template

this commit updates how versioning is communicated across the codebase.
the most important change is that SCVersion.txt now separates the
'patch' and 'tweak' version components in new CMake variables called
SC_VERSION_[MAJOR,MINOR,PATCH,TWEAK]. 'patch' is always numeric, while
'tweak' is the optional component used for '-beta1', '-rc2'. the old
variables are kept for backwards compatibility.
we use these to set the VERSION in the CMake call to project(), which
fixes #4648. however, this requires that we strip the 'tweak' component
since only digits and periods are allowed in version strings. so, we
replace references to PROJECT_VERSION with SC_VERSION where appropriate.
this also allows us to be more precise with versioning in the class
library. previously, we only had a method that would …

Versioning reform

---

HelpSource/Classes/UnitTest.schelp
SCClassLibrary/Common/UnitTesting/UnitTest.sc

This PR prevents individual unit tests from inheriting the `*runAll` class method.
Fixes #4720.
- Bug fix
- Breaking change (not sure?)

classlib-unittest: fix/clarify runAll for UnitTest subclasses

---

HelpSource/editor.js

fixes: #4536. also, strings, symbols and chars containing `(` or `)` will now be correctly ignored by the paren matcher. 
side note: i really wish that it was possible to hook into the sc-ide 's code parser/evaluator instead of duplicating the logic just for the help browser. maybe possible with that webchannel/socket thingy?
- Bug fix

help browser: ignore certain tokens when matching parens

---

HelpSource/Classes/Document.schelp
SCClassLibrary/scide_scqt/ScIDE.sc
testsuite/classlibrary/TestDocument.sc

Fixes #4549.
Previously, `Document.initAction = { ... }` or autorun documents took effect only when opening the document programmatically (`Document.open` or `Document.new`), but these were ignored when opening the document using IDE menu commands.
The simplest fix also means that autoRun documents will execute whenever recompiling the class library (if they are open). Per discussion under #4549, this seems to match the original autoRun behavior under Cocoa, and it's justifiable as an easy way to write "soft" startup code. However, the documentation inaccurately claimed that autoRun fires only when opening the document. So I updated the help file as well.
This PR touches two behaviors that are impossible to test automatically:
- User action in the IDE.
- Startup behavior after recompiling …

Fix Document.initAction to fire when opening from the IDE

---

HelpSource/Classes/Plotter.schelp
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
SCClassLibrary/deprecated/3.10/Plotter.sc
testsuite/classlibrary/TestPlotter.sc

As indicated in https://github.com/supercollider/supercollider/pull/4510#issuecomment-515826646, #4082 introduced `Plotter -plotColors` and it got into 3.10.3. PRs related to #4510, particularly #4459, are still in the process of being reviewed. This was a larger rework of `Plotter` and the latter PR plans to rename the method in question to singular `-plotColor` for consistency (see https://github.com/supercollider/supercollider/pull/4459#issuecomment-507089578).
Since it seems like the singular form was preferred, AFAIU from the review of #4459, I propose to deprecate the plural method name ASAP to discourage its use. 
@mtmccrea since `-plotColors` got into 3.10.3 and the PR reverting it did not, it seems that we need to deprecate the method before removing it. Is that OK with you?
- …

Deprecate -plotColors

---

lang/LangSource/SC_TerminalClient.cpp

Fixes #4214 - "IDE can't run code on Windows, stuck at Sending Request....".
Under certain circumstances, the initial read of stdin appeared to be lost while starting the async io service - this left the interpreter unresponsive as it stopped listening to scide and failed to setup the IPC.
This PR reads from stdin once synchronously, just before starting the service to ensure all stdin is read - which appears to resolve the issue, but will need testing.
It initially presented as an IPC breakdown. 
The IPC has two parts:
- ScProcess::mIpcServer (QLocalSocket)
- ScIpcClient
When the IDE launches sclang (ScProcess) it writes to STDIN:
```_ScIDE_Connect(<socketID>)```
passing in the QLocalSocket address of the IPC server.
sclang executes the primitive, which creates the IPC client.
The IPC …

[sclang][win] Fix hang on Windows - read from stdin synchronously before starting

---

HelpSource/Classes/ServerOptions.schelp
HelpSource/Reference/AudioDeviceSelection.schelp
common/SC_PaUtils.cpp
common/SC_PaUtils.hpp
lang/CMakeLists.txt
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangPrimSource/SC_AudioDevicePrim.cpp
lang/LangPrimSource/SC_AudioDevicePrim.hpp

Add listing devices with PortAudio backend (by default on Windows). With this PR following commands will work on Windows:
```supercollider
ServerOptions.inDevices;
ServerOptions.outDevices;
ServerOptions.devices;
```
Fixes #1557.
RE #1557 - the issue mentions listing devices not working on Linux as well, but since we use JACK on Linux there's [no point implementing listing devices](https://github.com/supercollider/supercollider/issues/1557#issuecomment-114677077). (Maybe at some point we could consider implementing available JACK server names... but this PR is really for Windows users and PortAudio).
- New feature
- ~~All tests are passing~~
- there are no tests

List audio devices on Windows

---

SCClassLibrary/JITLib/Patterns/Pdef.sc
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
testsuite/classlibrary/TestNodeProxy.sc

When no key was passed into `copy` for an Ndef (and analogous classes),
it would fail obscurely. This happens easily, e.g. in `dup`. It is good
to throw an error, because usually one expects copy to return a
separate object. But in cases like `dup`, a copy isn’t needed.
This fixes #4685.
- Bug fix
Separate documentation isn't needed, because arguably it now just behaves as expected.

class library: fix def proxy dup

---

HelpSource/Classes/Image.schelp

A number of examples in the `Image` helpfile did not run, due to using some obsolete methods (`Integer .fromRGBA`, `Array .asRGBA`, `Integer .red` etc.) This corrects the examples so they at least run.
Some examples are a little awkward now, as `Color` returns values `0.0 - 1.0`, while the examples are generally using 8-bit integers. I'm open to suggestions if more changes should be made.

classlib: fix helpfile examples for Image class

---

testsuite/classlibrary/TestEnv.sc
testsuite/classlibrary/TestEnvGen_server.sc

This PR is a redo of #3684, keeping only its UnitTest and not the other changes. The history around #3684 is a bit complicated. The new tests introduced here pass on current `develop`. I believe this is because #4436 was merged.
Thanks to @jamshark70 for twritting these tests. I made the changes to `setUp` and `tearDown` that @brianlheim requested.
- UnitTests

add tests for PR 4436

---

SCClassLibrary/Common/Control/GraphBuilder.sc

A NamedControl's `name` is converted from a Symbol to a String in cases where the `.init` function is called (when `res == nil`). I stumbled upon this while testing #3814. This issue should be fixed before that PR gets merged. 
I'm not sure how to demonstrate the issue using current `develop`, but it may be simple enough to understand just by looking at the changes. Some unused variables were removed (`ctlName`, `ctl`, & `selector`), and `name` stays a Symbol throughout the `.init` function.
- Bug fix

Fix NamedControl 'name' String convertion

---

SCDoc/SCDoc.cpp
SCDoc/SCDoc.h

otherwise may end up segfaulting on deep trees
this function is only used in `SCDoc/main.cpp`, which is just a test driver for the SCDoc parser. that file is not even compiled normally when building. so this has no impact on anything user facing.
- Bug fix

SCDoc: use vector for recursive function

---

server/scsynth/SC_World.cpp
server/supernova/server/server.cpp

[Edit] Updated in line with https://github.com/supercollider/supercollider/pull/4504#issuecomment-517965808
This fixes #4046 - Windows not guarding denormals.
MSVC doesn't set the usual `__SSE__` and `__SSE2__` etc definitions, so denormals aren't properly handled on Windows.
This PR uses boost.predef to check for requested SIMD instructions.
- Bug fix
Fixes #4046
- Breaking changes (?)
This changes how every platform works, so may have unintended consequences
scsynth, yes. supernova doesn't compile on msvc
~~- [ ] Updated documentation~~

[scsynth][supernova] fix Windows not guarding denormals

---

server/scsynth/SC_Jack.cpp

Fixes #4596
Which basically consist on a lot of jitter in scsynth clock when uses Jack on windows or linux
Causes are:
TimeDLL was not used because SC_JACK_USE_DLL was not defined
TimeDLL.Reset was not called on DriverStart
time provided by secondsSinceEpoch(getTime()) was not correct
- Bug fix
Let JACK use TimeDLLby defining SC_JACK_USE_DLL
sc_JACKOSCTimeSeconds (mimics portaudio for scsynth) instead of secondsSinceEpoch(getTime()) 
calling mDLL.Reset on DriverStart
cast with uint64 (as done in portaudio) instead of int64

SC_JACK repair

---

testsuite/server/supernova/CMakeLists.txt

without this ordering, libsupernova is used to resolve symbols first and results
in undefined reference linker errors on supernova tests
- Bug fix

CMake: fix linking with makefiles+supernova+macos

---

include/plugin_interface/SC_PlugIn.hpp

this is an addendum to #4356
msvc complains about signed to unsigned conversion ( see
https://github.com/supercollider/cookiecutter-supercollider-plugin/pull/21)
i also changed this argument to a boolean since there are really only
two possible values. it made sense to use `int` in the C interface since
bool is not a fundamental C type
- Bug fix
- Breaking change (technically, but the change just went into develop
last week and no releases have occurred from it in the meantime)

plugin intf: fix compile error, change type of arg to bool

---

server/scsynth/SC_World.cpp
server/supernova/server/server.cpp

As reported here:
https://scsynth.org/t/error-building-sc-on-raspberry-pi3/1799
PR #4046 added some incorrect preprocessor directives for BOOST_SIMD
This PR fixes those directives.
- Bug fix
Still resolves the denormal issues of 4046
supernova untested

[scsynth][supernova] fix boost_simd preprocessor directives

---

HelpSource/Classes/Plotter.schelp
HelpSource/Guides/Tour-of-Special-Functions.schelp
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
testsuite/classlibrary/TestPlotter.sc

This PR adds the ability to specify multiple plot modes, as you can with plot colors.
It follows the same implementation as `plotColors` for consistency. This includes making a `plotMode` variable local to `Plot`, and settable through `Plotter` via `-plotModes_`. 
- `-plotMode` (singular) getter and setter methods are left for backwards compatibility. This also offers syntax that suit the common case of a single plot (`-plotMode` calls `-plotModes` internally).
- In the same way that with `plotColors` stores all the plot colors internally in an array, `plotModes` an array of modes, even when it's a single mode. The getter method will return this array, _unless there is only one mode or all modes of a multi-channel plot are identical_, in which case it just returns the `Symbol` of the …

[classlib] Plotter: add multiple concurrent modes

---

SCClassLibrary/JITLib/ProxySpace/NodeMap.sc
testsuite/classlibrary/TestNodeProxy.sc

For deriving the controls of a `ProxyNodeMap`’s values, we cannot convert
them to control inputs before rate checking, because this will return
symbols for busses that have no explicit rate information (like `[\a1,
\a2]`).
This was introduced in 1b88d80c7dd761170fbf970f813466feac9cddcf.
Thanks to James Harkins for analysis (see #4311).

class library: do not convert value before rate check

---

CMakeLists.txt

When building SC, warnings "your boost version is older than your compiler" are displayed frequently. These changes should remedy that, per advice by @brianlheim 
- (Bug fix)

build: hide boost warnings

---

HelpSource/Guides/News-3_11.schelp
HelpSource/Help.schelp

In the home page of 3.11-rc1 documentation, there was a link to "News in 3.10".
Now there's a new page "News in 3.11" and the home page points to that page.

Added News in 3.11

---

external_libraries/CMakeLists.txt

This arose from discussion on the Slack recently, and improvements that @brianlheim made to the wiki...
The point when users will most benefit from this wiki is when they have cloned the repo but not the sub-modules...
For those who have just cloned or forked this repo, and not updated submodules, there is already a really helpful message printed as soon as they run cmake, with the command needed to clone submodules.
This commit extends that, to also point to the wealth of extra tips at:
https://github.com/supercollider/supercollider/wiki/git-cheat-sheet#working-with-submodules
- Build usability
Old console output from cmake when submodules missing:
```
CMake Error at external_libraries/CMakeLists.txt:2 (message):
It appears you haven't cloned this project's git submodules: please run …
```

cmake: Better help for users new to submodules.

---

HelpSource/Classes/Pdiff.schelp
HelpSource/Classes/Pdrop.schelp

Added a short help file for class Pdiff

---

editors/sc-ide/CMakeLists.txt

This fixes #4809 - which is that a change I made previously had stopped the translations/scide_*.qm files from being added to distributions.
- Bug fix
The fix was to make the sc-ide exe depend on the translation files, instead of the libscide library...

scide: Reinstate translations files in distributions.

---

editors/sc-ide/CMakeLists.txt
editors/sc-ide/core/main_function.cpp

The fix is to use the QTranslator::load() overload that takes a QLocale, instead of searching for the filename ourselves.
That way, Qt's documented logic takes care of finding scide_fr.qm when the locale contains fr_FR.
- Fixes #4619
- Replaces the closed, unmerged #4620
- **Note** that this also depends on a change that is in PR #4810
Please see the detail about the fix, and how I tested it, in that ticket.
- Bug fix

scide: Fix the finding of locale-specific translations (#4619)

---

CMakeLists.txt
lang/CMakeLists.txt

This enables package maintainers to use a system version of Ableton Link by specifying `-DSYSTEM_ABLETON_LINK=ON` when running cmake.
This fixes #4818 in a packaging context (because a system version of Ableton Link is preferred over the vendored version).
- New feature

Devendor ableton link

---

.gitignore
package/create_source_tarball.sh

This script creates a source tarball from a valid tag in this repository by checking out the SuperCollider sources recursively in a temporary working directory. Optionally, this script can also provide a detached PGP signature. The naming scheme of the tarball and the contained directory follows the current naming scheme.
The script automatically removes its working directory on exit or fail and is tested on Linux and macOS.
Eventually I think this should run in CI, but it can also be done manually by whoever is in charge of the release process (to be able to provide a detached PGP signature).
To create a source tarball:
```
./package/create_source_tarball.sh -v Version-3.11.0
```
To create a source tarball with detached PGP signature:
```
./package/create_source_tarball.sh -v …
```

Release tarball script

---

QtCollider/QcApplication.cpp

This is a workaround for a workaround introduced in #4105 (which fixed #4058, but caused #4309). **This fixes #4309**.
It's not pretty, but it works. I hope that at some point someone looks into a proper fix that's hacked in #4105, but until then it would be great to have the ability to close windows from the keyboard again...
- Bug fix

QT GUI: close window with cmd-w on macos

---

SCClassLibrary/Common/Collections/EnvironmentRedirect.sc
SCClassLibrary/JITLib/GUI/EnvirGui.sc

Fixes #4831 by making 
1. `EnvironmentRedirect` implement `keys` and `values` method for it to be more alike `Environment`, which inherits these two methods from `Dictionary`. Strictly speaking, only the `keys` method suffices to make `EnvirGui` happy.
2. Change `EnvirGui`'s `accepts` method to accept an `EnvironmentRedirect` as its `object` explicitly, since the latter don't derive from `Environment` (probably due to some intricate VM reasons; e.g. see #4829). **Style alert:**  for now this a quick fix using the maligned `isKindOf` check, which `EnvirGui` was already doing. I'm (very) open to suggestions to doing this differently, but I'd rather not change many files with this simple feature/fix. A rework by adding `isLookup` or `isDictionary` to `Dictionary` and its subclasses has been …

classlib: Make EnvironmentRedirect work as EnvirGui's object

---

SCClassLibrary/Common/Control/GraphBuilder.sc
testsuite/classlibrary/TestNamedControl.sc

Fixes #4816 .
Formerly, `res.spec = spec` at the bottom of NamedControl `*new` would overwrite a spec in metadata with the default ControlSpec.
(Note that the unit test can't use assertEquals on the spec objects -- I tried it but it fails spuriously. No time to debug that, so I just test same/different maxval.)
- Bug fix

classlib: Fix NamedControl spec arg (if nil, do not overwrite metadata)

---

SCClassLibrary/Common/Streams/FilterPatterns.sc
testsuite/classlibrary/TestPattern.sc

Fixes #4807 Pfset doesn't do cleanup if its sub-pattern yields nil immediately.
- Bug fix

class library: Pfset - do cleanup on nil stream

---

HelpSource/Classes/AbstractFunction.schelp
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

As discussed on [scsynth.org](https://scsynth.org/t/how-to-plot-a-transfer-function/1911/4), it seems the ^ was forgotten at the end of AbstractFunction:plotGraph, and this function does not return the Plotter like plot does.

Return plotter in AbstractFunction:plotGraph

---

.appveyor.yml

it seems like it might take appveyor some time to address us hitting our storage limit due to the COVID pandemic, so in the meantime i propose we use this method to manually push to S3. by not listing the ZIP and html file we push to S3 as an "appveyor artifact", we avoid having them also store it, which would count toward our Appveyor storage limit.
that storage behavior and retention policy is currently an [unconfigurable aspect](https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy) of appveyor. i've asked their support about this in the past and been told manually deploying like in this PR is the only way to avoid it.
this is a temporary workaround. we will need to revert this (or augment it) before a release, since it does not handle github deployments. it may …

Appveyor: workaround for storage limit

---

.travis/before-install-osx.sh
README_MACOS.md
common/SC_fftlib.cpp
editors/sc-ide/CMakeLists.txt
server/CMakeLists.txt
server/scsynth/CMakeLists.txt
server/supernova/CMakeLists.txt

In the process of trying to find solutions to #4289, it was suggested to use the `FFTW` library on macOS for supernova.
This PR adds build instructions for including FFTW in supercollider built on macOS (for supernova only; scsynth still uses vDSP). 
~~In order to provide static FFTW I am using a custom homebrew formula. This formula is temporarily hosted on my [github](https://github.com/dyfer/homebrew-fftw-sc), but if we decide to accept this PR, it should be moved to a more permanent place (and appropriate portions of this PR should be updated).~~
EDIT: This uses a regular FFTW from homebrew. Thanks to @brianlheim for figuring out how to fix linking with it.
- Bug fix

Use fftw in supernova on macos

---

SCClassLibrary/Common/Math/SimpleNumber.sc
testsuite/classlibrary/TestSimpleNumber.sc

Negative `SimpleNumber -asTimeString` returned incorrect string.
Previously:
```supercollider
-1.asTimeString;
-> 0-1:23:59:59.000
```
Now:
```supercollider
-1.asTimeString;
-> -00:00:01.000
```
- Bug fix

classlib: fix SimpleNumber asTimeString for negative values

---

server/scsynth/scsynth_main.cpp

In the process of working on #4009, it turned out that device names with unicode characters are not handled properly on Windows. AFAICT they need to be encoded in UTF-16 (AKA "wide characters") on the stdio level on Windows.
EDIT: This PR is now updated according to https://github.com/supercollider/supercollider/pull/4479#pullrequestreview-262017862. Scsynth on Windows reads command line arguments in UTF-16 and converts them to UTF-8; it also sets the terminal to UTF-8, similarly to what sclang does. This should allow selecting devices with non-ASCII characters in their name. 
Please note, while the requested (non-ASCII) device name is properly displayed in the the terminal when scsynth boots, **I'm not able to test if the device selection works properly for devices with non-ASCII …

[scsynth:windows] support unicode in argv

---

.appveyor.yml

In the previous PR to fix this i neglected to mark the uploaded artefacts as publicly readable. Thanks to @dyfer for
noticing this; it was something i should have checked in the first place.
Fixed #4860
- Bug fix

appveyor: make s3 artefacts readable

---

icons/sc_ide.svg
icons/sc_ide_svg.scd

The icon was broken when displayed with the Qt SVG renderer. This patch fixes and cleans up the SVG code generated by `sc_ide_svg.scd` as well as the actual SVG (`sc_ide.svg`).
Fixes #2646 
- Bug fix

Fix sc_ide.svg when used with Qt SVG renderer, clean up sc_ide_svg.scd

---

QtCollider/widgets/QcCanvas.cpp

Fixes #4844 
- Bug fix
Specific testing would require changing the user's HiDPI settings, which can't be done from sc

HiDPI fractional scaling: remove rounding to int

---

QtCollider/interface.cpp
editors/sc-ide/core/main_function.cpp

Maybe helps with #2442, ~badly needs testing on Windows though.~ @dyfer tested it, and it works, with his addition (see below).
Enables Qt's auto-detection for devicePixelRatio (HiDPI scaling), for both sclang and scide.
Qt provides ways to override this feature by setting environment variables, if the user prefers so.
For example:
- it's possible to turn auto-detection off by setting QT_AUTO_SCREEN_SCALE_FACTOR or QT_ENABLE_HIGHDPI_SCALING to 0
- it's possible to combine auto-detection with a user-supplied scale factor, for either GUIs, fonts or both, by setting QT_SCALE_FACTOR and QT_FONT_DPI
What I've found on my system, is that without any env var set, scide's and sclang's GUIs look very small, especially the help browser text and sclang-generated GUIs ( this resembles the situation …

Qt: AA_EnableHighDpiScaling flags

---

.appveyor.yml
.travis/before-install-osx.sh

appveyor 32-bit build kept at 5.9 because it's the last version to have qtwebengine
Motivated by #4850 , but we should be using latest versions anyway.
- Bug fix

CI: use qt 5.14 in builds, switch to VS 2019

---

HelpSource/Classes/SequenceableCollection.schelp
HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/SequenceableCollection.sc
lang/LangPrimSource/PyrArrayPrimitives.cpp
lang/LangPrimSource/SC_Levenshtein.h
lang/LangSource/PyrSlot32.h
lang/LangSource/PyrSlot64.h
testsuite/classlibrary/TestArray.sc
testsuite/classlibrary/TestString.sc

To add fuzzy string comparisons.
__EDIT__: this PR has changed focus to providing more general, fuzzy Array comparisons
Initial motivation came from the work on choosing an audio device for Windows, I started thinking if we could work out the most similar string for a device name to make guessing a little smarter, accounting for typos etc.
The core of this is fuzzy string comparison.
It's very easy to take these new methods, and write a quick check for nearest string, comparing each word to find the most relevant match (or if agreed, add the methods below for this).
Fuzzy comparison would prove useful to the language, including within the interpreter itself.
This PR adds the following instance methods to the SequenceableCollection class:
- `editDistance`
Alternatively known as Levenshtein …

[classlib] add fuzzy array comparisons

---

.appveyor.yml
README_WINDOWS.md
server/supernova/audio_backend/portaudio_backend.hpp
server/supernova/dsp_thread_queue/dsp_thread_queue.hpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_plugin_interface.cpp
server/supernova/sc/sc_synth.cpp
server/supernova/sc/sc_synth.hpp
server/supernova/sc/sc_ugen_factory.cpp
server/supernova/server/main.cpp
server/supernova/server/node_graph.cpp
server/supernova/server/server.cpp
server/supernova/server/synth_definition.hpp
server/supernova/utilities/static_pool.hpp

Fixes #3766.
This is an attempt to make `supernova` available on Windows with the supported toolchain (Visual Studio). I think I figured out _what_ to change, but I'm looking for advice _how_ to change it. More information below.
EDIT: In the interest of brevity, I've hidden parts of the description that have already been addressed.
<details>
EDIT: This builds and runs on my machine under VS 2017. CI fails because I'm using my own fork of nova-tt. Is this something to be solved temporarily, before changes to nova-tt are submitted upstream?
EDIT 2: I've temporarily changed the nova-tt submodule to use my fork for the CI to pass.
EDIT 3: nova-tt submodule is now updated upstream
</details>
- Bug fix
- (Documentation)
<details>
`nova-tt` generally has cross-platform implementation for the …

supernova: fix msvc build

---

server/supernova/server/main.cpp

Support unicode characters in argv (primarily for setting device name) on Windows.
Companion supernova PR for scsynth's #4479. Implementation is pretty much identical.
- Bug fix

supernova: support unicode in argv on windows

---

SCClassLibrary/Common/Collections/osx/extString_osx.sc

Fixes #4878 
It seems that `String -runInTerminal` got broken in 3.11 since we changed `PathName.tmp` from `/tmp/` to `~/Library/Application Support/SuperCollider/tmp/` (note the addition of space in the path).
I decided to go for quoting the path, but alternatively, as suggested in the linked issue, it could instead have its spaces escaped:
```supercollider
fpath = fpath.escapeChar($ );
```
I'm not sure whether one is better than the other. I'm happy to change this as requested.
- Bug fix
- I don't know if there's a way to test this

classlib: fix String -runInTerminal

---

HelpSource/Classes/DoesNotUnderstandError.schelp
SCClassLibrary/Common/Core/Error.sc
testsuite/classlibrary/TestDoesNotUnderstandError.sc

huge thanks to @jrsurge for laying the groundwork for this. now that we have an easy way to calculate edit distance,
we can automatically provide suggested corrections for typos made in method names. For example:
```supercollider
sc3> [].isnil
ERROR: Message 'isnil' not understood. Did you mean 'isNil'?
RECEIVER:
Instance of Array {    (0x55eb540e9a68, gc=74, fmt=01, flg=00, set=00)
indexed slots [0]
}
ARGS:
CALL STACK:
DoesNotUnderstandError:reportError
arg this = <instance of DoesNotUnderstandError>
Nil:handleError
arg this = nil
arg error = <instance of DoesNotUnderstandError>
Thread:handleError
arg this = <instance of Thread>
arg error = <instance of DoesNotUnderstandError>
Object:throw
arg this = <instance of DoesNotUnderstandError>
Object:doesNotUnderstand
arg this = [*0]
arg …
```

classlib: provide suggested fixes for method name typos

---

lang/CMakeLists.txt

Fixes #4899
On some systems readline is not linked against ncurses; developers must
choose to link with it against either ncurses or termcap. since ncurses
is widely available, we simply find and link against it directly on Linux.
This also appears to be the same problem as https://scsynth.org/t/installation-issue-in-ubuntu-19-10/1952
- Bug fix

cmake: link libsclang against ncurses

---

SCClassLibrary/Common/Streams/PmonoStreams.sc
testsuite/classlibrary/TestPmono.sc

It was reported on the user forum that Pmono and PmonoArtic do not recover from being stopped and resumed.
```
(
p = Pmono(
\default,
\freq, Pexprand(200, 800, inf),
\dur, 0.5
).play;
)
p.stop;
p.play;
FAILURE IN SERVER /n_set Node 1000 not found
FAILURE IN SERVER /n_set Node 1000 not found
p.stop;
```
This is because the EventStreamCleanup did not clear the old node ID. (PmonoArtic needed an additional check for the ID being nil.)
While I have, for health reasons, been cutting back on PR authoring, this is an easy fix in code that I wrote -- took me about five minutes to figure it out, where it would probably be longer for someone else.
The UnitTest does use a hardcoded wait time. Normally this is not recommended. But, the sequence of user actions that triggers the problem is to start …

Classlib: PmonoStreams must create a new node after being paused

---

HelpSource/Classes/Server.schelp
SCClassLibrary/Common/Control/Server.sc

This PR makes `Server -killAll` command kill both `scsynth` and `supernova`.
Fixes #3999
- Bug fix
I think that handling `scsynth` vs `supernova` throughout the `Server.sc` should be revisited, possibly defining executable strings in one place only. I had some [initial thoughts](https://github.com/supercollider/supercollider/issues/3999#issuecomment-414836118) on this, but it would be for a separate PR anyway.

classlib: kill both scsynth and supernova with Server -killAll

---

server/scsynth/CMakeLists.txt
server/supernova/CMakeLists.txt

This PR changes `Audio API` message in CMake to match the `FFT library` message. IMO this improves readability.
This is example output of CMake on macOS after this PR:
```
...
-- FFT library (scsynth): vDSP
-- Audio API (scsynth): coreaudio
-- Found fftw3f: /usr/local/lib/libfftw3f.dylib
-- FFT library (supernova): FFTW
-- Audio API (supernova): portaudio
...
```
- Cosmetic change :)

cmake: update audio API message

---

HelpSource/Classes/Git.schelp
HelpSource/Classes/Quark.schelp
SCClassLibrary/Common/Quarks/Git.sc
SCClassLibrary/Common/Quarks/Quark.sc
SCClassLibrary/Common/Quarks/QuarksGui.sc

The current branch was never mentioned in the Quarks gui, which can be confusing. This adds the quark name to:
1. the LATEST in the versions tree (there, at the moment, latest always means master)
2. an extra field that displays the current branch
- Bug fix
- New feature
This fixes #4321.

quarks: Display current branch name in Quarks.gui

---

HelpSource/Reference/Server-Architecture.schelp
SCClassLibrary/Common/Control/Server.sc

When specifying only input or only output device with `s.options.inDevice`/`s.options.outDevice`, the other device is set to `"nil"`. This has not been a problem so far since in the server if a device with a matching name is not found, a default device is used. This would theoretically result in incorrect behavior if we had a device called "nil" in the system :)
From what I understand looking at server implementation, an empty string is the correct value for "default device". This also was not documented anywhere AFAICT, so I added documentation in the help.
example of old behavior:
```supercollider
s.options.inDevice_("TestIn");
s.options.outDevice_(nil);
s.options.asOptionsString;
->  -u 57110 -a 1024 -i 2 -o 2 -H "TestIn" "nil" -R 0 -l 1
s.options.inDevice_(nil); …
```

Name of the default device in ServerOptions

---

lang/LangPrimSource/SC_CoreMIDI.cpp

CoreMIDI backend checked num in ports instead of out ports by mistake
fixes #4652
i am making this PR against 3.11 because it seems like a really obvious and simple fix to me, but i would appreciate
if someone on macOS could test it.
- Bug fix

sclang: fix spurious out-of-range error

---

SCClassLibrary/Common/Quarks/Quarks.sc

We have received multiple reports of the following error message:
```
ERROR: Failed to read quarks directory listing:
https://github.com/supercollider-quarks/quarks.git
a PrimitiveFailedError
```
Troubleshooting this is deadlocked because the error message embeds the error object `asString`, which only prints the error's class name and omits the error string.
We should print a descriptive error message, if one is available.
- Bug fix
As this is a class-library-only change, it does not need to wait for codebase reformatting.

Classlib: Quarks: Print errorString if fetchDirectory failed

---

server/supernova/audio_backend/portaudio_backend.hpp
server/supernova/server/server.hpp

Fixes #4029 
~~This is WIP - it works as expected, but the implementation is hack-y.~~
The gist of the issue was that in ```void nova_server::prepare_backend(void)```, as well as in ```inline void run_scheduler_tick(void)``` (in `server.hpp`/`server.cpp`) we needed to use number of input channels clipped to the number of available ins in the hardware, but number of output channels as requested by the user (_not_ clipped to what HW provides).
After modifications to `server.cpp` and `server.hpp` and making `input_channels`/`output_channels` variables available globally to fix this, I have also tested JACK and non-real-time (soundfile) backends; both seem to work as expected. (Soundfile needed a fix, which is now included).
**I'm open to suggestions if there's a better way to fix this :)** …

supernova portaudio: fix for requesting number of I/O channels exceeding hardware capabilities

---

server/scsynth/SC_PortAudio.cpp
server/supernova/server/main.cpp

A follow up to first sentence in https://github.com/supercollider/supercollider/pull/4476#issuecomment-623772589
Print `(default)` when server is requested to use a default input/output device. Applies to PortAudio backend only. Examples:
scsynth:
```
Requested devices:
In:
- (default)
Out:
- (default)
```
supernova:
```
Requested audio devices:
In: (default)
Out: (default)
```
Additionally, scsynth will not print `(matching device NOT found)` when selecting default device.
Tested with following code:
```supercollider
// all tests run for scsynth and supernova
Server.supernova;
Server.scsynth;
// note that PortAudio backend does partial matching for device name
(
// default input and output
s.options.inDevice_(nil);
s.options.outDevice_(nil);
s.reboot;
)
(
// non-existing input …
```

servers: print "(default)" when booting with default devices

---

.travis.yml
.travis/before-install-linux.sh

Store clang download in cache.
Prevents CI failures when download source is not available.
clang download and extracted archive is now stored in `$TRAVIS_BUILD_DIR/../downloads/`, (previously `$TRAVIS_BUILD_DIR/../`), I hope that's okay.
- (Bug fix)

ci: use cache for clang-format

---

server/scsynth/CMakeLists.txt
server/supernova/CMakeLists.txt

MinGW needs this flag since we are now using `wmain()` in servers.
- Bug fix

servers: fix unicode support for mingw

---

lang/LangPrimSource/OSCData.cpp

When I tried to initialize a remote scsynth with
Server.remote(\salt, NetAddr("192.168.7.2", 57110),
ServerOptions.new.maxLogins = 4);
sclang answered by crashing with a segmentation fault.
gdb revealed that the crash happens in prMatchLangIP.  And this got me 
thinking: "Maybe I should stop my VPN?"  And indeed, that fixed the symptom.
Reading getifaddrs(3) explains it:
The ifa_addr field points to a structure containing the interface address.
(The sa_family subfield should be consulted to determine the format of the
address structure.)  This field may contain a null pointer.
So fix prMatchLangIP by checking that ifa->ifa_addr is not NULL.

Fix segfault in prMatchLangIP on Linux

---

SCClassLibrary/Common/Core/Error.sc

The current error fixing suggestion can be misleading. Typically, the receiver is wrong, not the message. So when you call:
```
nil.flop
```
you get a suggestion that you mistyped `flop`, but it happens to be nil which doesn't understand flop:
```
ERROR: Message 'flop' not understood. Did you mean 'stop'?
RECEIVER:
nil
ARGS:
```
This branch improves this situation.
If the receiver is nil, no suggestion is made - this seems like a reasonable thing not to do.
Otherwise, we post this:
```
"Did you mean '%'? Or should '%' have been called on another receiver?"
```
So that:
```supercollider
Set[1, 2, 3].flop 
// returns 
ERROR: Message 'flop' not understood by 'Set[ 1, 3, 2 ]'
Did you mean 'stop'? Or should 'flop' have been called on another receiver?
RECEIVER:
Instance of Set { …
```

class library: improve suggestions in method not found error

---

SCClassLibrary/Common/Collections/windows/extString_windows.sc

Implement `String -runInTerminal` on Windows.
This seems to work fine, but I'm open to suggestions.
- New feature
- I tested on Windows 10 only
- no tests were added...

classlib: implement String -runInTerminal on Windows

---

editors/sc-ide/core/doc_manager.cpp

Fixes #4380
- Bug fix
I just replace the asAscii call with the definition of asAscii in wslib quark.

remove use of asAscii in doc_manager.cpp

---

editors/sc-ide/core/main_function.cpp

Solves #3511
Adds basic usage to SC Ide executable.
- New feature
- Breaking change (because `scide --h` does not launch the IDE any more)

add -h and --help to SC Ide executable to show usage, solves #3511

---

HelpSource/Classes/WebView.schelp
QtCollider/widgets/QcWebView.h
testsuite/classlibrary/TestWebView.sc

Fixes #4933.
We need to use the fully qualified "QtCollider::QcCallback", otherwise the qt metatype system
doesn't find the function signature. this seems to be a deficiency in the way qt matches function
signatures, but solving it more cleverly might be difficult and introduce other bugs, so i'm just
doing the straightforward thing for now.
another problem (maybe?) raised by this is that findText on a web view that isn't visible will
lock up the interpreter. same with findText(""). i don't know why.
- Bug fix

QtCollider: fix method linking

---

SCClassLibrary/Common/UnitTesting/UnitTest.sc

Fixes the message that's posted when using `assertFloatEquals`. Currently, the formatting is done only on the last bit of the String:
```
PASS: a TestFoo: test_foo1 - foo this is true
Is:
% 
Should equal (within range 0.0001):
1.0
```
- Bug fix

Fix assertFloatEquals string formatting

---

SCClassLibrary/Common/Control/Server.sc

`Server`'s `wait` method is defined as
```supercollider
wait { |responseName|
var routine = thisThread;
OSCFunc({
routine.resume(true)
}, responseName, addr).oneShot;
}
```
Currently, `wait` doesn't pause the running thread. This PR proposes
a fix using a `Condition` to pause and resume the thread. It is based on the discussion for #4942.
It follows a similar pattern found in `Server`'s `sendMsgSync` and `bootSync` methods. Specifically, we have
```supercollider
wait { |responseName|
var condition = Condition.new;
OSCFunc({
condition.test = true;
condition.signal
}, responseName, addr).oneShot;
condition.wait
}
```
Fixes #4942.
- Bug fix

Server's 'wait' method reimplemented using Condition.

---

SCClassLibrary/JITLib/ProxySpace/extStoreOn.sc
testsuite/classlibrary/TestProxySpace.sc

There are a couple of weaknesses in `ProxySpace:storeOn`. Note that this is used to save the state of a ProxySpace into a document, so that the user can execute that document's contents and recover the state (assuming the user avoided open functions, Buffers etc.) -- so it's important to get as much of it right as possible.
- In `ProxySpace:document`, the header line hardcodes "ProxySpace" instead of using `this.class.name`. This disallows subclasses. I don't see a good reason to disallow subclasses.
- Proxies found in a ProxyNodeMap may be referenced without being initialized (for rate and number of channels). In my test case, this meant that a stereo `ar` proxy was restored as a mono `kr` proxy, corrupting the original state. So, this PR goes through the nodeMap and, for any NodeProxies …

ProxySpace:storeOn: Fix initialization of children

---

testsuite/classlibrary/TestPatternProxy.sc

Psetpre's constructor method signature is `Psetpre(name, value, pattern)`. But line 92 inappropriately copies the arguments from the Pfset test on the previous line: `Psetpre({ ~gg = 8; ~zz = 9; }, x)` -- since `pattern` is empty, this won't produce any values.
This PR only fixes this typo.
The test passed before, and after, the fix. So there might be something missing in the test logic: if events were expected but not produced at all, this test doesn't detect that. But I think that should be out of scope for this PR.
- Bug fix

Testsuite: Correct Psetpre typo in TestPatternProxy

---

.appveyor.yml
server/scsynth/scsynth_main.cpp

This is a workaround for #4368 
On some Windows 10 computers, Windows Defender delays scsynth.exe start for around one minute. Users can mark scsynth.exe as safe by adding the scsynth.exe process to Windows Defender exclusion list.
This PR adds a warning to scsynth output if it has not booted after 10 seconds.  
It may be difficult to get this delay at the first place, but having sc3-plugins and some quarks installed seem to increase the probability of getting it.
I tried the NRT example and it seems to work.
Please squash the commits if the PR is accepted (I could install the linter on my machine now 🙄).
- New feature

Adds a warning if scsynth does not boot after 10 seconds on Windows to circumvent #4368

---

HelpSource/Classes/Array.schelp
lang/LangPrimSource/PyrArrayPrimitives.cpp
testsuite/classlibrary/TestArray.sc

Fixes #4930.
this pr contains the commits from #4935, that should be merged first and then 3.11 into develop
since this is technically a breaking change i put it in develop instead of 3.11
- Bug fix

sclang: fix return value for [x].mirror1

---

tools/release/make_release.py

This is the first step toward automating the release process: a script
that provides a series of yes/no prompts for guiding the release manager
through an entire release from start to finish.
Huge thanks and credit also go to @claremacrae and @jrsurge!
The current idea (correct me if i'm wrong!) is that we merge this
quickly, so @joshpar can use it to create the 3.11.1 release. this would
also serve as a test drive to catch any missing information or steps.
this script is designed to completely describe the release process, so
once this is merged the entire wiki section on the release process will be
replaced with "run `tools/release/make_release.py`.
- New feature

Add tools/release/make_release.py

---

.appveyor.yml
common/SC_ServerBootDelayWarning.cpp
common/SC_ServerBootDelayWarning.h
server/scsynth/CMakeLists.txt
server/scsynth/scsynth_main.cpp
server/supernova/CMakeLists.txt
server/supernova/server/main.cpp

This is the followup to #4941 (thanks for guiding me @brianlheim).
It displays a warning message for Windows users when supernova takes longer than 10 seconds to boot, which may come from Windows Defender scanning all the UGens.
Manually tested :
[X] Message is displayed if supernova takes more than 10 seconds to boot
[X] Message is not displayed if supernova takes less than 10 seconds to boot
[X] Message is displayed if scsynth takes more than 10 seconds to boot
[X] Message is not displayed if scsynth takes less than 10 seconds to boot
- New feature
Please squash the commits if you merge this PR !

Add warning when windows defender delays supernova boot

---

QtCollider/primitives/prim_QPen.cpp
QtCollider/widgets/QcGraph.cpp
QtCollider/widgets/QcLevelIndicator.cpp
QtCollider/widgets/QcMultiSlider.cpp
QtCollider/widgets/QcScopeShm.cpp
QtCollider/widgets/soundfileview/view.cpp

This fixes the build when using Qt 5.15 ~and system boost 1.72.0~. Tested using GCC 10.1.0.
I don't think these changes should break things on older versions (~the built-in Boost also has `boost/predef/other/endian.h`, and~ the Qt change was always a missed include, it just happened to work on older versions).
- Bug fix (build fix)

Build fixes for Qt 5.15

---

HelpSource/Overviews/Operators.schelp

Re-closes #3621
Re-introduces a clarification about the behavior of pow with UGens producing negative output.
Since this behavior contradicts basic math, I thought it would be mindful to write this as a NOTE::

docs: operators: UGens pow of negative value [skip ci]

---

SCClassLibrary/Common/GUI/tools/HelpBrowser.sc

There is no way to resize the (WebView based) HelpBrowser dynamically. This PR adds key down actions to be able to resize the content similar to the way the built-in HelpBrowsers docklet works in the IDE. It also fixes the key down action (Cmd-f on macOS) to toggle the "Find text" utility.
- Bug fix
- New feature

Add keydown actions to resize the HelpBrowser

---

.appveyor.yml

This prevents AppVeyor from trying (and failing) to push artifacts from PRs to S3 storage. This is just a cosmetic change - it tidies up the log, the failure to upload was not treated as CI failure anyway.
Solution copied from https://github.com/supercollider/sc3-plugins/pull/283
- Cosmetic change

appveyor: don't push PR artifacts to S3 storage

---

HelpSource/Classes/Routine.schelp

In preparation for adding more `.p` methods to other Streams (#4997), I thought I should document first what the (presently undocumented) `Routine.p` does.
Also mention in Routine's help file `Function.r` as shortcut for constructing routines.

help: Routine: document '.p' method; 

---

HelpSource/Classes/Pfunc.schelp

Fixes #5009 i.e. there's no argument passed to `reset` in the classlib code, so I've removed the claiam that that happens from the Pfunc documentation.
Also, I've add examples of using the argument in nextFunc, including one on how to delete keys from event streams, which is a bit of a newbie gotcha if done from a Pbind "directly", by setting a key to nil.
Alas, it might not be easy to find this example from the most relevant context, i.e. the Pbind help page ... but since it exists now in a help file, it could linked/mentioned from there, although I've not included that in this PR. (If you think that's a good idea, I'll push another commit on Pbind's help page.)

help: Pfunc: remove erroneous mention of argument being passed to resetFunc

---

HelpSource/Classes/TWindex.schelp
server/plugins/OscUGens.cpp
testsuite/classlibrary/TestCoreUGens.sc
testsuite/classlibrary/TestTWindex.sc

Reported at https://scsynth.org/t/strange-twchoose-ar-behavior/2277/5:
```
a = {
var trig = Impulse.ar(ControlRate.ir * 4),
index = TWindex.ar(trig, [0, 1]),
sampleCount = Sweep.ar(0, SampleRate.ir);
Poll.ar(trig * (index <= 0), sampleCount, "failed");
Line.ar(0, 1, ControlDur.ir, doneAction: 2);
Silent.ar(1)
}.play;
```
Four triggers are generated within one control block. The first one behaves correctly, skipping over the zero probability and returning an index == 1. The 2nd, 3rd and 4th return index == 0, which should be impossible according to the probability table.
The reason why is that TWindex initializes its `sum` variable only once per control block. It should initialize for every incoming trigger. That is, it currently assumes there will never be more than one trigger in a …

Fix TWindex 'sum' initialization bug

---

HelpSource/Classes/EventPatternProxy.schelp
HelpSource/Classes/Pdef.schelp
HelpSource/Classes/TaskProxy.schelp
HelpSource/Classes/Tdef.schelp
SCClassLibrary/JITLib/Patterns/Pdef.sc
testsuite/classlibrary/TestEventPatternProxy.sc
testsuite/classlibrary/TestTaskProxy.sc

Fixes #4803 
Both TaskProxy and EventPatternProxy were ignoring instances' clock in .play().
They should do what they do in .playOnce(): if a clock is not provided as an argument, fallback to instances' clock, which in turn falls back to TempoClock.default if unset
- Bug fix

sc class library: TaskProxy: play on instances' clock if no argClock

---

SCClassLibrary/Common/Audio/UGen.sc
testsuite/classlibrary/TestComplex.sc

UGen:composeBinaryOp checks if the other operand isValidUGenInput, and if not, calls `otherOperand.performBinaryOpOnUgen(this)` (pseudo). However, it doesn't return the latter's return value, making it ineffective. 
This has been like that since the dawn of time (+18 years?), however, all implementations of `performBinaryOpOnUgen` seem to expect their value to be returned:
https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/SCClassLibrary/Common/Math/Complex.sc#L78
https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/SCClassLibrary/Common/Math/Polar.sc#L50
https://github.com/supercollider/supercollider/blob/9be3fe2b6e2250b6ed5cb0f4e02d4c4246ebef69/SCClassLibrary/Common/Core/Object.sc#L683
EDIT: another …

sclang: Ugen: composeBinaryOp add missing ^

---

SCClassLibrary/JITLib/Patterns/Pdef.sc
testsuite/classlibrary/TestEventPatternProxy.sc

#Fixes #4954
I have checked that fix this works with both the present cleanup system and the one proposed in #4806. 
- Bug fix

classlib: fix EventPatternProxy premature cleanup of faded-in stream

---

server/scsynth/CMakeLists.txt
server/supernova/CMakeLists.txt

scsynth: set SC_ServerBootDelayWarning as source to scsynth not to libscsynth solves #4992

scsynth: set SC_ServerBootDelayWarning as source to scsynth

---

editors/sc-ide/core/sc_process.cpp

Fixes: #4688 
This is a pretty nasty bug that causes all sorts of random failures. The message processor for the IPC between ide and lang will fail if it doesn't process a message in one go because it loses track of the remaining available data.
When this happens, it never recovers, causing all sort of problems in the IDE, anything that depends on ScIDE.send stops to work, include the HelpBrowser. The only way to recover is restarting the whole IDE.
Please see #4688 for an easy way to reproduce the problem. 
On Linux you might need a bigger value (60000 for example) and a few tries to trigger the bug, but it is pretty constant. I think other bugs reported are also caused by this, including in quarks that use a lot the interaction between the IDE and language such as @adcxyz 's  SyncText. …

Fix the IPC message processing on scide

---

SCClassLibrary/Common/Collections/String.sc
testsuite/classlibrary/TestString.sc

Fixes #4944 
- Bug fix
Note: I verified the fix manually. I think it warrants some unit tests, especially because the method in question doesn't currently have any. But I'm new to hacking on this project so it will take a bit to get my dev environment set up.
Update: Added tests and everything is passing locally now.

return early after first path separator in splitext

---

lang/LangSource/Bison/make_parser.sh

Fixes #2259
There was no actual compatibility issue, but the script arguments were wrong.
I would have preferred to commit a CMake rule instead of fixing this script that needs to be manually run, but it looks like [getting a working Bison rule in CMake is a bear](https://github.com/supercollider/supercollider/issues/5021#issuecomment-647004008).
Also, with bison 3.5.1, while the parser builds and runs ok, there's this warning:
```
LangSource/Bison/lang11d:36.1-14: warning: deprecated directive: ‘%error-verbose’, use ‘%define parse.error verbose’ [-Wdeprecated]
36 | %error-verbose
| ^~~~~~~~~~~~~~
| %define parse.error verbose
LangSource/Bison/lang11d: warning: fix-its can be applied.  Rerun with option '--update'. [-Wother]
```
which I didn't fix because I don't know how far backwards …

Fix bison args in make_parser.sh

---

HelpSource/Reference/Syntax-Shortcuts.schelp

* Split function/class definition section from calls section, i.e. the fist non-intro section is now two sections… because I found it too confusing the way it was before with e.g. `||` arguments introduced somewhere in the middle of the old section and it was even after less important stuff like "defining instance variable accessor methods", which people don't get to until they start writing their own classes.
* Detailed that blocks need be such (function literals) for the moving blocks out of argument lists feature.
* Detailed some semantic caveats in the calls section when mixing operator styles (dot with binary).
* Mentioned functional (prefix) notation for native binary operators (seldom useful)
* Mention & link list comprehensions
* Mention limitations of partial application syntax …

help: Syntax-Shortcuts split first non-intro section in two and added a number of details on call syntax

---

QtCollider/LanguageClient.cpp

In qt tick event handler there's potential for language deadlock with a recursive event loop call.
This fix uses trylock to bail early from handler when unable to obtain language lock.
e.g. deadlock can happen when tick called during work event handling, which is rare but possible.
Solution seems not too radical as SuperCollider appears to have precedence of this approach:
[SC_LanguageClient::tick](https://github.com/supercollider/supercollider/blob/master/lang/LangSource/SC_LanguageClient.cpp#L266)
[SCApp AppClock handler](https://github.com/supercollider/supercollider/blob/96e56b57edb66ae538bf7360901f3f3b3b451571/editors/scapp/SCVirtualMachine.M#L182)
Tested with no apparent issues on MacOS 10.14.6.
Document the cause of #1640
- Bug fix

QtCollider:LangClient - event loop deadlock fix - issue #1640

---

editors/sc-ide/CMakeLists.txt

there is a better way to do this -- parse the output of otool and use that to fixup bad paths, but since install_name_tool doesn't consider it an error if the path doesn't exist, this works for now
that more complex solution is worth implementing, but i don't have time to do it at the moment and want to keep CI running
- Bug fix

[3.11] travis: fix CI error

---

editors/sc-ide/CMakeLists.txt

there is a better way to do this -- parse the output of otool and use that to fixup bad paths, but since install_name_tool doesn't consider it an error if the path doesn't exist, this works for now
that more complex solution is worth implementing, but i don't have time to do it at the moment and want to keep CI running
- Bug fix

[develop] travis: fix CI error

---

.travis/before-install-osx.sh

for some reason homebrew has started spuriously failing when installing
fftw. i'm not sure why and don't have time to look into it, but ignoring
the failure seems to work fine for now.
- Bug fix

[3.11] fix travis failure

---

.travis/before-install-osx.sh

for some reason homebrew has started spuriously failing when installing
fftw. i'm not sure why and don't have time to look into it, but ignoring
the failure seems to work fine for now.
- Bug fix

[develop] fix travis failure

---

tools/cmake_gen/SuperColliderServerPlugin.cmake

Removing quotes to allow correct expansion of lists, for plugins with more than one schelp or sc file. Previous behavior caused errors on `make install`.
- Bug fix

cmake: unquote lists (SuperColliderServerPlugin) [skip ci]

---

README_BEAGLEBONE_BLACK.md
README_LINUX.md
README_RASPBERRY_PI.md

ncurses is now a dependency and apparently not installed by default on some flavors of linux, so document it.
these are the right package names in debian's repos as far as i can tell. would be nice if someone can confirm.
https://packages.debian.org/jessie/libncurses5-dev

[skip ci] readmes: include ncurses in dependencies

---

HelpSource/Classes/SelectXFocus.schelp

'focus' arg was explained backwards.
'focus' arg was explained backwards -- with focus approaching 1, less (not more) adjacent channels are mixed in.
- [x ] Code is tested

Fix args explanation SelectXFocus.schelp

---

HelpSource/Classes/SelectXFocus.schelp

'focus' arg was explained backwards.
Cherry-pick #5078 into 3.11
- Cherry-pick

Cherry-pick #5078 into 3.11

---

external_libraries/boost_sync/include/boost/sync/detail/throw_exception.hpp

Splitting this off from #4986, see also #4914.

boost_sync: workaround to build with Boost 1.72.0

---

HelpSource/Classes/Server.schelp
SCClassLibrary/Common/Control/Server.sc

`Server -quit` does not quit unresponsive servers. This PR adds `kill` command to the server quit process if the given server is unresponsive.
IMO this should prevent majority of issues with hanging servers, since we'd be killing them e.g. on exit and recompile. However, I realize that this is also quite a strong measure and I'd like to hear if anyone feels like this has any major drawbacks.
- Bug fix
- New feature
~~- [ ] All tests are passing~~

kill unresponsive servers on quit

---

platform/renderAllHelp.scd

SCDoc.renderAll needs to be told explicitly to exclude extension dirs, even if sclang is run in standalone (-a) mode. renderAllHelp.scd is already meant to exclude them since its purpose is to compile Help files after building sc, using only the class library from the source tree and disabling extensions (-a flag to sclang) and startup files. 
Unfortunately for this case, SCDoc.indexAllFiles will automatically include extensions' HelpSource dirs anyway, regardless of -a (which can be better fixed after #3733 is merged). 
However, IMO it doesn't hurt to be explicit about excluding extensions in this script, which otherwise would cause errors in SCDoc.renderAll.
- Bug fix

build: renderAllHelp: exclude extensions

---

HelpSource/Classes/SCDoc.schelp
SCClassLibrary/SCDoc/SCDoc.sc
testsuite/classlibrary/TestSCDoc.sc

This is a more proper fix for an issue encountered in #5089 (which is meant for 3.11 before #3733 is ~cherry-picked~ included in a release).
Resume: SCDoc indexes userExtensionDir and systemExtensionDir regardless of them being included or not in class library compilation. This creates an issue when compiling Help Files from renderAllHelp script, which is meant to run in a standalone (-a) sclang, but will anyway try to build help for extensions and fail because they are not part of its class library.
With #3733, it is possible to check LanguageConfig for `excludeDefaultPaths`, and include extension dirs in SCDoc.helpSourceDirs only if default paths are not excluded from the class library.
- Bug fix
- New feature

classlib: SCDoc: include extensionDirs only if not excluded by LanguageConfig

---

HelpSource/Guides/Non-Realtime-Synthesis.schelp

#5093 fixed a typo in the NRT guide (`Platform.tmp` did need to be fixed).
But, I believe the correction in that PR was not the right one. It should be `PathName.tmp` and not `Platform.defaultTempDir`.
1. `PathName.tmp` appears in six other places (lines 221, 241, 446, 447, 513, 534). The occurrence that was fixed should be consistent with these (or, change all of them).
2. `Platform.defaultTempDir` is not user-configurable, while `PathName.tmp` is. I don't see a good reason here to enforce a system default. Let's use the one that the user could override if needed.
#5093 was merged almost immediately, so there was no chance for comment from people living outside the Western hemisphere.

Help: NRT Guide: Replace Platform.defaultTempDir with PathName.tmp

---

CMakeLists.txt

Switch off SSE and SSE2 flags for aarch64 build (allows build on Raspberry Pi 64bit OS)
- Bug fix
- New feature

Update CmakeLists.txt for aarch64

---

SCClassLibrary/Common/Control/Node.sc

The `Node.orderNodesMsg` method is supposed to order nodes from first to last (one after the other) but is sending the wrong server message which causes the node order to be reversed. It should be sending `n_after` (number 19) instead of `n_before` (number 18).
- Bug fix

Use the correct message number for n_after message in orderNodesMsg

---

SCClassLibrary/Common/GUI/Base/QView.sc
testsuite/classlibrary/TestView.sc

Fixes #5105.
Without this change, `View:font` (getter) fails with nil.
I checked other `font_` methods; they seem to be fine.
- Bug fix

View:font_, change to set 'font' variable

---

SCClassLibrary/Common/Control/Buffer.sc
testsuite/classlibrary/TestBuffer_Server.sc

This PR fixes `Buffer.getToFloarArray` by checking to see if its `count` argument is equal to `-1`.
The documentation for `Buffer.getToFloatArray` states that `count` can take a value of `-1` and treat it as "from index until the end of the buffer". This doesn't work because 1) count's value is checked for `nil`, not `-1`, 2) count's default value is `nil`.
Since it's well established that `-1` means "the entire buffer", rather that document count as implemented, I've chosen to add a check for `-1` alongside the check for `nil`. I've also changed the default value of count to `-1`. This PR shouldn't break any user code that relied on `nil`.`getToFloatArray` now reflects its documentation and better matches other Buffer method implementations.
- Bug fix

Fix getToFloatArray 'count' argument

---

.appveyor.yml

this undoes PRs #4993, #4861, and #4847, which were nice in that they allowed us to have S3-published builds but did not
have support for github releases. hopefully, by now enough stored artifacts have expired that we won't hit the
storage limit for long enough to make the release; it's nice also to have the artifacts get stored on Appveyor anyway.
- Bug fix

[Release] appveyor: undo temporary storage limit workaround to prepare for release

---

HelpSource/Classes/ServerOptions.schelp
SCClassLibrary/Common/Control/Server.sc
server/supernova/server/server_args.cpp

Per discussion in #4729 I think it would be good to have supernova use system clock by default, to match scsynth's behavior.

supernova: use system clock by default

---

server/plugins/PanUGens.cpp
testsuite/classlibrary/TestPanAz.sc

Fixes an hardcoded fade-in from 0 in ak/kr cases, due to missing initialization of amplitudes.
I've included suggestions from @mtmccrea https://github.com/supercollider/supercollider/issues/4387#issuecomment-483887517.
However, instead of creating a new PanAz_init function, I'm calling PanAz_calc_ak for 1 sample (as it seems to be a common practice throughout classlib)
Fixes #4387 
- Bug fix

class library: PanAz: initialize amps in Ctor

---

SCClassLibrary/Common/Streams/FilterPatterns.sc
testsuite/classlibrary/TestPattern.sc

When Pfindur reaches the end of its duration, it replaces the original event with a copy, where `delta` has been shortened so that the total duration matches the `Pfindur` limit.
*But* if `event[\delta]` is a Rest, then `localdur - elapsed` is not a rest -- so the event loses its `isRest` status and may play sound, even though the user pattern specified a Rest.
```supercollider
Pfindur(1, Pbind(\dur, Rest(1))).trace.play;
( 'dur': Rest(1), 'delta': 1.0 )   -- does not make sound
Pfindur(1, Pbind(\delta, Rest(1))).trace.play;
( 'delta': 1.0 )   -- does make sound
```
(It *is* valid for a pattern to specify timing using `\delta`, and it's valid for rests to be specified in a `\delta` stream -- so, Pfindur should respect that.)
- Bug fix

Classlib: Fix Pfindur bug where the last event could lose its Rest status

---

HelpSource/Classes/Pattern.schelp
SCClassLibrary/Common/Streams/Patterns.sc

Pattern.record used to simply ignore header and sample formats provided 
as arguments.
Issue reproducer:
```supercollider
Pbind().record("test","wav")
// CmdPeriod to stop rec
SoundFile.use("test"){|f| f.headerFormat.postln} // -> "AIFF"
```
- Bug fix
- Breaking change? I can't say if anyone relied on Patterns ignoring settings provided as arguments... sounds unlikely to me

classlib: Pattern.record correctly set header and sample formats

---

HelpSource/Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp
HelpSource/Tutorials/Getting-Started/11-Busses.schelp
HelpSource/Tutorials/Getting-Started/15-Sequencing-with-Routines-and-Tasks.schelp

Just saw a question on Facebook where a new user had hardcoded bus 0 into a SynthDef, and then used a feature that assumes the bus will not be hardcoded.
Since the question was coming from a user who had just started, I wondered if our tutorial series was pointing in the right direction about bus usage.
It doesn't. The tutorials throughout write `Out.ar(0, ...)`.
This PR replaces all of those with `out` arguments (following the convention used throughout the class library).
I can understand why we wanted the tutorial series to start in the simplest possible place. But the question this morning reveals also that users extrapolate principles from our code examples. So I'm proposing this in the interest of improving the code models we give to beginning users.

Help: [skip ci] Getting Started should model correct use of 'out' arg

---

HelpSource/Classes/MIDIFunc.schelp
HelpSource/Classes/MIDIdef.schelp
HelpSource/Guides/UsingMIDI.schelp

MIDIFunc help for srcID directs the user to the `MIDIClient` help file, which... doesn't explain MIDIEndPoints or UIDs at all.
Just had a thread on the user forum where it was not clear how to use this parameter.

Help: [skip ci] Using MIDI guide: Explain MIDIFunc/MIDIdef filtering

---

HelpSource/Classes/NotificationCenter.schelp

Add better help to NotificationCenter class.  This push fixes some coding conventions for help files:
using tabs in code examples and code:: :: for delimiting inline code. 

docs: improve NotificationCenter documentation

---

SCClassLibrary/Common/Streams/TimePatterns.sc
testsuite/classlibrary/TestPattern.sc

Fixes #5140.
I thought about unit testing, but didn't do that yet. First, to be formally correct, we should check *every* pattern's behavior when wrapped in Pn. Second, this class depends on advancing a clock (`Pn(Pseg(Pseq([0, 1], 1), 0.01), 2).asStream.nextN(10)` is a stream of zeroes because clock time is not advancing) -- so, before adding any tests, I wanted to doublecheck what is the right way to handle this. E.g., if I keep it below 10 ms, OK? 
- Bug fix

Classlib: Pseg embedInStream should return 'inval'

---

HelpSource/Classes/Document.schelp
SCClassLibrary/scide_scqt/ScIDE.sc
testsuite/classlibrary/TestDocument.sc

1. `Document:getText` had a typo -- omitted `this.` -- so it could only throw an error.
a. Also, remove `action` from its argument list.
2. Restore an asynchronous version of `getText` that had been commented out, under a new name `getTextAsync`.
Some history.
The asynchronous version was introduced in https://github.com/supercollider/supercollider/commit/977bd3a290ed70bbd399ea37899b763ebb098144 on July 18, 2013 (tagged Version-3.7.0-alpha0).
The synchronous version replacing it (https://github.com/supercollider/supercollider/commit/578ab14cf73d185ac90d90a12f99e49f22647704) dates to August 8, 2013, also tagged Version-3.7.0-alpha0.
So the asynchronous version existed for only about three weeks and was superseded before its alpha release. It's a safe bet, then, that no user code relies on …

Document:getText fixes

---

HelpSource/Classes/LFSaw.schelp

"radians" not "radiants"
- Bug fix
- New feature

Fix typo in LFSaw.schelp

---

editors/sc-ide/CMakeLists.txt

see QTBUG-86759 and issue #5175 for background
we solve this by removing the unexpectedly empty directory, copying it back from the Qt installation, then fixing up loader paths using some hyper-specific hardcoded assumptions that should hold since this is for a single version of Qt
- Bug fix

cmake: fix deploy of qtwebengine w/ qt 5.15.1

---

.appveyor.yml

Temporarily disables deployment for AppVeyor and uploads builds to Amazon S3.
The same as #5185 but against 3.11 branch

AppVeyor: temporary workaround for artifact storage limit

---

.travis.yml
.travis/before-install-osx.sh
.travis/package-osx.sh
editors/sc-ide/CMakeLists.txt

~~EDIT: this PR will include using custom Qt version in regular builds to fix #5167 and #5175~~
Inspired by [this comment](https://github.com/supercollider/supercollider/issues/5033#issuecomment-696100369) and following conversation, I wanted to see if adding a "legacy" build to our build matrix would be an option.
In this PR I propose to add one more macOS build to our travis build matrix, based on XCode 10 running on macOS 13 and using Qt 5.9. IIUC, this build should run on systems as old as 10.10 (untested). 
I propose this build to be an **unsupported** legacy build, as a courtesy to users running older systems. Once maintaining this becomes a burden, we'd just drop it. But for now it seems to build just fine. 
~~As far as implementation goes, I ended up using a modified QT formula on …

travis: add legacy macos build and custom Qt version

---

.travis.yml
.travis/before-install-osx.sh
.travis/package-osx.sh
editors/sc-ide/CMakeLists.txt

Add legacy build for the 3.11 branch, as discussed in https://github.com/supercollider/supercollider/issues/5188#issuecomment-703364684
This PR focuses on a minimal amount of changes, copied from #5174 
As the implementation is incomplete (e.g. macos deployment is active for all builds, instead of conditional on specified prefix/suffix), these changes should be discarded when merging 3.11 back to develop 
The deployment itself was tested:
https://github.com/supercollider/supercollider/releases/tag/3.11-legacy-test-01
see also [s3 legacy build](https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-legacy-79035341eda52146bc6142420f0b35deac1c87fd.zip) and [s3 regular build](https://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/SC-79035341eda5 …

add legacy build temporarily

---

SCClassLibrary/JITLib/ProxySpace/ProxySpace.sc
testsuite/classlibrary/TestProxySpace.sc

This fixes  #5180
When used within a `ProxySpace`, a NodeProxy's function may contain dynamically scoped references to the local environment. When the `ProxySpace` is copied, the proxies are copied, but they still point to the original sources. This patch updates the references  by rebuilding every proxy from within the new environment. It avoids double rebuilding by keeping a set of those which have been touched already (`checkedAlready`);
- Bug fix

class library: rebuild proxyspace after copy

---

HelpSource/Classes/Dictionary.schelp

Connected to Issue #4573: it should be explicitly stated if a
function checks for equality or identity. A lot of the examples
used the shortcut for initializing an event, which leads to
a different behaviour regarding checks for equality. So I decided
to also change all the examples to use a correct initilization for
creating a dictionary object. See also discussion in the forums:
https://scsynth.org/t/docs-dictionary-vs-event/2642
Connected to Issue #4573, but not completely fixing the issue.

Docs: Dictionary: clarify equality checks and object initialization

---

.gitignore
tools/release/git_utilities.py
tools/release/make_release.py
tools/release/requirements.txt
tools/release/utilities.py

working toward #4974. this is the result of working with @claremacrae  this morning, thanks Clare!
added the following:
- `YesNoStageWithUrl`: same as `YesNoStage`, but opens a URL in a web browser
- copied over some helpful utility files from ApprovalTests.cpp's automation scripting
- added a requirements file with 3 packages
- added command-line option for the new version number
- add some stages and reword some stages based on experience with last release
- we're git-ignoring 'venv' and '__pycache__' directories now since those were generated by pycharm while working on this
Clare, for handling versioning logic i found and used the semantic_version package. it seems to work well with the
kind of version strings we use, and it's less code we need to test, what do you think?
- New …

make_release.py: add some automation for opening webpages

---

HelpSource/Classes/AbstractFunction.schelp
HelpSource/Classes/Object.schelp
HelpSource/Classes/Pkey.schelp
HelpSource/Overviews/Operators.schelp
SCClassLibrary/Common/Audio/UGen.sc
SCClassLibrary/Common/Core/AbstractFunction.sc
SCClassLibrary/Common/Core/Object.sc
testsuite/classlibrary/TestAbstractFunction.sc

Fixes #5179.
Confusion about `aPattern == something` or `aUGen == something` has been a two-decade annoyance.
This PR introduces a new operator such that:
```supercollider
(
p = Pbind(
\a, Pwhite(1, 3, inf),
\b, Pif(
Pkey(\a) == 2,
"equals 2",
"nope"
)
).asStream;
p.nextN(20, ()).any { |event| event[\b] == "equals 2" };
)
// ^^ false, but, the probability of
// Pwhite(1, 3) *never* returning 2, in 20 tries, is (2/3) ** 20 == 0.03%
(
p = Pbind(
\a, Pwhite(1, 3, inf),
\b, Pif(
Pkey(\a) |==| 2,
"equals 2",
"nope"
)
).asStream;
p.nextN(20, ()).any { |event| event[\b] == "equals 2" };
)
// ^^ true
```
If both operands are regular objects, `|==|` returns the Boolean result immediately.
If either operand is some kind of abstract function, `|==|` returns a composite operator -- `2 |==| Pkey(\a)` …

Add "lazy equality" |==| operator

---

cmake_modules/FindPortaudio.cmake

fixes #5176, both the spurious warning message about PkgConfig and the macos/cmake compatibility issue
these are minimal changes to fix compilation on macOS; can definitely be improved further.
while i was at it i removed a bit of cruft in the module -- this business with PORTAUDIO2 wasn't really necessary and
just served to obfuscate.
- Bug fix

cmake: improve FindPortaudio.cmake

---

editors/sc-ide/widgets/main_window.cpp

A small addition.
When the restoreDocuments dialog appears, it currently focuses on the "No" button, so that pressing Enter will discard backups. This feels counter-intuitive, since the dialog is asking if you want to restore those backups, and a positive answer like pressing Enter should be supposed to restore them.
With this PR, Yes is set as default, focused button, so that pressing Enter will restore backups, while Esc will discard them.
Additional note: if anyone wonders about the spacing in this PR, I did run clang-format :)
- New feature

scide: restoreDocuments dialog focuses Yes button

---

HelpSource/editor.js
QtCollider/factories.cpp
QtCollider/widgets/QcWebView.cpp
QtCollider/widgets/QcWebView.h
SCClassLibrary/Common/GUI/Base/QWebView.sc
SCClassLibrary/Common/GUI/tools/HelpBrowser.sc
editors/sc-ide/CMakeLists.txt
editors/sc-ide/widgets/help_browser.cpp
editors/sc-ide/widgets/help_browser.hpp

Fixes #4542 and #4000
Explained more in detail in an RFC and open for discussion. Please let's discuss it, I don't want to push this in any way. I also would really benefit from some other pairs of eyes on it. And it needs testing on Windows.
RFC: https://github.com/elgiano/rfcs/blob/helpbrowser/rfcs/0009-helpbrowser-code-evaluation.md
- fixed code execution in both HelpBrowser class and Widget + in WebView, if the rendered webpage has selectLine()/selectRegion() javascript functions. It works with selected text/line, and with selected text/region.
- code execution in webviews is more consistently delegated to javascript, calling a function to get selected text, receiving it in a callback and then sending it to the interpreter
- a workaround WebView's "funny" keypress behavior, now …

Help Browser code execution

---

server/scsynth/SC_World.cpp
server/scsynth/scsynth_main.cpp
server/supernova/server/main.cpp

fixes #5210
thanks @giuliomoro for the report
tested on Arch Linux, the option appears and is used
- Bug fix
- New feature (kind of a new feature since it wasn't available for a while)

servers: include unistd.h when using _POSIX_MEMLOCK macro

---

server/plugins/LFUGens.cpp
testsuite/classlibrary/TestEnvGen_server.sc

Fixes #5104.
in EnvGen UGen, \hold shaped segments never set their level to their end value. They hold the previous segment's value, and are supposed to switch "instantly" to their endValue at the end of the segment, but that actually never happens in UGen code.
While this PR doesn't make EnvGen output that endValue, it sets it internally before calculating the next segment, to avoid problems with shapes which rely on the the previousEndValue, like linear shapes using it to calculate their grow factor. For example, with:
```Env([0,1,0], curve:[\hold,\lin])```
the linear segment does nothing because it has an endValue of 0 and also a previousEndValue of 0, since \hold didn't ever set it to 1, resulting in a grow factor of 0 for the linear segment, a.k.a noop. Thus, this envelope is …

server: EnvGen: set endValue for shape \hold

---

CHANGELOG.md
README.md
SCVersion.txt

This updates the changelog, readme, and main version number in the repo to prepare for the 3.11.2-rc1 release.
- New feature

Prepare for 3.11.2-rc1

---

QtCollider/QcSignalSpy.h
QtCollider/widgets/QcWebView.cpp

I encountered a problem while working on #4883 : when sclang calls `WebView::runJavascript`, it would fail to get back return values. I digged into it and this is how it works:
- A Function (the callback) is connected to a Qt signal (the onCalled signal of QcCallback)
- A QcSignalSpy is connected to the signal
- When the signal fires, QcSignalSpy gets its arguments, and converts them to a QList<QVariant> to be passed to QtCollider::runLang and from there back to sclang. Since QcSignalSpy receives arguments as a (void**) and their types as a separate argument, it wraps each of them into a QVariant and pushes it to the list.
The problem is that the callback for runJavascript returns a QVariant already, that when wrapped becomes a QVariant<QVariant>, which QtCollider::runLang doesn't know …

qtcollider: QcSignalSpy prevent creating QVariant<QVariant>

---

HelpSource/Classes/WebView.schelp
testsuite/classlibrary/TestWebView.sc

Completing #5216, adding tests for WebView:-runJavaScript return types, and a note in the docs.
- Tests

classlib: WebView.runJavaScript() return types: add tests and docs

---

editors/sc-ide/widgets/help_browser.cpp

fixes #5229
tested here: https://github.com/supercollider/supercollider/issues/5229#issuecomment-720119452
since this only affects the legacy build, which uses a version of Qt we no longer support, it is a harmless change.
- Bug fix

help browser: fix crash on exit with qt 5.9.3 build

---

lang/LangPrimSource/SC_PortMIDI.cpp

Fixes #5199 (well... pending testing... I don't have a Windows build environment so the changes here are not tested).
MIDI system real-time messages should perform a method call like `MIDIIn.doSysrtAction(code, data)` -- internally, this means four items go onto the stack: the receiver, method selector and two arguments.
SC_PortMIDI.cpp currently pushes three items onto the stack (receiver, method selector, and a data value *without* the message type number) -- but then specifies four stack values to be processed. Because one of those stack entries doesn't exist, it segfaults.
I'm not able to test in Windows.
I discovered this by accidentally replicating the crash in Linux (by deleting the message type argument, without changing the number of stack entries). I'm fairly confident but …

sclang: MIDI realtime messages: Push correct number of values onto the stack

---

HelpSource/Classes/ServerOptions.schelp
HelpSource/Reference/AudioDeviceSelection.schelp

On Windows, setting `sampleRate` to `nil` for `ASIO` devices does not result in using hardware sample rate.
I believe other APIs default to a mix of 44100 or 48000 and use resampling if needed, but I might be wrong; I'm documenting only for ASIO here, as I'm sure this is the behavior with this API.
Suggested in https://www.listarc.bham.ac.uk/lists/sc-users/msg68893.html
EDIT: I manually cancelled builds since this is a help-only PR

note about default sample rate on Windows

---

HelpSource/Classes/SynthDef.schelp
SCClassLibrary/Common/Audio/SynthDef.sc

supersedes the broken PR: #5236
Currently, the warning:
```
WARNING:  SynthDef lalala too big for sending. Retrying via synthdef file
```
is more irritating than useful. This patch removes it in the default case.
An option is left to switch it on for debugging purposes.

class library: don't warn by default when sending SynthDef

---

HelpSource/Classes/ServerOptions.schelp
SCClassLibrary/Common/Control/Server.sc
include/server/ErrorMessage.hpp
include/server/SC_OSC_Commands.h
include/server/SC_WorldOptions.h
server/scsynth/SC_CoreAudio.cpp
server/scsynth/SC_CoreAudio.h
server/scsynth/SC_World.cpp
server/scsynth/scsynth_main.cpp

Related to #4894.
Proposes a fix for CoreAudio handling of loud volumes. Since CoreAudio only applies a relative attenuation, setting a low system volume doesn't prevent output values > +- 1 from sounding absolutely loud, possibly leading to hear damage.
This PR attempts to fix it by:
- introducing a new ServerOption + cli switch: `-s safetyClipThreshold`
- clipping values between +-safetyClipThreshold when CoreAudioDriver writes out
- safetyClipThreshold defaults to 2.0 to allow some headroom and save some ears
Although clipping affects inter-app routing (as it happens through the same out busses), it doesn't affect recording.
Note: `s.options.safetyClipThreshold = inf` is valid (thx c++!) and makes clipping ineffective
This is initially macos only. Any consideration about making it …

scsynth: macOS: clip values on hw out busses

---

.github/workflows/actions-test.yml

Add GitHub Actions CI for linux and macOS. See #5261 for prior discussion
Implemented:
- build matrix for both linux and macOS (mostly complete)
- ccache (cached between builds)
- linting
- artifact names use either tag or commit sha (if tag is not present)
todo:
- upload/publish nightly builds
not implemented / for later:
- run tests
- create windows builds
- fix macOS legacy builds
- automatic deployment
Notes:
- I think we need a new label. Should it be "GitHub Actions", "GHA", "Actions" or maybe just "CI"?
- Most names (like names of steps etc) are starting lowercase now. Is this OK or should they start with a capital letter?
- For nightly builds: we either need to upload them to S3, or maybe there's a way to use some external script with [GH …

GHA: add github actions for linux and macos

---

HelpSource/Classes/LinuxPlatform.schelp
HelpSource/Reference/AudioDeviceSelection.schelp
SCClassLibrary/Platform/linux/LinuxPlatform.sc

Fixes https://github.com/supercollider/supercollider/issues/5260
This PR makes it possible to set the Jack environment variables on Linux to let SC automatically connect it's inputs and outputs to other jack nodes on startup. These were hardcoded to be "system" by default and were never checked by the system but they are with this PR.
The usage of these has been documented as well in the LinuxPlatform help file. 
- Bug fix

Make Jack Startup environment variables usable.

---

SCClassLibrary/Common/Audio/SynthDesc.sc

Fixes #5276.
It turns out that SynthDesc, when building a UGen object from a binary graphdef stream, has always been creating demand units with rate = `nil`.
By chance, this never threw an error -- but the error was exposed by the first multi-out demand unit to be added into sc3-plugins.
Simple fix: Just provide `\demand` in the table that converts a rate index to a symbol.
- Bug fix

Classlib: SynthDesc should produce a valid rate symbol for DUGens

---

.github/workflows/actions.yml

Previously `ccache` cache would never be updated between builds, save for manually changing the cache file key. With this PR `ccache` cache will be updated daily.
I also added caching homebrew downloads. Some observations on that:
- homebrew downloads seem to take ~~>3.5GB (!)~~ EDIT: it seems there were previous downloads there; I added cleanup step before caching them, now it's ~250MB
~~- I _think_ most of that is `FFTW`'s dependencies, but haven't checked closely~~
~~- retrieving cache happens at varying speed, sometimes it seems to take longer than re-downloading the files from their original locations... but I think it's still better to use cache, right?~~
- I've set homebrew download cache to reset monthly, to cache possible package updates etc.
- I've also moved the archive name …

GHA: refresh ccache daily, add homebrew download cache

---

server/scsynth/SC_CoreAudio.cpp

See discussion in #5168
In macOS Big Sur, the clock provided by `high_resolution_clock` (using `mach_absolute_time`) drifts apart from the host time reported by CoreAudio. This is most apparent after a computer running Big Sur is in sleep mode for a bit, causing sounds from SuperCollider to be played after their scheduled time roughly by the amount of time the computer slept.
This change makes it so that the time of day offset is calculated against the CoreAudio host time (instead of `high_resolution_clock` time) since that offset is later used against the CoreAudio host time to get OSC time.
This commit effectively reverts the changes in 95a6604.
I read through the [wiki page](https://github.com/supercollider/supercollider/wiki/Creating-pull-requests) for making pull requests (and didn't …

scsynth: use CoreAudio host time to calculate time of day offset

---

.travis.yml

It seems that #5234 was incorrect... sorry about that.
As a result, the [latest develop build](http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/develop-latest.html) links to ba3cb869536ff11b623ef683644502b1e77d220f, which is just before https://github.com/supercollider/supercollider/commit/71ef241bf0ca0d945f1cec91e0578a30ca9555a8, or #5234; the latest develop link hasn't been updated since then...
This should fix it. The link from this branch works: http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/osx/topic/fix-latest-develop-build-link-latest.html
Sorry again for my previous mistake! :-)
- Bug fix

travis: fix latest develop link

---

HelpSource/Reference/NodeProxy_roles.schelp
SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc

Fixes #5291 
Following a conversation with @adcxyz here are some tests and the proposed fix:
```supercollider
// tests for filter vs filterIn roles: 
(
// test sig at full level
Ndef(\x)[5] = { 
LFPulse.kr(3, 0, 0.2)
* SinOsc.ar(LFNoise0.kr(3!2).exprange(200, 2000))
};
// comb filter as simplest ringing FX - use \filter here:
Ndef(\x)[10] = \filter -> { |in| CombL.ar(in, 0.03, 0.03, 2) };
Ndef(\x).play;
s.scope;
)
Ndef(\x).set(\wet10, 1); // full wet, just comb signal
Ndef(\x).set(\wet10, 0.5); // 50/50 mix
Ndef(\x).set(\wet10, 0); // just dry signal - ringing comb is cut off
///// same tests with filterIn: 
// comb filter as simplest ringing FX:
Ndef(\x)[10] = \filterIn -> { |in| CombL.ar(in, 0.03, 0.03, 2) };
Ndef(\x).set(\wet10, 1); // full wet, just comb signal
Ndef(\x).set(\wet10, …
```

class library: wetamp should not affect output of \filterIn function

---

HelpSource/Classes/Env.schelp
SCClassLibrary/Common/Audio/Env.sc

When specifying envelope as control points, one needs to specify curve for each point. With this PR, curve parameter can be omitted, in which case `\lin`ear curve will be used.
- New feature

Env xyc: use default curve

---

external_libraries/portaudio/CMakeLists.txt

Fixes #5315
add `remove_definitions(-DNOMINMAX)` for mingw in CMakeLists.txt on portaudio folder
previously added with: https://github.com/supercollider/supercollider/blob/develop/CMakeLists.txt#L132

portaudio: mingw needs MINMAX

---

server/scsynth/SC_UnitDef.cpp

`Unit_DoCmd` didn't set `gMissingNodeID`, so when we try to run a unit command on a non-existent node, the error message would contain a wrong node ID.
- Bug fix

\u_cmd: make sure to print correct node ID in case of an error

---

HelpSource/Reference/NodeProxy_roles.schelp

Fixes a typo in the `NodeProxy_roles` help file.

Topic: Help: NodeProxy: fix pset typo [skip ci]

---

SCClassLibrary/Common/Control/Server.sc

Previously `Server.remote` was not instantiating connection properly when using the TCP protocol. `Server.remote` is all that's needed to use a remote server when using UDP. My understanding is that it also should be the case for TCP.
This PR attempts to fix the issue with TCP. I'm not 100% sure this is the correct fix, but it does seem to work as expected.
Here's one way to test this locally by starting the server using `.unixCmd` and connecting to it as if it was a remote server:
```supercollider
// start the server
~serverPid = "/Applications/SuperCollider.app/Contents/Resources/scsynth -t 57110".unixCmd({"server command finished".postln}); // on macOS; NOTE we assume that SuperCollider.app is directly in /Applications - adjust the path if needed
// or
~serverPid = "scsynth -t …
```

class library: fix TCP connection in Server.remote

---

SCClassLibrary/Common/Streams/Patterns.sc

https://scsynth.org/t/calling-supercollider-script-from-windows-batch-file/2964/8 reports that an audio file produced by `pattern.record` begins with some silence, where a reasonable expectation would be that the recording begins exactly at the onset of the pattern's audio.
This is because `pattern.record` uses the convenience class Recorder, so it gives up control over the exact moment of launching the recording synth.
I posted an alternate version on the forum, and it was only a couple more minutes to turn it into a PR.
Tested with:
```supercollider
Pbind(\degree, Pseries(0, 1, 8), \dur, 0.5).record("~/tmp/testzzz.wav".standardizePath, "wav", "int16");
```
... and the file is produced correctly, with no gap at the beginning.
- Bug fix

Classlib: Pattern:record should sync recording synth to pattern synths

---

.github/workflows/actions.yml
testsuite/classlibrary/TestAbstractFunction.sc
testsuite/classlibrary/TestOSCBundle.sc
testsuite/classlibrary/TestSanitize.sc
testsuite/classlibrary/TestServer.sc
testsuite/scripts/gha_test_run_proto.json
testsuite/scripts/run/.gitignore

This PR implements running our full test suite in GitHub Actions on Linux and macOS. It is another milestone in implementing #5261. Fixes #3132, supersedes #4749.
Result: `3036 TESTS PASSED`, as reported by the [GH runner](https://github.com/supercollider/supercollider/pull/5332/checks?check_run_id=1803991060#step:8:18085).
In the process on working on this, I have discovered numerous issues, some of them are fixed, while others are "patched" in this PR, yet others are still in place and documented below.
We are using [qpm](https://github.com/supercollider/qpm) for running the test suite. @patrickdupuis's work on #4749 was a big help to understand how it works. 
Qpm uses the following [SuperCollider code](https://github.com/supercollider/qpm/blob/topic/xvfb-temp-fix/qpm/scscripts/test_runn …

GitHub Actions: add test suite

---

HelpSource/Classes/TempoClock.schelp

`beatsPerBar` help explains: "Setting must be done from within the scheduling thread" -- this is less than clear. (E.g., a user recently asked if it was necessary to `sched` or `schedAbs` -- it isn't -- but it requires a fair degree of advance knowledge to be sure from reading this.)
Added further explanation and examples.

Help: TempoClock:beatsPerBar, explain "scheduling thread" better

---

cmake_modules/MacOSXBundleInfo.plist.in

On macOS, builds with Qt 5.15.2 were not triggering the "Microphone permissions" dialog in Catalina and Big Sur, and thus did not have access to audio input.
Adding the appropriate field to the `info.plist` file seems to fix this issue. In my testing with this fix SC asks for correct permissions whether the build is signed or not.
Thanks @brianlheim for suggesting this!
- Bug fix

macOS info.plist: add microphone access prompt

---

README_LINUX.md

Nothing controversial -- old version says "for clang 4, pass `-DSC_ALBETON_LINK=OFF` when configuring the project" but that is unlikely to succeed.

README_LINUX: Fix typo about SC_ABLETON_LINK option

---

platform/linux/CMakeLists.txt

I am working on a [flatpak manifest for SuperCollider](https://github.com/jmaibaum/flathub/tree/io.github.SuperCollider) (using the pipewire jack replacement libraries on the host). `flatpak-builder` doesn't like icons to be stored in `share/pixmaps/*`, but looks for them in `share/icons/hicolor/*` only. Freedesktop's specifications are a little bit unclear in this regard, but one can find relevant lines, for example https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s07.html:
> ## Installing Application Icons
> 
> So, you're an application author, and want to install application icons so that they work in the KDE and Gnome menus. Minimally you should install a 48x48 icon in the hicolor theme. This means installing a PNG file in $prefix/share/icons/hicolor/48x48/apps. …

Linux packaging: Install icons into share/icons/hicolor/*

---

editors/sc-ide/core/sc_introspection.cpp
editors/sc-ide/core/sc_introspection.hpp
editors/sc-ide/widgets/code_editor/autocompleter.cpp
editors/sc-ide/widgets/code_editor/highlighter.cpp
editors/sc-ide/widgets/lookup_dialog.cpp

Previously, scide would highlight any token beginning with an uppercase letter as a class.
This can be very confusing when learning SC.
This PR checks introspection to ensure the class exists before highlighting.
* Uses Introspection::findClass rather than findClassPartial
* findClassPartial uses QString::contains, so produces false positives
* ~~This required adding a bool to findClass to allow the suppression of the status message warning about not finding the class~~
* This required removing the warning from `findClass` and adding `findClassOrWarn` to allow suppression of the warning message.
- Bug fix
technically a bug fix? more a behaviour change

[scide] fix classname highlighting

---

HelpSource/Classes/Nil.schelp

This came up on Slack as the source of a bug in some user code.
`Nil` cannot be `nil`, so using it in comparisons doesn't produce the results one might expect.
This PR adds a note to the helpfile for `Nil` to clarify usage.

[docs] add note about comparing Nil and nil

---

HelpSource/Classes/Pbind.schelp

this responds to a couple threads on forums [here](https://llllllll.co/t/supercollider-tips-q-a/3185/416) and [here](https://scsynth.org/t/in-pbind-alternative-syntax/3262) where it seems the wording in Pbind documentation is confusing to readers. this PR attempts to clarify the wording and also adds links to relevant documentation.

doc: clarify syntactic shortcuts in Pbind documentation

---

.github/workflows/actions.yml

Further implementation of #5261
This PR adds deployment steps for our GitHub Actions workflow, making it pretty much complete for Linux and macOS.
Here's an example of a build from this branch: [commit](https://github.com/supercollider/supercollider/actions/runs/587998211) and [tag](https://github.com/supercollider/supercollider/actions/runs/587999778).
(it seems that the release artifacts have been since overwritten by Travis... but I can attest they were uploaded properly beforehand)
Here are some implementation notes for a possible discussion before merging:
- both GH release deployment for releases, as well as S3 upload for all commits is implemented in a single job
- the deployment job runs either in the main repo, or for tagged commits (in all repos/forks)
- for GH release uploads I …

GitHub Actions: add deployment to GH releases and S3

---

testsuite/scripts/gha_test_run_proto.json

Exclude only `test_nodeMap_controlNamesConvertsObjectToControlInput` from `TestProxyNodeMap`
See https://github.com/supercollider/supercollider/pull/5368#issuecomment-787510733
- Bug fix

exclude a specific failing test in TestProxyNodeMap

---

README.md

In #5374 I forgot to add the GitHub Actions link to the badge. 
Since we are going to remove AppVeyor soon, I've also removed its badge.
EDIT: I cancelled CI since this is a docs-only change (and I forgot to add `[skip ci]` to the commit message)
- Bug fix

README.md: add link to github actions, remove appveyor badge

---

.github/workflows/actions.yml
CMakeLists.txt
cmake_modules/FindSndfile.cmake

Further implementation of #5261
This PR adds Windows guilds to our GHA
Notes, particularly highlighting differences with our AppVeyor builds:
- we use [chocolatey](https://chocolatey.org/) to install `libsndfile`
- `FindSndfile.cmake` needed to be updated to include different search paths
- we are effectively using a newer version of the library, I think
- this is arguably cleaner than the way we installed libsndfile in appveyor :)
- both 32- and 64-bit builds use Qt 5.15.2
- added `/Zc:__cplusplus` switch for MSVC (thanks @brianlheim and @jrsurge !)
- `fftw` and `ASIO` for portaudio are installed manually, as before
- installer creation is triggered for tagged builds only
- build artifacts (non-installer zip) are uploaded to s3
- both the installer and the non-installer zip is uploaded …

GitHub Actions: add Windows builds

---

.github/workflows/actions.yml

It seems that GHA runners [updated homebrew qt to version 6](https://github.com/dyfer/supercollider/runs/2033649718?check_suite_focus=true#step:11:49). This PR fixes our builds, specifying `qt5` for homebrew.
- Bug fix

GitHub Actions: use qt5 on macOS

---

.github/workflows/actions.yml
CMakeLists.txt
editors/sc-ide/CMakeLists.txt
lang/CMakeLists.txt

Fixes #5294
Because `verify_app` fails for builds done with the official Qt (as opposed to the one from homebrew), we disable it by default and add a cmake switch to turn it back on.
See https://github.com/supercollider/supercollider/issues/5294#issuecomment-791988719 for more details
In this PR:
- `SC_VERIFY_APP` cmake flag is added on macOS, defaulting to OFF
- the implementation of that flag is not the most elegant, I'm open to suggestions
- `SC_VERIFY_APP`is turned ON in CI
- `rpath` settings in cmake are defined specifically for the `libscide` and `libsclang` targets
- Bug fix

Make verify_app optional, improve rpath setting

---

editors/sc-ide/CMakeLists.txt

Addendum to #5388
Since we are adding various ["fixup" steps](https://github.com/supercollider/supercollider/blob/develop/editors/sc-ide/CMakeLists.txt#L505) to `VERIFY_CMD`, I shouldn't have completely removed it when skipping verification. This PR fixes this issue, so that only `verify_app` is conditionally included/excluded.
- Bug fix

cmake: fix verify_app switch

---

.github/workflows/actions.yml
editors/sc-ide/CMakeLists.txt

#5294 was a roadblock in offering macOS legacy build in GitHub Actions. Now that that issue is resolved, it's possible to offer legacy build again. Legacy build uses "official" Qt distribution, since there's no easy way to add Qt 5.9 from homebrew to GH runners, which run macOS 10.15.
Deployment should work, though it was not explicitly tested for this addition.
I've also moved the position of the `aqtinstall` step to match the structure on Linux.
~~EDIT:
I guess it does not work, something is indeed wrong with the `rpath`. When trying to run the legacy build downloaded from Actions, I am getting~~
<details>
```sh
dyld: Library not loaded: @rpath/QtConcurrent.framework/Versions/5/QtConcurrent
Referenced from: /path/to/SuperCollider.app/Contents/MacOS/SuperCollider
Reason: image not found …
```

GitHub Actions: add macOS legacy build

---

HelpSource/Classes/EnvGen.schelp

Clarify when EnvGen samples its inputs. The observed behavior, and inspection of [EnvGen code in LFUGens.cpp](https://github.com/supercollider/supercollider/blob/develop/server/plugins/LFUGens.cpp#L2386) reveals that EnvGen arguments and the associated envelope are sampled at the start of each segment. The existing documentation is clear about this in the descriptions of the `levelScale`, `levelBias`, and `timeScale` arguments, but the main description and the description for the `envelope` parameter are less clear.

docs: clarify that EnvGen samples args per segment

---

README_BELA.md
README_LINUX.md
server/plugins/BelaUGens.cpp

Fixing some Bela related issues. The most pressing one was that `DigitalIn` was broken since a refactoring in d75aa123fa.
The others are in the docs.
- Documentation: added mention of Bela to the Linux README; tell `cpack` to strip symbols.
- Bug fix: fixed `DigitalIn`

Bela: various fixes

---

HelpSource/Classes/ContiguousBlockAllocator.schelp
SCClassLibrary/Common/Control/Engine.sc
SCClassLibrary/deprecated/3.12/deprecated-3.12.sc

A question arose on the forum about ContiguousBlockAllocator's `findNext` method where the answer wasn't evident in the code or the documentation.
Also, at the time I wrote this class, I favored "method call" syntax for `if` -- which I now find to obscure meaning. It had been in the back of my mind to clean up the code style for readability.
At the same time, it's a good opportunity to add comments explaining some of the implementation details, and expand the help file.
The only functional change is to deprecate `findNext` and `findPrevious` in favor of `pr*` versions (i.e. explicitly marked private). Users should not be calling these methods directly.
- Breaking change (deprecation)

 ContiguousBlockAllocator cleanup (code style, help)

---

lang/LangPrimSource/PyrSched.cpp

The `sclang` command sometimes hangs when exiting when run with a file that exits. This PR makes a small adjustment to how the scheduler thread in `PyrSched.cpp` coordinates with the main thread to eliminate this race condition.
- Bug fix
The `sclang` command sometimes hangs when exiting when run with a file that exits. This PR makes a small adjustment to how the scheduler thread in `PyrSched.cpp` coordinates with the main thread to eliminate this race condition.
I'm building SuperCollider to run on Linux without QT or X11 present so that I can run `sclang` in a an automated test suite in a container on GitLab CI for a project I'm working on. I'm using nix to build SuperCollider with the following command and derivation (`.nix` file). I've included a patch to add logging statements to …

Fix bug where sclang hangs forever when exiting

---

CMakeLists.txt
common/server_shm.hpp

It's an attempt to fix #2409
It seems that on Windows server's shared memory interface can be broken (way too easily IMO) by missing logs.
~~This PR overrides boost's shared memory creation function and uses a fixed location in SC Resource Directory.
**I'm not sure if this is the correct fix**, however I was able to reproduce the bug from #2409 (*) and I can confirm that this PR fixes it. The fix was adopted from https://stackoverflow.com/questions/39742630/boost-shared-memory-cant-be-initialized~~
EDIT: after lengthy tests and back-and-forth with @brianlheim it looks like boost also provides another method for obtaining the stamp for the shm location, enabled by defining `BOOST_INTERPROCESS_BOOTSTAMP_IS_SESSION_MANAGER_BASED`. This seems to fix the issue on my system and seems like the …

Servers: workaround for boost interprocess

---

.github/workflows/actions.yml

Fixes #5278 (to some extent at least)
This is a basic version of idea from https://github.com/supercollider/supercollider/issues/5278#issuecomment-742248040
While currently created DMG does not have a custom background and instructions to drag SuperCollider to `/Applications`, it still prevents the user from dragging whole folder, as the folder is replaced by disk image.
I've also chosen `bzip2` compression for the archive, as this has resulted in the file size most closely resembling the previously used `.zip` (it's larger by just a couple of MB).
~~The fix will be "operational" once we fully migrate to github actions for macOS deployment.~~
EDIT: I've added a link to `/Applications`, as requested
- Bug fix

Create dmg for macOS artifacts

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

There was an issue with displaying labels in plots. 
An example code from ```Plotter```  help file in ```.setProperties``` method now does exactly what was inteded.
This PR fixes displaying the labels, in this case the "Humidity" string on X axis.
```
(
a = { (0..30).scramble }.dup(2).plot;
a.setProperties(
\fontColor, Color.red,
\plotColor, Color.blue,
\backgroundColor, Color.black,
\gridColorX, Color.white,
\labelX, "Humidity"
);
a.refresh;
);
```
- Bug fix
- [ X] Code is tested
- [X ] All tests are passing
- [X ] This PR is ready for review

Classlib: Fix displaying labels in Plotter

---

README_LINUX.md

Document that `sclang` can be run without X server when `QT_QPA_PLATFORM` env variable is set.
This is meant to "fix" #5420

README_LINUX.md: add note about headless operation

---

.github/workflows/actions.yml

It seems that we don't need the `QT_PLATFORM_PLUGIN` environment variable when running tests in GHA, for two reasons:
- it is meant to be used when there's no X display, however we do run a virtual X display with `xvfb`
- looking online it seems that it should've been `QT_QPA_PLATFORM` instead anyway... `QT_QPA_PLATFORM` seems to be the variable to set if one wants to use the "offscreen" plugin. If I set `QT_QPA_PLATFORM=offscreen`, I can run `sclang` in terminal without X (on Linux)
- Bug fix

gha testsuite: remove environment variable

---

SCClassLibrary/Common/Core/Function.sc
testsuite/classlibrary/TestFunction.sc

when calling a UGen function from within a SynthDef, the arguments should be converted to controls with default values. For this, we have to use `SynthDef.wrap`
Fixes #5435 
- Bug fix

fix function plot when called with unspecified arguments

---

HelpSource/Classes/CondVar.schelp
SCClassLibrary/Common/Core/CondVar.sc
testsuite/classlibrary/TestCondVar.sc

Cleaned up PR #5394
Description from the commit message:
A condition variable implementation that intends to replace Condition.
Main features:
- a more intuitive interface
- stronger guarantees about exception safety and blocking/unblocking
conditions
- predicates are given per-wait instead of per-object
- timeouts
- more closely matches classic condition variable design and what's
found in other implementations
- New feature

Add CondVar redux

---

editors/sc-ide/widgets/code_editor/highlighter.cpp
editors/sc-ide/widgets/code_editor/highlighter.hpp

This aims to fix issue #5434.
Introduced in #4890 on develop, classnames would not highlight correctly if a file was opened before introspection was available.
This PR prevents highlighting until introspection is available, and triggers highlighting when introspection changes.
The classname highlighting was broken and formatted everything beginning with an uppercase letter.
The changes in #4890 mean that  classnames now have to exist before being highlighted, which means we need to wait for introspection before highlighting them.
It would highlight things incorrectly and then magically correct itself, which could be confusing.
Ultimately, I think it would be more confusing to have a file partially highlight and then have things magically appear.
* A file would have different highlighting …

[scide] Fix classname highlighting before introspection available

---

.github/workflows/actions.yml

We are getting random build failures on macOS while using the `hdiutil` command to create the archive, see https://github.com/supercollider/supercollider/runs/2495736121?check_suite_focus=true#step:14:15 
I couldn't find the reason of these failures... so for now I propose that we just run the command again in case it fails. 
- Bug fix

GHA: run hdiutil again if it fails

---

HelpSource/Classes/Slider.schelp

One example had excessive indentation, which prevented code-block execution from the Help Browser

docs: fix slider example indentation [skip ci]

---

editors/sc-ide/CMakeLists.txt

Due to a recent change in library version we need to update the paths we are manually fixing in our build script. The failure can be observed here: https://github.com/supercollider/supercollider/runs/2578525954#step:13:20667
- Bug fix

build system: fix path to libgcc v 11

---

SCClassLibrary/Common/Core/CondVar.sc

This PR fixes a data race that can happen when a `CondVar` is signaled immediately as it is timing out. The problem is easy to reproduce:
```supercollider
(
var cond = CondVar();
var test = false;
var waitTime = 1.0;
fork {
waitTime.wait;
cond.signalOne;
};
fork {
cond.waitFor(waitTime, { test });
"waitFor timed out".postln;
};
)
```
An error is thrown because the time out mechanism is trying to wake a thread that has already been woken by the signal. `this.prRemoveWaitingThread(waitingThread);` returns `nil` in this case, so `this.prWakeThread(wokenThread);` throws an error having received a `nil` value.
It doesn't look like this change has any adverse effects. `TestCondVar.sc` is still passing. I tried to write a test for this issue, but couldn't figure out a way to write one using …

Fix data race in CondVar timeout

---

HelpSource/Classes/UnitTest.schelp
SCClassLibrary/Common/UnitTesting/UnitTest.sc
testsuite/classlibrary/TestCoreUGens.sc
testsuite/classlibrary/TestDocument.sc
testsuite/classlibrary/TestEnvGen_server.sc
testsuite/classlibrary/TestFilterUGens.sc
testsuite/classlibrary/TestNode_Server.sc
testsuite/classlibrary/TestOSCBundle.sc
testsuite/classlibrary/TestPprotect.sc
testsuite/classlibrary/TestSanitize.sc
testsuite/classlibrary/TestServer.sc
testsuite/classlibrary/TestServer_boot.sc
testsuite/classlibrary/TestUnitTest.sc
testsuite/classlibrary/TestWebView.sc
testsuite/classlibrary/server/TestMixedBundleTester.sc
testsuite/scripts/gha_test_run_proto.json

Fixes #5366
This PR removes all but one use of `UnitTest.wait` inside our test suite (the exception being testing that method itself). `CondVar` is used as a preferred alternative. I've updated the documentation, and added comments and notes pointing users towards `CondVar`.
I've also re-written the implementation of `UnitTest.wait`. This method no longer makes use of `Condition` as this Class is likely going to be deprecated in the future (or at least no longer be used inside the SC class library).
- Bug fix
- Breaking change (maybe?)

Use CondVar instead of UnitTest.wait in tests

---

SCClassLibrary/Common/Control/Buffer.sc
testsuite/classlibrary/TestBuffer_Server.sc

There is a bug in `Buffer.getn` that causes it to not call the `action` if the index passed in is a float. This happens because the OSC message generated casts the value to an integer, but the `argTemplate` does not.
#4598 did a large pass over the Buffer methods to try to make them all properly cast to integer in the right places, but it appears that this location was missed.
To repro the issue (and verify that it is fixed):
```sc
(
s.boot;
s.waitForBoot({
b = Buffer.alloc(s, 10);
s.sync;
b.getn(0.0, 10, {|msg| msg.postln}); // Doesn't print anything without this fix
});
)
```
- Bug fix

Fix bad argTemplate in Buffer.getn

---

.github/workflows/actions.yml
SCClassLibrary/Common/UnitTesting/UnitTest.sc
testsuite/scripts/gha_test_run_proto.json

This PR fixes an issue where a test class' `setUpClass` and `tearDownClass` functions aren't being called. To reproduce the issue, try running the following:
```supercollider
// reboot the interpreter before running this
UnitTest.runTest("TestUnitTest:test_setUpClass_already_happened")
```
`setUpClass` and `tearDownClass` are being run on `UnitTest` not `TestUnitTest`. To fix this, I've called `prRunWithinSetUpClass` on `class` instead of `this` in a couple places inside `UnitTest`.
This seems to work, however, I'd appreciate having another pair of eyes on this. I can't tell if this change will have any unforeseen side-effects, or if the same change needs to be made elsewhere.
- Bug fix

Fix test setUpClass and tearDownClass not being called

---

.github/workflows/actions.yml

It seems that macOS builds [fail again](https://github.com/supercollider/supercollider/runs/2713058604?check_suite_focus=true#step:14:20) due to an issue with `hdiutil`.
My assumption in #5462 was incorrect - `hdiutil` sometimes fails _before_, not after creating an image. This PR brings back the fix (more like a workaround) introduced in #5439.
- Bug fix

gha macos: run hdiutil again if it fails

---

lang/CMakeLists.txt

Original configuration would add `-D-flto -D-flto-report` to CFLAGS when building sclang, resulting in compilation failing.
LTO builds don't work properly with current cmake configuration, this PR fixes this issue.
- Bug fix
N/A, change is trivial.

Fixed LTO builds failing due to incorrect flags.

---

HelpSource/Classes/Server.schelp

Fix for Server.remote example. SeverOptions object is already an holder for 'options' so this is fix for this small mistake.

docs: Server.remote example bug

---

.github/workflows/actions.yml

Fixes #5510
It turns out that `libsndfile` installed with homebrew doesn't work on macOS <10.14. One option is to build libsndfile ourselves, specifying an earlier deployment target. This adds ~90 seconds to our macOS build time.
I'm open to suggestions whether this is the right solution.
I've tested this on macOS 10.13, using the example in the linked issue.
- Bug fix

GitHub Actions: build libsndfile on macos

---

.github/workflows/actions.yml

Fixes #5505
This PR fixes the following issues:
- macOS binaries were not uploaded to the release page
- Windows installers were not created on tagged commits
I've also incorporated changes from #5452, triggering builds only for code changes (i.e. not for changes in `HelpSource` etc). These were tested previously (see #5452) except for the release process, but for this PR I've tested the release, effectively testing all the changes at once. If desired, I can remove changes from #5452 from this PR, please let me know, but I thought testing them on a release should be enough to get them in as well.
(One thing to note about the change to the CI is that documentation changes _only_ will not trigger new experimental builds (i.e. builds from the `develop` branch), which I'm fine with, but I …

GitHub Actions: fix Windows installer creation, release uploads

---

HelpSource/Classes/PMOsc.schelp

Provide improved description of pmindex argument in PMOsc help file. This value is not measured in radians; it represents the ratio of modulator deviation to modulator frequency.

docs: modify description of pmindex argument

---

testsuite/classlibrary/TestSynthMapping.sc

This makes sure that node order doesn't matter for audio rate mapping, up to block delay.

test: add test for audio rate controls

---

.github/workflows/actions.yml

Fixes #5536
There seem to be 2 issues with the current macOS legacy build:
- it uses APFS, unsupported on older systems
- even though we build `libsndfile` ourselves, it depends on `libvorbis` and other libraries provided by homebrew.
I propose to change this by building all of the libsndfile's dependencies ourselves (libvorbis, libogg, flac, opus). I've also changed filesystem in the DMG to HFS+.
Currently in this PR all of the libsndfile's dependencies (libvorbis, libogg, flac, opus) **are build as static libraries.** `libsndfile` itself stays as shared library. Please let me know what you think about this. [I was having problems](https://github.com/dyfer/supercollider/runs/3268243473?check_suite_focus=true#step:14:21666) when they were all shared libraries.
~~I'm still testing whether …

Build libsndfile's dependencies and change DMG filesystem

---

SCClassLibrary/Platform/linux/LinuxPlatform.sc

This adds to the awesome work made on the LinuxPlatform class in 3.12 where .runInTerminal was improved and had default terminals added to it. The list is missing two (gpu accelerated and) popular terminals: kitty and alacritty and so this is a simple PR that adds those two
- New feature

Add kitty and alacritty to list of Linux terminals

---

HelpSource/Reference/Control-Structures.schelp

Updates Control Structures help:
1. At one point we had a code style guideline document. (Aside: Has this been deprecated intentionally? https://supercollider.github.io/contributing/ links to https://supercollider.github.io/development/code-style-cpp.html but "Sorry this page does not exist =(.") In that document, we recommended trailing-closure syntax for control flow structures. But, Control Structures help consistently recommended e.g. `if(expr, trueFunc, falseFunc)` which... basically nobody writes it like that anymore. So I updated all the syntax examples to put trailing-closure syntax first, and present others as alternatives.
2. The `switch` section claims that an equality `==` test is always used. But, if it's inlined, the hash lookup is based on identity. This has actively misled …

Update errors and outdated usages in Control Structures help

---

.github/workflows/actions.yml

Steinberg has [updated their website](https://twitter.com/SteinbergMedia/status/1429046887726866435?s=19) recently and the download link for the ASIO library has changed. The new link is https://www.steinberg.net/asiosdk and seems to redirect to the latest SDK. This PR updates the download link in GitHub Actions so that Windows builds work again.
- Bug fix

GitHub Actions Windows: update ASIO download

---

.github/workflows/actions.yml

Working on sc3-plugins GitHub actions, I noticed that the platform for creating MSVC FFTW library (Windows) was [set incorrectly](https://github.com/supercollider/supercollider/runs/3107869909#step:8:27) for the 32-bit build. The reason it worked was that it defaulted to `x32`. I've also streamlined FFTW installation - the zip is downloaded straight to the proper `Program Files` location and expanded there. The msvc library is created in the same location.
~~It's not crucial that it gets into 3.12, but it's a relatively simple fix so it might as well... let me know what you think.~~ Maybe let's not risk anything, I've changed base to `develop`.
I've tried the Win32 build, started the server, run `Tartini`, and it seems to work fine.
- Bug fix

GHA updates - FFTW on Windows

---

HelpSource/Classes/PathName.schelp

The code example references GetFileDialog instead of the correct FileDialog.

Fixing PathName documentation

---

server/scsynth/SC_MiscCmds.cpp

- g_head should always fire an n_move reply,
even if the parent group remains the same.
This is in line with the other commands such
as g_tail, and ensures that a client can build
a copy of the tree structure by observing the
server's n_move notifications.
fixes #5579
- Bug fix

fixes #5579

---

QtCollider/widgets/QcRangeSlider.cpp
QtCollider/widgets/QcRangeSlider.h

Fixes issue #3696. The proposed change makes it possible to
adjust the height / width of a RangeSlider by using stretch
factors. The behaviour of RangeSlider will then match the behaviour
of Slider.
Fixes #3696
- Bug fix

GUI: QcRangeSlider: fix stretch behaviour

---

SCClassLibrary/Common/Audio/BufIO.sc

To prevent unintentional changes in pitch due to the difference between the system samplerate and the buffer samplerate.
- Bug fix

fix: Tap Ugen samplerate compensation with BufRateScale.kr()

---

.github/workflows/actions.yml

It looks like an [issue with aqtinstall](https://github.com/jurplel/install-qt-action/issues/67) action resurfaced. 
This PR fixes macos legacy builds (and in turn enables testsuite again, which didn't run because of the failed build).
- Bug fix

GitHub Actions: fix macos legacy build

---

.github/workflows/actions.yml
lang/LangPrimSource/SC_CoreMIDI.cpp

This reverts commit c6790a9168be1972724034e79f83d53ef4f0399c, reversing changes made to 13be6e8202674a98d0e20b58201ec10763515de3.
Fixes #5622
See linked issue for explanation and details.
I also cherry-picked CI commit that fixes the macOS legacy build.
I'm suggesting to merge this into `3.12` branch in order to release `3.12.2` with this fix, but I'm open to suggestions about this.
- Bug fix

Revert #4725 - MIDI use logical time on macOS

---

.github/workflows/actions.yml

I've originally set artifacts produced by GitHub Actions to expire rather quickly, after 7 days.
I think this time could be extended (e.g. I wanted to check out a build from a PR from 10 days ago and the artifact was no longer there). 
Moreover, I see now that the default retention period can be set in the repository preferences (Settings -> Actions).
In that case, I proposed that we remove the hardcoded retention time from the actions yaml file and instead rely on the time set in preferences. This way it will also be individually configurable in forks, I believe.
I've set the retention time in the settings of the main repo for 30 days.
- Maintenance

GHA: remove retention time for GHA artifacts

---

SCClassLibrary/Common/Control/GraphBuilder.sc

make sure specs in synthdef reach metadata in all cases
implicit control parameters in synth functions allow setting control specs.
These specs specs should be stored in a synthdef's metadata, so they are 
available e.g. for controller ranges. 
Due to a bug in NamedControl, these specs are not stored when the control 
in question is optimized for fixed lag. 
```supercollider
// an implicit control without lag works:
~lagnone = SynthDef(\lagnone, { \ctl.kr(0.2, spec: [0, 11]); 0.0 }).add;
~lagnone.metadata; // \ctl specs here
// an implicit control with a fixed lag loses its spec:
~lagfix = SynthDef(\lagfix, { \ctl.kr(0.2, 0.2, spec: [0, 11]); 0.0 }).add;
~lagfix.metadata; // specs empty
// an implicit control with a variable lag also works
~lagvar = SynthDef(\lagvar, { \ctl.kr(0.2, …
```

fix implicit specs in synth functions

---

HelpSource/Classes/Function.schelp

Documents `Function.awake` in the help.
It is actually different than `Object.awake` in that it calls `.value`, not `.next`, which return different things for a function, so worth documenting.

Document Function.awake

---

HelpSource/Classes/NodeProxy.schelp
HelpSource/Reference/NodeProxy_roles.schelp
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc
testsuite/classlibrary/TestNodeProxy.sc

This pull request adds a new method `seti` to `NodeProxy`, modelled after `seti` in `Synth`. The method allows the user to set controls in a multi-channel NodeProxy based on a channel index.
Additionally it adds a new `NodeProxy role` `\seti` that allows independent sequencing on a per channel basis.
- add `seti` method to `NodeProxy`
- add NodeProxy role `\seti`
- documentation for method `seti` and NodeProxy role `\seti`
- unit tests for method `seti`
- New feature

Node proxy seti

---

SCClassLibrary/Common/Streams/Stream.sc

Fixes #5597.
`Pprotect` is not sufficient to catch errors thrown while playing an event produced by a pattern. In this case, state variables had not been updated to reflect a PauseStream's new non-playing state.
Julian had the good idea to embed `protect` into the Routine being managed by a PauseStream (I hadn't thought of this!), but an earlier version didn't apply this consistently.
This version introduces it into `PauseStream`, `Task`, and `EventStreamPlayer`.
- Bug fix
Under #5623, Julian had proposed some test cases, and volunteered to turn those into formal unit tests. So this PR does not include unit tests directly, but they will follow.

Classlib: Put 'protect' in PauseStreams (update state on error)

---

SCClassLibrary/Common/Control/Server.sc

While looking for a fix of #5568, a small refactoring was recommended.
- Bug fix

class library: refactor functionality: connectToServerAddr

---

testsuite/classlibrary/TestNodeProxy.sc
testsuite/classlibrary/TestNodeProxy_Server.sc

NodeProxy tests that failed because of wrong assumptions in the test.
- Bug fix

Topic fix  some tests

---

HelpSource/Classes/Task.schelp

Some users reported that they got spooked away from using Task, because of warnings near the top of the file that it "doesn't work with Condition." This hasn't been true for years, though.
So I removed the warning.
Also "not 100% compatible with Routines" makes it sound like Routines might be preferred -- also not the case. So I reworded some of this, and added another example to explain how to handle a case that is a bit confusing with Task.

Help: Remove negatives from Task help, clarify example

---

HelpSource/Classes/SinOscFB.schelp

Update to fix #5641.
In discussion of the PR #5654, @dyfer and @adcxyz suggested to refer to the default length of the control period instead of refering to a generic control rate ([see e.g. here](https://github.com/supercollider/supercollider/pull/5654#issuecomment-1008046281)).

SinOscFB.schelp: updated FM caveat

---

testsuite/classlibrary/TestNodeProxy.sc
testsuite/scripts/gha_test_run_proto.json

The test passes locally but failes on GHA. Therefore it's been added to
gha_test_run_proto.json
Signed-off-by: Stefan Nussbaumer <st9fan@gmail.com>
The test `test_seti_nodeMap` has always passed on my local machine but fails in GHA. So I've added the test to `gha_test_run_proto.json`
- Bug fix

Add UnitTest test_seti_nodeMap again

---

SCClassLibrary/Common/Collections/SequenceableCollection.sc

When the collection "this" is not an array, a flop is very expensive. Better convert first. This commit is dedicated to John Bercow.
Discussion: https://scsynth.org/t/sorting-out-sorting-by/4472
calling `order` on a `List` is very slow, and unnecessarily so.
- Breaking change (very unlikely, but in principle this is possible)

class library: improve efficiency of calling "order"

---

.gitmodules

Fixes #5693
GitHub made changes to improve security, deprecating the use of `git://` protocol. Our builds started to fail because of this, since the submodules were not being fetched. The solution is to update the submodule URLs to use `https://`. 
See https://github.blog/2021-09-01-improving-git-protocol-security-github for more details.
After this change is pulled in, all repository users should **update their forks** to pull in the fix and then **run `git submodule sync` afterwards** to update the URLs in the local repository.
- Bug fix

Git submodules: update urls to use https

---

SCVersion.txt

As discussed in https://github.com/supercollider/rfcs/pull/16, I'd like to propose that the builds from the `develop` branch indicate the "next" SC version, along with the appropriate suffix, like `-prerelease` or `-preview`. This change has been briefly discussed with @joshpar and @jrsurge during the dev meeting on 2021-09-05 and I'm open to further suggestions on this. 
One expected side effect of this is that any future merges from the `<release>`/`main` branch into `develop` would need to resolve the conflict in `SCVersion.txt` (only once per version change though). The version on the develop brach should still stay as the "next" version.
- New feature

Use newer SC version on the develop branch

---

HelpSource/Classes/OSCFunc.schelp

URL needs ".html" on the end or following it will return 404
- Bug fix
- New feature

OSCFunc.schelp: fix link to opensoundcontrol.org

---

CMakeLists.txt
HelpSource/Reference/Server-Command-Reference.schelp
SCVersion.txt
common/SC_Version.hpp.in
server/scsynth/SC_MiscCmds.cpp
server/supernova/sc/sc_osc_handler.cpp

Before this PR, the "About" dialog in the IDE of the release (tagged) builds would report `Built from branch 'HEAD' [<SHA>]`. After this PR, the dialog reads `Built from tag '<tag-name>' [<SHA>]`. The non-tagged builds display the branch name as they have previously.
Here are the dialogs from builds from this branch and from a temporary tag:
For a tagged commit, the beginning of cmake config now looks like this:
```
$ cmake ..
-- SuperCollider Version: 3.13.0-dev
-- Building from tag Version-3.13.0-testTagName, commit hash is 354b10d266
-- Please specify the build configuration in the next step
```
There is a very slight change to the response in the server API, if we even consider this a change. Previously, for the release builds the response to the `/version` message would include …

Add tag name in the about dialog for tagged builds

---

SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc

Fixes #5485 
Before this fix, the following would cause `ERROR: Qt: You can not use this Qt functionality in the current thread. Try scheduling on AppClock instead. (...)`:
```supercollider
(
(Server.program + ServerOptions().maxLogins_(10).asOptionsString).unixCmd;
Server.default.makeGui;
)
// recompile class library
// after recompile run
Server.default.makeGui;
```
See the issue for more information.
- Bug fix

ServerPlusGUI: defer GUI updates

---

CMakeLists.txt
editors/sc-ide/CMakeLists.txt

Fixes #5603
On macOS all binaries needs to be signed when run on M1 hardware (arm64 / aarch64)
When building, the binaries are signed ad hoc, however it turns out that `macdeployqt`, as well as manipulations with `install_name_tool` invalidate these signatures.
I propose the solution that runs ad hoc signing after the `macdeployqt` step.
I'm open to suggestions whether this is the desired solution and if there's a better name for the introduced CMake flag.
The PR includes the following changes:
- A new option is added to `CMakeLists.txt` to trigger ad-hoc codesigning after building (`SC_CODESIGN_AFTER_DEPLOY`, defaults to `ON`, macOS only)
- The following components are signed: binaries `SuperCollider`, `sclang`, `scsynth`, `supernova`, all `.framework` and `.dylib` files in …

Explicitly add ad hoc code signing on macOS

---

HelpSource/Classes/QuartzComposerView.schelp
SCClassLibrary/deprecated/3.13/QQuartzComposerView.sc

Quartz Composer bindings are not available in Qt 6. We currently plan to drop Quartz Composer once we move to Qt 6, so we'll deprecate it in SC 3.13.
- Deprecation

Deprecate QuartzComposerView

---

HelpSource/Classes/Env.schelp
SCClassLibrary/Common/Audio/Env.sc
testsuite/classlibrary/TestPatternStreamArg.sc

To work as expected in PatternProxy (and in Pbindef and Pdefn), a class that does not simply return itself when embedded in a stream should implement streamArg. This fixes #5285.
```supercollider
a = PbindProxy.new;
a.set(\midinote, Env([60, 70, 60], [2, 2]));
a.asStream.next(Event.default); // => ( 'midinote': 60.0 )
```
- Bug fix

class library: envelopes behave like patterns in a pattern proxy

---

SCClassLibrary/JITLib/ProxySpace/ProxySynthDef.sc

Instead of failing, we better convert a mixed output that contains an audio rate UGen and non-audio-rate UGens, because this is hard to understand. There is an informative warning.
See discussion here: https://scsynth.org/t/why-does-multichannel-expansion-not-work-for-mul-in-nodeproxy/5232
- New feature

class library: NodeProxy converts mixed outputs instead of failing

---

SCClassLibrary/Common/Control/Server.sc

After commit c3301b8b0573ee1329210766505612e0be4260f2, `Server.remote` is broken. At this line:
https://github.com/supercollider/supercollider/blob/c3301b8b0573ee1329210766505612e0be4260f2/SCClassLibrary/Common/Control/Server.sc#L392
`this` is evaluated as `Server`, the class, instead of the newly created instance, resulting in `^^ ERROR: Message 'startAliveThread' not understood. RECEIVER: Server`
Before this PR, test `Server_clientID_booted:test_remoteLogin` was failing, which is not anymore the case.
- Bug fix

classlib: fix Server.remote startAliveThread

---

lang/LangPrimSource/PyrSymbolPrim.cpp

The situation presented in #2954 stemmed from Symbol:isPrimitiveName testing a string and returning true given an empty symbol. Checking the minimum length between the two symbol and making sure it isn't 0 might fix this. The prefix method still works as intended but now doesn't accept empty symbols as input.

Possibly Fixes #2954 

---

testsuite/classlibrary/TestNodeProxy.sc
testsuite/scripts/gha_test_run_proto.json

Fix what looks like a typo in `TestNodeProxyBusMapping:test_audiorate_mapping`.
I think control proxy for this test should be audio rate, for the mapping to be audio rate. Other than this, having it control rate with no `numChannels` specified makes it mixed down to mono by default, creating the discrepancy that makes this test impossible to pass. Initializing `controlProxy` as `\audio` fixes it.
- Bug fix

testsuite: fix NodeProxy ar mapping test

---

server/CMakeLists.txt

after ee2aba7984fcb50a6a29093e2d97e52f5939fa63 `LIB_SUFFIX` was defined using  `option`, and thus as a boolean option with a default value of `OFF`. 
This incorrectly caused the default search path for plugins to be `/CMAKE_INSTALL_PREFIX/libOFF`. As a consequences, scsynth wouldn't find `sc3-plugins` anymore, if they were built and installed from source.
Fixed by using `set` instead of `option`.
References:
https://cmake.org/cmake/help/latest/command/option.html
https://cmake.org/cmake/help/latest/command/set.html#set-cache-entry
- Bug fix

server: LIB_SUFFIX should be STRING, not BOOL

---

.github/workflows/actions.yml
testsuite/classlibrary/TestBus.sc
testsuite/classlibrary/TestFunction.sc
testsuite/classlibrary/TestIndexUGenRates.sc
testsuite/classlibrary/TestNetAddr.sc
testsuite/classlibrary/TestNodeProxy.sc
testsuite/classlibrary/TestPV_ChainUGen.sc
testsuite/classlibrary/TestServer.sc
testsuite/scripts/gha_test_run_proto.json

This PR fixes a number of issues with UnitTests, particularly for running them in the CI:
- most (all?) tests using a server now use a unique server instance
- the use of default server, particularly if it was not shut down, has led to multiple tests failing, some without reporting failure in the CI (i.e. with the [Did not complete](https://github.com/supercollider/supercollider/runs/4808924636?check_suite_focus=true#step:8:12377) message)
- `TestFunction -test_plot` arguably was hiding the server booting most covertly...
- a number of tests was fixed
- the link to the API quark, used by QPM for testing was updated to point to the address that's specified in the quarks directory
- I'm not sure if this was causing any of the issues we experience in qpm or not...
- we now have ~~3483~~ …

Fix multiple UnitTests

---

SCClassLibrary/Common/Audio/SynthDef.sc

Fixes #5656
- New feature
If reviewers don't think this is another horrible idea of mine, I'll even write a test case and documentation for this, if deemed necessary. SynthDescLib does document its `changed` notification hooks in the help, although many other classes in SC do not.

SynthDef.build gets a changed posthook

---

SCClassLibrary/Common/Streams/TabFileReader.sc

```
c = CollStream("5,7,hello,\"a comma, in quotes!\"");
r = CSVFileReader(c);
ERROR: Primitive '_FileOpen' failed.
Wrong type.
```
But... FileReader's interaction with the `stream` is, in total:
- `stream.reset` -- `CollStream` implements this
- `stream.getChar` -- `CollStream` implements this
- `stream.close` -- `CollStream` doesn't implement this, but we can use `tryPerform` to make it a no-op
So there is not a compelling reason why a FileReader must be accessing a file on disk and disallow a stream of characters in memory.
(Editorial: The usual OOP advice is to program toward interfaces rather than class hierarchies: `respondsTo` rather than `isKindOf`. This looks like a case where "oh, `isKindOf` will be fine just this once" except that it isn't, not really.)
Since the really …

Classlib: Allow any type of text stream in the FileReader hierarchy

---

server/plugins/IOUGens.cpp
testsuite/classlibrary/TestIOUGens.sc

I have noticed a weird behavior of the `AudioControl` and `InFeedback` UGens.
If you run this code, you'll notice that the last audio cycle will run twice, generating a "double" dropout:
```SuperCollider
(
s.waitForBoot({
SynthDef(\test, {
Out.ar(\out.ir(0), { SinOsc.ar(2) * EnvGen.ar(Env([1, 1], [0.2]), doneAction:2) })
}).add;
s.sync;
~bus = Bus.audio(s);
Pbind(
\instrument, \test,
\dur, 1,
\out, ~bus.index,
\addAction, \addToHead
).play;
~reader = { \in.ar }.play(args:[ \in, 'a' ++ ~bus.index]);
{ In.ar(0) }.plot(0.5);
})
)
```
This happens because the `AudioControl` UGen (as well as the `InFeedback` one) only check if the bus has been touched in the current audio cycle. In my opinion, it should probably take into consideration if the bus has been touched in the previous audio cycle …

Plugins: Fix AudioControl and InFeedback processing for an extra cycle

---

QtCollider/widgets/QcWebView.h
SCClassLibrary/Common/GUI/Base/QWebView.sc

WebView scrollPosition setter was not impemented even it was in docs. 
This small example demonstrates what it does:
```
(
~webview = WebView();
~webview.url = "https://ferokiraly.com";
View(bounds:900@700).layout_(VLayout(~webview)).front;
)
~webview.zoom_(1)
~webview.scrollPosition
~webview.scrollPosition_(0@504) // scroll it  !
~webview.scrollPosition // 0@504
~webview.zoom_(2)
~webview.scrollPosition_(0@0) // scrolls correctly back to top
~webview.zoom_(1) // zooms back
```
- New feature

QWebView: added ability to set scrollPosition of QcWebView

---

testsuite/classlibrary/TestDocument.sc

Fixes errors occurring while testing the Document class outside the IDE. 
`Document` is not defined outside the IDE, so UnitTests needs to skip, and most of them do. This PR adds a few missing skips.
- Bug fix

testsuite: Document: add missing skips

---

.github/workflows/actions.yml

In GitHub Actions current "macOS system libraries" builds fail, most likely due to requesting compatibility with the older deployment target than what the system libraries provide. This PR should fix this failure.
- Bug fix

GHA: update macOS system libraries build

---

testsuite/classlibrary/TestServer_boot.sc
testsuite/classlibrary/TestWebView.sc

I've noticed two tests that _sometimes_ fail and the following changes seem to help with this.
The tests in question are `TestServer_boot -test_waitForBoot_fourWaysToPlaySound` and `TestWebView -test_runJavaScript_returnTypes`.
- Bug fix

Fix more tests

---

HelpSource/Classes/SimpleNumber.schelp
HelpSource/Classes/String.schelp
SCClassLibrary/Common/Math/SimpleNumber.sc
testsuite/classlibrary/TestSimpleNumber.sc

After discussion in #4661, I'd like to propose adding an argument to control number of decimal places for ```aNumber.AsTimeString```.
Before I write tests for this, I wanted to see if others think this is a worthwhile addition.
- (Documentation)
- New feature

classlib: add number of decimal places to SimpleNumber -asTimeString

---

SCClassLibrary/Common/Streams/PmonoStreams.sc

Fixes #5024 
Commit 83e4607cd merged in PR #4787 exposed an underlying problem in Pmono's two-part cleanup setup, which can (now at least) fire a `type: off` event with no `id` set, turning everything off in the default group, e.g. as in:
```
Synth(\default);
PfadeOut(Pmono(\default, \dur, 0.4), 0.3).play;
```
This is an "emergency fix" that prevents Pmono's cleanup from firing that `off` event if `id` is still not set by the time the
cleanup is executed. (The mechanism is also inherited by PmonoArtic.)
A better solution would be to rewrite Pmono so that it doesn't register an incompletely specified cleanup at all, but that is somewhat involved given the number of variables it would need to capture in a closure.
Also this PR will very likely cause a merge conflict with the solution …

Quick fix for Pmono (and PmonoArtic) turning everything off in the default group

---

SCClassLibrary/Common/Collections/linux/extString_linux.sc
SCClassLibrary/Common/Collections/osx/extString_osx.sc
SCClassLibrary/Common/Collections/windows/extString_windows.sc

Fixes #2297.
String:openOS calls systemCmd, resulting in:
- sclang being blocked until the executed command exits (e.g. when the file browser window is closed)
- only spaces are escaped, and not ampersands and other characters as described in #2297
This PR switches to SequenceableCollection:unixCmd, as suggested by @nhthn, fixing both problems at once.
I've changed implementations for Linux and macOS, but not for Windows, which I don't understand and can't test. 
- Bug fix
- New feature
- Breaking change?
could anyone rely on openOS being blocking? I don't see it very likely, as openOS is not a file-chooser and doesn't return anything.

classlib: String:openOS escaping

---

SCVersion.txt

I noticed that builds in the PRs are not on the tip of the branch and thus are not properly described in CMake and in the "about" window of the build from the PR (see [here](https://github.com/supercollider/supercollider/runs/5383960643?check_suite_focus=true#step:8:20) and [here](https://github.com/supercollider/supercollider/runs/5383961277?check_suite_focus=true#step:11:36))
This PRs aims to handle this case by [reporting](https://github.com/supercollider/supercollider/runs/5384387513?check_suite_focus=true#step:8:33) `building from detached HEAD, commit ...`
The implementation is arguably not the prettiest, i'm open to suggestions. 
- Bug fix

CMake: identify detached head state when describing repository branch/tag/commit

---

lang/CMakeLists.txt
server/plugins/CMakeLists.txt
server/scsynth/CMakeLists.txt
server/supernova/CMakeLists.txt

Previously, when selecting `-D SC_QT=OFF` build option on macOS, the configure step would fail due to references to `SuperCollider` target in other targets: sclang, scsynth, supernova and the plugins. 
This PR allows to run the configure step, and thus build SC without Qt on macOS.
(I vaguely remember this issue has been mentioned before, but I can't find it in the open issues)
- Bug fix

CMake: allow building without Qt on macOS

---

.gitmodules

This will make pulling 3.12 branch possible again. We are just adding the single commit without creating a new tag/release. See https://github.com/supercollider/supercollider/issues/5695#issuecomment-1100920416 for previous discussion.
- Bug fix

[3.12 branch] Git submodules: update urls to use https

---

SCClassLibrary/Common/Collections/String.sc

When a file is unsaved or a path can't be found for other reasons, `loadRelative` and `resolveRelative` warn the user. So far, they have thrown an error, but it seems better to warn with more details and bail out instead.
- New feature
- Breaking change (possibly)

class library: loadRelative – improve behaviour of error

---

include/plugin_interface/SC_SndBuf.h
server/plugins/DiskIO_UGens.cpp
server/scsynth/SC_HiddenWorld.h
server/scsynth/SC_SequencedCommand.cpp
server/scsynth/SC_World.cpp
server/supernova/sc/sc_plugin_interface.cpp

Fixes compatibility with `libsndfile` >=1.1.0
Fixes #5756 
See https://github.com/supercollider/supercollider/issues/5756#issuecomment-1094378766 for previous discussion.
Thanks @Spacechild1 for providing this fix.
I also had to add additional Windows includes in `SC_HiddenWorld.h`, similarly to `SC_SndFileHelpers.hpp`. 
Please review carefully, as I have limited experience with this aspect of the project.
- Bug fix

libsndfile: use a macro instead of redefining the struct

---

HelpSource/Classes/MIDIOut.schelp

Linux MIDIOut users frequently get confused when `MIDIOut.newByName` pseudo-connections don't appear in patchbay GUIs.
This documentation change explains that the mechanism bypasses visible connections altogether.
Previously, the documentation (written by myself) claimed that "one-to-one connections" were made. That's misleading -- targeting a device by uid is a completely separate mechanism.

Help: Linux: Clarify behavior of MIDIOut objects with uid

---

SCClassLibrary/Common/Streams/Patterns.sc

Pbind doesn´t record anything when using .record(). There was no buffer passing to DiskOut.
- Bug fix
- [ x] Code is tested
- [ x] All tests are passing

pbind: fix pbind not recording

---

HelpSource/Classes/NodeProxy.schelp
testsuite/classlibrary/TestNodeMap.sc
testsuite/scripts/gha_test_run_proto.json

One would naturally assume that ControlNames always contain numbers as defaultValues, but here we use them differently: any object can be value of the ControlNames. This is now tested and documented.
See also #5796 and #5797.

test: correct wrong assumption in test

---

HelpSource/Classes/SoundFileView.schelp
SCClassLibrary/Common/GUI/Base/QSoundFileView.sc

avoid common error when setting data. a Float samplerate crashes sclang.
also removed unused variable in helpfile last example.
problem demonstration...
```
s.boot;
a= SoundFileView().front;
a.setData({1.0.rand2}!100, samplerate: s.sampleRate);
ERROR: Primitive '_QObject_InvokeMethod' failed.
```
to get around the error one always have to use an integer (e.g. in the above demo `s.sampleRate.asInteger`), so i propose we include .asInteger in the source code.
minor, harmless

SoundFileView - cast sampleRate to Integer in setData

---

HelpSource/Guides/WritingTests.schelp
README_MACOS.md
README_WINDOWS.md

I saw that we were referencing Travis (the build system we stopped using a while back) in a few places. Let's remove these references.

Docs: remove references to Travis

---

server/supernova/sc/sc_osc_handler.hpp
server/supernova/server/server.hpp

Allow supernova to use the `/error` message just like scsynth. This was previously being ignored. As discussed on the [forum](https://scsynth.org/t/error-message-not-working-for-supernova/6275/4), it is a feature that is needed to match scsynth's capabilities. 
This patch does not take into account the local bundles (`/error, -1` and `/error, -2`), as supernova appears to treat the OSC bundles a little differently than scsynth, and I am still studying that part of the code base. This will come as a secondary patch in the future
- Bug fix

supernova: use the `/error` messages to turn on / off the console printing

---

HelpSource/Classes/MIDIOut.schelp

MIDIOut sysex help is confusing: "On Windows, the function call must contain a full sysex message..."
That implies that it may be different on other OSes.
I tested in Linux, and it's the same. And a [helpful person from the forum](https://scsynth.org/t/midi-sysex-out-platform-compatibility/6312/4?u=jamshark70) repeated the test in May, and also the same.
So it should really just advise the user to include the delimiters.
- [n/a] Code is tested
- [n/a] All tests are passing

[skip ci] Help: Clarify full sysex format for all OSes

---

SCClassLibrary/scide_scqt/ScIDE.sc

Fixes #4557.
```
Class.allClasses.select { |cl| cl.findMethod(\duration).notNil };
```
Error:
```
ERROR: Message 'split' not understood.
RECEIVER:
nil
ARGS:
Character 46 '.'
CALL STACK:
DoesNotUnderstandError:reportError
arg this = <instance of DoesNotUnderstandError>
... snip ...
Object:doesNotUnderstand
arg this = nil
arg selector = 'split'
arg args = [*1]
Meta_ScIDE:findMethod
```
Per discussion in #4557, the offending method seems to have been used in an early version of IDE auto completion, but all references to it were removed with a major re-factoring. As far as I can see, it's 1/ expected to be called from the IDE internally, 2/ unused in the IDE!, and 3/ breaks a core class library feature.
So I'm (2 years late) removing it.
- Bug fix

classlib: Delete unused method `*findMethod` from ScIDE class

---

HelpSource/Classes/ProxySpace.schelp

fix typo issues in ProxySpace.schelp. ```clear``` applies to all node proxies, rather than a single node proxy.

docs: fix ProxySpace typo

---

HelpSource/Classes/EZRanger.schelp
HelpSource/Classes/NotificationCenter.schelp
HelpSource/Classes/ProxySpace.schelp

EZRanger.schelp references ```Slider``` several times, but should probably be referencing ```RangeSlider``` instead. Removed what felt like a superfluous link to ```NumberBox``` help file. Also fixed a few typo/language issues.

docs: ez ranger typo

---

SCClassLibrary/Common/Quarks/GUI/QuarksGui.sc

Quark:help first tries to display a SCDoc help file, if one is listed under `schelp` in the quark file.
Failing this, it falls back to `helpdoc` (which is handled by `openOS`).
But QuarksGUI will display the "Open help" button only if `helpdoc` is populated.
So, in current development, if a quark author wants the help doc to be a SCDoc help file, they have to specify both schelp and helpdoc, but helpdoc will never be used.
Expected behavior: Check both keys, and display the button if either one is populated with a string.
- Bug fix

Classlib: QuarksGUI should check schelp as well as helpdoc

---

examples/GUI examples/analog-drum-tuner.scd

analog-ringz-tuner.scd could not load files because it uses the now-deprecated File.openDialog.
- Example file

Update analog-ringz-tuner: Replace deprecated file-open dialog

---

HelpSource/Classes/FSinOsc.schelp
HelpSource/Classes/FoldIndex.schelp
SCClassLibrary/Common/Audio/Osc.sc
server/plugins/OscUGens.cpp

A majority of UGens do not initialize with a correct initialization sample, and subsequently output an incorrect first sample. A lack of clarity and consistency around how UGens are initialized has led to many UGens being improperly initialized. The affects include: UGen graphs aren't properly "primed" (users see unexpected results), samples are delayed, filters can pop from incorrect feedback coefficients, accessing unassigned memory, etc. Users regularly report Issues that can be traced back to UGen initialization problems. 
This PR also serves as a concrete reference for discussion found in the [RFC: Fix UGen Initializations](https://github.com/supercollider/rfcs/pull/19), more details can be found there.
(I will update this post with Issues this fixes.)
- Documentation (`FSinOsc`, …

Fix UGen initialization: OscUGens

---

README_LINUX.md

Trying to update our Linux build matrix I found that the package names in the Linux readme don't always work - particularly `qt5-default` doesn't seem to be available in Ubuntu 22.04. The packages now listed in the "Ubuntu" section of the Readme seem to work for Ubuntu 18.04, 20.04 and 22.04, at least in the configurations provided by GitHub Actions. 
I would appreciate if some Ubuntu users could confirm the updated packages are correct and complete (particularly, whether `qt5-default` is still needed for older systems).

Update README_LINUX for Ubuntu 18.04-22.04

---

HelpSource/Classes/SpecPcile.schelp
SCClassLibrary/Common/Audio/MachineListening.sc
server/plugins/ML.h
server/plugins/ML_SpecStats.cpp

If enabled, outputs the bin number directly instead the calculated 
frequency. If interpolate is true, performs linear interpolation and 
outputs a fractional bin as a float.
I needed the functionality of SpecPcile UGen but needed the bin number as opposed to the frequency. Works as expected.
- New feature

server: added binout to SpecPcile

---

server/plugins/OscUGens.cpp

Part fo the [initialization sample fix project](https://github.com/supercollider/rfcs/pull/19), specifically in the [OscUGens subset](https://github.com/supercollider/supercollider/pull/5787).
- Bug fix
Changes to `Klang`:
- correct the initial phase (it was off by 1 sample).
Change to `Klank`:
- Don’t assume init sample is zero—reorganize coeff calc func and ctor to get correct init sample.
- The memory allocation for `m_coefs` was moved to the Ctor, otherwise, the `return` statement escapes the `Klank_SetCoefs`, but not the Ctor, so `m_coefs` might still be accessed after allocation fails.
- Calculate the correct init sample by calling `Klank_next(unit, 1)`, temporarily setting `mFilterLoops` and  `mFilterRemain` for the single cycle of initialization. 
- Usually the pattern of calling …

Klang, Klank: Fix initialization

---

.github/workflows/actions.yml
README.md

Fixes #5843
Github Actions runner image of macOS 10.15 is getting deprecated. This PR updates our build matrix to use macOS 11 and macOS 12 images.
- the legacy build still works down to macOS 10.10. I confirmed that by testing on that system
-  in order for this to work, I switched to build the "vendored" portaudio library (just for the legacy build); this applies to supernova only anyway
- for reference, the build only seemed to work on 10.10 when built using Xcode 12.4; it did not work when built using 11.7 or 13.1 (I haven't investigated that further, just chose the configuration that worked)
- the main build **doesn't work on macOS 10.13** (High Sierra) anymore. This is due to the use of homebrew build of Qt, which only supports macOS 10.14 (for homebrew installed on macOS 11). I've …

Update macOS build matrix

---

SCClassLibrary/Common/Audio/SynthDef.sc
SCClassLibrary/JITLib/GUI/EnvirGui.sc
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc
SCClassLibrary/JITLib/ProxySpace/ProxyInterfaces.sc

Fixes #5515.
Currently, NdefGui does not find controlspecs embedded in synth functions, 
thus NdefGui cannot use such specs for its slider ranges.
With this PR, core JITLib NdefGui finds these specs and uses them. 
- Bug fix
```
// Ndef with an embedded spec:
n = Ndef(\1, { Saw.ar(freq: \fff.kr(200, spec: [50, 500, \exp])) * 0.1 });
// before this PR, this gui uses guessed range of 10-4000
n.gui;
// with this PR, ndef finds the embedded spec:
n.findFirstSpecFor(\fff);
// also in the specs method
n.specs;
// and the gui uses the 50 - 500 range given in the embedded spec:
n.gui;
```
Note: this fix works for plain SC without JITLibExtensions quark;
JITLibExtensions update to use it is simple, and ready to go.

ndef uses embedded specs for guis

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

Revealed in fa67b746fa6cf9cd29eb42d4fba3f63133e3bf8d, `Plotter` never really handled default colors correctly. When accessing `QtGUI.palettle` colors, it would return unset colors, which would "gracefully" fail by defaulting to black. It seems that correcting the behavior of `-asHSV` made these calls break...ungracefully.
The problem is seen by running 
```supercollider
7.collect({ 15.collect({ rrand(0,1.0) }) }).plot.superpose_(true)
```
The proposed defaults access `QtGUI.palette.highlight`, which returns a valid color, whereas `QtGUI.palette.windowText`, used before, didn't.
I've also reduced the default `plotColor` down to one color. Four colors was a rather random number of colors to default to, and in any case the user can set them explicitly in `Plot` (more easily through `Plotter` …

Plotter: update default colors to valid colors.

---

testsuite/classlibrary/TestMIDI.sc
testsuite/scripts/gha_test_run_proto.json

Fixes #5198 (for Linux, not totally sure about Windows -- there is a pending PR to fix a related crash in Windows).
In Linux, song position pointer and song select messages were sent with an incorrect sysrt message type code. We thought we were getting the type code from `evt->data.control.channel` (and maybe that was actually the case a decade or two ago), but I found in testing that this is always 0.
SC_CoreMIDI.cpp and SC_PortMIDI.cpp simply pass the code byte as a constant. So, I'm updating SC_AlsaMIDI.cpp accordingly.
I also found that the song position data value (`(pkt->data[2] << 7) | pkt->data[1]` for Core MIDI) is a wrong calculation in Alsa. Through debugging posts, I found that `evt->data.control.value` is already the 14-bit value, and doing `evt->data.control.value << 7` …

lang: Fix system realtime message type codes

---

HelpSource/Classes/Plotter.schelp
SCClassLibrary/Common/GUI/Base/Grid.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

This adds full support for grid labels and axis labels for `Plotter`.
- build label margins for each axis independently
- refresh when updating plot bounds
- account for x-AND y-labels when sizing left and right margins
- always draw the outer edge grid lines
- xlabels: handle edge case of very small width
- distinguish between x and y grid edges when getting label size
- rename x/yLabels -> x/ytkLabels - they're tick labels not axis labels
- fully support axis labels: add -labelX, -labelY methods, support multichannel plot labels
- docs: cleanup, fix examples, reorganize by subcategory
- don't display `.0` if all grid labels are whole numbers
- Env:plot: don't assume units are seconds.
- Buffer:plot: display units in x-axis label, not grid labels.
- Buffer:plot: match argument order to …

Plotter: fix grid and axis labels

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

The example:
```supercollider
(
a = { (0..30).scramble }.dup(2).plot;
a.setProperties(
\fontColor, Color.red,
\plotColor, Color.red,
\backgroundColor, Color.gray,
\gridColorX, Color.white,
\gridColorY, Color.black,
\labelX, "Humidity"
);
a.refresh;
);
```
would not have a red `plotColor` because it was internally converted to an array (`Color`unfortunately responds to `asArray`with an array of values).
This fixes it.
- Bug fix

class library: make sure color is not converted to array

---

SCClassLibrary/Common/GUI/Base/Grid.sc

There should be no uninlinable variables in common, it creates inline warnings
- Bug fix

class library: remove inline warnings in common

---

SCClassLibrary/Common/GUI/PlusGUI/Core/HistoryGui.sc

HistoryGui has not been updated for Qt Guis, and thus had visual problems: 
Too small font size and too large tabWidth. 
Also, the window name was a bit confusingly "HistoryGui_History", 
which this PR clarifies to just say "History".

HistoryGui: improve display readability (fontsize and tabWidth)

---

HelpSource/Classes/Impulse.schelp

A block of duplicate text somehow made it into the `Impulse` help file, which also broke the `DISCUSSION` delimiter.
This PR fixes that, and while I was at it I clarified some of the language in that section.

[docs] Impulse: remove repeated Discussion, reword.

---

testsuite/scripts/gha_test_run_proto.json

These tests occasionally fail when run in the CI
Some server boot tests fail in our CI more often than not, so I propose that we disable them for the time being so that the test suite passes.
- Bug fix
-

TestSuite: skip server boot tests

---

HelpSource/Classes/ServerOptions.schelp
SCClassLibrary/Common/Control/Server.sc

Seen in a sc-forum thread (https://scsynth.org/t/how-do-i-connect-sclang-to-an-already-running-server/2498):
```supercollider
o = ServerOptions.new;
o.maxLogins = 100;
```
Currently ServerOptions allows this to be set. But, NodeIDAllocator doesn't allow a clientID >= 32 (https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/Engine.sc#L8) -- clientID may be 0-31. So maxLogins should never exceed 32.
We should validate this in ServerOptions.
I also added a short sentence to ServerOptions help.
- Bug fix

Classlib: ServerOptions: maxLogins may not exceed 32

---

.github/workflows/actions.yml
vcpkg/triplets/arm64-osx-release-supercollider.cmake
vcpkg/triplets/x64-arm64-osx-release-supercollider.cmake
vcpkg/triplets/x64-osx-release-supercollider.cmake

We currently don't offer arm64 builds on macOS. This PR provides such build.
More info:
GHA runners currently run on x64 only, so it's not possible to natively build arm64 SC. Cross-compiling an arm64 binary is supported, but requires arm64 or universal binaries of the supporting libraries, which is the most work that went into making this PR.
TL;DR
I created a script (embedded in your GHA yaml file) that combines native (x64) homebrew libraries with the binaries extracted from an archive for another architecture (arm64). This also involves manually correcting templated loader paths in the extracted libraries. The resulting "fat"/universal binaries are put in place of the original homebrew binaries. This is used for `qt@5` and its dependencies, as well as readline (due to issue documented …

macOS: create arm64 build

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

When plotting functions with a short duration, individual samples are visibly misaligned with the grid. The x-axis position of each sample doesn't account for the duration of the last sample period (a "fencepost problem"). This PR sets the sample position of the plotted points explicitly in the case that this time offset would be visible (i.e. a maximally wide plot would contain samples separated by ~2.5 pixels).
Below, both `SinOsc` and `Impulse` are plotted for a duration of 2 times their cycle period. So we expect the cycles to start at the leftmost part the plot (first cycle) and the center of the plot (second cycle). 
Currently:
After the fix:
Note the differences: 1. the second cycle begins at the center of the plot, 2. the _duration_ of the last sample is properly accounted for on …

[classlib] Function:plot fix sample alignment with grid lines

---

server/supernova/server/server.hpp

Currently, Supernova's `Print` plugin API method prints garbage if variadic arguments are used.
This regression has been introduced with https://github.com/supercollider/supercollider/commit/bd3aa3fd3256ea69f79be4b3e9b31b5085a07840. Mea culpa.
add missing `va_list` overload for `nova::log_printf`.
- Bug fix

supernova: fix Print plugin API method

---

server/plugins/FilterUGens.cpp
testsuite/classlibrary/TestFilterUGens.sc

Integrator double-counts the initial value, because of calling `next` in the Ctor.
See the added unit test: Without this fix, the integral of a single 1 followed by endless 0s ends up being 2. With the fix, it's 1 as expected.
(This is related to #2343 but it's only a spot fix of one UGen.)
- Bug fix

Plugins: Integrator Ctor passes through the first sample only

---

lang/LangPrimSource/PyrFilePrim.cpp

I noticed that a wave file with RF64 header was not recognized properly:
```supercollider
f = SoundFile.new;
f.openRead("/path/to/rf64/file.wav");
f.headerFormat.postcs; // result: " "
f.close
```
This PR fixes this, so that `f.headerFormat` returns `RF64`.
I also noticed that when reading, the Wave64 header was returned as `WAV`. I don't think this is right, since when writing the Wave64 file, one should specify the header as `"W64"` (see [here](https://github.com/supercollider/supercollider/blob/develop/common/SC_SndFileHelpers.hpp#L79)). 
I changed this accordingly and Wave64 is now reported as the "W64" header.
I tested this by reading the RF64 and Wave64 files into `SoundFile` and checking the `headerFormat`. 
- Bug fix
- n/a All tests are passing

Fix RF64 and W64 format recognition

---

.github/workflows/actions.yml
README.md

Our build matrix had no builds on Ubuntu 22.04 and only one on 20.04. This update brings building using newer compilers and newer OSs.
~~Please note, Linux builds with `clang-11`, `clang-12` and `clang-13` fail to build (see https://github.com/dyfer/supercollider/runs/6531974521?check_suite_focus=true) and are thus disabled. I don't know whether the issue has to do with the OS configuration/missing packages, or with our build system... However, clang builds seem to be fine on macOS (I think locally I've been building using all or most of these clang versions throughout the last few years) so I'm hoping this is not an issue with our codebase.~~
~~EDIT: After discussion with @jrsurge he decided to look into the reason for these failures. Let's wait for a proposed fix before merging this …

Update Linux build matrix

---

.github/workflows/actions.yml

This is a maintenance PR, updating the cache action to the newest version.
`install-qt-action` was also updated and now features built-in caching, which is enabled instead of a separate caching action for downloaded qt.
I also added `restore-keys` to homebrew cache, so that the download cache will get updated daily, while still using cache from the previous day.
EDIT: `qtwebengine` was explicitly added to the Windows build matrix so that it can be disabled in the MinGW build. IIUC qtwebengine was never available for the `'win64_mingw81'` architecture, but previous version of the `install-qt-action` would not check that and proceeded to install qt regardless.
- Housekeeping (?)
- n/a All tests are passing

Update GHA cache actions

---

.github/workflows/actions.yml
CMakeLists.txt
README_WINDOWS.md

Ccache added support for MSVC in version 4.6.1.
Using it with MSVC requires some additional switches in the CMake which I added. 
There's also one "gotcha" - the _actual_ ccache executable, not a chocolatey "shim", needs to be in the PATH for this to work. I've added a note about it in the Windows README
- New feature

GHA/Build system: use ccache on windows

---

HelpSource/Guides/Non-Realtime-Synthesis.schelp

Added an example in Non-Realtime-Synthesis.schelp called "Bus allocation and synth/LFO mapping" at the bottom of the page.
I also added an addition to the note found in "Timed messages" to stop users from looking for bus allocation OSC messages.
Fixes #5609 
- [x ] Code is tested
- [x ] All tests are passing
- [x ] Updated documentation

docs: added bus allocation and LFO mapping example

---

HelpSource/Tutorials/Streams-Patterns-Events1.schelp
HelpSource/Tutorials/Streams-Patterns-Events7.schelp

Corrected a couple of typos on said tutorial. The "~instrument" one was especially jarring, or is there something I'm not getting about it?

Fix couple of typos in Stream-Patterns-Events tutorial

---

SCClassLibrary/Common/Control/Bus.sc

When returning a subBus, the bus should use the same server as the receiver. 
This fixes #5886. Thanks to @catniptwinz.
- Bug fix

class library: subBus uses same server as receiver

---

HelpSource/Classes/AbstractGridLines.schelp
HelpSource/Classes/ControlSpec.schelp
HelpSource/Classes/DrawGrid.schelp
HelpSource/Classes/GridLines.schelp
SCClassLibrary/Common/Control/Spec.sc
SCClassLibrary/Common/GUI/Base/Grid.sc

This PR fixes exponential GridLines, which previously were not drawn cleanly. Fixes #5156
In detail this PR:
- fixes drawing exponential gridlines, based on solution by @sternsc 
- both positive and negative ranges are supported
- adds control over grid density through ~`DrawGrid -pixDensity`~ `DrawGridX -tickSpacing`
- ~~adds option to not draw individual labels if they'd overlap, through `DrawGrid -dropLabelIfTooNarrow `~~
- labels are now dropped within the exponential gridlines generation for the X axis, based on line spacing and label width
- ~~removes `.0` from integer labels~~ this was addressed in #5827
- I realized that the original design [intended to create separate GridLines objects for various Warps](https://github.com/supercollider/supercollider/blob/develop/HelpSource/Classe …

GridLines improvements: fix exponential grids and add spacing control

---

server/plugins/PanUGens.cpp
testsuite/classlibrary/TestPanAz.sc

PanAz was having a small leak into adjacent-to-focused channels, due to
both an imprecision in sc_reciprocal and in ft->mSine. This fixes it
without touching either of the two.
Fixes #4970
https://github.com/supercollider/supercollider/blob/f806ace7bd8565dd174e7d47a1b32aaa4175a46e/server/plugins/PanUGens.cpp#L1325
Changing this to` >= 1.f` should fix it.  `ft->mSine[4096]` should be zero (even if it is a very small number instead), so it makes sense to shortcut to 0 IMO.
However, due to an imprecision in `float32 sc_reciprocal()`, `chanpos` ends up not being `== 1.f` and so this fix doesn't work.
https://github.com/supercollider/supercollider/blob/f806ace7bd8565dd174e7d47a1b32aaa4175a46e/include/plugin_interface/SC_InlineUnaryOp.h#L210
It works however if the float64 version of …

scsynth: PanAz: fix leaks and imprecisions

---

lang/LangPrimSource/SC_ComPort.cpp
server/scsynth/SC_ComPort.cpp
server/supernova/sc/sc_osc_handler.cpp

This fixes a couple of discrepancies in UdpInPort error reporting.
1. sclang prints newline after the error text; scsynth inexplicably does not. Obviously a typo.
2. In the current release, the above typo is the *only* way to tell whether sclang or scsynth encountered a UdpInPort error. This is rather less than informative from the user's perspective. So, this PR adds prefixes "(sclang)" "(scsynth)" "(supernova)" to the error posting.
3. sclang suppresses "connection refused" errors (apparently because this error happens a lot in Windows, spuriously). scsynth does not. Windows users encounter this error, particularly when quitting the server, and then worry that something has gone terribly wrong. So this PR copies the sclang `if` block into scsynth.
For the third -- I did not port the …

sclang/scsynth/supernova: Two fixes for UdpInPort error reporting

---

HelpSource/Classes/Function.schelp
SCClassLibrary/Common/Core/Function.sc
SCClassLibrary/Common/Core/Kernel.sc
testsuite/classlibrary/TestFunction.sc

Reimplements `flop` by `makeFlopFuncString`, which returns a flopped function s that can be used with keyword arguments. This also fixes #5498. Ellipsis arguments didn't work before, and for all usual cases there tests have been added.
- Bug fix
- New Functionality
There is a possibly breaking change, that functions without arguments will also flop: `{ 3 }.flop.value`returns `[3]` and not `3`. just like  in the case of arrays `[3].flop` returns `[[3]]` and not `[3]`. It is probable that the original behaviour caused more trouble, because it is unexpected. This change is up to discussion and can be separated from the rest of the changes if so desired.

Better function flop implementation that works with string ellipsis and keyword arguments

---

SCClassLibrary/DefaultLibrary/Main.sc

Per forum thread: https://scsynth.org/t/win10-primitive-netaddr-sendmsg-failed-and-primitive-getlangport-failed/2085 -- it's possible for sclang to fail to get a UDP port at startup.
The rest of the startup sequence is omitted, which could cause any number of other problems.
Also, the error reported to the user is confusing -- a couple of users encountering this problem thought that they needed to kill servers, but it looks like it may be more relevant to kill language clients that didn't shut down.
So this PR provides more descriptive output.
- Bug fix

Classlib: Handle `langPort` startup error descriptively

---

HelpSource/Classes/Signal.schelp
lang/LangSource/PyrSignal.cpp

When calling `.thresh` on a Signal, the supplied threshold is squared:
```supercollider
Signal.sineFill(1024, [1]).thresh(0.5).reject(_==0).minItem
// -> ~0.25
// Signal.thresh zeroes out everything below threshold.squared?
// as expected SimpleNumber.thresh zeroes out everything below a threshold
({1.0.rand2}!1024).thresh(0.5).reject(_==0).minItem
// -> ~0.5
```
I would expect `thresh` to do the same operation on SimpleNumbers and Signals. Am I missing something?
The threshold gets squared only for signal_thresh_fx, in `lang/LangSource/PyrSignal.cpp`:
https://github.com/supercollider/supercollider/blob/6de068ba83587d33d06d1b21f99b7a73ef5d8997/lang/LangSource/PyrSignal.cpp#L216
It looks like a copy-paste leftover from signal_ring4_xf, which is just above. Removing this line produces the …

sclang: fix signal_thresh_xf typo

---

HelpSource/Classes/SimpleNumber.schelp
SCClassLibrary/Common/Math/SimpleNumber.sc
SCClassLibrary/Common/Streams/FilterPatterns.sc
SCClassLibrary/Common/Streams/Stream.sc
testsuite/classlibrary/TestPatternProxy.sc
testsuite/classlibrary/TestSimpleNumber.sc

- add smallButNotZero method on SimpleNumber.
- incorporate changes from @telephon PR #4801: Psync now rounds up time.
- add fix for #4767, related to time precision, causing Event doubling when redefining Pdefs.
Fixes #4767.
- Bug fix

Fix time precision issues with Psync and EventStreamPlayer

---

HelpSource/Classes/NamedControl.schelp

Refactors the examples in the help file to working code. Before an exception was thrown because the NamedControl was instanced with multiple different default values.

Fix NamedControl example code

---

server/plugins/UnaryOpUGens.cpp

This is a workaround for #5893 and fixes the behavior of `.sqrt` and `.reciprocal` UGens on Apple M1.
The PR disables nova-simd (vectorized) implementations of `recip` and `sqrt` functions on ARM CPUs due to an issue upstream: https://github.com/timblechmann/nova-simd/issues/11
Once these functions are fixed upstream, the changes introduced in this PR should be reverted for best performance.
I'm adding the `macOS` label since performance on Apple M1 CPU is the primary target of this "fix". However, this might apply to all ARM64 CPUs, so I'm guessing it may also affect RaspberryPi 4 (not tested).
To test:
```supercollider
s.boot;
x = {DC.ar(2).reciprocal.poll; Silent.ar()}.play; // UGen(UnaryOpUGen): 0.5 (was: 0.499998)
x = {DC.ar(0).sqrt.poll; Silent.ar()}.play; // UGen(UnaryOpUGen): 0 …
```

Fix .sqrt and .reciprocal on the server on M1 CPUs

---

SCClassLibrary/Common/GUI/Base/QWebView.sc
SCClassLibrary/Common/GUI/tools/HelpBrowser.sc

Users of fantastic scnvim plugin in neovim can choose pandoc version of helpfiles, or classic style, which uses ```HelpBrowser``` class. For those, which are using a classic helpdoc this PR adds some VIM like keystrokes for comfortable browsing documentation. I've found it very useful and handy, code is tested & working on Linux.
the new keys are:
* h,j,k,l - back histo,down, up, forward histo
* ctrl + D, ctrl + U - bigger step scroll down, up
* g,G - go to top, to bottom of document
* J,K - zoom out, zoom in
* F3 - go to main Search page
* F5 - reload page
* / - search page
* alt + leftArrow, alt + rightArrow - back histo, forward histo
- New feature
This needs to be checked on other than Linux platforms.

NEW Vim like keyshortcuts in HelpBrowser

---

HelpSource/Classes/Function.schelp
HelpSource/Classes/FunctionDef.schelp
HelpSource/Guides/Multichannel-Expansion.schelp
SCClassLibrary/Common/Core/Function.sc
SCClassLibrary/Common/Core/Kernel.sc
testsuite/classlibrary/TestFunction.sc

- The old implementation of function flop was hard to understand and not useful for other puroses.
- inEnvir had no support for keyword arguments
This fixes both.
Up for discussion: the benchmarks are all very low. Maybe just replace the old inEnvir with the new one.
```
f = { |a, b| [a, b, ~c, ~d] };
x = f.inEnvir((c: 1, d: 2));
y = f.inEnvirWithArgs((c: 1, d: 2));
bench { 1000.do { x.value(1, 2) } }
bench { 1000.do { y.value(1, 2) } }
bench { 100.do { f.inEnvir((c: 1, d: 2)) } }
bench { 100.do { f.inEnvirWithArgs((c: 1, d: 2)) } }
```
- New feature

Topic refactor function flop

---

HelpSource/Classes/AbstractGridLines.schelp
HelpSource/Classes/ControlSpec.schelp
HelpSource/Classes/DrawGrid.schelp
HelpSource/Classes/ExponentialGridLines.schelp
HelpSource/Classes/GridLines.schelp
HelpSource/Classes/LinearGridLines.schelp
SCClassLibrary/Common/GUI/Base/Grid.sc
SCClassLibrary/deprecated/3.13/GUI/Grid.sc

This is a follow-on PR to the recently merged #5161, refactoring the `DrawGrid:*test` into  a new standalone class, removing clutter from `DrawGrid` and allowing access to the grid object under test as well as its enclosing view. This was brought up in the discussion of #5161, but deferred to its own PR.
There's also expanded and clarified the documentation, with examples and scdoc syntax formatting added.
- Bug fix
- New feature
- `DrawGrid:-numTicks` and `-tickSpacing` now allows setting x and y axes individually.

Add DrawGridTest

---

server/plugins/TriggerUGens.cpp

Reset state of `PauseSelf` and `FreeSelf` after init sample calculation, otherwise a trigger on the first sample will be missed.
Note the `FreeSelf` change fixes an edge case where a UGen would free the synth on the  first sample.
This example doesn't currently work, but works with this proposed fix.
```supercollider
(
x = {
Silent.ar.poll(4, label: "I am not paused.");
// FreeSelf.kr(Impulse.kr(0)); // immediately free
FreeSelf.kr(Impulse.kr(1, phase: 0.5)); // free after 0.5 sec
}.play
)
```
Fixes #5910, and hopefully [SuperDirt #277](https://github.com/musikinformatik/SuperDirt/issues/277)

Free/PauseSelf: restate state of Ctor after init sample calc

---

SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/GUI/PlusGUI/Control/server-meter.sc
SCClassLibrary/Common/GUI/tools/ServerMeter.sc
SCVersion.txt

This fixes #5545. ServerMeter now behaves like Scope. By result of the discussions in #5549, it may make sense to rethink the design of all server windows, and potentially an easy way to handle unique windows.
A refactoring of the server views is recommended, this is just the minimal step to fix the issue at hand.
Multiple ServerMeters can be created by directly instantiating the object (like Stethoscopse for multiple scopes).
Thanks to @capital-G and everyone else for discussion.
- Bug fix

class library: only one server meter by default

---

SCClassLibrary/Common/Audio/SynthDef.sc

Move the check for name.isNil from the do to the reject loop.
Another (less conservative) approach would have been to eliminate
the check altogether.  It likely never did anything anyways,
because if it did, it would have resulted in an invalid file.

Avoid writing invalid synthdef files

---

.github/workflows/actions.yml

The main reason I did this was to be able to build SC under MinGW on Windows, as the issue for building `Link` submodule with MinGW was fixed upstream. I also assume "newer is better", however I'm not using LinkClock myself and I'd like to hear from folks who actually use it.
~~I would hold off on reviewing/merging this until we get LinkClock unit tests operational in CI again.~~
EDIT: Due to the lack of response, I suggest that we merge this and see if it causes any issues for the users.
- Bug fix (?)
- Breaking change (hopefully not)

Update Ableton Link submodule to version 3.0.6

---

HelpSource/Classes/AbstractGridLines.schelp
HelpSource/Classes/Collection.schelp
HelpSource/Classes/Plotter.schelp
HelpSource/Classes/Signal.schelp
HelpSource/Classes/SimpleNumber.schelp
SCClassLibrary/Common/Control/Spec.sc
SCClassLibrary/Common/GUI/Base/Grid.sc
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc
SCClassLibrary/Common/Geometry/Rect.sc

This follows  up #5161, in response to [feedback](https://github.com/supercollider/supercollider/pull/5161#issuecomment-1321457870) about retaining previous functionality in how the tick labels are handled in `DrawGrid`.
In particular this adds functionality so that you can achieve the same look as previous version of SC:
- Move and align tick axis labels
- Append a string to axis labels
- Constrain labels to the edges of the grids
- en/disable labels independently
- set the Font and Color of tick and axis labels independently
~~This PR is unfinished but as it's blocking the next RC, I'm posting it early so those involved can comment on what's been done so far. @dyfer @sternsc.~~
This required basically a complete overhaul of how the new tick/axis label spacing is calculated so that …

classlib: Plotter: extend tick labels

---

SCClassLibrary/Common/Core/AbstractFunction.sc
testsuite/classlibrary/TestAbstractFunction.sc

Ensure that if using FunctionList directly that removeFunc can be used before addFunc.
Ran the tests locally using [gist](https://gist.github.com/gorenje/10ea2903a55f395f3e436f08abe9e402).
Fixes #5935 
- Bug fix

fix: FunctionList has an empty list by default.

---

SCVersion.txt

The version on `develop` should end in `-dev`. 
This will create a conflict for the later merge `3.13` -> `develop`, but once it's resolved (on the first merge), it shouldn't be an issue anymore.
- Misc

Update SCVersion on develop

---

.github/workflows/actions.yml

I noticed that caching [didn't work](https://github.com/supercollider/supercollider/actions/runs/3942642953/jobs/6746690038#step:21:2) for the newer Linux builds in GHA.
The default ccache directory [has changed](https://ccache.dev/manual/4.3.html#:~:text=is%20set%2C%20otherwise-,%24HOME/.cache/ccache,-.%20Exception%3A%20If%20the) in a recent version of ccache. This PR updates our GHA workflow accordingly.
AFAIU, this change is only needed on Linux at this time.
- Bug fix

GHA: use updated ccache directory on Linux

---

.github/workflows/actions.yml
CHANGELOG.md
HelpSource/Guides/News-3_13.schelp

This PR replaces a partial script for manual creation of universal libraries for homebrew packages with a [3rd-party script which I wrote](https://gist.github.com/dyfer/6c83905d4593750105897e51e87ec345), that achieves this more reliably.
A little history how we got here:
GHA does not offer arm64 macOS runners, so in order to provide an arm64 build (or a universal one), we need to cross-compile. This requires all dependencies to be available as universal binaries, so at first we used vcpkg to create arm64 binaries of libsndfile and fftw, and created a script that manually created universal binaries of readline, qt5 and its dependencies. This script was fairly specific, didn't handle some packages well, was able to use caching in a limited way etc. Also, libsndfile in homebrew was not …

GHA: create macOS universal binary with homebrew libraries

---

.github/workflows/actions.yml

This was missing from #5953 
S3 upload seems broken ATM anyway due to an issue with credentials, but the name should've been updated for the universal build.
- Bug fix

GHA: update artifact name for upload to AWS S3

---

server/plugins/TriggerUGens.cpp

`Poll` misses a trigger on the first sample... but not anymore!
This bug was revealed only with the updated behavior of `Impulse` (as of 3.13). There was no issue filed, but addresses a [discussion](https://github.com/supercollider/supercollider/issues/4127#issuecomment-1424294256) that uncovered the bug.
- Bug fix
- [N/A] Updated documentation

Poll: fix initialization to fire on first-sample trigger

---

.github/workflows/actions.yml
CHANGELOG.md
HelpSource/Guides/News-3_13.schelp
SCVersion.txt

Docs update before 3.13.0-rc3
Please note: I added an unrelated but IMO minor commit that should prevent from creating unnecessarily large homebrew caches. This should save some time for macOS builds.

Update Changelogs and SCVersion for 3.13.0-rc3

---

.github/workflows/actions.yml

The recent macOS legacy builds are [failing](https://github.com/supercollider/supercollider/actions/runs/4208593518/jobs/7304787719#step:10:67) because vcpkg needs `pkg-config`, which is missing. This issue was [fixed upstream](https://github.com/actions/runner-images/pull/7125), but - IIUC - it will take about 2 weeks until this makes it into the runner image release. In order to be able to release SC in the meantime, I propose to manually install `pkg-config`. This can be reverted once the issue is fixed upstream.
- Bug fix

GHA macOS: temporary fix for the legacy build

---

.github/workflows/actions.yml

This is a temporary change to make it work down to macOS 10.10. macOS 10.15 images will be unavailable at the end of March 2023.
This should allow for making one last release that supports macOS 10.10. After that we'll have to bump to... 10.11 :) (this seems to work fine on macOS 11 runner with Xcode 12)
This is a fix for an issue reported [on the forum](https://scsynth.org/t/problem-starting-sc-13-3/7188).
- Bug fix

GHA: use Xcode 10.3 for macOS legacy build

---

.github/workflows/actions.yml

It seems we were unnecessarily installing Qt from homebrew when we also used Qt from `aqtinstall` action. This just wasted some time, there are no functional changes here. 
In practice, this only affected the macOS legacy build.
~~This PR should go in after #5976 is merged.~~ This is now rebased on top of `develop`, ready for review/merging.
- Bug fix

GHA: fix logic for installing Qt from homebrew

---

.github/workflows/actions.yml
README.md

This is a GitHub Actions maintenance PR, combined with documentation update.
I updated README.md to reflect, more or less, our [platform support guarantees](https://github.com/supercollider/supercollider/wiki/Platform-Support), based on the build environment in GitHub Actions and information I came across on the forum and in the PRs in the last few months, with the exception of the following:
- MSVC version: there might be issues with MSVC 2022; in any case, I feel there should be a separate PR that updates the build environment to MSVC 2022, at which point we should update the Readme
- Qt version: I think this should be updated once we migrate to Qt6
- "Tested with": we are testing with OS version outside of the "guaranteed support" window; I am planning to provide a separate PR to …

Update Linux build matrix and Readme on supported OSes and Libraries

---

.github/workflows/actions.yml

Our build caches are fairly large and we are hitting [GHA's 10GB limit](https://github.com/supercollider/supercollider/actions/caches) fairly soon, after just a few subsequent builds. The worst offender is the cache for homebrew "universal" binaries (1.3 GB per run, once in the matrix), with homebrew downloads being also considerable (~140 MB * ~~4~~ 3 macOS builds). 
Currently each build cache uses the daily timestamp, so a new build each day would create new cache. This becomes a problem if we have just a few PRs building and the cache from the `develop` build gets evicted (if we go over 10GB total). This will cause every new build on a new branch after that not having the cache available and thus taking much longer.
I think this can be minimized by changing renewal of the caches in …

GHA: refresh some caches weekly, not daily

---

.github/workflows/actions.yml
README.md

After 3.13 release it turned out that setting 10.10 deployment target with Xcode 12 yielded unbootable server. We [fixed that temporarily](https://github.com/supercollider/supercollider/pull/5984) for 3.13 by using the older OS image with Xcode 10.3, but this image is deprecated and won't be available after March of 2023.
In my previous tests, I discovered that setting deployment target to 10.11 (one version higher) results in a working build with bootable server, so I suggest we update our legacy build to that setting.
**NOTE:** ~~I don't have a 10.11 system right now to test this. However,~~ EDIT: I tested the legacy build on both 10.11 and 10.13 and the server booted, so I think this is okay.
- Bug fix

macOS: raise legacy build OS requirement to 10.11

---

.github/workflows/actions.yml

Ubuntu 18.04 images are [deprecated](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) and will soon be unavailable (see [this job](https://github.com/supercollider/supercollider/actions/runs/4633290823)). This PR updates some jobs to use the latest ubuntu images. 
Please note that I've changed these jobs to use `ubuntu-latest`, which will be periodically updated by GH to point to the latest "stable" image. I believe that for the "helper" tasks (upload to S3 and upload to the release) this should be fine.
Remaining 18.04 jobs are updated in #6003 
- Bug fix

GHA: update Ubuntu 18.04 jobs

---

.github/workflows/actions.yml

I noticed that Windows builds were taking quite long, despite supposedly using ccache. It turns out that ccache 4.8 didn't cache our MSVC builds due to an [issue upstream](https://github.com/ccache/ccache/issues/1262); 4.8.1 should fix that, so in the meantime let's revert back to the version that worked.
- Bug fix

GHA Windows: revert ccache version

---

SCClassLibrary/Common/Audio/Trig.sc

Fixes #6022 as currently `.signalRange` returns bipolar on `SetResetFF` but it is indeed unipolar. This change was requested in #6020 
https://github.com/supercollider/supercollider/blob/18c4aad363c49f29e866f884f5ac5bd35969d828/HelpSource/Classes/SetResetFF.schelp#L1-L13
- Bug fix

mark SetResetFF explicitly as unipolar 

---

testsuite/scripts/test_run_proto_gha.scd

The test `TestThreadReschedule:test_Threads_rescheduleToOtherClock` often fails on Linux when run in GHA, see e.g. [1](https://github.com/supercollider/supercollider/actions/runs/5844171201/job/15953568411#step:9:128), [2](https://github.com/supercollider/supercollider/actions/runs/5633446654/job/15262730723#step:9:128)
Since the failure seems to be hard to recreate (likely requiring heavy system load) and my lack of understanding of the thread mechanisms in SC, I'm not attempting to fix it at this time.
I propose to disable this test for now so that we have fewer CI failures unrelated to issues at hand.
- Bug fix (?)

testsuite: skip TestThreadReschedule in GHA

---

.github/workflows/actions.yml

Our main macOS universal build started to fail. 
FYI In the universal build we use [my script](https://gist.github.com/dyfer/6c83905d4593750105897e51e87ec345#file-brew-install-universal-sh) for creating "universal" (x86_64 + arm64) homebrew binaries.
The script recently stopped producing proper binaries, due to hardcoding homebrew bottles' urls. I [updated](https://gist.github.com/dyfer/6c83905d4593750105897e51e87ec345/revisions#diff-984e11579406a2aa02938c5257e95cbf5e850d5173b3a7e484211aa5189b5637L139) the script on my repo to extract the urls from `brew info` command instead.
This PR updates the version of the script in our CI to pull in this change.
- Bug fix

GHA macOS: Fix an issue with hardcoded bottle urls

---

SCClassLibrary/Common/Quarks/GUI/QuarksGui.sc
SCClassLibrary/Common/Quarks/Git.sc
SCClassLibrary/Common/Quarks/Quark.sc

currently "master" is hardcoded as the branch to checkout in Quark.update causing update to fail for Quarks using "main" (which has become a norm in recent years).
This adds a method which uses "git symbolic-ref refs/remotes/origin/HEAD --short
" to find out the appropriate name
Fixes #6071  
Fixes #5096
- Bug fix
If someone could test further it would be great! Its working for me so far.

added defaultBranchName method to Git.sc

---

.github/workflows/actions.yml
README.md

macOS 11 is not officially supported by homebrew anymore. This means that binary packages for some formulae stopped being available and homebrew would build them locally. This is problematic for large packages like Qt5 - the last CI attempt [stopped after 6 hours](https://github.com/supercollider/supercollider/actions/runs/6444265220/job/17497064701#step:15:428), in the middle of building qtwebengine...
Please note that I did not change the legacy build, since 1) we are not using Qt5 from homebrew there and 2) it will likely go away when we move to Qt6. It still builds fine though!
EDIT: I also updated macOS and Xcode versions in`README.md`.
- Bug fix

GHA: update macOS runner image to macOS 12

---

HelpSource/Classes/Amplitude.schelp

Amplitude help claims that the convergence times are toward 60 dB.
But in the plugin source code, a 60 dB convergence coefficient is calculated as `exp(log001 / (decayTime * SAMPLERATE));` (see [Decay](https://github.com/supercollider/supercollider/blob/develop/server/plugins/FilterUGens.cpp#L1127)).
Amplitude uses `exp(log1 / (clampTime * SAMPLERATE));` ([line 3495](https://github.com/supercollider/supercollider/blob/develop/server/plugins/FilterUGens.cpp#L3495)) where log1 = std::log(0.1) (SC_Constants.h).
The first is calculated relative to 0.001 == -60 dB while the second is relative to 0.1 == -20 dB, so I conclude that the Amplitude convergence time is really 20 dB.

Help: Amplitude's convergence time is really 20 dB

---

SCClassLibrary/Common/Collections/Array.sc
SCClassLibrary/Common/Collections/Array2D.sc
SCClassLibrary/Common/Collections/Collection.sc
SCClassLibrary/Common/Collections/EnvironmentRedirect.sc
SCClassLibrary/Common/Collections/SparseArray.sc

This PR is a correct PR (based on my branch) of the following closed wrong PR (based on the develop branch):
https://github.com/supercollider/supercollider/pull/6105
The post window output of the collection's subclasses does not follow the recommended code style.
This PR makes these post-window outputs follow the recommended code style, so that users can use the post-window output in new code without removing whitespace.
Please see the following scsynth forum thread:
https://scsynth.org/t/array-recommended-style-of-code-and-how-to-return-to-the-post-window/8310
- minor but practical change

Removed white space in brackets printed on the post window.

---

CMakeLists.txt

Make it build on RISC-V, MIPS etc.
- Bug fix

CMakeLists: only enable SSE on x86 variants

---

.github/workflows/actions.yml

We use my [script](https://gist.github.com/dyfer/6c83905d4593750105897e51e87ec345#file-brew-install-universal-sh) to create "universal" (x86_64 + arm64) homebrew packages to facilitate macOS universal build.
A recent change in homebrew caused an issue with deploying some libraries with `macdeployqt` (see https://github.com/supercollider/supercollider/issues/6104). While we wait (I think?) for the updated libsndfile bottle in homebrew, I realized that I can "manually" change the non-fully qualified paths to full paths in the manually prepared bottles, since I am manipulating the paths already: https://gist.github.com/dyfer/6c83905d4593750105897e51e87ec345#file-brew-install-universal-sh-L226-L251
In this update, the script converts the non-fully qualified paths (@loader_path/.. etc) to …

GHA: update the brew-install-universal script

---

SCClassLibrary/Common/Collections/Event.sc
SCClassLibrary/Common/Collections/SparseArray.sc
SCClassLibrary/Common/Control/Server.sc
SCClassLibrary/Common/Geometry/Point.sc
SCClassLibrary/Common/Math/Complex.sc
SCClassLibrary/Common/Math/Polar.sc
testsuite/classlibrary/TestNodeProxy.sc

Remove whitespace from .storeOn .printOn methods. A follow-up PR for #6106. 
Not thoroughly tested...
- Breaking change (technically)

classlib: remove whitespace from .storeOn .printOn

---

.github/workflows/actions.yml

While I acknowledge that it's unsure how much longer we'll be supporting the macOS legacy build, I'd like to make its impact on our GHA build times minimal.
Due to homebrew dropping support for macOS 11, some dependencies of fftw started to [build from source](https://github.com/supercollider/supercollider/actions/runs/6579631472/job/17881931695#step:9:115), increasing build times significantly. I'd like to switch fftw to build from vcpkg, which is faster, and is also cached.
EDIT: I decided to also change the runner image to macOS 12, since there seem to be other issues with using macOS 11.
- Bug fix (kind of)

GHA macOS legacy: build fftw

---

server/scsynth/SC_ComPort.cpp
server/scsynth/SC_CoreAudio.cpp
server/supernova/server/server.cpp
server/supernova/utilities/osc_server.hpp

On macOS, `nova::thread_priority_interval()` just returns dummy values (0), thus it would accidentally *lower* the thread priority. This can lead to particularly poor performance on recent Apple Silicon machines because the thread might get scheduled on efficiency cores. I removed any calls to `nova::thread_priority_interval`; instead we simply keep the default thread priority (for now).
On Windows, thread priorities are not a continuous range, so you cannot take the mean of the range return by `nova::thread_priority_interval_rt`. In fact, this would pass an invalid value to `SetThreadPriority` and essentially do nothing. Instead I simply use the lower value which effectively raises the thread priority a bit (`THREAD_PRIORITY_ABOVE_NORMAL`). This also matches the behavior of Supernova, …

scsynth/supernova: fix thread priorities

---

SCClassLibrary/scide_scqt/ScIDE.sc

When opening a `/*RUN*/` auto-run file, `thisProcess.nowExecutingPath` is not set so the code in the document can't resolve paths relative to its own location.
E.g. if I have `~/test.scd`:
```
/*RUN*/
thisProcess.nowExecutingPath.debug("path");
```
... and open it, I should get `path: /home/xxx/test.scd` in the post window. Without the fix, it's `path: nil`.
Easy fix.
- Bug fix
- ~[ ] Updated documentation~

classlib: IDE Document should set path before autorun

---

.github/workflows/actions.yml

It [seems](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7926) that building parallelism is now available with cmake + msvc. In that case, let's set the parallelism to the number of cores of the gha runner for msvc.

GHA Windows: enable multithreaded builds for MSVC

---

HelpSource/Overviews/MidiPatterns.schelp

This is a small PR that adds an overview file in the help system for midi commands. I generally found it very hard to figure out without having to dig into the Event.sc source code, so I figure someone else could use this :) 

docs: Add overview of pattern midi events

---

testsuite/classlibrary/TestEnvGen_server.sc

One unit test has been breaking for a while on account of a doneAction firing in the course of initializing `EnvGen`:
- `test_zero_gate_n_off_not_sent`: let synth be initialized before adding responders
Another test started failing once the initialization sample problem for `EnvGen` was fixed (https://github.com/supercollider/supercollider/pull/6175), because incorrect initialization led to a false positive:
- `test_shapeHold_setEndValue`: let synth run long enough to pass.
- Bug fix

Tests: TestEnvGen_server: fix 2 tests

---

SCClassLibrary/Common/Core/Function.sc

See https://scsynth.org/t/why-are-the-multiple-plots-in-a-routine-affected-by-the-last-plot-duration-when-using-a-single-function-defined-as-a-variable/8836
```
(
s.waitForBoot {
var freq = 440, sig = { SinOsc.ar };
sig.plot(freq.reciprocal * 9, bounds: Rect(0, 250, 400, 250)); // plot 1.
sig.plot(freq.reciprocal, bounds: Rect(0, 530, 400, 250)) // plot 2.
}
)
```
You would expect the durations of the two plots to be independent, but in fact, the signal of the longer plot (plot 1) is truncated.
- Plot 1: Graph covers 20 ms but only the first 2.2 ms show a signal.
- Plot 2: Graph covers 2.2 ms and is fully populated.
Function:asBuffer redundantly encodes the plot duration twice: once in the buffer size, and again in a `Line` with `doneAction: 2`. The latter is hardcoded as a constant in …

Classlib: Simplify Function:plot 'dur' redundancy

---

HelpSource/Classes/DecodeB2.schelp
HelpSource/Classes/DiskIn.schelp
HelpSource/Classes/GrainBuf.schelp
HelpSource/Classes/GrainFM.schelp
HelpSource/Classes/GrainIn.schelp
HelpSource/Classes/GrainSin.schelp
HelpSource/Classes/MultiOutUGen.schelp
HelpSource/Classes/PanAz.schelp
HelpSource/Classes/TGrains.schelp
HelpSource/Classes/VDiskIn.schelp
HelpSource/Classes/Warp1.schelp
SCClassLibrary/Common/Audio/InOut.sc
SCClassLibrary/Common/Audio/UGen.sc

`InFeedback` and other MultiOutUGen subclasses only accept numerical arguments for `numChannels`, throwing a confusing error ("Non boolean in test"). This PR validates the `numChannels` argument in `init` and throws a straightforward error there. In addition it validates for integer values only.
- Bug fix (really an improvement, but arguably the old error was a "bug")
I don't think testing is appropriate, given that this simply reports a failure differently/better. IMO validating error message text in tests is not a good practice on its own. Any errors introduced by this change should be discovered in CI.

class library: MultiOutUGen: better error for non-numeric numChannels arg

---

HelpSource/Classes/Pfindur.schelp

Removed an invalid keyword from a code example in the Pfindur help file. This example included the keyword 'filling.' Evaluating this example returns a warning, and I have absolutely no idea why this keyword is included in the example.
I believe this example, in combination with the example immediately above it, are simply meant to show how Pfindur behaves when constraining an infinite-length pattern compared to a finite-length pattern.

remove bogus argument keyword in Pfindur help file

---

HelpSource/Classes/Function.schelp
HelpSource/Classes/OSCpathResponder.schelp
HelpSource/Classes/Synth.schelp
HelpSource/Guides/News-3_11.schelp
HelpSource/Guides/SuperColliderAU.schelp
HelpSource/Guides/Tracing-Processes.schelp
HelpSource/Overviews/Operators.schelp
HelpSource/Tutorials/Mark_Polishook_tutorial/08_Rates.schelp
HelpSource/Tutorials/Mark_Polishook_tutorial/Japanese_version/09.schelp

I recently saw a PR where Ugen was considered a typo. I found all these things in the built-in schelp and changed it accordingly.

typo correction: change Ugen/Ugens in help documents to UGen/UGens

---

SCClassLibrary/JITLib/ProxySpace/wrapForNodeProxy.sc

This fixes #6222. The number `-1` was probably a misunderstanding anyway, since the node id is -1 for anonymous synths. There is no such thing as a meaningful bus number of -1.
- Bug fix

class library: when NodeProxy is neutral, rest source pattern

---

HelpSource/Classes/ArrayedCollection.schelp

Rephrased the Note accompanying perfectShuffle in the ArrayedCollection help file. The wording was inaccurate (the number of items should be even, rather than the number of item pairs) and there was also a spelling mistake.

docs: fix note for perfectShuffle in ArrayedCollection help file

---

HelpSource/Classes/UGen.schelp
SCClassLibrary/Common/Audio/UGen.sc
SCClassLibrary/Common/Core/AbstractFunction.sc
testsuite/classlibrary/TestCoreUGens.sc

The method `binaryValue` is valid only for booleans and numbers, not for functions and UGens. This makes it valid.
Note that there is a comment in SimpleNumber: " // TODO in the long-run, deprecate for asInteger"
We did this because we thought that it is better expressed as a conversion (beginning with "as").
But I don't think it should be `asInteger` but `asBinaryValue`. This is a separate issue.
- New feature

complete binaryValue implementation for AbstractFunction and UGen

---

HelpSource/Classes/PanAz.schelp
server/plugins/PanUGens.cpp

When width is negative in `PanAz` the server crashes #6012 
```supercollider
{PanAz.ar(2, DC.ar, 0, 1, -0.001)}.play
```
Since width is a magnitude, it makes no sense for it to be negative. Taking the abs is an easy fix for #6012
Fixes #6012
- Bug fix
- Docs

ServerPlugins: PanAZ: fix bug when width is small and negative

---

SCClassLibrary/Common/Collections/Dictionary.sc
testsuite/classlibrary/TestDictionary.sc

This fixes #6000.
- Bug fix
- Breaking Change
Considering the possible breaking changes:
|      trueAt            | obj | nil | true | false |
|-|--|-|-|-|
| previous: | obj | false | true |false |
| new:        | false | false | true |false |
So if you were assuming that `trueAt` and `falseAt` would return a boolean, your code would previously fail.
The change only extends the range of possible correct answers and does not change those that were already correct.
I however can imagine boundary cases where you'd use a `try { }` around the statement. Or, if someone were trying to fix the problem by calling `.trueAt(key).asBoolean`.
*Edit* There is an alternative possibility, that I favour (not implemented here yet, please discuss): The original idea of `trueAt` – I think – was to allow an …

fix Dictionary trueAt

---

SCClassLibrary/Common/Quarks/Quarks.sc

Fixes #6155  - installing Quarks with circular dependencies would hang - I added an "installing" classvar that keeps track of any Quarks in the process of installing and prevents re-installing them as dependencies
- Bug fix

Add check before installing Quark dependencies

---

HelpSource/Classes/Amplitude.schelp

Facebook conversation:
> Why does Amplitude return an unexpected value?:
> (
> {
>  Amplitude.ar(SinOsc.ar).poll;
>  Silent.ar
> }.play
> )
> Polled value is around 0.63, but I would expect the value to be 1.
Me: "You're expecting the peak amplitude. Many ways of measuring amplitude (e.g. RMS, which is well standard in audio) reflect the average level rather than the peak. ... Amplitude will return a larger value for louder signals but if you really need the peak, see Peak.ar ."
Them: "Makes sense, although my assumption was based on the description of the UGen: 'Tracks the peak amplitude of a signal.'"
Misleading wording.

Help: Correct wording in Amplitude help (it's not the peak)

---

lang/LangSource/PyrParseNode.cpp

This is uncontroversial and can be quickly reviewed.
Cannot have more than 255 arguments to a function, but the message was printed twice. This removes that duplication.
Some code to test, it should only show one error message after this PR.
```supercollider
{| foo , foo0, foo1, foo2, foo3, foo4, foo5, foo6, foo7, foo8, foo9, foo10, foo11, foo12, foo13, foo14, foo15, foo16, foo17, foo18, foo19, foo20, foo21, foo22, foo23, foo24, foo25, foo26, foo27, foo28, foo29, foo30, foo31, foo32, foo33, foo34, foo35, foo36, foo37, foo38, foo39, foo40, foo41, foo42, foo43, foo44, foo45, foo46, foo47, foo48, foo49, foo50, foo51, foo52, foo53, foo54, foo55, foo56, foo57, foo58, foo59, foo60, foo61, foo62, foo63, foo64, foo65, foo66, foo67, foo68, foo69, foo70, foo71, foo72, foo73, foo74, foo75, foo76, …
```

SCLang: tidy duplicated error message

---

HelpSource/Classes/DebugFrame.schelp

`DebugFrame` had no documentation, now it does.
Creates a new file.
Also includes an example of how to construct a backtrace.

Docs: Add documentation for DebugFrame

---

.github/workflows/actions.yml

The current macOS build `macOS x64 use system libraries` is broken, see https://github.com/supercollider/supercollider/actions/runs/9187974816/job/25266805454
This is caused due to an upgrade to a new boost version 1.85 via brew which is not compatible with our codebase (as this build configuration is using the boost lib from the system instead of the provided via our codebase). By using https://formulae.brew.sh/formula/boost@1.76 instead of https://formulae.brew.sh/formula/boost we can still use an older version of boost for the build which will make the build pass. Please note that this is already deprecated.
As these boost files are not symlinked by brew, we need to link them explicitly for cmake.
We should still make the codebase compatible with the new boost version as this causes …

Fix boost version for macOS use system libraries build

---

HelpSource/Classes/ScopeView.schelp
HelpSource/Classes/Stethoscope.schelp
QtCollider/widgets/QcScopeShm.cpp

Currently ScopeView's lissajou style limits itself to the first two channels being monitored. It is however useful to be able to plot lissajou curves for more than one channel pair, the simplest way being overlaying them. ScopeView is already able to monitor more than two channels, and it has an option to choose different `waveColors`, which make overlaid XY plots discernible, like in the current `overlay` style.
Before making this PR, I've tried composing two stethoscopes in a `StackLayout`, with transparent backgrounds, but it failed at overlaying plots, perhaps due to the QtCollider implementation drawing a bitmap.
This PR doesn't compromise previous functionality: when scoping a 2 channel bus, XY plots are still 2 channels, and default GUIs have options to change number of channels …

ScopeView: allow lissajou for more than 2 chs as overlaid pairs

---

CMakeLists.txt
cmake_modules/cmake_uninstall.cmake.in

This PR updates deprecated commands and improves the handling of compiler flags with recommended syntax. Goal: more clear, forward-compatible code, with some added comments. 
No changes in functionality. 
- Overall: a) clarity and compatibility; b) documentation for future devs
- Replacement of deprecated command: Replaced the deprecated `exec_program` with `execute_process` for better handling of compiler version, and compatibility with future CMake versions
- Compiler flag: Replaced `add_definitions` with `add_compile_options` to specify compiler flags. `add_compile_options` is used to add any compiler options, making it more flexible, not just preprocessor definitions. `add_definitions is not recommended and primarily intended for adding preprocessor definitions, so its use is being …

Update CMakeLists.txt replace deprecated commands

---

HelpSource/Classes/Dictionary.schelp
SCClassLibrary/Common/Collections/Dictionary.sc
SCClassLibrary/Common/Core/Object.sc

#6001 introduced a breaking change that answers `-trueAt` based on the receiver's `-booleanValue`. 
But `-booleanValue` is only defined for `Boolean`, `Nil`, and `SimpleNumber`, so any other object will fail.
```supercollider
d = (num: 23.7, yes:true, no:false, symb:\bar);
d.trueAt(\num) // true
d.trueAt(\yes) // true
d.trueAt(\no) // false
d.trueAt(\foo) // false (d[\foo] is nil)
d.trueAt(\symb) // breaks
```
The proposed solution is that `Dictionary:-trueAt` answers `false` for any object that isn't `true` or a positive `SimpleNumber` (this aligns with the initial proposal in #6001).
```supercollider
trueAt { arg key;
^try { this.at(key).booleanValue } { false }
}
```
This lets individual kinds of objects change behavior in the future by implementing `-booleanValue`, rather than …

Fix Dictionary:-trueAt to respond to all objects

---

HelpSource/Classes/GVerb.schelp
include/common/SC_Types.h
include/plugin_interface/SC_Unit.h
server/plugins/ReverbUGens.cpp

This decltype...
```c++
float a[12];
decltype( a[0] );
```` 
...returns a referenced type, e.g. `float&`, ***not*** `float`.
The macro `sc_typeof_cast` and `CALCSCOPE` used this to perform a c cast.
When converting from a double to a float, this is fine. 
When converting from an double to a float&, this is ***very bad***, and was the main issue with GVerb's roomsize. 
This PR creates a new conversion function using static_cast that does the correct behaviour and will break at compile time if the user attempts to pass something unexpected.
Following the alias violations (#6245) I retested GVerb, and this stopped it from blowing up. The second commit here just adds just more static_casts and uses `std::pow` converting everything to doubles, which further improved it.
Fixes #2302.
Partially …

Scsynth & Plugin: Remove c cast from CALCSCOPE and fix GVerbs roomsize.

---

.github/workflows/actions.yml
.pre-commit-config.yaml

Closes #6096 
SuperCollider has a formatter/linter policy for its C++ files, which is checked via clang-format.
This check is also done in CI, and any commit that does not pass the clang-format stage results in a failed build that is not checked further.
As the formatting rules of clang-format are not consistent between major versions, it is necessary to enforce a specific version of clang-format to create deterministic formatting - the correct version is checked by our formatting tool `clang-format.py`.
https://github.com/supercollider/supercollider/blob/766791ca951f39a9479de2663fe51ab76dd06841/tools/clang-format.py#L121-L122
To have access to a specific clang-format version on a system is not trivial and made e.g. #6196 necessary.
In order to reduce dev dependency management for users …

Add pre commit

---

.github/workflows/actions.yml
.pre-commit-config.yaml
tools/clang-format.py

Currently pre-commit performs a full scan of the C++ files on every commit that touches them - this is necessary because we need to verify the state of the full repo in the CI and not just of the latest commit so it is not possible to "sneak in" unformatted code when pushing multiple commits.
We can assume though that for local setups it is sufficient to check only the diff staged for the current commit.
This drastically speeds up local pre-commit times (from 50 seconds down to 2 seconds).
On CI we still perform a full check of the repo. As it is not possible to pass the `--all-files` flag of the pre-commit invocation to the actual script, we use an environment variable.
Also see https://github.com/supercollider/supercollider/pull/6319#issuecomment-2159966408 and reply/below
- New feature …

add `FULL_CHECK` flag for clang-format

---

HelpSource/Classes/Impulse.schelp
HelpSource/Classes/Plotter.schelp
SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

This PR adds a number of new modes for plotting:
- `dots` is like `points` but with filled circles. (not crazy about the name, open to suggestions)
- in the following, modes are prepended with 'p' or 'd' denoting that 'points' or 'dots' are added to the mode
- `stems`, `pstems`, and `dstems` introduce a mode for a [PCM](https://en.wikipedia.org/wiki/Pulse-code_modulation#Modulation)-style perspective on discrete time sampling/synthesis, common in DSP pedagogy.
- `dlines` is probably the most common waveform representation when "zoomed in" (in DAWs, editors, etc), again highlighting _discrete_ sampling. This is the same as the existing `plines` mode, but the "dots" are filled.
- `filled` fills the area under a waveform, and assumes a bipolar signal (filled to the zero-crossing), like SC's …

Plotter: add new plot modes

---

HelpSource/Classes/SystemSynthDefs.schelp

Just whitespace cleanup... I merged a PR without a [comment](https://github.com/supercollider/supercollider/pull/6323#discussion_r1636417548) being addressed, this addresses that.

help: SystemSynthDefs - remove EOF whitespace

---

HelpSource/Classes/Decay.schelp
HelpSource/Classes/Decay2.schelp
server/plugins/FilterUGens.cpp
testsuite/classlibrary/TestFilterUGens.sc

A majority of UGens do not initialize with a correct initialization sample, and subsequently output an incorrect first sample. This addressed that issue for `Decay` and `Decay2`. Unit test also added.
Fixes #6143
This PR is part of an ongoing effort to [fix UGen initializations](https://github.com/supercollider/rfcs/pull/19), the progress of which is [tracked here](https://github.com/mtmccrea/supercollider/wiki/UGen-Fix-List).
- Bug fix
- Breaking change - initial sample changes are technically breaking.
- added unit test for `Decay2`

Decay, Decay2: fix UGen initialization

---

HelpSource/Classes/ArrayedCollection.schelp
HelpSource/Classes/Object.schelp
SCClassLibrary/Common/Collections/ArrayedCollection.sc
lang/LangPrimSource/PyrArrayPrimitives.cpp
lang/LangSource/PyrKernel.h
testsuite/classlibrary/TestArray.sc

Checks that array is regular is shape (not [jagged](https://en.wikipedia.org/wiki/Jagged_array#:~:text=In%20computer%20science%2C%20a%20jagged,edges%20when%20visualized%20as%20output.)).
I needed this in SoundFile:write to make sure all the channels were the same size, while this is overkill for that solution, functions like Array:size and others make this assumption. 
Implementing this is sclang would be significantly slower.
However, by doing it as a primitive means it only works on Array, and not List. This is because List overloads what a 'size' is. 
Examples:
```supercollider
[].isRegular == true;
(0..10).isRegular == true;
[[1,2], [3,4]].isRegular == true;
[[1,2], [3]].isRegular == false;
// yet...
[[1,2], [3,4]].shape == [[1,2], [3]].shape;
[[1], []].isRegular == false;
```
- New …

Add primitive `isRectangular` to array.

---

.github/workflows/actions.yml

A **temporary** fix for building the macOS universal binary, see #6352 
Supersedes https://github.com/supercollider/supercollider/pull/6357 which deactivated the build completely, here we just de-activate the verifying step during build macOS - I am surprised that the binary can be picked up by a different runner for testing though.
- Bug fix
-

Skip verify on macOS universal CI

---

HelpSource/Classes/Slider2D.schelp
QtCollider/widgets/QcSlider2D.h
SCClassLibrary/Common/GUI/Base/QSlider2D.sc

Simply adds another q_property to QcSlider2D.h
Closes #724.
Some code to demonstrate this change.
```supercollider
Window().layout_(
VLayout(
~a = Slider2D().action_({
~b.thumbSize = ~a.x.linlin(0, 1, 5, 50)
}),
~b = Slider2D().action_({
~a.thumbSize = ~b.x.linlin(0, 1, 5, 50)
})
)
)
.front
```
- New feature

SClang: GUI: Add thumbSize option for Slider2D

---

editors/sc-ide/widgets/util/status_box.cpp

During startup of the IDE, it yields a log message
```
qt.qpa.fonts: Populating font family aliases took 242 ms. Replace uses of missing font family "Monospace" with one that exists to avoid this cost. 
```
This can also take longer (500ms), depending on your system, slowing down every startup of the IDE.
This PR replaces the font with the default monospace font of the system and therefore removes the error message.
I increased the font size a bit in order to match the current size (only checked this on MacOS).
- Bug fix

replace "Monospace" with system monospace font

---

server/plugins/LFUGens.cpp
server/plugins/TriggerUGens.cpp
testsuite/classlibrary/TestCoreUGens.sc
testsuite/scripts/test_run_proto_gha.scd

A majority of UGens do not initialize with a correct initialization sample, and subsequently output an incorrect first sample. This PR is part of an ongoing effort to [fix UGen initializations](https://github.com/supercollider/rfcs/pull/19), the progress of which is [tracked here](https://github.com/mtmccrea/supercollider/wiki/UGen-Fix-List).
This fixes the initialization of a batch of `LFUGens`:
- `Line`, `XLine`
- `Vibrato`
- `LFPulse`, `LFSaw`, `LFPar`, `LFCub`, `LFTri`
- `Trig` and `Trig1` were also fixed (they're in `TriggerUGens`) - this was needed in order to pass related unit tests
`Line` was also made to call `Line_next_nova_64`, which was omitted previously.
(fixed Issues will be updated here)
- Fixes #4279
- Bug fix
- Breaking change - changes are technically breaking for the …

Fix UGen initialization: LFUGens pt. 1/3, Trig, Trig1

---

HelpSource/Classes/UnitTest.schelp

While reading `UnitTest` documentation, I found a typo in a link. This is fixed.

UnitTest.schelp - fix typo

---

lang/LangPrimSource/SC_LinkClock.cpp
testsuite/classlibrary/TestLinkClock.sc
testsuite/classlibrary/TestTempoClock.sc

Fixes #6355.
For compatibility with TempoClock, beats2secs(inf) and secs2beats(inf) should return inf (and, -inf --> -inf).
- Bug fix (I believe it's a regression -- critical bug for my live coding system actually, it breaks slurring notes)
- ~~ [ ] Updated documentation~~

lang: LinkClock beats/secs conversion should trap 'inf'

---

HelpSource/scdoc.css

Current state:
Fixed state:
Fix was made necessary by https://github.com/supercollider/supercollider/commit/39702ec3a9cdc9a4e2ee7385db747e9ba135c3d1
Supersedes https://github.com/supercollider/supercollider/pull/6275
Thanks @prko for bringing this up and providing the impulse.
- Bug fix

Fix doc icon position

---

lang/LangSource/PyrMessage.cpp
testsuite/classlibrary/TestKwargs.sc

Use slotCopy rather than SetObject as the default for kwargs is nil, not an empty array.
Quick fix for bug found by @telephon.
```
(
~forwardCrash = { |func|
{ |...args, kwargs|
var val = func.performArgs(\value, args, kwargs);
val
}
};
~forwardWorks = { |func|
{ |...args, kwargs|
func.performArgs(\value, args, kwargs)
}
};
~forwardWorks2 = { |func|
{ |...args|
func.performList(\value, args)
}
};
)
f = ~forwardWorks.({ |a, b=100, c| [a, b, c] });
f.([1, 2])
f = ~forwardWorks2.({ |a, b=100, c| [a, b, c] });
f.([1, 2])
f = ~forwardCrash.({ |a, b=100, c| [a, b, c] }); // crashes.
f.([1, 2])
// while this is fine:
(
f = { |...args, kwargs|
{ |a, b, c| [a, b=100, c] }.performArgs(\value, args, kwargs)
};
f.([1, 2])
)
```
- Bug fix

SCLang: fix performArgs, wrong type was assumed as default.

---

HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/String.sc
lang/LangPrimSource/PyrStringPrim.cpp
testsuite/classlibrary/TestStringReplaceRegex.sc

https://scsynth.org/t/testing-a-draft-of-replaceregexp
- New feature

Implement replace regex using boost

---

lang/LangPrimSource/PyrStringPrim.cpp
testsuite/classlibrary/TestEnvironmentVars.sc

https://scsynth.org/t/sc-jack-default-env-too-long/7729/4
Use std::string when assigning environmental variables as their length is unknown.
- Bug fix

Use std::string for set and get environment variables - 

---

common/SC_Win32Utils.cpp
common/SC_Win32Utils.h
editors/sc-ide/CMakeLists.txt
lang/CMakeLists.txt
lang/LangPrimSource/PyrStringPrim.cpp
server/scsynth/CMakeLists.txt
server/scsynth/SC_Lib_Cintf.cpp
server/supernova/CMakeLists.txt
server/supernova/sc/sc_ugen_factory.cpp

On Windows it seems that for the Qt6 build we need to be building with the `UNICODE` flag set, and in turn make system calls using UTF-16 (WideChar) functions and convert the strings to/from UTF-8 as needed. This PR includes only the UTF-16 changes so that it can be reviewed separately from the rest of the Qt6 update (which is still WIP). Another improvement is that it's now possible to use any allowed unicode characters for environment variables on Windows.
EDIT:
This is updated after env variable interface was redone with `std::string`: #6216.
This PR is now using the [codecvt](https://github.com/supercollider/supercollider/blob/develop/common/SC_Codecvt.hpp#L60-L69) functions that already existed in the codebase, instead of adding more helper functions.
I removed unused function …

[Windows] switch system calls to UTF-16

---

lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/PyrSlot.h

In `slotStrVal`, use `memcpy` instead of `strncpy`, since the latter does not terminate the string if the length exceeds the given buffer size! See https://en.cppreference.com/w/cpp/string/byte/strncpy. In general, `strncpy` should always be avoided.
There are a few other occurances of `strncpy` in the SC codebase, but this one has the largest impact, as `slotStrVal` is widely used.
- Bug fix

fix `slotStrVal` implementation

---

HelpSource/Classes/Env.schelp
SCClassLibrary/Common/Audio/Env.sc

Since `Impulse` was fixed, this construction doesn't work as intended (last line):
```supercollider
circle { arg timeFromLastToFirst = 0.0, curve = \lin;
var first0Then1;
if(UGen.buildSynthDef.isNil) { ^this };
first0Then1 = Latch.kr(1.0, Impulse.kr(0.0));
```
This PR fixes that, but relies on the merge of https://github.com/supercollider/supercollider/pull/6110, which fixes `Delay1`
An alternative would be 
```supercollider
first0Then1 = Latch.kr(1.0, TDelay.kr(Impulse.kr(0.0), ControlDur.ir));
```
But there's unfortunately a yet-to-be corrected initialization bug in `TDelay`.
Discovered in, but is a separate bug than, https://github.com/supercollider/supercollider/issues/6180.
- Bug fix
- it's complicated... but this doesn't cause any tests to fail that weren't failing …

Fix Env:-circle, add to docs

---

HelpSource/Classes/ServerOptions.schelp
SCClassLibrary/Common/Control/Server.sc
common/SC_Win32Utils.cpp
common/SC_Win32Utils.h
server/supernova/CMakeLists.txt
server/supernova/dsp_thread_queue/dsp_thread.hpp
server/supernova/server/main.cpp
server/supernova/server/server.cpp
server/supernova/server/server.hpp
server/supernova/server/server_args.cpp
server/supernova/server/server_args.hpp
server/supernova/server/server_scheduler.hpp
server/supernova/utilities/hardware_topology.cpp

1. Fix bogus error message `Warning: cannot raise thread priority` on Windows
2. Add Windows implementation of `nova::name_thread` (only really works on Windows 10+, but still compiles/runs on older Windows versions)
3. Add Windows implementation of `nova::thread_set_affinity` (two different implementations; can be chosen at compile time)
4. Make thread pinning a runtime option:
* add `--thread-pinning` resp. `-y` option to `supernova` app
* add `threadPinning` member to `ServerOptions` class (ignored for `scsynth`)
5. Fix "supernova" check on Windows for Server options.
6. Fix assignment of CPUs to DSP helper threads.
Before, supernova would simply pick CPUs in ascending order; with SMT enabled, this might cause DSP helper threads to share a single CPU core. Instead, we parse the actual …

Supernova: thread affinity fixes/improvements

---

.github/workflows/test_linux.yml
.github/workflows/test_macos.yml

Fixes #6442 by wrapping the post test results command in a timeout for macOS and Linux.
More of a hack as the post script should not freeze in the first place, but in the end it works and I think is a valid approach using common Unix tools.
- Bug fix

Wrap post test results in timeout

---

HelpSource/Classes/Object.schelp

Fixes
```
WARNING: SCDoc: In .../SuperCollider/SuperCollider.app/Contents/Resources/HelpSource/Classes/Object.schelp
Method -performArgs has arg named 'kwargs', but doc has 'argument:: kwArgs'.
```
as reported @ https://github.com/supercollider/supercollider/pull/6427#issuecomment-2328079480
- Bug fix

Fix case typo on kwargs argument in docs of `Obect.performArgs`

---

lang/LangSource/PyrMessage.cpp

I wrote an equality the wrong way around when tidying the code and create many duplicate keyword arguments by mistake — sorry all!. This fixes that.
Closes #6437
Test:
```
// none in class lib
f = { |a, b| }
f.(b: 10) // none
f.(1, b: 1) // none
f.(1, 1, b: 10) // duplicate b
f = { |x, y| [x, y] };
f.value(x:8); // OK
f.value(y:8) // OK
f.value(x: 2, y:8) // OK
```
- Bug fix

SCLang: fix duplicate arg warning.

---

HelpSource/scdoc.js

I sometimes need an overview of class trees, and I think instant and direct access via the indexes at the top of the SCDoc menu would not be bad.
- New feature

Add ClassTree to the Indexes of SCDoc Top Menu

---

testsuite/classlibrary/TestPV_ChainUGen.sc

This test was waiting until the timeout occurred due to the confusion around #6449  and #6448. 
Should now take circa 5 seconds to run, rather than 100 ish.
There are a large number of line changes here because the code was indented wrong.
See method `pv_equivalencetests_common` for actual changes.
- Bug fix

UnitTest, TestPV_Chain: bug fix, CondVar should have a predicate.

---

server/plugins/ML_SpecStats.cpp

SpecPcile calls RTAlloc in its _next function (thus after _Ctor). If RTAlloc fails, the UGen still outputs some non-zero values for one block. This is not the expected behavior, especially by RTAlloc UnitTests, which were failing.
This PR ensures clear output when RTAlloc fails.
- Bug fix

plugins: SpecPcile output zeros on RTAlloc fail

---

.github/workflows/build_macos.yml

I observed that despite the presence of cache, [macOS builds take a long time after changing the deployment target](https://github.com/supercollider/supercollider/actions/runs/10761956706/job/29841728669). I think that the old cache is not valid when changing the deployment target, so the cache key should also include deployment target.
- Bug fix

GHA: macOS: fix caching when switching deployment targets

---

HelpSource/Classes/Server.schelp
HelpSource/Reference/Server-Command-Reference.schelp
SCClassLibrary/Common/Control/Server.sc
include/server/SC_OSC_Commands.h
server/scsynth/SC_MiscCmds.cpp
server/scsynth/SC_SequencedCommand.cpp
server/scsynth/SC_SequencedCommand.h
server/supernova/sc/sc_osc_handler.cpp
server/supernova/utilities/simple_pool.hpp

scsynth provides a call for querying the amount of currently free real-time memory, but this call is never used and inaccessible. This PR adds a server /cmd (and related sclang interface) to get this information:
```
s.boot;
s.rtMemoryStatus
// Used RT memory: 16.5625 kb
// Free RT memory: 8175.4375 kb
// Largest free chunk: 8175.4375 kb
x = {DelayN.ar(DC.ar(0.0), maxdelaytime: 4.0)}.play;
s.rtMemoryStatus
// Used RT memory: 1043.0625 kb
// Free RT memory: 7148.9375 kb
// Largest free chunk: 7148.0625 kb
x.free;
s.rtMemoryStatus
// Used RT memory: 16.4375 kb
// Free RT memory: 8175.5625 kb
// Largest free chunk: 8175.5625 kb
```
I have no idea how to implement this for supernova.
Perhaps another option would be to include mem info in /status? Sounds nicer to me, but perhaps also too much …

server: add /rtMemoryStatus cmd for debugging

---

.github/workflows/build_macos.yml

IIUC we don't need this after #6331 was merged.
This gets rid of the warning about the versioned boost formula in the CI.
- Bug fix (?)

Revert pinning boost version for macOS system libs

---

QtCollider/style/routines.hpp

Fixes #3704 
Fixes #2574
Some widgets (e.g. EnvelopeView and Slider2D) have a "sunken" effect, obtained by drawing a semi-transparent rectangle on top of their background. Since the alpha value for such shadows is hardcoded, a user can't make such widgets have a transparent background.
This PR makes the shadow's alpha dependant on the widget's background alpha, thus making it possible to achieve full transparency.
Example code for comparison:
```
// a green window with a transparent red widget should look green
var win = View(bounds:200@200).background_(Color.green);
var ev = EnvelopeView().background_(Color.red(1, 0));
win.layout = VLayout(ev);
win.front
```
Here the square on the left is before PR, and the one on the right is after PR:
- Bug fix

QtCollider: sunken inset shadows respect alpha

---

common/SC_Filesystem_macos.cpp

To make SC compile for macOS 14/clang15, we need to import cassert.
Thanks for reporting this, @mtmccrea @ https://github.com/supercollider/supercollider/pull/6477#issuecomment-2352375615
- Bug fix

Include cassert import for clang 15

---

.github/workflows/build_macos.yml

Currently CI on macOS fails.
I realized that we were previously deleting all homebrew cache, instead of just the downloads. This PR fixes that. It also prevents the recent failures in macOS GHA runners.
With this change we won't need #6492 anymore.
- Bug fix

GHA macOS: clear homebrew downloads only

---

SCClassLibrary/Common/Quarks/Git.sc

Add a kind instruction to the error message for git not installed.
Using Quarks is a barrier for newcomers. The current error message is not helpful in this regard:
>ERROR: Quarks requires git to be installed
By adding the following sentence, newcomers can reduce the time to resolve the error:
>Follow the installation instructions at <https://git-scm.com>.
- New feature: not exactly a new feature. Just an error message is a detailed explanation.

Add <https://git-scm.com> to the Quark error message

---

server/scsynth/SC_UnitDef.cpp

When triggering a Plug-in defined command (with a `/cmd` osc message), and that command is not registered, the current error message is:
FAILURE IN SERVER /cmd failed
Which could be clearer, if the requested command name and actual failure reason were specified. This PR makes it to:
FAILURE IN SERVER /cmd /nn_load not found
Where /nn_load is the supposed plug-in command name, thus giving users a more precise hint of what has gone wrong. While I was there I have also applied the same change to Unit Commands.
Note that in order to print a dynamic error message, I had to resort to throwing an exception, which although didn't have precedents in any other server command, is already expected (and caught) by the function which runs these commands. An alternative could be to directly print to …

scsynth: add cmdName to error when /cmd not found

---

lang/CMakeLists.txt

This adds `HAVE_ISXDIGIT` compiler definition when building with MSVC.
For some reason this is needed to compile under MSVC 2022. You can see the working MSVC 2022 build [here](https://github.com/dyfer/supercollider/actions/runs/11266388136/job/31329811627).
I don't know why we need this, IIUC the `isxdigit` function should be available by default. OTOH it enables building under MSVC 2022 and I don't see how it would break anything else, so I think it's a fairly safe, if mysterious, addition.
The solution was provided by @sadguitarius [here](https://github.com/supercollider/supercollider/issues/6490#issuecomment-2395790391). 
Fixes #6490.
- Bug fix
- n/a ~~All tests are passing~~ (we don't run tests on Windows)
- n/a ~~Updated documentation~~

lang: add isxdigit definition

---

.github/workflows/actions.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml
README.md

~~Draft PR to explore issues with the toolchain upgrades~~
This PR updates the build matrix:
- Linux
- enable clang 16-18 builds
- macOS:
- separate arm64 and x64 builds
- remove `brew-install-universal` script and the "universal" build, which took a long time
- use qt6 from aqt install to provide compatibility with macOS versions lower than the build OS (I checked, the builds using homebrew qt@6 done on macOS 13 did not run on macOS 12)
- update qt to version 6.7.3, the last one compatible with macOS 11
- change structure of the build script, grouping installation steps by package source, rather than package name
- minor cleanup of the yaml file - cache keys etc
- Windows:
- add MSVC 2022 build and use artifacts from it for releases etc
- update qt to version 6.7.3
- stop uploading …

GHA: update build matrix

---

HelpSource/Classes/Pbind.schelp

Applies the following conversion in Pbind's help file.
```supercollider
#[a, b] == [\a, \b]
```
The former is confusing because they look like variables and this is seldom used syntax. While there are places it is useful, it is unnecessary here.

Help: replace esoteric syntax in Pbind help file.

---

.github/workflows/actions.yml

We started running GHA weekly after I added the custom script that was creating "universal" x86_64 and arm64 versions of homebrew binaries on macOS. It seems this was in late 2022.
When a cached version of these "universal" binaries was not available, the main macOS build would take 40-50 minutes to complete. I then added the scheduled running of the CI so that the cache was updated weekly and thus was (theoretically) always available to other CI jobs (cache from the default branch is available to jobs from other branches, but not vice versa).
After #6489 we don't make a universal macOS build anymore and  don't use the script. Now the uncached build takes 15-20 minutes, and cached builds take 4-10 minutes. I don't think it's as crucial to keep the cache updated, especially that sometimes …

GHA: don't run weekly

---

testsuite/classlibrary/TestCoreUGens.sc

This update does some minor fixes and updates to the CoreUGen tests, which came up in the course of other work.
- the tolerance of the UGen equivalence tests was too permissive — `0.001` corresponds to a -60 dB tolerance, so that's been lowered to -90 dB. It could be a bit lower if not for the reversible test for `\midicps`<-> `\cpsmidi` test, which seems to have higher error because of the exponential operations involved. 
- this change caught an erroneously passing `Integrator`/`Line` equivalence test.
- the delays/bufdelays tests and the reversible ops tests were refactored with a rate switch for a smaller footprint
- Note that for the delays tests, previously the `kr` test was still running the Delay UGens at `ar`, and only switching the delaytime argument to `kr`. I assume this was …

[tests] TestCoreUGen updates

---

QtCollider/CMakeLists.txt

This ~~should fix~~ fixes Qt6 detection on some systems that have both Qt6 and Qt5 installed.
Since we run `find_package(QT (...) )` in CMake, then the resulting variable should indeed be `QT_FOUND` and not `Qt6_FOUND` (thought the latter seemed to work on some systems), since in the call to the `find_package` function we set the package name to be `QT`. This behavior is described in the [cmake help](https://cmake.org/cmake/help/latest/command/find_package.html#basic-signature).
- Bug fix

CMake: fix qt6 detection

---

editors/sc-ide/widgets/style/style.cpp

When building with the latest Qt6 changes, the icons in the tab bar and help toolbar are showing up with the wrong size in the tab bar case and not centered properly in the help toolbar case. This commit should hopefully fix the issue, although more testing may be needed for other platforms and display resolutions.
- Bug fix

scide style.cpp: fix icon sizes on tab bar and help toolbar

---

testsuite/scripts/print_results.scd

This is a silly little change...
If we have failures, it's quite often only 1 _test_ failing, so I thought I'd make the posting grammatically correct.
Now the failed posting says:
```
----------------------------------------
1 TEST FAILED, xx skipped, out of xxx
----------------------------------------
```
or
```
----------------------------------------
2 TESTS FAILED, xx skipped, out of xxx
----------------------------------------
```
- Maintenance

Update testsuite printing result(s)

---

editors/sc-ide/core/sc_lexer.cpp
editors/sc-ide/core/sc_lexer.hpp
editors/sc-ide/widgets/code_editor/editor.cpp
editors/sc-ide/widgets/code_editor/editor.hpp
editors/sc-ide/widgets/code_editor/sc_editor.cpp
editors/sc-ide/widgets/find_replace_tool.cpp
editors/sc-ide/widgets/find_replace_tool.hpp
editors/sc-ide/widgets/util/gui_utilities.hpp

This pull request is a follow-up for the Qt6 [migration](https://github.com/supercollider/supercollider/issues/5169),  replacing `QRegExp` with `QRegularExpression` in the scide codebase.
- New feature

Qt: replace QRegExp with QRegularExpression

---

editors/sc-ide/widgets/main_window.cpp

I encountered the similar error message described in https://github.com/supercollider/supercollider/issues/2823#issuecomment-294336058
This pull request fixes https://github.com/supercollider/supercollider/issues/2823 by storing file path in `QAction`'s data field.
- Bug fix

scide: fix failing to open recent files if mnemonic is enabled

---

HelpSource/Classes/SequenceableCollection.schelp

The documentation of Array.sort does not match the implementation.

Docs: fix documented Array.sort default argument

---

editors/sc-ide/widgets/main_window.cpp

Fixes https://github.com/supercollider/supercollider/issues/6523
Only affects macOS.
Currently the IDE takes around 1-2 seconds after "tabbing into" before it displays, while also consuming lots of CPU.
I profiled the application and it turns out that the scaling of icons consumes lots of CPU cycles.
I remembered that the icons appeared with Qt6 (see https://github.com/supercollider/supercollider/pull/6475#issuecomment-2351937292) so, I decided to disable the icons and the "tabbing in" performance is as in Qt5 now.
Old:
With PR:
For some reason this problem only seems to affect Intel Macs (verification needed), so maybe there is a better way than simply disabling the Icons? I looked through https://doc.qt.io/qt-6/qiconengine.html (which is present in the flamegraph), but I couldn't find a …

Disable IDE menu bar icons on macOS

---

lang/LangPrimSource/OSCData.cpp

Big thanks to @Spacechild1 who came up with the solution and helped me a lot!
Fixes https://github.com/supercollider/supercollider/issues/6488 and enables https://github.com/supercollider/supercollider/issues/6531
Releasing the socket explicitly to avoid "double-destruction" of the global socket variable.
- Bug fix
Would be great if all major platforms could verify it works - simply exit `sclang` and if it exits without a crash/segfault, everything is how it should be.

Destroy UDP socket explicitly

---

HelpSource/Classes/Pbind.schelp
SCClassLibrary/Common/Streams/Patterns.sc
testsuite/classlibrary/TestPattern.sc

Simply append the kwargs (as keyword-value pairs) to the list of pairs.
Explain different in the help file, along with the nuance with unpacking multiple keys from PTuple.
Add test to check keywords are identical with key-value pairs.
```supercollider
Pbind(a: Pseq([1, 2, 3]), dur: 1).trace.play
```
- New feature

ClassLib: Make Pbind work with kwargs

---

.github/workflows/actions.yml
.github/workflows/test_macos.yml
README.md

macOS 12 runners will be disabled soon; let's run the tests on macOS 15.
Fixes #6531 
EDIT: it turned out that on newer macOS runners we need to grant microphone access to `/usr/local/opt/runner/provisioner/provisioner`. This PR adds it as well.
- Maintenance
- Bug fix

GHA: move macOS tests to the latest OS

---

.github/workflows/build_macos.yml

I noticed that "macOS x64 use system libraries" GHA job typically takes longer to build. Upon closer look, I realized that it uses the same cache string as the "shared libscsynth" job.
I know that we've discussed whether we really need both of these... I'm not sure, but for now I proposed to fix caching so that it's differentiated between these builds.
- Bug fix

GHA: fix caching on macOS

---

CMakeLists.txt
external_libraries/portmidi/pm_win/pmwinmm.c

Fix `incompatible-pointer-types` warning/error for portmidi. Fixes #6435.
I originally wanted to fix this by updating protmidi to a newer version, but then realized the upstream fix has not been released yet.
- Bug fix

Fix `incompatible-pointer-types` warning/error for portmidi

---

editors/sc-ide/widgets/code_editor/highlighter.cpp
editors/sc-ide/widgets/code_editor/sc_editor.cpp
editors/sc-ide/widgets/code_editor/tokens.hpp

Currently the IDE resets the indentation within multi-line comments - this PR changes the behavior.
E.g. given the code
Currently the IDE aligns the indentation within the multi-line comment with its surrounding, resulting in
This PR disables the indentation within multi-line comments, so the code would look like in image 1 after indentation. 
It also does not align/indent a line if it is equal to `/*` (the beginning of a multi-line comment).
I am not sure if this is the proper way to implement, therefore I would greatly appreciate a review.
edit: it seems win32 does not allow for `and` within if cases? Am I right if this should be switched for `&&`?
Also sorry for pushing directly as a sc branch, I forgot to set the proper origin.
- Bug fix
Should be squashed.

Do not change indentation within multiline comments

---

HelpSource/scdoc.js
HelpSource/themes/monokai.css
editors/sc-ide/core/settings/default_themes.cpp
editors/sc-ide/core/settings/theme.cpp
editors/sc-ide/core/settings/theme.hpp

Adds the dark theme *monokai* to sc ide and the docs
- New feature

Add monokai theme

---

testsuite/classlibrary/TestUGen_RTAlloc.sc

Currently we have a high failure rate of macOS tests. I haven't made a proper analysis yet, but I came across the following error multiple times.
Notice the timestamps.
**Example 1**
```log
2024-12-01T20:17:00.1068700Z UNIT TESTS FOR 'TestUGen_RTAlloc' COMPLETED
2024-12-01T20:17:00.1069460Z There were no failures
2024-12-01T20:17:00.5599240Z server 'TestUGen_RTAlloc' disconnected shared memory interface
2024-12-01T20:17:00.5600460Z '/quit' message sent to server 'TestUGen_RTAlloc'.
2024-12-01T20:17:00.5601920Z 
2024-12-01T20:17:00.5603110Z 	Test: [1mtest_allocFail_continueProcessing_otherNodes[0m
2024-12-01T20:17:00.5603710Z TestUGen_RTAlloc : setting clientID to 0.
2024-12-01T20:17:00.5669380Z Booting server 'TestUGen_RTAlloc' on address 127.0.0.1:57110.
2024-12-01T20:17:00.6813470Z …
```

Restart server for each RTAlloc test

---

QtCollider/QObjectProxy.cpp
QtCollider/QcObjectFactory.h
QtCollider/metatype.hpp

In the process of reviewing https://github.com/supercollider/supercollider/pull/6521 it turned out that the issue in https://github.com/supercollider/supercollider/issues/6508 was already present with Qt 5.15 after adding https://github.com/supercollider/supercollider/commit/f70364c704ea18f00e5aa10aa390aa1ef1b8fdb6. This PR brings back old behavior at the cost of four extra ifdefs in the codebase, reverting that change for Qt5. See discussion in https://github.com/supercollider/supercollider/pull/6521#issuecomment-2539351954.
Thanks @xunil-cloud for the tip.
There might be a better way to address this issue, but I have no expertise to pursue that. I think the ifdef is a quick and easy fix, and will be removed when we remove Qt5 support altogether.
Fixes …

[qt5] QMetaType fix for Qt5

---

SCClassLibrary/Common/Core/Nil.sc

Fix nil.addAll returning original collection instead of a copy.
Adapting addAll method to piping syntax.
Fixes #6414 .
- Bug fix

ClassLib: fix nil.addAll returning original collection instead of a copy

---

QtCollider/LanguageClient.cpp
lang/LangPrimSource/OSCData.cpp
lang/LangPrimSource/PyrSerialPrim.cpp
lang/LangPrimSource/SC_ComPort.cpp
lang/LangPrimSource/SC_ComPort.h
lang/LangSource/SC_TerminalClient.cpp
lang/LangSource/SC_TerminalClient.h
server/scsynth/SC_ComPort.cpp
server/supernova/sc/sc_osc_handler.hpp
server/supernova/utilities/osc_server.hpp

Fixes #6572
Boost 1.87 replaces the deprecated `boost::asio::io_service` with `boost::asio::io_context`. The CI using system boost from brew is already failing because of this.
This PR simply replaces every `io_service` occurence with `io_context`.
- Bug fix

Boost 1.87 support

---

SCClassLibrary/JITLib/GUI/TaskProxyGui.sc

- always focus the new editor
- include proxy key in doc name instead of just "edit me"
- do not prompt to save on close
- fix doc reference, was broken
It is nice to edit src/env contents directly from TaskProxyGui but was annoying to work with it. The newly opened editor was not in focus and closing it triggered a save dialog needlessly.
Also, upon a closer look the code was expecting to receive a doc reference from `String.newTextWindow` which actually returns the string; so the call to set the new document bounds would have never worked. Note that there are other instances  of `newTextWindow` usage with this exact problem, this PR does not address them.
- Bug fix/improvement
A fairly minimal change to 12 year old code, opening a document directly instead of via `String.newTextWindow` …

JITLib: TaskProxyGui: improve src/env editing

---

QtCollider/QWidgetProxy.cpp

Delta values in View.mouseWheelEvent are truncated, mostly producing zeroes, on my macbook trackpad. This is due to the delta integer being multiplied with 0.25 (apparently for historical reasons), truncating all small changes to zero. By casting the delta value to QPointF _before_ scaling, delta should no longer be truncated.
- Bug fix

QtCollider: Fix touchpad mousewheel event scaling

---

HelpSource/Classes/Env.schelp
SCClassLibrary/Common/Audio/Env.sc
server/plugins/LFUGens.cpp
testsuite/classlibrary/TestCoreUGens.sc

This fixes the initialization of `EnvGen` as well as improves (but doesn't fully fix) a segment duration bug, #6180.
Additionally:
- unit tests added to check initialization by the first output sample.
- fix an `Env.circle` startup behavior
This PR is part of an ongoing effort to [fix UGen initializations](https://github.com/supercollider/rfcs/pull/19), the progress of which is [tracked here](https://github.com/mtmccrea/supercollider/wiki/UGen-Fix-List).
**Note:** I did some cleanup of extraneous print statements and stray comments, as a standalone commit. If this isn't preferred, I can remove it. I think it's helpful to clean up as we go.
- Bug fixes
- Breaking change - changes are technically breaking for the first output sample (or, e.g., a one-sample phase change from previously)
- …

[plugins] EnvGen: fix initialization

---

SCClassLibrary/Common/Streams/ListPatterns.sc
testsuite/classlibrary/TestPattern.sc

See discussion at https://scsynth.org/t/pwalk-how-do-you-always-fold-at-both-boundaries/10401/10?u=jamshark70
- Bug fix

Fix Pwalk boundary behavior when using directionPattern for folding

---

SCClassLibrary/Common/Control/Engine.sc
testsuite/classlibrary/TestContiguousBlockAllocator.sc

Fixes #6585. This isn't a high-traffic method but not good to leave a bug here.
- Bug fix

Fix block allocator 'reserve' for start addresses in the middle of a free range

---

lang/LangSource/SC_TerminalClient.cpp

Fixes intropsection and syntax highlighting within IDE as mentioned in https://github.com/supercollider/supercollider/pull/6576#issuecomment-2568267476 which is a regression of #6576 .
I decided to use lambda expressions here b/c `Context::post` has been deprecated for `boost::asio::post` and, iiuc, these can be checked during compile time(?).
Sorry for the inconvenience in the meantime.
Please verify that it actually works before merging :) But tested it on macOS 15 (intel) and ubuntu 22.04 where it fixes the issue. 
- Bug fix

Fix asio post invocation for `SC_TerminalClient`

---

HelpSource/Classes/UGen.schelp
SCClassLibrary/Common/Audio/UGen.sc
SCClassLibrary/Common/Math/Complex.sc

- complex on ugens work for square root
- sign checks work for UGens
- It is generally possible to use complex numbers whose components are ugens. Only the square root function has a tacit type assumption in it. This PR fixes this.
- there are a number of methods that check the sign of numbers – they should also be lifted to UGens.
- New feature

classlib: support ugens for more math ops

---

HelpSource/Classes/Limiter.schelp
HelpSource/Classes/Normalizer.schelp

I figured out you cannot change `Normalizer` and `Limiter` durations once the synth is running.
This can be tested with:
```
(
x = SynthDef(\normalizerTest, { |dur = 0.01|
var signal = Impulse.ar(1);
var result = Normalizer.ar(signal, 1.0, dur);
Out.ar(0, [signal, result]);
}).play;
)
x.set(\dur, 0.25)
```
So I added notes about this within related help files. Since I was there, I updated the reference to the `lookAheadTime` concept.

Docs: Normalizer/Limiter: update help file

---

common/SC_Filesystem_win.cpp

Fixes #6501
- Bug fix
The fix is related to the incompatibility of `FindFirstFileW` with paths that end in trailing path separators, documented [here](https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-findfirstfilew). If anyone knows of a better way to do this without having to mess with strings, suggestions are welcome!

fix Windows pathname resolution

---

server/scsynth/SC_GraphDef.cpp
server/supernova/sc/sc_synthdef.cpp

solves issue #6611 
There are other ifstream and ofstream in the codebase that COULD need that but they are in components not used by me, so I am not sure.
Basically: when a file is opened in binary mode in windows there is not alteration of content, when it is opened in text mode ends of line are converted.
https://stackoverflow.com/questions/73570406/what-are-the-consequences-of-opening-a-file-in-c-in-text-or-binary-mode

synthdef load needs binary on windows

---

HelpSource/Classes/SequenceableCollection.schelp

The documentation for class `SequenceableCollection`'s method `flatten`'s example seems to have a typo. For:
```
a = [1, 2, [3, 4, [5, 6, [7, 8, [9, 0]]]]];
a.flatten(1);
```
It should return `[ 1, 2, 3, 4, [ 5, 6, [ 7, 8, [9, 0] ] ] ]` rather than `[ 1, 2, [ 3, 4, [ 5, 6, [ 7, 8, [9, 0] ] ] ] ]` (which is recorded in the current documentation).
This pull request only changes documentation.

Fix typo in documentation (class `SequenceableCollection`'s method `flatten`)

---

server/scsynth/SC_ComPort.cpp

Fixes issue #6647
Also fixed for internal server.
Just in case: supernova does not have this issue.
(There are two failing CI tests completely unrelated and they also fail in other PRs)
`CMake Error at QtCollider/CMakeLists.txt:38 (find_package):`

scsynth tcp: fixes uninitialized ReplyAddress (issue #6647)

---

.github/workflows/build_macos.yml

Fixes #6648 - See https://github.com/supercollider/supercollider/issues/6648#issuecomment-2706222529 for more details.
Essentially it gets harder to build SuperCollider on older macOS x64 platforms due to lacking support from Hombrew (new qt version 6.8.2 ships without webengine on macOS 13 on x64 and it is somehow hard to install older versions using homebrew. Although the most recent macOS 15 still works w/ x64 macs, this is not supported by GitHub anymore...).
This PR bumps Qt to 6.8.2 in our macOS CI and switches completely to aqt for installing Qt on macOS (instead of using homebrew).
This provides a more stable CI, but may create a divergence on how users build SuperCollider locally and how we build in CI, but that's just the way it is now it seems :/
Maybe we can introduce an macOS …

Use aqt for macOS x64 in CI and switch macOS system lib build to arm

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

Fixes #6565
It easily happens that a subarray is a number.
- more tolerant plot behaviour
- Release Notes: plot doesn't fail with opaque error when subarray turns out to be a number in a multichannel array

classlib: more tolerant plot

---

lang/LangSource/PyrInterpreter3.cpp
testsuite/classlibrary/TestCorrectArgCount.sc

When the compile/parser see a method with only a single call, or a call to `super.something`, it 'inlines' it.
For these methods, all the user's arguments were being passed through, regardless of how many were declared in the function signature.
This commit checks this, and removes any excess args from the stack.
Fixes #1087
Here is some code to demonstrate the error, before this commit, `b` and `c` would be set.
```
TestCopyArgs {
var a, b, c;
*new { |a| ^super.newCopyArgs(a) }
}
```
```
TestCopyArgs(\a, \b, \c).dump
```
- Bug fix
This should not break any code, and if it does, that code is wrong.

SCLang: Too many args passed to certain 'inlined' methods

---

HelpSource/Classes/Object.schelp
SCClassLibrary/Common/Audio/SynthDef.sc
SCClassLibrary/Common/Core/Object.sc
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/PyrParseNode.cpp
testsuite/classlibrary/TestConstructor.sc

If you have a class with many instance variables and want to only initialise some of them, you currently need to call setters, which gets messy and can be overloaded.
Now you can call them like so...
```
super.newCopyArgs(1, 2, 3, foo: 10, bar: 20)
```
You can also directly expose the constructor like this...
```
*new { |...args, kwargs|
^super.performArgs(\newCopyArgs, args, kwargs)
}
```
In future this could become the default implementation of `Object*new`.
This PR applied this to `SynthDef` as an example.
- New feature

SCLang: add keywords to newCopyArgs as constructors are messy with many instance variables

---

SCClassLibrary/Common/Collections/Dictionary.sc
SCClassLibrary/Common/Collections/Scale.sc
SCClassLibrary/Common/Core/Object.sc
lang/LangPrimSource/PyrPrimitive.cpp
testsuite/classlibrary/TestPerformArgs.sc

`super.performArgs` doesn't work as expected, so this is needed.
Fixes #6567 
- Bug fix

SCLang: implement superPerformArgs fixing inf. loop

---

HelpSource/Classes/DetectIndex.schelp

As requested in Issue https://github.com/supercollider/supercollider/issues/6641.
First PR attempt https://github.com/supercollider/supercollider/pull/6656 had messy commit history, hopefully this one is better. 
Documents return values, search method, behavior in case of multiple possible matches.
Change to code comment for clarity.
@JordanHendersonMusic's issue

Docs: DetectIndex: add doc

---

SCClassLibrary/scide_scqt/ScIDE.sc

The issue of Windows paths being displayed in the UNIX manner has been partially addressed in this PR.
I would like to extend my gratitude to @JordanHendersonMusic and @telephon for their insights and contributions, which made this improvement possible:
https://github.com/supercollider/supercollider/pull/6291#issuecomment-2747742875
Please note, however, that this PR does not address instances where a user manually types "/" in the code. Addressing such cases will require a separate PR in the future.
- Bug fix

Change the style of path in Windows by updating ScIDE.sc

---

HelpSource/Classes/Buffer.schelp
HelpSource/Classes/BufferExamplesPath.schelp
SCClassLibrary/Common/Files/BufferExamplesPath.sc
testsuite/classlibrary/TestBufferExamplesPath.sc

Closes #5859
Hopefully I am not the only one who would consider such a class helpful - still can't remember `a11wlk01-44_1.aiff` after some years...
Docs:
In a future this class could be used to add additional sound examples.
- New feature
Questions:

Add BufferExamplesPath class

---

testsuite/classlibrary/TestUGen_RTAlloc.sc

When I was running the TestUGen_RTAlloc test locally, it failed to boot the server, as my hardware was not able to run at the requested samplerate (there might be a separate bug here...).
I don't believe tests should request a specific samplerate, as this is environment dependent. AFAICT this is the only test that actually requests a particular sample rate.
I understand that there might be tests that are samplerate-specific, but I think handling such cases should be discussed separately.
- Bug fix

TestUGen_RTAlloc: don't set samplerate or blocksize

---

HelpSource/Classes/Env.schelp
server/plugins/LFUGens.cpp
testsuite/classlibrary/TestCoreUGens.sc

EnvGen accumulates rounding error over the durations of its segments. This can be especially noticeable if the Env has many breakpoints, especially at control rate. 
Another example is if you're expecting equivalence between, e.g., Line and linear segment of an Envelope, because of the incorrect Env duration, the step size is incorrect so sample values aren't identical to a Line with the same nominal duration.
For example, this envelope's duration is 1.0 sec but ends early:
```supercollider
(
{	EnvGen.kr(Env(
[0, 1, 0.3].dup(10).flat ++ 0,
[0.02, 0.03, 0.05].dup(10).flat // duration sums to 1.0
))
}.plot(1)
)
```
Fixes #6180. 
This follows on #6175, where the duration bug was found and partially addressed.
- Bug fix
- Tests added
- equivalence test for Line vs. linear Env, …

plugins: EnvGen: fix endtime

---

include/plugin_interface/SC_Unit.h

The `ClearUnitOnMemFailed` macro must zero the first sample of all outputs before returning from the current function; otherwise the output will contain garbage.
- Bug fix

plugin interface: fix ClearUnitOnMemFailed macro

---

HelpSource/Classes/Collection.schelp
SCClassLibrary/Common/Collections/Collection.sc

The behaviour of `lastForWhich` and `lastIndexForWhich`, defined in `Collection` class, does not match their names. The original implementation **only** checks the first element of the array.
Also, to match the convention of naming in the `Collection` class, `detectLast` and `detectLastIndex` is suggested to be added as an alternative name of `lastForWhich` and `lastIndexForWhich`.
You can see the relevant discussion at [the post on `scsynth` site](https://scsynth.org/t/intention-for-undocumented-method-in-class-collection-lastforwhich-and-lastindexforwhich/11289).
- Bug fix
- New feature
(synonym method, `detectLast` and `detectLastIndex`)

Fix wrong behaviour of `lastForWhich` and `lastIndexForWhich` of `Collection`, also add synonym method of them

---

server/plugins/IOUGens.cpp

LocalIn takes the default values from its UGen inputs instead of just outputting zero!
Fixes a regression introduced by https://github.com/supercollider/supercollider/commit/8401e8633140b603573c418e4c99489951b3c284
- Bug fix

plugins: fix regression in LocalIn

---

editors/sc-ide/CMakeLists.txt
lang/CMakeLists.txt

cmake: repair resource compiling of sclang for nmake without breaking MSYS or MINGW
fixes #6618 
only for sclang (still not scide)
The same can be done for sc-ide cmake (althought I can not try it but CI checks can)
It could also close PR #6111
Unrelated CI checks fails:
Known CI test errors: ` Could NOT find Qt6WebEngineCore (missing: Qt6WebEngineCore_DIR)` issue #6648
plus a new one!!
`TestMixedBundle_Server:test_send_synth_bundle (1.72s)`

cmake: repair windows resource compiling

---

HelpSource/Classes/ArrayedCollection.schelp

Closes #6539
In the `NOTE` part of `.copySeries` in the `ArrayedCollection` help file, `.copyRange` and `.copySeries` are incorrectly changed. This PR fixes the typo and adds some examples. 

Correct explanation of copyRange and copySeries in ArrayedCollection.schelp

---

SCClassLibrary/Common/GUI/PlusGUI/Math/PlotView.sc

Wavetable.plot internally calls Wavetable.asSignal.plot because Wavetables have a special format. The case of Arrays of Wavetables was overlooked, this commit fixes that.
Also replaces the nested ifs with case for clearer conditional structure. 
Old behavior:
```
u = Wavetable.sineFill(1024, [1]);
u.plot; //single Wavetable works fine (picture on left)
u.dup(2).plot; //array of wavetables doesn't. (picture on right).
```
New behavior: The expected one (i.e., sines not zigzags back and forth to 0).
- Bug fix
Tested with all the examples from https://github.com/supercollider/supercollider/pull/6566 to ensure I didn't break anything by rearranging the conditional.
Noticed along the way: superpose doesn't work with Arrays of envelopes. Is this known behavior?

Classlib: PlotView.sc: ArrayedCollection.plot should convert wavetables to Signals before passing to Plotter

---

external_libraries/portaudio/CMakeLists.txt

This PR includes 2 workarounds to provide compatibility with Cmake 4 on Windows:
- set CMAKE_POLICY_VERSION_MINIMUM in CMake for PortAudio before adding the subproject
- ~~set CMAKE_POLICY_VERSION_MINIMUM env variable in CI to fix building libsndfile in vcpkg on Windows~~
Fixes #6696. 
- Bug fix

Fix compatibility with CMake4 (portaudio)

---

README.md

In the last dev meeting it was decided that we should phase out the RFC procedure.
A first step towards this would be to
* add a deprecation note on the RFC repo -> https://github.com/supercollider/rfcs/pull/23
* remove it from the main repo `README.md` (this PR)

Remove RFC section from README

---

README.md

Does what the title says.
Old link is expired, proposed change is both functional and perene (because it's a university link) https://ccrma.stanford.edu/~ruviaro/texts/A_Gentle_Introduction_To_SuperCollider.pdf
- [ X] Updated documentation
[skip ci]

proj docs:readme Fixing "A Gentle Introduction to SC"'s link

---

HelpSource/Classes/KeyState.schelp
HelpSource/Classes/MouseButton.schelp
HelpSource/Classes/MouseX.schelp
HelpSource/Classes/MouseY.schelp

Based on testing on Fedora 41 (Kernel 6.13.0) using Gnome 47 w/ Wayland.
Documents the status of https://github.com/supercollider/supercollider/issues/4544#top and also as requested in the forum , e.g. @ https://scsynth.org/t/mousex-mousey-not-working-on-rpi5/11376/6?u=dscheiba

Add documentation about wayland incompatibility of keyboard/mouse UGens

---

HelpSource/Classes/Buffer.schelp
HelpSource/Classes/ExampleFiles.schelp
SCClassLibrary/Common/Files/ExampleFiles.sc
testsuite/classlibrary/TestExampleFiles.sc

This is a follow up from the conversation on https://github.com/supercollider/supercollider/pull/6685 about changing this class name. The conversation came the idea that `BufferExamplesPath` might be misleading in that the class points to soundfiles rather than "buffers", also that `ExampleFiles` was more generic and could be extended in the future to a variety of file types.

Change class name `BufferExamplesPath` to `ExampleFiles`

---

server/scsynth/SC_CoreAudio.cpp

I believe we shouldn't try to get properties of an input device when `numInputBusChannels = 0`, as some devices have no inputs.
Fixes #6203 and I think #4281
- Bug fix

CoreAudio backend: don't try to query input device when numInputBusChannels = 0

---

HelpSource/Classes/KeyState.schelp

Compare 
```
Ndef(\k, {KeyState.kr((0..127), lag: 0.0).sum.poll})
```
with and without Security Settings applied - only if Input monitoring is allowed keys like `abc` will be received by SuperCollider, otherwise it will only capture the arrow keys etc.
This PR documents that keystate usage is tied to Security settings on macOS.

Document keystate usage on macOS

---

editors/sc-ide/widgets/code_editor/editor.cpp
editors/sc-ide/widgets/code_editor/editor.hpp
editors/sc-ide/widgets/post_window.cpp
editors/sc-ide/widgets/post_window.hpp

Allows to zoom via touchpad. Only tested on macOS. Is not the "native macOS" zoom as it only increases the font size and does not increase the focus of a viewport - still useful.
https://github.com/user-attachments/assets/b11ff198-d7e6-435b-8f02-285d8f458b9d
Also added a boundary for font size.
- New feature

Add basic zoom via touchpad gesture

---

HelpSource/Classes/Ndef.schelp
SCClassLibrary/JITLib/ProxySpace/NodeProxy.sc

Current Ndef.clear seems too drastic for many uses, so this PR proposes two separate methods: 
```Ndef.hardClear;```, which clears all existing Ndefs, and removes the proxyspaces in ```Ndef.all```, 
which is how Ndef.clear behaves so far. 
and 
```Ndef.clear;```, which clears all existing Ndefs, but now keeps the (empty) proxyspaces in Ndef.all.
This changes the default behavior of clear: all objects that track spaces in Ndef.all will keep seeing them, 
which fixes the surprise/arguable bug noted in #6189 with minimal intervention.
The current harder behavior is still available with a clearer name ```hardClear```, 
in analogy to ```Server:freeAll, Server:hardFreeAll```, ```Main:stop, Main:hardStop```, etc. 
- Small change of default behavior
- Bug fix

Ndef: make clear methods more flexible

---

editors/sc-ide/widgets/multi_editor.cpp

This post will be kept up-to-date to reflect the state of the PR.
Closes https://github.com/supercollider/supercollider/issues/977 by using ctrl+(shift)+tab to cycle through documents like tabs in a browser. (edit: this is actually control on macOS and windows).
This replaces the alt + arrow keys shortcut.
Works on macOS, needs testing on Windows and Linux.
This could be added to https://dev.docs.supercollider.online/Reference/KeyboardShortcuts.html but I somehow think this document should include not just macOS shortcuts, so I think this should be done in another PR?
- New feature

Use tab to switch between documents

---

lang/LangSource/SC_TerminalClient.cpp

Currently, when the library compilation fails, we get stuck in a limbo; the interpreter doesn't quit, but also doesn't operate. This makes it impossible to react to such failure programmatically.
I believe this would be an improvement for testing etc., among possible future uses.
~~This behavior can be disabled by setting an environment variable `SCLANG_NO_EXIT_ON_FATAL_ERROR`, borrowed from #6671. I'm open to suggestions whether we really need an env var, or if it should be called something else. I thought it would be easiest if it's the same as in the other PR, but that can also change.~~
~~I've chosen `1` as the exit code. Another option would be `-1` I guess (IIUC that would overflow to `255`?).~~ EDIT: I changed the exit code to `EXIT_FAILURE` macro from `<cstdlib>`, but ideally we'd …

sclang: exit if the library has not been compiled

---

SCClassLibrary/Common/Control/MIDIOut.sc

For those who forgot to clean up MIDIClient before calling init several times, this caused an issue. This does it automatically. Fixes #4495.

class library: MIDIClient init cleans up old connections

---

HelpSource/Classes/Event.schelp

This is a pull request in response to this discussion: #6386.
I've added a subsection "Syntax subtleties" right below "Event as a name space for keeping objects" which in turn is the first paragraph under "Basic Usage" - seemed like the best place. Let me know if it should go somewhere else.

Add section 'Syntax subtleties' to Event helpfile

---

HelpSource/Classes/AmpCompA.schelp
HelpSource/Classes/InRange.schelp
HelpSource/Classes/InRect.schelp
HelpSource/Classes/SyncSaw.schelp
HelpSource/Classes/T2A.schelp
HelpSource/Classes/T2K.schelp
HelpSource/Classes/VarSaw.schelp
SCClassLibrary/Common/Audio/Trig.sc
SCClassLibrary/Common/Audio/UGen.sc
server/plugins/LFUGens.cpp
testsuite/classlibrary/TestCoreUGens.sc

A majority of UGens do not initialize with a correct initialization sample, and subsequently output an incorrect first sample. This PR is part of an ongoing effort to [fix UGen initializations](https://github.com/supercollider/rfcs/pull/19), the progress of which is [tracked here](https://github.com/mtmccrea/supercollider/wiki/UGen-Fix-List).
- `VarSaw`: properly reset state on initialization
- `T2A`: fix initialization, clip offset to buflength
- `InRect`: check input rates on x and y, init is OK
- `AmpComp`: call correct calc func in Ctor
- `VarSaw`, `T2A`
- `LinExp`: remove repeated code from `LinExp_SetCalc`
- `Wrap`, `Trapezoid`: remove commented-out code
- `Unwrap`:  add note re: missing class definition
- `Cutoff`: remove struct to non-existant UGen
- `VarSaw`, `SyncSaw`, `T2K`, …

Fix UGen initialization: LFUGens pt. 2/3

---

include/plugin_interface/SC_PlugIn.hpp

Quoting myself from a recent Discord discussion:
> Late to the party, but I have run into this issue before! The problem is the following:
> Any instance of a class with virtual functions will start with its vtable pointer(s). With single inheritance, a derived class replaces the vtable pointer of its bass class. (With multiple inheritance its a bit more complicated.)
> Now, if the base class has no vtable (i.e. no virtual functions), the derived class will put the vtable pointer before the data members of the bass class. This means that the derived class has a different data layout than the base class! static_cast would fix up the pointers when casting between the two classes. Scsynth, however, does not obtain a Unit * via a static_cast from TestDummy * - after all, it does not even know …

registerUnit: make sure that the UGen class is not polymorphic

---

HelpSource/Classes/PathName.schelp

I often had trouble specifying pathnames as method arguments. I just figured out why : I was expecting `PathName` instances to be valid pathname arguments. But they're not.
Somehow, `PathNames` are not pathnames. So I added a note to the help file to disambiguate the situation.
Someday, it might get worth reworking `PathName` so it can actually be used directly ? Could it inherit from `String` while retaining its functionalities ?

Docs: PathName: Clarify that a PathName instance is not a valid pathname argument

---

SCClassLibrary/scide_scqt/ScIDE.sc

This PR fixes a bug in Document.string_, 
where default arguments for start and range are wrong.
```
// Demonstrate current bug:
d = Document("test-string", "string")
// ask its string:
d.string // correct: -> string 
// now set it to something else
d.string = "strong"
// now the open document shows "strongtring", which is wrong;
// and it thinks it still has "string", which is also wrong.
d.string 
// by comparison, setting via .text_ works as expected:
d.text = "strong"
d.text.cs // correct "strong"
```
This PR sets the default so ```d.string_ = "something" ``` works correctly. 
- Bug fix

Document.string_ : fix default args

---

server/plugins/LFUGens.cpp

A majority of UGens do not initialize with a correct initialization sample, and subsequently output an incorrect first sample. This PR is part of an ongoing effort to [fix UGen initializations](https://github.com/supercollider/rfcs/pull/19), the progress of which is [tracked here](https://github.com/mtmccrea/supercollider/wiki/UGen-Fix-List).
This fixes the initialization of `IEnvGen`, and removes duplicate code from the constructor by calling the calculation function instead and properly resetting the state.
**Note:** I did some cleanup of extraneous print statements and stray comments, as a standalone commit. If this isn't preferred, I can remove it. I think it's helpful to clean up as we go.
- Bug fix

Refactor IEnvGen initialization

---

server/scsynth/SC_GraphDef.cpp
server/scsynth/scsynth_main.cpp
server/supernova/audio_backend/sndfile_backend.hpp
server/supernova/server/main.cpp

1. Supernova: catch exceptions in NRT synthesis and post helpful error message, instead of silently aborting the program.
Also make sure that the soundfile backend is automatically closed in the destructor so we can rely on RAII.
Fixes https://github.com/supercollider/supercollider/issues/6746
2. Scsynth: call `World_CleanUp()` after `World_NonRealTimeSynthesis()` throws an exception to prevent hang
- Bug fix

supernova: catch exceptions in NRT synthesis

---

HelpSource/Classes/NetAddr.schelp
SCClassLibrary/Common/Control/NetAddr.sc
lang/LangPrimSource/OSCData.cpp

- `localIP` returns the local IP address as a String; the optional `network` argument allows to specify a particular network, in case the machine is connected to multiple networks.
- `localEndPoint` returns a `NetAddr` with the local IP and a user provided port number (default: sclang port)
Interestingly, the `localEndPoint` class method already existed, but it was not documented and did not really work. Strangely, it tried to call a class method `langIP`, which does not really exist, thus it would always fail.
I have successfully tested this with
- a single interface with Internet
- a single interface without Internet
- two interfaces (one with Internet, the other without)
Also, `NetAddr.localIP("127.0.0.1")` correctly yields "127.0.0.1".
I implemented this as a result of the following …

Add `localIP`, `localEndPoint` and `localIPs` class methods to NetAddr

---

editors/sc-ide/widgets/main_window.cpp

Fixes #6562 
- Bug fix
I checked the call stacks of both dialog instances
```cpp
// call stack of first window
ScIDE::MainWindow::promptSaveDocs() main_window.cpp:1224
ScIDE::MainWindow::quit() main_window.cpp:807
ScIDE::MainWindow::onQuit() main_window.cpp:819
// call stack of second window
ScIDE::MainWindow::promptSaveDocs() main_window.cpp:1224
ScIDE::MainWindow::quit() main_window.cpp:807
ScIDE::MainWindow::closeEvent(QCloseEvent *) main_window.cpp:885
```
~~I decided to make the second call stack, invoked by a `closeEvent`, to do nothing. Please review if this could have any unintended side-effects - but I haven't figured out any so far.~~
=> I applied the fix suggested in https://github.com/supercollider/supercollider/pull/6609#issuecomment-2646122928 which seems to fix the issue. …

Fix double invocation of unsaved documents dialog upon quitting

---

lang/LangSource/SC_TerminalClient.h

Fixes #6764
After #6644, uninitialized cli options caused problems at startup for sclang on linux (see issue above).
The issue was that bool members of SC_TerminalClient::Options need to be initialized to `false`, since they are not zeroed by the default constructor. Before #6644, it was done by the user-defined constructor now removed.
The effect is that sclang is forced in either daemon (no interactivity) or standalone (no lib) mode.
Initializing all bool members to false fixes it.
I don't know why this is a problem only on linux and not on macos and windows.
Bug fix

sclang: fix cli options flags initialization

---

HelpSource/Classes/EnvGen.schelp

Document solutions for a problem with EnvGen modulation of filter cutoff, which was exposed by #6175.
Previously, a short attack would cause EnvGen's first output sample to be close to the target of the first segment. This was bad for most use cases but good for filter cutoff because it reduced the slope of the first segment, avoiding a too-sudden ramp.
There's a nice approach that isn't immediately obvious -- this PR adds that to EnvGen help..

Help: EnvGen: Add filter modulation example (re: new init behavior)

---

HelpSource/Classes/ContiguousBlock.schelp
SCClassLibrary/Common/Control/Engine.sc
testsuite/classlibrary/TestContiguousBlockAllocator.sc

Fixes #5464, where `reserve` logic failed for allocators whose addrOffset is nonzero (e.g., server's audioBusAllocator).
(Note, because of #6764, I had to base this on an earlier commit than current dev head. I think nothing since that point touches Engine.sc, though.)
- Bug fix

classlib: ContiguousBlockAllocator: Fix 'reserve' bug when addrOffset > 0

---

common/SC_ServerBootDelayWarning.cpp
common/SC_ServerBootDelayWarning.h
server/scsynth/scsynth_main.cpp
server/supernova/server/main.cpp

Currently, the Server boot delay timer thread is not joined when the main function returns early due to an error condition. This causes the program to terminate instead of exiting cleanly.
I have turned the free functions into a RAII class to make sure that the timer thread will be joined automatically when the main function returns.
- Bug fix
- Refactoring

scsynth/supernova: refactor SC_ServerBootDelayWarning

---

README_LINUX.md

Based on #6694 (and therefore supersedes #6694) plus
* makes the md document https://github.com/DavidAnson/markdownlint-cli2 compliant (e.g. use `##` as headline indicator instead of a mix of `----` and `##`) and add some blanklines between parts
* put each dependency in its dedicated line to provide a better overview and allow annotation of dependencies and have better git history support
* put each sentence into its dedicated line for better git history support
* move dedicated Qt installation part as part of Debian/Fedora dependency installation
* add some more explanation regarding build flags
Please review @prko :)
See https://github.com/capital-G/supercollider/blob/linux-readme-improvements/README_LINUX.md for a rendered version

Further `README_LINUX.md` improvements

---

editors/sc-ide/widgets/settings/dialog.cpp

Closes https://github.com/supercollider/supercollider/issues/6560
Fixes a bug in the settings menu on macOS which was introduced by Qt6 which introduced QtIcons in some places on macOS.
As these icons seem to be not consistently available (I don't know where they are located and which are available) I decided to use conditions to only display icons in the settings menu if we are not on macOS, restoring the 3.13/qt5 layout for macOS.
w/o PR
w/ PR
- Bug fix

Do not display setting menu icons on macOS

---

editors/sc-ide/widgets/settings/editor_page.cpp
editors/sc-ide/widgets/settings/sclang_page.cpp

Fixes #6692
Apparently `currentIndexChanged(const QString&)` signal has been deprecated / removed and instead we should use `currentTextChanged(const QString&)`.
This also fixes theme/font dialogs, I believe.
- Bug fix
- ~~[n/a] Updated documentation~~

IDE: fix sclang config file dialog behavior

---

HelpSource/Reference/AudioDeviceSelection.schelp

Help stated: "If these are not set, SuperCollider will default to connecting SuperCollider's inputs and outputs to your system's inputs and outputs." This is not true. PR matches current behavior.

Help: Correct error in Linux env vars discussion

---

testsuite/classlibrary/TestLinkClock.sc

Per discussion under #5421, we should remove one possible source of errors in the LinkClock test of `newFromTempoClock` rescheduling of patterns.
Note that #5421 includes other issues, so, merging this should not close that issue.
- Bug fix
- [+] This PR is ready for review

Testsuite: LinkClock: Avoid Event errors in newFromTempoClock test

---

editors/sc-ide/widgets/settings/sclang_page.cpp
editors/sc-ide/widgets/settings/sclang_page.hpp

Fixes #3530
I moved the dialog to a separate function and added another flag to keep track of changed config file, without marking the file "dirty" (i.e. needing to save it). Please review the logic carefully.
~~Note: I'll rebase this after #6817 is in - I needed to include the commit from the other PR in order to test this functionality.~~ The PR is now rebased.
- Bug fix

Add dialog to restart interpreter after switching config file

---

.github/workflows/build_macos.yml
CMakeLists.txt
README_LINUX.md
README_MACOS.md
cmake_modules/launch-c.in
cmake_modules/launch-cxx.in

This PR cleans up our ccache integration, inspired by redundancies exposed by #6209. It also adds the `USE_CCACHE` CMake flag which allows disabling ccache. This PR supersedes #6209.
Waiting for the CI run to confirm caching still works, particularly on macOS, where the implementation was updated... EDIT: seems to work! The [build step took under a minute](https://github.com/supercollider/supercollider/actions/runs/14697811939/job/41242079773#step:14:1).
I kept the option to use ccache **ON** by default. CMake configuration posts an information if ccache is found, but there's no posting if it isn't. Do we have a preference on setting it on or off by default? I'm happy to go either way and update this PR as needed (including CI and docs).
- Bug fix
- New feature

CMake: update ccache integration

---

SCClassLibrary/Common/Collections/Array2D.sc
SCClassLibrary/Common/Collections/Bag.sc
SCClassLibrary/Common/Collections/Interval.sc
SCClassLibrary/Common/Collections/LinkedList.sc
SCClassLibrary/Common/Collections/ObjectTable.sc
SCClassLibrary/Common/Collections/Pair.sc
SCClassLibrary/Common/Collections/SequenceableCollection.sc
SCClassLibrary/Common/Collections/Set.sc
testsuite/classlibrary/TestCollection.sc

Fixes #6408 
```supercollider
[1, 2, 3].remove(3) //  3
Set[1, 2, 3].remove(3) // Set[1,2]  << incorrect
[1, 2].remove(3) // nil
Set[1, 2].remove(3) // Set[1, 2] << incorrect
```
From `Collection` help file
> Remove anObject from the receiver. Answers the removed object.
- Bug fix
Could be a breaking bug fix, but documentation is clear

ClassLib: fix Set.remove not returning the item

---

HelpSource/Classes/String.schelp

While testing #6312 and #6639, I found the following code does not work on Windows due to `+/+`:
```supercollider
(
var url = "https://raw.githubusercontent.com/supercollider/supercollider"
+/+ "refs/heads/develop/sounds/a11wlk01.wav";
var localPath = "~/Downloads".standardizePath +/+ url.split($/).last;
/// var localPath = Platform.defaultTempDir +/+ url.split($/).last;
var finishedFunc = {
localPath.openOS;
"downloaded to %".format(localPath).postln
};
var errorFunc = {"error".postln };
var progressFunc = { |receivedBytes, totalBytes|
var downloadProgress = (receivedBytes / totalBytes * 100).round(1e-2);
"Downloaded %\\%".format(downloadProgress).postln;
};
d = Download(url, localPath, finishedFunc, errorFunc, progressFunc)
)
``` 
I believe there may be other users who, like myself, …

Add note about '+/+' and url address

---

server/plugins/TriggerUGens.cpp

Minimal fix for TDelay initialization, just providing the necessary internal state reset.
Due to missing internal state reset after init, TDelay used to incorrectly advance its internal counter. This caused an incorrect delay time of a trigger occuring on its first input sample, which would be delayed one sample too early.
This PR is part of #6813, and introduces small bug-fixing breaking changes in TDelay output.
- Bug fix
Output changes only if TDelay has a trigger on its first sample of input. If delayTime > dt (where dt is the time between first and second trigger), the output re-aligns with the previous version at the second trigger.
```supercollider
(
~printOutput = { |fn, nSamples(s.options.blockSize), action(_.postln)|
fn.loadToFloatArray(nSamples/s.sampleRate, …
```

plugins: TDelay: fix initialization sample

---

testsuite/classlibrary/TestServer_clientID_booted.sc

Two tests in `TestServer_clientID_booted` mock remote servers by launching an extra scsynth process and then calling `Server.remote`,  which initializes a `StatusWatcher`, but when the process exits, doesn't clean it up by default. This causes an accumulation of `/status.reply` listeners, resulting in multiple ServerAction calls when another server shares their same address (which is `localhost:57110`, so every other default server).
To be discussed if we should fix this behavior in any other way, for now I just fixed the tests by adding `stopAliveThread`. Perhaps `stopAliveThread` could be called by `Server:-remove`?
This should fix the failures for `TestServer_boot:test_notifyAndServerBootActions` and `TestServer_boot:test_notifyAndServerTreeActions`, or at least one possible cause of …

testsuite: TestServer_clientID_booted: fix cleanup

---

HelpSource/Classes/LevelComp.schelp
HelpSource/Classes/Splay.schelp
HelpSource/Classes/SplayAz.schelp
HelpSource/Guides/Level_Compensation.schelp
SCClassLibrary/Common/Audio/Splay.sc

Level Compensation for Splay and SplayAz were questioned and discussed at length 
in #5706. As there is not one single correct formula, but situation-dependent considerations, 
this PR adds: 
- A Guide page that discusses these considerations, with examples.
- A LevelComp class that implements a fully backwards-compatible, more flexible logic.
- Updates to Splay and SplayAz that use this logic. 
- Documentation / Guide
- Bug fix - sync pos calculation in PanAz.kr with fix in PanAz.ar
- New feature - more flexible level compensation.
[x] Code is tested
[x] All tests are passing
[x] Documentation : updated Splay and SplayAz help files, added Guide file.
[x] This PR is ready for review

Splay level comp flexify

---

HelpSource/static/scdoc.css

Merge note: Squash it
When navigating to a method one "overshoots" currently b/c the height of the menu bar is not respected - e.g.
This PR fixes this by providing a `scroll-margin-top` to every anchor
I hope we are not using something else than `a` for anchors...
- Bug fix

Add `scroll-margin-top` to fix scrolling to anchor

---

HelpSource/Classes/Date.schelp
testsuite/classlibrary/TestDate.sc

On Windows `Date` resolution doesn't work for pre-Epoch dates.
I think for now we can "fix" this by documenting this behavior and using a post-epoch date in the test suite.
Fixes #6765
- Bug fix

Date: Windows notes and testsuite fix

---

common/sc_popen.cpp
common/sc_popen.h
lang/LangPrimSource/PyrFilePrim.cpp
lang/LangPrimSource/PyrUnixPrim.cpp

In this PR:
- `ArrayedCollection -unixCmd` is fixed to _not_ run the command through `cmd.exe`, which matches behavior on *nix
- as a result, a proper PID of the requested command is now returned from this method
- `sc_popen()` is renamed to `sc_popen_shell()` to reflect the behavior of the function.
The rest of the functionality previously present in this PR will be addressed in separate Issues/PRs.
How to test this:
```supercollider
// pid with ArrayedCollection
r = [Server.program, "-u", "57110"].unixCmd; // run scsynth using ArrayedCollection -unixCmd
r.postln; // this should match the scsynth pid in Task Manager
thisProcess.platform.killProcessByID(r); // scsynth should exit
```
- Bug fix

Fix SequenceableCollection -unixCmd on Windows 

---

HelpSource/Classes/DoubleArray.schelp
HelpSource/Classes/Float.schelp
HelpSource/Classes/FloatArray.schelp
HelpSource/Classes/Int16Array.schelp
HelpSource/Classes/Int32Array.schelp
HelpSource/Classes/Int8Array.schelp
HelpSource/Classes/Integer.schelp

Closes #6687. Overflow is an interesting behavior whose definition or lack thereof should be apparent in the documentation for classes that exhibit the behavior. Overflow behavior for float and (signed) integer types in C++ is undefined, and those types are on the backend of several `Number` and `RawArray` classes in sclang. 
There's already a divergence in overflow behavior for the `Int32Array` dependent on the platform (see linked issue).
(If I missed any other affected classes, please let me know.)

doc: add undefined overflow notes to affected Number, RawArray classes

---

server/plugins/TriggerUGens.cpp

Add internal state resets for the sake of enforcing conventions on UGens initialization.
This PR is the first part of a larger effort to fix init sample behavior for Trigger UGens. This part doesn't change any init sample or output value, so no breaking change. UGens that require a fix that would change either init sample or output values are left for subsequent PRs.
When initializing a UGen, the convention is to reset internal state after the first calc function call in Ctor. UGens changed by this PR were already calculating init sample and managing internal state correctly, so adding an explicit reset was not functionally necessary. However, it makes it easier to reason about initialization, by aligning with the convention, and provides a better reference to be imitated when writing new …

plugins: TriggerUGens standardize init sample

---

editors/sc-ide/widgets/lang_status_box.cpp

#6838 has introduced a serious bug on linux and windows, making the IDE crash during startup.
For more information see https://github.com/supercollider/supercollider/issues/6862#issuecomment-2889937573
This introduces a quick fix which simply comments out the line which creates a segfault (at least on Linux).
W/o this line the style of the language status box will not be updated upon a theme change - not nice but better than a crash of the IDE ;)
I tested this fix on linux, but @jamshark70 can you give this a try if this fixes your issue?
@prko @dyfer can you verify that this also fixes the issue on windows?
Once it is verified that it fixes the issue on windows I think this could be merged?
- Bug fix

Disable redrawing lang status box on theme change

---

HelpSource/static/scdoc.css

Currently, the lead (line spacing) between the first child of the nested list and the previous line is too small.
This PR adds `margin-top` to `li:first-child`, and the result is as follows:
- Bug fix

Remove <p> after every `\prose` and modify line-spacing using `margin` in scdoc.css

---

HelpSource/Classes/Float.schelp

The helpfile for `Float` would not render correctly after #6787 was merged:
```supercollider
ERROR: In /(...)/src/supercollider/HelpSource/Classes/Float.schelp:
At line 148: syntax error, unexpected ::, expecting end of file
```
This PR adds the missing tag.
Note to self: it would be great to have a CI job that would catch schelp errors...
- Bug fix

Float.schelp: add missing `code` tag.

---

server/plugins/TriggerUGens.cpp

This is the second part of the implementation plan in #6813.
This PR fixes a batch of UGens, affecting their init sample or output sample in a limited way. Although this is a breaking change, I would argue that it's of the same entity as the ones introduced by #6035, and so I propose we merge it in SC 3.14, if there is no objection of course.
- ToggleFF: changes init sample to 1 if UGen has trig on first input sample (x[0] from now on)
- Peak, PeakFollower: changes init sample for negative input on x[0]
- PulseDivider: changes first output sample for x[0] > 0 and div[0] = 1
- Timer: changes output correcting the first measured duration by one sample
The following code illustrates the kind of breaking changes this PR introduces
```supercollider
(
~printOutput = { |fn, …
```

plugins: TriggerUGens: fix initialization sample

---

editors/sc-ide/widgets/lang_status_box.cpp

Fixes #6876.
LangStatusBox needs to initialize mLang before calling applySettings,
otherwise when applySettings calls onInterpreterStateChanged(mLang->state()), mLang is a garbage pointer.
- Bug fix

scide: redraw status bar on applySettings

---

SCClassLibrary/SCDoc/SCDocRenderer.sc

When creating links on Windows, use `/` instead of `\`. This caused some `TestSCDocHTMLRenderer` tests to fail on Windows.
I haven't follow the logic of SCDocRenderer fully... please review carefully. I'm looking forward to any feedback on this.
- Bug fix

scdoc renderer: use forward slash on Windows

---

SCClassLibrary/scide_scqt/ScIDE.sc
editors/sc-ide/core/doc_manager.cpp
editors/sc-ide/widgets/multi_editor.cpp

This PR aims to improve the sclang <-> ScIDE communication and adds a rudimentary signaling during the handshaking process. This should solve issues with the Document classes and calls from IDE triggering sclang errors, particularly on Windows.
This is possibly not a final fix, but it should be a reasonable workaround for the linked issues.
It seems to work fine on a Windows 11 VM, but more testing would be very desirable.
There's no need to uninstall your current SC version!
First, **confirm that the issue still occurs** on your system using a recent [develop build](http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/win64/develop-latest.html)
- download a [develop build](http://supercollider.s3.amazonaws.com/builds/supercollider/supercollider/win64/develop-latest.htm …

IDE<->sclang Document fixes

---

QtCollider/widgets/QcWebView.cpp
editors/sc-ide/widgets/help_browser.cpp
editors/sc-ide/widgets/help_browser.hpp

Fixes #6315 , #6136, #5672
Keyboard shortcuts for "Back", "Forward" and "Reload" actions can be ambiguous depending on OS and Desktop Environment.
This PR makes sure these actions are called when the Help Browser is in focus, resolving the ambiguity.
It also makes the "Reload" shortcut configurable in IDE settings (using the same shortcut as ide-reload-document).
- Bug fix

scide: HelpBrowser fix ambiguous shortcuts

---

README_LINUX.md
editors/CMakeLists.txt

This PR only affects linux users.
When building SC on linux in the default configuration, one needs emacs as a dependency.
This PR makes emacs an optional dependency and one explicitly needs to turn on the building of the plugin using CMAKE flags.
At the same time I also turned off to build the vim plugin in the default configuration (though I think this didn't need to have vim as a dependency, or maybe this is only due that vim is already present on most systems).
I think this can be "voted" in the dev meeting - I personally think it would be good to have this merged for for 3.14 release.
edit: We still build the plugins in CI, so we don't abandon the build process and get aware of issues early.

Convert emacs and vim to an opt-in build flag on linux

---

lang/LangSource/DumpParseNode.cpp
testsuite/classlibrary/TestFloat.sc

Closes #6863
Nan & inf should be printed the same across platforms and c library implementations.
This is particularly salient for `inf` as it must be convertible to a compile string and back.
- Bug fix
- Breaking change ? Maybe if someone relied on this, but it didn't work across platform anyway.

SCLang, UnitTests: standardise nan & inf printing across platforms

---

.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml
CMakeLists.txt

We have shit C++ test coverage (with the exception of supernova), and the ones we have, we don't run. Going forward we should add more C++ tests,  which can easily be done using the already existing boost tests.
Enable ctests during build on CI.
You can't run these in the 'test' phase because you need the build directory and only the install directory is exported as an artefact.
This means the sclang unit tests won't run unless the ctests pass, but that seems fine.
This is only run on linux because that is the only one I know how to make a virtual display for. In future we could run this elsewhere.
- new tests
- ci change

CI: run ctests with linux build

---

HelpSource/Classes/Phasor.schelp
server/plugins/TriggerUGens.cpp

Phasor was not calling its calcFunc in its Ctor, ignoring a trigger on its first sample and assuming its initial value to be its startPos. This PR fixes it, causing Phasor to start from resetPos instead if triggered on its first input sample.
This PR is part of #6813, and introduces a bug-fixing breaking change in Phasor output.
This is the only PR in this process for which I think somebody might be using the wrong behavior on purpose (Phasor always starts from startPos, and can reset to resetPos only later). However, I still see it as marginal. Documentation is clear on Phasor resetting to resetPos every time it receives a trigger, and never mentions it ignoring a trig on x[0] or always starting from startPos regardless of trig. There is no instance in the docs or examples in which this …

plugins: Phasor: fix init sample: don't ignore trig on first sample

---

lang/LangSource/GC.h
testsuite/sclang/sclang_gc_crash_1.scd

When there are a large number of temporary objects mNumToScan can overflow leading to undefined behaviour (from the overflow of a signed int) and the implementation defined behaviour of right shifting a negative value, creating a GC bug that only appears on some systems, and incorrect, potentially leaking, but non-crashing behaviour on others.
This code cause a crash on some systems.
```supercollider
b = Pwhite.new(0, 10, inf).asStream;
Array.fill(1810000, {b.next});`
```
This commit places an upper limit on the number of objects to scan (5'000'000). Note, SC uses an incremental allocator, meaning this isn't a limit on the amount of memory, but amount of unchecked memory.
While all allocations should cause a collection, when PyrParseNode.cpp creates a PyrMethod, sometimes it sets …

Sclang: PyrGC: Fix GC segfault caused by uncollected temporary function objects by placing an upper limit on un-scanned objects. 

---

HelpSource/Classes/NodeTreeView.schelp
HelpSource/Classes/Server.schelp
SCClassLibrary/Common/GUI/PlusGUI/Control/ServerPlusGUI.sc

After merging #6834 I found some discrepancies between the documentation and the implementation.
- `s.plotTree` returns a `NodeTreeView`, as [introduced](https://github.com/supercollider/supercollider/pull/6834/files#diff-a35b5be480643c127f781e8f7c8cc60f263ca1af432aa3c881ba3d043623e6c0R377) in #6834. I reverted the previous change in this PR as suggested by @telephon.
- I made the `s.plotTreeView` (the method that actually creates a view, but that's not typically called directly by the user) return the newly created instance of the NodeTreeView. In SC 3.13 this return a function that needed to be called to clean it up, or something like that. This is technically a _breaking change_, comparing with the state in SC 3.13. I don't think this function is meant to be used directly by the users …

Update node tree view help / implementation

---

platform/linux/CMakeLists.txt
platform/linux/io.github.supercollider.SuperCollider.metainfo.xml
platform/linux/online.supercollider.SuperCollider.metainfo.xml
tools/release/make_release.py

This change introduces the metainfo.xml file, that is required by the flatpak build and distribution system.
AppStream is an initiative that aims to create a unified software metadata database.
Add installation directive to install metainfo file
Fix issues with metainfo related to AppStream linter
This MR is a follow-up to #3604. A [PR](https://github.com/flathub/flathub/pull/5350) into Flathub databse was opened and the only thing missing, at this point, is AppStream metainfo file. 
- build/install
- [] Updated documentation
I think the only thing missing from this PR is integrating updates to the `metainfo` file via CI at release-time. I'm willing to look into that (I have not yet looked at the SC CI pipeline). It could be a separate PR.
In any case, the Flathub merge will likely not …

build: install: add an AppStream metainfo file

---

SCClassLibrary/Common/Control/Volume.sc

Fixes #6937.
It turns out that the Volume class *does* track whether the synth is expected to be playing, but it doesn't use this information to check whether it's necessary to release.
- Bug fix

classlib: Don't try to free a Volume synth that doesn't exist

---

lang/LangPrimSource/SC_ComPort.cpp
lang/LangPrimSource/SC_ComPort.h
server/scsynth/SC_ComPort.cpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp

Set `SOL_SOCKET/SO_RCVBUF` using [boost API](https://live.boost.org/doc/libs/1_86_0/doc/html/boost_asio/reference/basic_datagram_socket/receive_buffer_size.html) to increase default UDP receive socket buffer size. Close #5993 and probably #5870. For now, I increase the buffer size to 8MB. But the choose is somewhat arbitrary and I'm happy to change it if we come up with a better default.
- New feature

Increase UDP socket buffer size

---

QtCollider/image.h
QtCollider/widgets/BasicWidgets.cpp
QtCollider/widgets/BasicWidgets.h
QtCollider/widgets/QcButton.h
QtCollider/widgets/QcCanvas.cpp
QtCollider/widgets/QcCanvas.h
QtCollider/widgets/QcMenu.h
QtCollider/widgets/QcSlider2D.cpp
QtCollider/widgets/QcSlider2D.h

Fixes #6936 
We had this problem before with `TreeView`, see #6521. This PR applies the same fix. 
`SharedImage` is a typedef for `QSharedPointer<QtCollider::Image>`. Qt registers it as a MetaType with its full name `QSharedPointer<QtCollider::Image>`, so Q_INVOKABLE methods needs to use the same name, otherwise method calls fail with `QMetaMethod::invoke: cannot convert formal parameter 0 from QSharedPointer<QtCollider::Image> to SharedImage.`. Even if the type is the same, Qt gets confused about its name.
Here is a note from [Qt docs](https://doc.qt.io/qt-6/qtqml-cppintegration-exposecppattributes.html#exposing-properties):
> Note: Do not use typedef or using for [Q_PROPERTY](https://doc.qt.io/qt-6/qobject.html#Q_PROPERTY) types as these will confuse moc. This may make certain type …

QtCollider: fix Q_INVOKABLE SharedImage typename

---

HelpSource/Classes/PbindProxy.schelp
HelpSource/Classes/Pbindef.schelp
SCClassLibrary/JITLib/Patterns/Pdef.sc

Since 3.14, we can write `Pbind(freq:8, dur:0.2)`, for the rc0, I forgot to add the syntax to `Pbindef` and `PbindProxy`. The change is trivial: `pairs = pairs ++ kwargs`. I've adjusted the whole file to use pipes as argument syntax.
The only functional change is here: https://github.com/supercollider/supercollider/pull/6977/commits/0a522a34cf401611875a05bc270ae6776b2a9d01
- New feature
- Release Notes: I'll edit the relesae note file accordingly.

classlib: kwargs for Pbindef and PbindProxy

---

lang/LangPrimSource/SC_ComPort.cpp
lang/LangPrimSource/SC_ComPort.h
server/scsynth/SC_ComPort.cpp
server/supernova/sc/sc_osc_handler.cpp
server/supernova/sc/sc_osc_handler.hpp

Fix #6969. Set UDP buffer size to 4 MB and fallback to 1MB if we fail to do that. 
- Bug fix

UDP: set max buffer size to 4MB and fallback to 1MB

---

HelpSource/Overviews/MidiPatterns.schelp

The example given to send pitchbend messages from a Pbind does not work as the `\bend` key used should be `\val`.

Fix example for bend Pbind

---

.github/workflows/build_macos.yml
.github/workflows/test_macos.yml
cmake_modules/FindReadline.cmake
tools/vcpkg_combine_libs.sh

The official Qt6 binaries that we use for the releases are compiled for both arm64 and x64 architectures. The only thing that prevented us from building a universal binary of SC on macOS was the unavailaility of dual-architecture dependencies: fftw, libsndfile, and readline.
I was previously experimenting with adding a universal "triplet" for vcpkg, but that doesn't work with some of the libraries which use autotools. 
Another option is to build packages for both architectures and then combine them manually. This is what this PR does... This is not the most elegant solution, but it seems to work. The script is embedded directly in the vcpkg install step, which makes the workflow file a bit bigger. Luckily, the script is not nearly as extensive as what we [used to use for making universal …

Let's consider macOS universal build... again

---

SCClassLibrary/Common/Streams/IOStream.sc

This should be uncontroversial: Post's `*close` method has been invalid in the 18 years since the `flush` method that it calls was deleted. We need to keep `.close` for compatibility with File streams, but it should be a no-op rather than a thrower of a DoesNotUnderstandError.
- Bug fix
- [-] Updated documentation (no need)

classlib: Post: Remove reference to the 18-years-deleted '.flush' method

---

HelpSource/Classes/Nil.schelp
HelpSource/Classes/Set.schelp
SCClassLibrary/Common/Collections/Set.sc

This documentation update reflects the current behaviour of nil in SuperCollider, which serves multiple purposes: representing uninitialised values, terminal markers, and acting as an internal sentinel within collections. While this multipurpose usage may be reconsidered in the future, the current update ensures the existing implementation is accurately described.
If nil is later restricted to represent only uninitialised values, the affected documentation should be revised accordingly. See #7010.

Add nil's behaviour in Set and Nil documentation

---

README_MACOS.md

As discovered in https://github.com/supercollider/supercollider/issues/7003 there was a typo in the qt5 building instructions in the macOS readme. 
Also clarified the use of supernova and added a stronger suggestion to drop Qt5 (EOL). 
See also https://github.com/supercollider/supercollider/issues/7006
- Bug fix

clarified use of supernova and fixed build instructions with qt5

---

editors/sc-ide/widgets/util/status_box.cpp

Regression of #6329 - restores font size of 3.13.
Left side 3.14-rc1, right side w/ applied fix. I don't know why #6329 changed the font size, and this needs some multi-platform testing in order to verify that everything works as expected. Should be part of 3.14 IMO, therefore it targets this as well.
I am somehow unhappy with hardcoding numbers, but I don't know what to do about it otherwise.
- Bug fix

Increase font size of status box

---

lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/PyrMessage.cpp

When the method selector is a symbol that is a class name, method lookup may be out of bounds. We check if the symbol is a monster and return.
This fixes #7016 and #7020.
```supercollider
[].respondsTo(\Object)
[].doesNotUnderstand(\Object)
[].perform(\Object);
[].performList(\Object);
[].performArgs(\Object);
```
This adds an extra check in a central place of method dispatch.
We should discuss if this is the best way to go, and make sure this is really the most performant way.
The community hasn't noticed this bug for 20 years, so is it worth checking for the monster every method call? Maybe yes, maybe no.
- Bug fix

sclang: protect method lookup from out of bounds index

---

QtCollider/widgets/QcAbstractStepValue.h
QtCollider/widgets/QcKnob.cpp
QtCollider/widgets/QcKnob.hpp
QtCollider/widgets/QcNumberBox.cpp
QtCollider/widgets/QcNumberBox.h
QtCollider/widgets/QcSlider.cpp
QtCollider/widgets/QcSlider.h
QtCollider/widgets/QcSlider2D.cpp
QtCollider/widgets/QcSlider2D.h
editors/sc-ide/widgets/audio_status_box.cpp

Fixes #7008
When migrating from deprecated .delta() to .angleDelta()/.pixelDelta() (9d10e196ce263faff1f9951d0db012a948ffbc87)
there were some errors in scaling the delta values, and some probably typos turning vertical scaling to horizontal.
`angleDelta()` is a direct translation of the old deprecated `delta()`, so I think we could skip checking for `pixelDelta()` in widgets like QcSlider and just use `angleDelta()`, to get the old behavior back. I'm not sure if using pixelDelta gives any better precision/smoothness in this case. However, for now I've kept also `pixelDelta`, and changed it's scaling to a value that gives me the same feel as angleDelta (and as in 3.13).
Can someone on a mac try it and report how does scrolling feel between this PR, 3.13 and 3.14-rc1? For me on linux …

QtCollider: AbstractStepValue widgets: improve wheelEvent scroll behavior + fix regression

---

editors/sc-ide/widgets/code_editor/completion_menu.cpp

Fixes #7007, according to a [user report](https://github.com/supercollider/supercollider/issues/7007#issuecomment-3049095148).
But... what does it break instead?
This is a somewhat blind attempt at fixing a crash on Wayland with multiple displays (see #7007 for bug description).
I don't know what was the purpose of `resize(0, 0)` in the first place though. For reference it was introduced in  https://github.com/supercollider/supercollider/commit/7f2db98b85e0cbdda03a55d6beb0ec8166e2ab39 as part of https://github.com/supercollider/supercollider/pull/1333. On the surface the autocomplete hints still show as they have before this PR, as far as I can tell...
I'd appreciate if others could test to make sure this doesn't break any functionality!
- Bug fix

IDE: don't call resize(0, 0) on completion widget

---

SCClassLibrary/DefaultLibrary/dumpFullInterface.sc

helpFileForMethod jumps to method, instead of just to the class documentation.
- Bug fix
- helpFileForMethod jumps to the method description, instead of to the class documentation only.

classlib: helpFileForMethod jumps to method

---

HelpSource/Classes/Class.schelp
HelpSource/Classes/Object.schelp
HelpSource/Classes/String.schelp
SCClassLibrary/Common/Collections/String.sc
SCClassLibrary/Common/Core/Error.sc
SCClassLibrary/Common/Core/Kernel.sc
SCClassLibrary/Common/GUI/Base/EZgui.sc
lang/LangPrimSource/PyrPrimitive.cpp
lang/LangSource/PyrPrimitiveProto.h
testsuite/classlibrary/TestClass.sc
testsuite/classlibrary/TestDoesNotUnderstandError.sc

The DoesNotUnderstandError suggestions sometimes are over-confident, because:
- they only give one suggestion even if there may be others that match almost as well
- they suggest that there has been a typo where there may have been other reasons
- the errorString contained the suggestion, which one may want to keep separate
This improves the DoesNotUnderstandError posting:
- it now suggests up to 4 similar names
- it uses a neutral language that doesn't speculate about the reason
- The errorString itself now does not contain the suggestion
- As an experiment to be evaluated over time, we sometimes post class suggestions if they are appropriate.
- for better introspection, some new methods have been introduced
- the implementation of DoesNotUnderstand is refactored
I took the liberty to …

classlib: DoesNotUnderstandError: refactor suggestions

---

QtCollider/widgets/QcWindow.cpp

Fix positioning of non-resizable windows.
Test:
```supercollider
Window("resizable", Rect(100, 100, 300, 300), true).front;
Window("not resizable", Rect(400, 100, 300, 300), false).front;
```
Before:
After:
Details: windows position was previously set using `move` for non-resizable and `setGeometry` for resizable windows. [move](https://doc.qt.io/qt-6/qwidget.html#move-1) (which is a setter for [pos](https://doc.qt.io/qt-6/qwidget.html#pos-prop)) calculates the position including the window frame. [setGeometry](https://doc.qt.io/qt-6/qwidget.html#setGeometry-1) (setter for [geometry](https://doc.qt.io/qt-6/qwidget.html#geometry-prop)) sets the position excluding the frame. This PR uses `setGeometry` whether the window is resizable or not, which seems to result in a consistent behavior. …

sclang / qt: fix positioning of non-resizable windows.

---

SCClassLibrary/Common/Control/Server.sc

Currently, the SCDoc message `SCDoc: Indexing help-files...` appears without an empty line before it and is not bold, which makes the sequence of post window messages harder to read:
```
Booting server 'localhost' on address 127.0.0.1:57110.
Device options:
- MME : Microsoft 사운드 매퍼 - Input
(2 ins, 0 outs)
- MME : Microphone(High Definition Audi
(2 ins, 0 outs)
- MME : Microsoft 사운드 매퍼 - Output
(0 ins, 2 outs)
- MME : Speakers(High Definition Audio 
(0 ins, 8 outs)
- Windows DirectSound : 주 사운드 캡처 드라이버
(2 ins, 0 outs)
- Windows DirectSound : Microphone(High Definition Audio Device)
(2 ins, 0 outs)
- Windows DirectSound : 주 사운드 드라이버
(0 ins, 2 outs)
- Windows DirectSound : Speakers(High Definition Audio Device)
(0 ins, 8 outs)
- ASIO : Magix Low Latency 2016
(2 ins, 8 outs)
- ASIO : ReaRoute …
```

Insert an empty line after server boot

---

HelpSource/Classes/SinOsc.schelp

Fix a typo (by @prko) - cherry pick #7064
Note, the typo was [introduced in 3.14.0-rc2](https://github.com/prko/supercollider/commit/fcdee4d6b08bbfb8bbd25d776f9efa18521dfd1b#diff-f4b6ed3bfc22c81984fa1fd9925fff175c5bfb01bb13afaa8d081b789a5c6596R12) so we need to fix this for the final 3.14.0 release, otherwise SinOsc helpfile won't render.

Correct a typo in SinOsc.schelp (#7064)
